### ISSUE TITLE
token-type when using token-info-uri

### ISSUE THREAD

**Issue by yelhouti** [spring-projects/spring-security-oauth#1006]
In the class RemoteTokenServices the tokenName is set to "token", and the variable: security.oauth2.client.tokenName doesn't change this value (I don't even know if it's purpose is to that). when trying to use Google with OpenIdConnect this variable should be set to access_token in my case, or in other cases could be id_token, token_handle.
could you please fix this if it's the job of tokenName (add it to the decription in the doc), or create another variable for that.
Thanks

**Comment by jgrandja** [comment]
@yelhouti As noted in #977, Spring Security OAuth currently does not provide support for OpenID Connect.

This project is in maintenance mode as we are limiting new features and only focusing on bug fixes and minor enhancements. We are currently working on a re-write of OAuth and integrating it into Spring Security proper and it will provide support for OpenID Connect. You can track the issue [here](https://github.com/spring-projects/spring-security/issues/3907).
