### ISSUE TITLE
'RSA Signature did not match content' while validating token signature with valid RSA key

### ISSUE THREAD

**Issue by gwallet** [spring-projects/spring-security-oauth#1010]
## Symptom
Given a JSON Web Token
And using _security.oauth2.resource.jwk.key-set-uri_ property to load public RSA key
When validating the token signature with the public key
Then the validation failed with the message 'RSA Signature did not match content'

## Diagnosis
In method org.springframework.security.oauth2.provider.token.store.jwk.JwkDefinitionSource#createRsaVerifier RSA key is created starting from **modulus** and **exponent** as signed integer instead of _unsigned_ int like specified in RFC 7518 (6.3.1)

**Comment by jgrandja** [comment]
Hi @gwallet. Based on the **RSA Cryptography Specifications Version 2.1**, the following is stated in [Section 3.1 RSA public key](https://tools.ietf.org/html/rfc3447#section-3.1):

> For the purposes of this document, an RSA public key consists of two
>    components:
> 
>       n        the RSA modulus, a positive integer
>       e        the RSA public exponent, a positive integer
> 

Both the _modulus_ and _exponent_ are **prime numbers**.

So when the `JwkDefinitionSource.createRsaVerifier()` creates the `BigInteger` types for the _modulus_ and _exponent_, the `signum()` is 1 (positive) and expected because _modulus_ and _exponent_ must be a prime number.

Your test uses a negative number for the _modulus_ which is not correct as per spec.
I don't see any issues here unless I'm missing something?

**Comment by gwallet** [comment]
Thx for your answer @jgrandja

I guess we're in sync on one point: _modulus_ and _public exponent_ are positive integers.

After reading [RFC 7518 - JSON Web Algorithms - 6.3.1.1.  "n" (Modulus) Parameter](https://tools.ietf.org/html/rfc7518#section-6.3.1)

> The "n" (modulus) parameter contains the modulus value for the RSA public key.  It is represented as a Base64urlUInt-encoded value.
>
> Note that implementers have found that some cryptographic libraries prefix an extra zero-valued octet to the modulus representations they return, for instance, returning 257 octets for a 2048-bit key, rather than 256.  Implementations using such libraries will need to take care to omit the extra octet from the base64url-encoded representation.

I understand that we should read the Base64url decoded bytes as **unsigned int**

There are several implementations following this principle :
* [org.keycloak.jose.jwk.JWKParser#toPublicKey](https://github.com/keycloak/keycloak/blob/1aeec2a83c6677cd7dcfccb6ba2c39d10143b920/core/src/main/java/org/keycloak/jose/jwk/JWKParser.java#L67)
* [com.nimbusds.jose.jwk.RSAKey:1395](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/jwk/RSAKey.java?at=master&fileviewer=file-view-default#RSAKey.java-1395) using [com.nimbusds.jose.util.Base64URL#encode(BigInteger)](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/a730749c3831e429617d0cb4203303b36edfc6f2/src/main/java/com/nimbusds/jose/util/Base64URL.java?at=master&fileviewer=file-view-default#Base64URL.java-92)

We also should consider to omit the first `0x00` prefix if any
I can take care of it in the same PR if you want

**Comment by jgrandja** [comment]
Ok makes sense @gwallet.

Let's keep the change you have in the PR calling the `BigInteger` constructor with sign arg, for example, `new BigInteger(1, decoded)`.

One request I have is to the change the naming of the test to follow this naming convention:

`methodNameWhen<condition>Then<Expectation>`

Take a look at some of the tests in `JwkDefinitionSource` or `JwkVerifyingJwtAccessTokenConverterTest`

**Comment by gwallet** [comment]
Great!

PR has been updated

**Comment by RawSanj** [comment]
I was getting this -> https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-rsa-msimatch-L137 exception with Release 2.1.0 release.

So I copied all the files from https://github.com/spring-projects/spring-security-oauth/tree/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/store/jwk to an utility `package`, changed the TokenStore bean from `import org.springframework.security.oauth2.provider.token.store.jwk.JwkTokenStore` to `utilility.JwkTokenStore` and interestingly it worked without any modification (apart from fixing the reference from `org.springframework.security.oauth2.provider.token.store.jwk` to `utility` package).

The logs for  `utilility.JwkTokenStore` -> https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-no-exception-L133

Here is my configuration -> https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-oauth2serverconfiguration-java-L1

Any idea why first one doesn't work and second one does?

**Comment by gwallet** [comment]
Hi @RawSanj,

Did you have a look to the _modulus_ and _exponent_ of the RSA keys ?
(respectively **n** and **e** return from the URI you used in JwkTokenStore constructor)

**Comment by RawSanj** [comment]
Hi @gwallet 

I added debugger on RsaJwkDefinition and RsaVerifier for both scenarios i.e. when using `org.springframework.security.oauth2.provider.token.store.jwk.JwkTokenStore` from framework and when using `utilility.JwkTokenStore` (copy of classes from framework) and found that the RsaVerifier(..) constructor is getting Negative **n** values from framework while it is positive when used custom.

Debbuger Output:
1. JSON from Jwks_uri:  https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-json-from-jwks_uri
2. Values from RsaJwkDefinition(.....) for both case:  https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-debbuging-rsajwkdefinition
3. Values from RsaVerifier(.....) for both case:  https://gist.github.com/RawSanj/1ce64f5118de473e99555a81dfc65a98#file-debbuging-rsaverifier
Here the value of **n** differs.
