### ISSUE TITLE
Drop support for Jackson 1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security-oauth#1013]
Spring Security OAuth is one of only two projects where the version that's currently in Spring IO Platform Cairo has a dependency upon Jackson 1.

Can you please consider a new Spring Security OAuth release for Cairo that drops support for Jackson 1?

**Comment by jgrandja** [comment]
@wilkinsona Will look into this after I get back from vacation. I'm out all next week.

**Comment by jgrandja** [comment]
Hi @wilkinsona. The project is currently using both Jackson 1 and 2. There are quite a few usages to Jackson 1 throughout the code so before I put in the effort here, @rwinch and I would like to understand what issue this may be causing you with the Spring IO builds? As you may be aware, this project is unofficially in maintenance mode so we're limiting the time we invest here with bug fixes and smaller enhancements. Please let us know and we'll figure it out.

**Comment by wilkinsona** [comment]
Given Jackson 1's age and limited usage across the Platform, my hope was to reduce the Platform's scope a bit by getting rid of it. Every dependency has an ongoing maintenance cost so the fewer we have the better.

Perhaps an alternative would be to consider a timeline on which Spring Security OAuth is removed from the Platform in favour of the OAuth support that's appearing in Spring Security?

**Comment by jgrandja** [comment]
Hi @wilkinsona. Let me have a chat with @rwinch and see what path to take. I'm pretty sure end of life for Spring Security OAuth won't be for another year or two so we might have to take the path on removing Jackson 1.

**Comment by jgrandja** [comment]
@wilkinsona As per your suggestion...

> Perhaps an alternative would be to consider a timeline on which Spring Security OAuth is removed from the Platform in favour of the OAuth support that's appearing in Spring Security?

This will have to be the path that we take. Removing support for Jackson 1 involves deleting a number of `JsonSerializer` and `JsonDeserializer` implementations and we're not keen on removing these classes in a minor release. Note that we are not planning on any major releases going forward.

When we reach feature parity for OAuth support in Spring Security 5.x than we can remove Spring Security OAuth 2.x from platform. This [feature matrix](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) is what we are tracking against. We're planning on reaching feature parity by end of this year the latest but likely earlier.

**Comment by leonard84** [comment]
@jgrandja as feature parity was dropped and the new implementation is no full replacement for Spring Security OAuth 2, is there any hope for a fix here, as jackson1 has several CVEs, e.g., https://bugzilla.redhat.com/show_bug.cgi?id=1715075

**Comment by jgrandja** [comment]
@leonard84 Apologies for not closing off this issue. Jackson 1 was removed in the 2.4 release. See 21d14d9
