### ISSUE TITLE
Allow ability to set custom OAuth2AuthenticationDetailsSource via ResourceServerSecurityConfigurer

### ISSUE THREAD

**Issue by karldmoore** [spring-projects/spring-security-oauth#1019]
Whilst the OAuth2AuthenticationProcessingFilter contains a setter for its authenticationDetailsSource, this isn't exposed on ResourceServerSecurityConfigurer and so it's not simple to use a custom OAuth2AuthenticationDetailsSource implementation.  A setter just needs exposing so the default can be overriden.

**Comment by armandino** [comment]
+1. I need to capture some request headers when the /token endpoint is invoked. Not sure what would be the best approach to inject a custom `AuthenticationDetailsSource` into the `OAuth2AuthenticationProcessingFilter`.
