### ISSUE TITLE
What is the policy for pull requests for this project?

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-security-oauth#1044]
This project currently has 67 open pull requests. Many of them are quite old. I'm wondering what the project owner's policy is on pull requests. For me, and obviously for many others, some of the pull requests are very useful, and I'd love to see them being merged. 

Because my production code relies on one of these pending pull requests, my production code is currently using a forked version of this project, that includes the required changes. Obviously, this is not a situation I would like to be in for a long time, because it makes upgrading to newer versions quite cumbersome. I guess many other users are also relying on one or more pull requests, and are experiencing the same problems.

In my opinion, it would be very helpful if pull requests would be evaluated shortly after they're created. Rejecting a pull requests is also helpful, because it means that other users won't have to wait for it, make forks in the mean time, etc. 

Pull requests are a really useful way of receiving contributions. Please treat them carefully, and don't ignore them.

**Comment by jgrandja** [comment]
Hi @tomvandenberge 

First off, we would like to apologize for the delay in reviewing PR's and Issues.

Just so you are aware, we are very tight on resources, hence the delays in getting to these PR's/Issues. As well, this project is unofficially in **maintenance mode** as our efforts are currently focused on the new OAuth 2.0 support we are building in the core Spring Security project. You can track the new support for OAuth 2.0 in Spring Security 5.0 [here](https://github.com/spring-projects/spring-security/issues/3907).

Although this project is in maintenance mode it's not to say we won't merge any PR's. Bug fixes and minor enhancements will get merged but we are limiting new (major) features from being merged. Our main focus going forward is to build out the OAuth 2.0 and OpenID Connect 1.0 support into Spring Security proper along with the many other spec extensions built on top of OAuth and OIDC.

We are planning our 1st milestone release next week which will include the new OAuth support. After this release, I'll be able to dedicate some of my time to review the PR's and issues.

**Comment by tomvandenberge** [comment]
Hi Joe,
Thanks for the clarification. Does this mean that all of the spring-security-oauth project functionality will be part of spring-security? What does this mean for migrating from spring-security-oauth to spring-security 5.0.0 -- will there be any loss of functionality or other breaking changes? And can you already say something features that have been added?

**Comment by jgrandja** [comment]
@tomvandenberge the new OAuth 2.0 support in Spring Security 5.0 is a complete re-write and therefore we are not reusing code from the existing OAuth project.
The functionality being provided in the initial release is focused on the client-side support. You can see the current set of features on this [PR](https://github.com/spring-projects/spring-security/pull/4257) which will be merged to master soon.
We will focus on the server-side support (Authorization/Resource server) in a later release.

**Comment by jgrandja** [comment]
@tomvandenberge I'm closing this issue given I've answered your question. Please reopen if you feel I haven't.
