### ISSUE TITLE
TokenEndpoint exception handler logging exceptions as error with stacktraces?

### ISSUE THREAD

**Issue by phrinx** [spring-projects/spring-security-oauth#1047]
Looking at https://github.com/spring-projects/spring-security-oauth/blob/0651688c5ef21c85a3a58576380b04870c47b12c/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/TokenEndpoint.java#L166 it's hard to debug issues, especially in production, as most production systems don't log info/debug messages.

I'm wondering whether we could raise the log level to ERROR or at least WARN and ideally include the stack trace here? Anyone who is not interested in it can disable logging for the package/class but debug/info is IMO to verbose to debug actual issues.

**Comment by madmath03** [comment]
I think @jgrandja handled this in the latest version 2.2.1.RELEASE.
This issue could be closed.

**Comment by jgrandja** [comment]
@phrinx This has been resovved in the 2.2.1.RELEASE. See [commit](https://github.com/spring-projects/spring-security-oauth/commit/0bc2a67ff6ce5069652d7a5412e61e0f147ff78e)

**Comment by jbiblio** [comment]
FTR: The logging logic has been changed again with #1290.
