### ISSUE TITLE
Allow JwkTokenStore to be created with multiple JWK Set URLs

### ISSUE THREAD

**Issue by habuma** [spring-projects/spring-security-oauth#1050]
As it stands, JwkTokenStore only supports a single JWK Set URL. In SCS, we have potential for multiple token issuers (various UAA identity zones), and therefore multiple JWK Set URLs. 

JwkTokenStore should either support multiple JWK Set URLs or there should be a separate implementation (perhaps MultipleIssuerJwkTokenStore) that does support multiple issuers and JWK Set URLs.

**Comment by wojtekk** [comment]
Great job guys!

Can I use this feature based on a configuration in property file only?

If this is possible, I can't figure out how to that - could you provide any example?

**Comment by jgrandja** [comment]
@wojtekk Yes, the Spring boot property is `security.oauth2.resource.jwk.key-set-uri`. I noticed that it's not documented in the Spring Boot reference so I logged this [issue](https://github.com/spring-projects/spring-boot/issues/10022).

**Comment by jgrandja** [comment]
@wojtekk Also, keep in mind that this property supports **only one** JwkSet uri. If you want to specify more than one than you will have to log a new issue in the Spring Boot repo to add this.

**Comment by wojtekk** [comment]
@jgrandja thanks, I was thinking about multiple properties - I will do that (or maybe I will try to prepare PR)

**Comment by KishorBachhav** [comment]
I can see that support for multiple JWK Set URLs is added but how to specify multiple urls through properties file.
@wojtekk did you get chance to file a separate issue so that I can refer to the same rather than me filing duplicate.

**Comment by KishorBachhav** [comment]
Issue#1479 is filed to provide support to specify multiple urls through properties file
