### ISSUE TITLE
An issue with grant_type password and a trusted client

### ISSUE THREAD

**Issue by luchob** [spring-projects/spring-security-oauth#1058]
I would like to get an access token with a password grant as described [here](https://aaronparecki.com/oauth-2-simplified/#others), for example. This means that a similar request will be issued to get a token:

```
POST https://myserver.com/oauth/token
      grant_type=password&
      username=USERNAME&
      password=PASSWORD&
      client_id=CLIENT_ID
```

This seems OK and is hinted in the [RFC](https://tools.ietf.org/html/rfc6749#page-39). To implement all this it seems that I just should call `allowFormAuthenticationForClients()` of `AuthorizationServerSecurityConfigurer` which essentially enables `ClientCredentialsTokenEndpointFilter` in the filter chain. (a small javadoc would be very nice :-) ) See a sample configuration [here](https://github.com/luchob/oauth2-passwordgrant-example/blob/demo1/auth/src/main/java/eu/balev/demo/auth/config/OAuth2Config.java#L63-L69). Now the problems:

**Problem 1.** I'm forced to permit the check access token end point ( `checkTokenAccess("permitAll()")` ) for anyone because the `/oauth/check_token` endpoint is not considered into `ClientCredentialsTokenEndpointFilter`. That is because of the internal class `ClientCredentialsRequestMatcher`. IMHO this is a bug - why should the filter be available only for the `/oauth/token` endpoint and what am I supposed to do with a token that can't be verified?

**Problem 2.** This comes from the previous problem. If I open the check token endpoint (which was not recommended by @dsyer at StackOverflow) then I'm running into the next issue, namely [this one](https://github.com/spring-projects/spring-security-oauth/issues/717).

Is this really a bug or I miss something?

**Comment by dsyer** [comment]
Fair enough I guess. Some comments:

* You don't need to `allowFormAuthenticationForClients()` (and the RFC recommends that you don't). It's better to use HTTP Basic for client authentication.

* Form-based authentication would be equally bad for /check_token, but if you want to enable it you could add your own filter. Enabling it with `allowFormAuthenticationForClients()` would be a new feature, but it probably won't be a high priority, unless there is a PR.

* There's nothing forcing you to use `RemoteTokenServices`, and nothing preventing you from customizing it (as I pointed out in #717).

**Comment by luchob** [comment]
Dave, thanks for the quick answer!

I understand that it is better unless I have a client in which I can't hide the client secret. Well... I can use a "public" secret which is kind of funny workaround :-) I just wanted to go on without `client_secret`.

What I do not understand is why when I decide to allow form authentication for my client (`allowFormAuthenticationForClients()`) I can authenticate only for retrieving the token but not for checking it. You said that it is equally bad so why not? What can I do with a token that I can't verify?

If I have to implement my own filter I won't use `allowFormAuthenticationForClients()` at all. And as it seems to me if I want to use `allowFormAuthenticationForClients()` then I need to implement my own filter.

I'll think about the PR these days, 10x!

**Comment by dsyer** [comment]
> What can I do with a token that I can't verify?

Nothing. But no-one forces you to use `RemoteTokenServices`. You can implement that contract any way that you like.

A "public" secret might as well be empty. And you might as well use `permitAll()` at that point.

**Comment by luchob** [comment]
Dave, a basic auth with empty password and no form authentication may be a workaround. Then one may not call `allowFormAuthenticationForClients()`, the `RemoteTokenServices` will certainly work and the check token endpoint may still be secured. I want to thank you for your time. If you do not consider this a bug then please close the issue. If I ever have the time I'll try a PR someday.

**Comment by luchob** [comment]
Hi, I've added some lines of code that enable the form auth for the other endpoints. Hope I didn't screw something :-)

**Comment by johnpeterdev** [comment]
Hello , I also think this is a bug. And the workaround I see is to add a dummy client secret like you mentioned.  Not sure if the standard makes the client secret mandatory for Resource Owner Password Credentials Grant.

Another thing I see is that lets say if I want to create multiple clients. This setting is global. So lets say I want to have a client described here with no access to "/oauth/check_token", and a second client with access . 
I think there should be something like .allowFormAuthenticationForClients("client_id...")

**Comment by jgrandja** [comment]
@luchob Please see [comment](https://github.com/spring-projects/spring-security-oauth/pull/1061#pullrequestreview-408165633).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
