### ISSUE TITLE
Access token expiry issue

### ISSUE THREAD

**Issue by adddaina** [spring-projects/spring-security-oauth#1068]
The Auth server sets the OAuth2AccessToken expires_in field to a number different from 0 but the client receives the token with an expires_in = 0.
After doing some investigation, found out there seems to be an issue with how the access token is being deserialized, more specifically, the OAuth2AccessTokenJackson2Deserializer does not deserialize properly the expires_in field.

### OAuth Client receiving the token:

The client receives the access token and it contains the 'expires_in' field with a text value different from 0.
`(Token stream: state=2 attr#=0 nextAttr#=0 name=expires_in text=5999982 repeat?=0 wrapper=[null] repeatElement=0 nextName=null)`
The client deserialization seems to be able to handle both scenarios in which the field value contains text or number but not quite succeeds:
```
public final class OAuth2AccessTokenJackson2Deserializer extends StdDeserializer<OAuth2AccessToken> {
...
	@Override
	public OAuth2AccessToken deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException,
			JsonProcessingException {
...
		while (jp.nextToken() != JsonToken.END_OBJECT) {
...
			else if (OAuth2AccessToken.EXPIRES_IN.equals(name)) {
				try {
					expiresIn = jp.getLongValue();
				} catch (JsonParseException e) {
					expiresIn = Long.valueOf(jp.getText());
				}
			}
```
The try catch block suggests that the field value is either number(try) and if not, an exception is thrown and it is text(catch). The problem is that JsonParser.getLongValue() does not throw JsonParseException if the field value is string, it simply returns 0.

### Auth server sending the token:

The Auth server uses OAuth2AccessTokenJackson2Serializer to add the expiration in seconds property as a number field:
```
public final class OAuth2AccessTokenJackson2Serializer extends StdSerializer<OAuth2AccessToken> {
//...

	@Override
	public void serialize(OAuth2AccessToken token, JsonGenerator jgen, SerializerProvider provider) throws IOException,
			JsonGenerationException {
//...
		Date expiration = token.getExpiration();
		if (expiration != null) {
			long now = System.currentTimeMillis();
			jgen.writeNumberField(OAuth2AccessToken.EXPIRES_IN, (expiration.getTime() - now) / 1000);
```

**Comment by alatushkin** [comment]
Looks like #1172

**Comment by jgrandja** [comment]
Closing as duplicate of #1172
