### ISSUE TITLE
Build against Spring Framework 5

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-oauth#1069]
The current codebase should be able to build against the latest snapshot of Spring Framework 5.

**Comment by Edholm** [comment]
I guess this will fix the removal of Base64 in spring-projects/spring-security@85719fcd6473ef167e58634f2e5cf1fce900b850 ?

**Comment by jgrandja** [comment]
@Edholm The current version of Spring Security used is 3.2.10.RELEASE and we're not planning on updating the dependencies at this time. Also, we still need to support Java 6 as well.
The work to be performed for this issue is to add a Maven profile that will update the dependency versions and ensure it build against Spring Framework 5. The default build profile will remain unchanged.
