### ISSUE TITLE
JwkSetConverter should handle arrays e.g x5c

### ISSUE THREAD

**Issue by nealeu** [spring-projects/spring-security-oauth#1082]
We're trying to use Auth0, but JwkSetConverter is only set up to handle strings, yet x5c is an array (as specified at https://tools.ietf.org/html/rfc7515#section-4.1.6), so the parsing blows up.

Is the workaround as simple as fix as it may appear (skip the x5 fields)?

**Comment by jgrandja** [comment]
@nealeu The `JwkSetConverter` supports a small subset of the available attributes in a JWK, which doesn't include the x5 attributes. However, I did spot the bug in the converter related to this issue.
Thanks for reporting this. I'll do my best to get a fix in over the next week or so after I finish some other priority items.

**Comment by nealeu** [comment]
Thanks @jgrandja

**Comment by nealeu** [comment]
@jgrandja #1087 will hopefully be adequate.  Can you ensure it gets onto 2.0.x too.

**Comment by jgrandja** [comment]
Hi @nealeu. This fix has been merged to master and will also get into 2.0.x. Thanks!

**Comment by nealeu** [comment]
Hi @jgrandja,

Any chance of you cutting 2.0.15 release so we've got this on a release build.

Cheers,

Neale

**Comment by jgrandja** [comment]
@nealeu I haven't scheduled 2.0.15 as of yet. However, 2.2.0 contains this fix. I would encourage you to upgrade to this latest release.
