### ISSUE TITLE
angular 2 / 4 hash location strategy and redirect_uri integration issue

### ISSUE THREAD

**Issue by stevenleadbeater** [spring-projects/spring-security-oauth#1084]
When using has location strategy routing in angular 2 / 4 URLs look like this: 

http://server/#/authorization-redirect-handler

If I pass a URL of this format to the oauth/authorize endpoint as the redirect_uri when using a response type of code, the 302 redirect spring security oauth returns looks like this: 

http://server?code=gh35jsw/#/authorization-redirect-handler

this doesn't work with angular 2 / 4 as the URL should be:

http://server/#/authorization-redirect-handler?code=gh35jsw

I've looked in to the code in  spring-security-oauth/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/AuthorizationEndpoint.java 
and in the following function:

```java
private String getSuccessfulRedirect(AuthorizationRequest authorizationRequest, String authorizationCode) {

		if (authorizationCode == null) {
			throw new IllegalStateException("No authorization code found in the current request scope.");
		}

		Map<String, String> query = new LinkedHashMap<String, String>();
		query.put("code", authorizationCode);

		String state = authorizationRequest.getState();
		if (state != null) {
			query.put("state", state);
		}

		return append(authorizationRequest.getRedirectUri(), query, false);
}
```
the 
```java
return append(authorizationRequest.getRedirectUri(), query, false);
```
line takes a fragment parameter hard coded to false. Changing that to true produces the URL in the format angular 2 / 4 is expecting. I would like to suggest externalizing that parameter to a config item. For example controlling it through supportClientHashRouting() when configuring the HttpSecurity object or enableUrlFragmentForClientRouting() or enableNg2HashRoutingSupport. I'm happy to do this myself if you guys will look at the PR for me when it's ready? Please let me know

**Comment by AmitBisht14** [comment]
Facing the same issue, while using Twitter OAuth

**Comment by stevenleadbeater** [comment]
Unfortunately, the hash fragment portion of the url is a browser side page reference. According to the http specs, the browsers aren't supposed to send anything after the hash to the server. Changing this is probably not going to work on all platforms and even if it does, it relies on off specification functionality so it shouldn't be implemented. If this causes you issues, you need to switch to PathLocationStrategy in ng2 and 4. There are a couple of caveats around making that work with the redirects, I'll try get the solution written up and link to it here for anyone else who comes across the problem

**Comment by LeoNdec** [comment]
I am facing the same issue.  Has anyone found a solution yet?

**Comment by stevenleadbeater** [comment]
Using path location strategy in @Angular works. I've had it in prod now for over a year. You absolutely shouldn't use the hash location strategy for this sort of redirect parameter as you can't guarantee that a browser will send the portion after the hash.
