### ISSUE TITLE
Potential Race Conditions in JwkDefinitionSource

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth#1105]
There is a potential race condition between the clearing out of the mappings and putting the entries in. This should be a single operation.

`JwkVerifyingJwtAccessTokenConverter decode` also has a race condition where a `JwkDefinition` might be found, another thread reloads the definitions which no longer contains the key id, then the `SignatureVerifier` is not found but a `JwkDefinition` is.

**Comment by jgrandja** [comment]
Resolved via beb0ea6 and 27f9f1d
