### ISSUE TITLE
Cannot build library

### ISSUE THREAD

**Issue by osgafarov** [spring-projects/spring-security-oauth#1123]
Hi, 

I have forked the repo and when I try to run:
```mvn install -P bootstrap```

I get errors in tests, here is one of them:

> testGetAccessTokenForDeletedUser(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests): Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused

Does it mean I should configure Redis? Or there is an additional step that is not documented on the wiki?

Thanks,
Osman

**Comment by jgrandja** [comment]
@osgafarov Yes, you need a local Redis server running as the build process requires it. Also, you don't need to activate any profiles to run the build locally.
