### ISSUE TITLE
Why I using bearer token access resource get 403?

### ISSUE THREAD

**Issue by jast90** [spring-projects/spring-security-oauth#1133]
I using client_credentials grant type  get a access token like as follows 
```
{
    "access_token": "11230f43-358a-44bb-b57e-f9652a44ede0",
    "token_type": "bearer",
    "expires_in": 43198,
    "scope": "read write"
}
```
Then i have resource `/me`
I using this access token to access the resource.
The request i had add a `Authorization` header the value is `Bearer 11230f43-358a-44bb-b57e-f9652a44ede0` i get 403 error.
Web security configuration is 
```
 @Override
    protected void configure(HttpSecurity http) throws Exception {
            http
                /*.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()*/
                .csrf().disable().authorizeRequests()
                .antMatchers("/resources/**"
                        , "/webjars/**"
                        , "/swagger-ui.html", "/webjars/springfox-swagger-ui"
                        , "/webjars/springfox-swagger-ui/o2c.html", "/v2/api-docs"
                        , "/swagger-resources/configuration/ui", "/swagger-resources"
                        , "/swagger-resources/configuration/security", "/oauth/authorize")
                .permitAll()
                .anyRequest().authenticated()/*.and().formLogin().and().httpBasic()*/
        ;
    }
```
If  no configuration extends WebSecurityConfigurerAdapter I can access resource using access token. The WebSecurityConfigurerAdapter and ResourceServerConfigurerAdapter has conflict?How can I configure some resources of a resource server  that everybody can access?

**Comment by adolfoweloy** [comment]
@jast90, there's no conflict between `WebSecurityConfigurerAdapter` and `ResourceServerConfigurerAdapter`.

 As I know you just have to make sure your URL patterns does not match for both security settings.
