### ISSUE TITLE
How could I customize the authorization error json?

### ISSUE THREAD

**Issue by pakkk** [spring-projects/spring-security-oauth#1149]
Hello,

I was wondering if I could customize the following authorization error:

```
{
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}
```

I get it when the user request does not have permissions. And I would like to customize it to be quite similar than Spring Boot error:

```
{
 "timestamp":1445441285803,
 "status":401,
 "error":"Unauthorized",
 "message":"Bad credentials",
 "path":"/oauth/token"
}
```

Could it be possible?

Many thanks.

Regards,
Paco.

**Comment by duergner** [comment]
@pakkk you might want to have a look at https://github.com/zalando/problem-spring-web which has support for Problem JSON error responses for Spring Web MVC (incl. Spring Security related errors)

**Comment by hamzahanafi11** [comment]
Hi @pakkk , 

You can customize all your exceptions attributes thrown as json by overriding the default attributes like below : 

``` java
@Bean
public ErrorAttributes errorAttributes() {
    return new DefaultErrorAttributes() {
        @Override
        public Map<String, Object> getErrorAttributes(RequestAttributes requestAttributes, boolean includeStackTrace) {
            Map<String, Object> errorAttributes = super.getErrorAttributes(requestAttributes, includeStackTrace);
            Throwable error = getError(requestAttributes);
            // of course you can customize any exception ( e.g : bad requests )
            if(error instanceof AccessDeniedException){
                errorAttributes.clear();
                errorAttributes.put("error", "unauthorized");
                errorAttributes.put("error_description", "Full authentication is required to access this resource");
            }
         return errorAttributes;
        }
    };
}
```

hope this help

**Comment by hamzahanafi11** [comment]
@duergner I think this issue is to close

**Comment by duergner** [comment]
Agree

**Comment by 15116339234** [comment]
Excuse me, are you the problem solved

**Comment by mxmlnglt** [comment]
> Hi @pakkk ,
> 
> You can customize all your exceptions attributes thrown as json by overriding the default attributes like below :
> 
> ```java
> @Bean
> public ErrorAttributes errorAttributes() {
>     return new DefaultErrorAttributes() {
>         @Override
>         public Map<String, Object> getErrorAttributes(RequestAttributes requestAttributes, boolean includeStackTrace) {
>             Map<String, Object> errorAttributes = super.getErrorAttributes(requestAttributes, includeStackTrace);
>             Throwable error = getError(requestAttributes);
>             // of course you can customize any exception ( e.g : bad requests )
>             if(error instanceof AccessDeniedException){
>                 errorAttributes.clear();
>                 errorAttributes.put("error", "unauthorized");
>                 errorAttributes.put("error_description", "Full authentication is required to access this resource");
>             }
>          return errorAttributes;
>         }
>     };
> }
> ```
> 
> hope this help

Hello, where does this go?

And what does it overrides?

**Comment by hamzahanafi11** [comment]
this is a bean object which will be loaded at startup, you can just place it anywhere you want (e.g a configuration class) just be sure it is scaned by spring
> > Hi @pakkk ,
> 
> > 
> 
> > You can customize all your exceptions attributes thrown as json by overriding the default attributes like below :
> 
> > 
> 
> > ```java
> 
> > @Bean
> 
> > public ErrorAttributes errorAttributes() {
> 
> >     return new DefaultErrorAttributes() {
> 
> >         @Override
> 
> >         public Map<String, Object> getErrorAttributes(RequestAttributes requestAttributes, boolean includeStackTrace) {
> 
> >             Map<String, Object> errorAttributes = super.getErrorAttributes(requestAttributes, includeStackTrace);
> 
> >             Throwable error = getError(requestAttributes);
> 
> >             // of course you can customize any exception ( e.g : bad requests )
> 
> >             if(error instanceof AccessDeniedException){
> 
> >                 errorAttributes.clear();
> 
> >                 errorAttributes.put("error", "unauthorized");
> 
> >                 errorAttributes.put("error_description", "Full authentication is required to access this resource");
> 
> >             }
> 
> >          return errorAttributes;
> 
> >         }
> 
> >     };
> 
> > }
> 
> > ```
> 
> > 
> 
> > hope this help
> 
> 
> 
> Hello, where should this piece of code go?
> 
> 
> 
> And what method does it override?

**Comment by mxmlnglt** [comment]
Ah.

I think the question was the other way round... NOT to get this JSON response with only "error" and "error_description" fields, but all the fields similar to default Sprint Boot error ("timestamp", "status", "error", "message", "path").

The thing is, I can't get where this `{ "error", "error_description" }` JSON is generated...

**Comment by jzheaux** [comment]
@pakkk glad you are getting the help you are looking for.

I'm going to close this ticket as a `question`, but please feel free to continue as needed.
