### ISSUE TITLE
Scopes not presented for user's approval page when using JWT

### ISSUE THREAD

**Issue by adolfoweloy** [spring-projects/spring-security-oauth#1155]
I have experienced that when using JWT, the scopes isn't being presented to the user's approval page. I am adding JWT support by declaring a `JwtTokenStore` bean as follows.

```java
@Bean
public JwtTokenStore tokenStore() {
    return new JwtTokenStore(accessTokenConverter());
}
``` 
When a tokenStore is defined, a `TokenStoreUserApprovalHandler` is created and it does not propagate scopes from request to the respective model attributes. Maybe it should be similar to what happens inside `ApprovalStoreUserApprovalHandler.getUserApprovalRequest` because even when working with JWT there should be useful to present required scopes on user's approval page.

I saw that when `AuthorizationServerEndpointsConfigurer` is configured with `approvalStoreDisabled`, a `TokenStoreUserApprovalHandler` is defined and it's expected to not return scopes in the approval model, so it constrained me to simply add scopes to the approval model inside `TokenStoreUserApprovalHandler`.

I would like to know if it could be considered an issue that deserves some Pull Request.

**Comment by jgrandja** [comment]
@adolfoweloy Please see [comment](https://github.com/spring-projects/spring-security-oauth/pull/1157#pullrequestreview-408146641)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
