### ISSUE TITLE
JwkSetConverter: KID should be optional

### ISSUE THREAD

**Issue by khamlaoui** [spring-projects/spring-security-oauth#1179]
Hello,

Regarding RFC 7517 the value of "kid"  should be optional.

_The value of "kid" (key ID) parameter is used to match a specific key.  This
   is used, for instance, to choose among a set of keys within a JWK Set
   during key rollover.  The structure of the "kid" value is
   unspecified.  When "kid" values are used within a JWK Set, different
   keys within the JWK Set SHOULD use distinct "kid" values.  (One
   example in which different keys might use the same "kid" value is if
   they have different "kty" (key type) values but are considered to be
   equivalent alternatives by the application using them.)  The "kid"
   value is a case-sensitive string.  Use of this member is OPTIONAL.
   When used with JWS or JWE, the "kid" value is used to match a JWS or
   JWE "kid" Header Parameter value._

However, actually the kid is mandatory inside JwtSetConverter class.

Is it possible to change the strategy as fellow:
If the KID is nul and there is one key so get the first one?

Thanks
Regards

**Comment by jgrandja** [comment]
@khamlaoui Yes, the `kid` is optional as per spec, however, `JwkDefinitionSource` requires a mapping of `kid` to `JwkDefinitionHolder`:

`private final Map<String, JwkDefinitionHolder> jwkDefinitions = new ConcurrentHashMap<String, JwkDefinitionHolder>();`

This is how the key selection has been implemented for `JwkTokenStore`, it matches on the `kid` from the `JWT` Jose header and the `kid` mapped in `JwkDefinitionSource.jwkDefinitions`.

I'm closing this issue as it's been implemented as designed.

**Comment by khamlaoui** [comment]
@jgrandja Thanks for your quick response.
I have a case with our IDP (NetIQ) that expose the metadata url to retrieve the keys, and there is just one key (which don't contain a kid).
I could make a pull request with my changes and you could take a look at it please ?

My idea is: if we have only one key, so we could generate random kid, and when we try to map it, i will first search by kid, if no match exist a retrieve the first key if i have just one.

Thanks
Regards

**Comment by blackandcold** [comment]
Old topic but I have the same problem @khamlaoui found a solution to this? NetIQ still has no kid provided in the JWK list but is set in the header of the token..
