### ISSUE TITLE
ClientDetails should Collection<? extends GrantedAuthority> getAuthorities() like UserDetails

### ISSUE THREAD

**Issue by kopax** [spring-projects/spring-security-oauth#1186]
I am facing a bug while implementing my client.

We have to use a ClientDetails for authentication, this interface discribed here:

https://github.com/spring-projects/spring-security-oauth/blob/0f732e48f2ec967756003758c6134bb1230671e2/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/ClientDetails.java#L82

needs to have an object type `Collection<GrantedAuthority>` instead of `Collection<? extends GrantedAuthority>` like in **[UserDetails](https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/core/userdetails/UserDetails.html)**:

https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/userdetails/UserDetails.java#L54

This result in dumb code to convert the list, is it possible to patch it ?

**Comment by icemagno** [comment]
I think you must:

```
@Entity
@Table(name = "users")
public class User implements UserDetails {
      ......
      @OneToMany(orphanRemoval=true,  mappedBy="user", fetch = FetchType.EAGER)
      @Cascade(org.hibernate.annotations.CascadeType.ALL)
      private List<UserRoles> roles;

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
            return this.roles;
        }
        ......
}
```

... and then:

```
@Entity
@Table(name = "users_roles")
public class UserRoles implements GrantedAuthority {

	@Override
	public String getAuthority() {
		return this.getRoleName();
	}	
	@ManyToOne()
	@JoinColumn(name="user_id", foreignKey = @ForeignKey(name = "fk_datalayer_server"))
	private User user;

}
```

**Comment by jgrandja** [comment]
This change cannot be applied since it will break existing applications. See [comment](https://github.com/spring-projects/spring-security-oauth/pull/1456#pullrequestreview-387548133)
