### ISSUE TITLE
Support for multiple RSA signing/verification keys

### ISSUE THREAD

**Issue by yyunikov** [spring-projects/spring-security-oauth#1201]
We have a use case, when for some of our resources we need to have multiple signing keys. Currently, there are no option to have multiple RSA signing/verification keys. With `JwtAccessTokenConverter` implementation it is possible to set only one. Also, `/oauth/token_key` endpoint returns only one public key. It can possibly provide different key depending on the `client_id` or `Principal`.

**Comment by jgrandja** [comment]
@yyunikov Take a look at `JwkTokenStore` as it provides support for Providers that expose multiple signing keys via a [JWK](https://tools.ietf.org/html/rfc7517) Set.

**Comment by matyee** [comment]
@jgrandja I am checking the code of `JWKTokenStore` for a while now, but I do not see how multiple keys are supported. The key handling is done by a `JwtAccessTokenConverter` that handles only one signing and verifying key pair. Could you please let me know what you meant in more details?

**Comment by jgrandja** [comment]
@matyee `JwkTokenStore` is meant to be used by Resource Server's only. It uses a `JwkVerifyingJwtAccessTokenConverter` (look at the constructor in `JwkTokenStore`) for verifying the signature and obtains the Public Key(s) using a `JwkDefinitionSource` which fetches the keys from the Authorization Server's JWK Set Url.

Just to be clear, this support is for Resource Server only. There is no support for the Authorization Server side where it manages and exposes these keys via the JWK Set endpoint.

**Comment by chrisoberle** [comment]
@jgrandja  Thanks Joe...this works beautifully.   I'm wondering if there are plans to add Authorization server support in the future?

**Comment by jgrandja** [comment]
@chrisoberle There are no plans to add JWK support. As an FYI, this project is in maintenance mode as our efforts are focused in building the new OAuth support in Spring Security 5. Please see this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for more details.

For your reference, see this [sample](https://github.com/jgrandja/spring-security-oauth-sample/commits/oauth-apps) which exposes a JWK Set via the Authorization Server using Nimbus JOSE library.
