### ISSUE TITLE
JwtHelper.decodeAndVerify method unable to verify valid JWS signatures if base64 string contains padding (=)

### ISSUE THREAD

**Issue by rozaydin** [spring-projects/spring-security-oauth#1205]
When using **spring-security-jwt** with JWTs generated by other parties, although valid **JwtHelper.decodeAndVerify** intermittently fails saying that the signature is invalid, we realized if the jwt claims part (in base64url encoded format) contains padding (=) at the end signature check fails. I have created a GIST demonstrating this issue [(link)](https://gist.github.com/rozaydin/d48c303c7869e4332362f8be0faab317) problem seems to be related with base64URL encoding and decoding when this happens the equals signs at the end are removed and hash calculated with the wrong input. Please let me know if gist is not enough and if you need logs etc.

**Comment by CRYX2** [comment]
Same problem, it's a bit annoying...

**Comment by khamlaoui** [comment]
same problem

**Comment by jgrandja** [comment]
@rozaydin I took a look at your gist and the JWT format is Base64 encoded **NOT** Base64 Url encoded, which is why your test is failing. **It has to be Base64 Url encoded**.

Here is your test:

```
@Test
public void base64Test() {
	// base64TestStr is Base64 encoded...it is NOT Base64 URL encoded
	String base64TestStr = "eyJpc3MiOiIwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMSIsInN1YiI6IjAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxIiwiYXVkIjoiTWluZFNwaGVyZSBBUyIsImlhdCI6MTUwOTM1MjI5NywibmJmIjoxNTA5MzUyMjk3LCJleHAiOjE1MDk0Mzg2OTcsInNjaGVtYXMiOlsidXJuOnNpZW1lbnM6bWluZHNwaGVyZTp2MSJdLCJ0ZW4iOiJ0ZXN0LXRlbmFudCIsImp0aSI6IjkxODE3YTJkLTU0ZjQtNDQ1OC04YTI5LWU5MGU5ZDQ3YTViIn0=";

	// Here you are encoding/decoding using Base64 URL,
	// but the data format is Base64 encoded, which is why the test is failing
	String base64StrOutput = new String(b64UrlEncode(b64UrlDecode(base64TestStr)));

	assertEquals(base64StrOutput, base64TestStr);
}
```

And here is the updated (and passing) test:

```
@Test
public void base64Test_updated() {
	String base64TestStr = "eyJpc3MiOiIwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMSIsInN1YiI6IjAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxIiwiYXVkIjoiTWluZFNwaGVyZSBBUyIsImlhdCI6MTUwOTM1MjI5NywibmJmIjoxNTA5MzUyMjk3LCJleHAiOjE1MDk0Mzg2OTcsInNjaGVtYXMiOlsidXJuOnNpZW1lbnM6bWluZHNwaGVyZTp2MSJdLCJ0ZW4iOiJ0ZXN0LXRlbmFudCIsImp0aSI6IjkxODE3YTJkLTU0ZjQtNDQ1OC04YTI5LWU5MGU5ZDQ3YTViIn0=";

	// Using b64Encode/b64Decode instead of b64UrlEncode/b64UrlDecode
	String base64StrOutput = new String(b64Encode(b64Decode(base64TestStr.getBytes())));

	assertEquals(base64StrOutput, base64TestStr);
}
```

You need to ensure the provider you are using is generating JWT's in Base64 Url encoded format, as defined by the [spec](https://tools.ietf.org/html/rfc7519#section-3):

> A JWT is represented as a sequence of URL-safe parts separated by
>    period ('.') characters.  Each part contains a base64url-encoded
>    value.
> 

I'm going to close this issue as things work as expected.
