### ISSUE TITLE
RedisTokenStore giving MethodNotFoundException 

### ISSUE THREAD

**Issue by pedroxs** [spring-projects/spring-security-oauth#1206]
Latest version of RedisConnection from spring-data-redis has changed its interface contracts and this is breaking the token store [#L160](https://github.com/spring-projects/spring-security-oauth/blob/0f732e48f2ec967756003758c6134bb1230671e2/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/store/redis/RedisTokenStore.java#L160).

- versions of dependencies:
  Gradle: org.springframework.data:spring-data-redis:2.0.0.RELEASE
  Gradle: org.springframework.security.oauth:spring-security-oauth2:2.2.0.RELEASE

**Comment by rieonke** [comment]
see #1230

**Comment by jgrandja** [comment]
@pedroxs See [comment](https://github.com/spring-projects/spring-security-oauth/issues/1230#issuecomment-345958098).

You can explicitly declare your dependencies in your POM or gradle file to use `spring-date-redis` 2.0.1.RELEASE and `jedis` 2.9.0.
