### ISSUE TITLE
JWK Set parsing fails if provider's set contains non-RSA keys

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security-oauth#1213]
Our OIDC Provider supports multiple JWS algorithms for signing access tokens and ID tokens, and therefore its `jwks_uri` provides both RSA and EC keys. For example:

```json
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "B9ch",
      "n": "..."
    },
    {
      "kty": "EC",
      "use": "sig",
      "crv": "P-256",
      "kid": "J3DJ",
      "x": "...",
      "y": "..."
    },
    {
      "kty": "EC",
      "use": "sig",
      "crv": "P-384",
      "kid": "uNgL",
      "x": "...",
      "y": "..."
    },
    {
      "kty": "EC",
      "use": "sig",
      "crv": "P-521",
      "kid": "YW0I",
      "x": "...",
      "y": "..."
    }
  ]
}
```

Unfortunately, Spring Security OAuth is unable to handle such JWK Set since `JwkSetConverter#createJwkDefinition` throws `JwkException` the moment it runs into a non-RSA key, regardless of the fact that JWK Set actually does contain an RSA key.

IMO the behavior of the JWK Set parsing should be changed to ignore the keys of unsupported types, until #1159 gets merged, which is currently targeted at the `2.3.0` release. This affects `2.0.x`/`2.1.x`/`2.2.x`.

I could put together a PR to address this in time for `2.2.1` release if we agree on the general approach on the changes to be made.

**Comment by jgrandja** [comment]
@vpavic Updating to ignore unsupported keys instead of throwing works for me. If you could put together a PR for this that would be great.
