### ISSUE TITLE
`JwtAccessTokenConverter` uses non-standard `client_id` and `scope` claims

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security-oauth#1214]
`JwtAccessTokenConverter` attempts to extract information about client ID and scope from non-standard claims named `client_id` and `scope`, respectively. This behavior is actually encapsulated in `DefaultAccessTokenConverter` to which `JwtAccessTokenConverter` delegates to, and the constants used for claim names are defined in `AccessTokenConverter` interface.

Our OIDC Provider aligns with the [OAuth 2.0 Token Exchange (draft-ietf-oauth-token-exchange-09)](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-09) which defines the following JWT claims:

- ["scp" (Scopes) Claim](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-09#section-4.2)
- ["cid" (Client Identifier) Claim](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-09#section-4.3)

It would be nice if `JwtAccessTokenConverter` would allow to specify the claims to be used to obtain client ID and scope information, since the currently used ones are non-standard.

**Comment by jgrandja** [comment]
@vpavic Would you be interested or have time to submit a PR for this? I can have it merged for upcoming 2.3.RC1.

**Comment by vpavic** [comment]
Thanks for the feedback @jgrandja. I'll try to take a look at this by the end of the week.

**Comment by evh69** [comment]
I have a use for the improvement that allows one to set the value of the scope attribute.  Is there a way to use "DefaultAccessTokenConverter" and still use the autoconfiguration provided with the OOTB @EnableResourceServer configuration?  I am struggling to see how one can adjust the configuration to use the "DefaultAccessTokenConverter" without exposing the JwkVerifyingJwtAccessTOkenConverter as public (or) creating a copy of it and other private classes.
