### ISSUE TITLE
OAuth2AccessTokenSupport.OAuth2AuthTokenCallback should not log form data

### ISSUE THREAD

**Issue by bhardwick** [spring-projects/spring-security-oauth#1218]
When using the password credentials grant, usernames and passwords are submitted as form data to the authorization server. In OAuth2AccessTokenSupport.OAuth2AuthTokenCallback, the form data is printed in the client application logs in plain text when debug logging is enabled (before the form post is submitted). This should be removed.

My temporary solution was to extend ResourceOwnerPasswordAccessTokenProvider and override the getRequestCallback() method.

**Comment by jgrandja** [comment]
Thanks for the report @bhardwick. This has been updated in master.

**Comment by XDaRangerX** [comment]
the password is still logged in OAuth2AuthTokenCallback.
Project: spring-security-oauth2
Version: 2.3.5
