### ISSUE TITLE
Spring Boot 2.x support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth#1240]
Spring Boot 1.x provided integration with spring-security-oauth project that has been removed in Spring Boot 2.x in favor of Spring Security 5. Spring Boot does not want to provide support for spring-security-oauth going forward since going forward Spring Security 5 is the recommendation for OAuth.

Spring Security 5 plans to provide all the features found in spring-security-oauth, but does not yet do so. For example, it is missing RestTemplate integration, resource server, and authorization server support.

We should provide a jar that provides the Spring Boot 1.x OAuth integration for Spring Boot 2. This jar's life cycle will be maintained along with spring-security-oauth project and allow users to continue to support the workflows they had in Spring Boot 1.x with spring-security-oauth until Spring Security 5 OAuth support is ready to be fully migrated to.

**Comment by denis111** [comment]
When I add it to Spring Boot 2 project and it works fine, i just dislike the dependency on Jackson 1.

**Comment by rwinch** [comment]
This has been fixed via https://github.com/spring-projects/spring-security-oauth2-boot
