### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by xugc** [spring-projects/spring-security-oauth#1241]
![duplicateentry](https://user-images.githubusercontent.com/12759354/33467148-5eee899a-d68d-11e7-83cd-0d8e1dc200df.png)
create  access token is not thread-safe with db(mysql)
when 100 clients with same client_id and scopes request,app throws this exception
I find that happened because of mysql transaction isolation level default is repeatable after tracing the source code .

**Comment by kopax** [comment]
Did you find a way to fix it?

**Comment by kopax** [comment]
Could you show me how did you fix it? I don't know redis nor redis-lock. How the unique index in db did help?

**Comment by jgrandja** [comment]
Duplicate of #1242.

**Comment by xugc** [comment]
@kopax I have use unique index and redis-lock solve the issue, and lock the authentication_id.The same time only one with same authentication_id can get the lock
@jgrandja can I do like this?
