### ISSUE TITLE
Unable to parse 1024 bit RSA public key in SSH-RSA format

### ISSUE THREAD

**Issue by shilei812** [spring-projects/spring-security-oauth#1245]
How to reproduce?

security.oauth2.resource.jwt.key-value=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCQDWJsmWXn/0X1KySdboIL/LjP/Hr5Pqqe9y1m3IXeIsq/SqZujH6JFppCKd7TD3PkN1SjatJna4wiHSoR+39ffa2Mk3EvcdmCiAE4VbzD9NeirKDtCgrwP/9Ysg8odDGvkGkbvc/jDXiwAPMmUUqVxuS1/ziWgcJgcDlhJdj17Q== abc

This is a 1024bit RSA public key.

Spring boot outputs error.
Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)

**Comment by shilei812** [comment]
pull request:
https://github.com/spring-projects/spring-security-oauth/pull/1246

**Comment by jgrandja** [comment]
@shilei812 Please see [comment](https://github.com/spring-projects/spring-security-oauth/pull/1246#issuecomment-624411696)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
