### ISSUE TITLE
Full authentication is required to access this resource path:oauth/token

### ISSUE THREAD

**Issue by MrSummer33** [spring-projects/spring-security-oauth#1284]
when i call the EndPoint "**oauth/token**" for a access token , i get a http status 401 "Full authentication is required to access this resource path" 
there is my url "http://localhost:9999/oauth/token?grant_type=password&client_id=xiaxi-client&client_secret=xiaxi-secret&username=xiaxi&password=123456"

**Comment by trueKiller07** [comment]
public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {

		security.allowFormAuthenticationForClients();
	}

**allowFormAuthenticationForClients** will solve your problem.
