### ISSUE TITLE
OAuthClientHttpRequestFactory doesn't get its additionalOAuthParameters from the ProtectedResourceDetails

### ISSUE THREAD

**Issue by kutsal** [spring-projects/spring-security-oauth#1286]
While trying to set an empty `oauth_token` on a `BaseProtectedResourceDetails` object via `        resource.setAdditionalParameters(singletonMap("oauth_token", ""))`, I noticed `OAuthClientHttpRequestFactory` simply doesn't copy the resource's `additionalParameters` map into its `additionalOAuthParameters` collection.

I created PR #1280 which fixes this issue.

**Comment by jgrandja** [comment]
Could you not use `OAuthClientHttpRequestFactory.setAdditionalOAuthParameters`?

**Comment by kutsal** [comment]
@jgrandja I could, and I did at first. But,

```java
@Bean
public ProtectedResourceDetails fooResource() {
	BaseProtectedResourceDetails resource = new BaseProtectedResourceDetails();
	resource.setConsumerKey("myKey");
	resource.setSignatureMethod("RSA-SHA1");
	resource.setAdditionalParameters(Collections.singletonMap("oauth_token", ""));
	resource.setSharedSecret(new RSAKeySecret("secret", null));
	return resource;
}

@Bean
public RestTemplate foo(ProtectedResourceDetails fooResource, ClientHttpRequestFactory httpFactory) {
	OAuthClientHttpRequestFactory oAuthHttpFactory = new OAuthClientHttpRequestFactory(httpFactory, fooResource, new CoreOAuthConsumerSupport());
	oAuthHttpFactory.setAdditionalOAuthParameters(fooResource.getAdditionalParameters());
	OAuthRestTemplate template = new OAuthRestTemplate(oAuthHttpFactory, fooResource);
	template.setInterceptors(Arrays.asList(new MyHeaderInterceptor());
	return template;
}
```

`ProtectedResourceDetails` has to be passed to both `OAuthRestTemplate` _and_ `OAuthClientHttpRequestFactory` **and** I need to call a set method on the factory and pass the additional parameters I just put into the protected resource it's wrapping. Moreover, `OAuthRestTemplate` *creates* an instance of `OAuthClientHttpRequestFactory` when its `setRequestFactory` method is invoked, but I can't get my hands on that object because the `getRequestFactory()` wraps it inside an `InterceptingClientHttpRequestFactory` because of the header interceptor. This makes it very irritatingly complicated way of passing that information as opposed to this snippet:

```java
@Bean
public RestTemplate foo(ProtectedResourceDetails fooResource, ClientHttpRequestFactory httpFactory) {
	return new RestTemplateBuilder()
		.interceptors(new MyHeaderInterceptor())
		.requestFactory(httpFactory)
		.configure(new OAuthRestTemplate(fooResource));
}
```

It's a simple one-line fix that gets rid of a lot of boilerplate code.

**Comment by jgrandja** [comment]
@kutsal I see and agree the extra code/configuration complicates things. I'll get this merged for you but please add a test first. Thanks.

**Comment by kutsal** [comment]
@jgrandja added test as requested.
