### ISSUE TITLE
Add support for clock skew when checking access token expiry

### ISSUE THREAD

**Issue by hbergmey** [spring-projects/spring-security-oauth#1287]
By standard JWT deliver an expiration date with resolution in seconds. This is used to set the field ``expiration`` of type ``java.util.Date`` in DefaultOAuth2AccessToken.

The DefaultOAuth2AccessToken (2.2.1.RELEASE) methods in question are realized as follows:
```
	public boolean isExpired() {
		return expiration != null && expiration.before(new Date());
	}

	public int getExpiresIn() {
		return expiration != null ? Long.valueOf((expiration.getTime() - System.currentTimeMillis()) / 1000L)
				.intValue() : 0;
	}
```

As ``new Date()`` generates a current time representation in milliseconds and this is not truncated to second values, the calculation of "isExpired" returns ``false`` for 999ms longer, than getExpiresIn() returns 0.

Example: Given expiration is at 10s = 10000ms and currentTimeMillis is 9001ms.
getExpiresIn = (10000 - 9001)/1000 = 999/1000 = 0
isExpired = 10000 before 9001 = 10000 < 9001 = false

Expected: isExpired() == (getExpiresIn() == 0)

This actually leads to real bug behavior. For example: ``org.springframework.security.oauth2.client.OAuth2RestTemplate#getAccessToken()`` uses ``OAuth2AccessToken#isExpired()`` to decide, whether to acquire a fresh token or to use the existing token. For almost one second, this will definitly lead to a an unauthorized request, if the server side actually validates seconds correctly. This is a behavior we actually observe in communication between a Spring-based client and a WSO2 secured server.

**Comment by akloeber** [comment]
@jgrandja This fix is not working in conjunction with `AccessTokenProviderChain`.
In our project the clock skew has no effect as there is an additional expiry check in `AccessTokenProviderChain` where it does not take the clock skew into account (see https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/token/AccessTokenProviderChain.java#L107). So, although `OAuth2RestTemplate` triggers refresh already 30s before actual expiration, the refresh is still not executed in `AccessTokenProviderChain` where the token is still considered valid.

**Comment by jgrandja** [comment]
Thanks for the report @akloeber. Would you be interested in submitting a fix for this?

Alternatively, as a workaround, you can override the default use of `AccessTokenProviderChain` and supply a custom `OAuth2RestTemplate.setAccessTokenProvider()`.

**Comment by akloeber** [comment]
@jgrandja Yes definitely, I will prepare a PR to fix this issue.

**Comment by akloeber** [comment]
@jgrandja I just added PR https://github.com/spring-projects/spring-security-oauth/pull/1910
