### ISSUE TITLE
Customisation of error logging in OAuth2 TokenEndpoint

### ISSUE THREAD

**Issue by szauner** [spring-projects/spring-security-oauth#1290]
I wonder why all the @ExceptionHandler-methods in TokenEndpoint automatically log an error (if error logging is enabeld of course). The thing is that the error level should in my opinion be reserved for errors of the application that represent erroneous behaviour of the applicatoin code. But for example as far as an OAuth2Exception is concerned it may also occur because of bad user credentials. That is hardly an error that can be treated by changing some code. The user might just have mistyped his password.
It gets bad when actual ERRORs in the logs trigger an alarm, which would wake you up in the middle of the night because a user gave wrong credentials.

Wouldn't it be a proper solution to let the ExceptionTranslator do the logging. That way it would be customisable. Or am I missing something that would allow me to customise the logging?

**Comment by jgrandja** [comment]
This has been fixed in 3148a7d and is scheduled for upcoming 2.3.0.RC1 release.

**Comment by szauner** [comment]
That's great news, thank you for the informaton! I just wonder why my GitHub-search for "TokenEndpoint log error" did not find the other issues...

**Comment by Ronnie76er** [comment]
It seems like there's been a lot of movement on this particular logging issue the past few months. I don't want to keep opening issues on it, so I made this stackoverflow question about what's the best way to customize the logging: https://stackoverflow.com/questions/49248317/how-can-i-intercept-and-log-errors-that-occur-when-hitting-the-tokenendpoint
