### ISSUE TITLE
Issue with webflux integration

### ISSUE THREAD

**Issue by thekalinga** [spring-projects/spring-security-oauth#1296]
Currently `spring-security-oauth2` refers to `spring-webmvc`. But `webflux` does not work well with `webmvc`.

Can the dependencies of oauth2 be updated to support `webflux` aswell

The same thing is true for `spring-cloud-starter-security` aswell

**Comment by thekalinga** [comment]
I have added the following configuration to build script

```gradle
configurations {
    all*.exclude group: 'org.springframework', module: 'spring-webmvc'
}
```

The application wont start as `ResourceServerTokenRelayAutoConfiguration` attempts to load `WebMvcConfigurerAdapter`. So I has to add this explicitly `@SpringBootApplication(exclude = ResourceServerTokenRelayAutoConfiguration.class)`

But with change, I will have explicitly copy the access token from security context into oauth2 contex

**Comment by Koernerbrot** [comment]
any news on this? i would really like to be able to use webflux with spring-security-oauth2 and spring-cloud

**Comment by jgrandja** [comment]
@thekalinga @Koernerbrot FYI, please see this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security).

As indicated in the recent announcement, this project is in maintenance mode and we will provide bug/security fixes and consider adding minor features but we will not be adding major features. We do not plan on integrating with Spring WebFlux as this is a major upgrade. However, we do plan on integrating Spring WebFlux with the new OAuth support we're building in Spring Security 5.

**Comment by thekalinga** [comment]
@jgrandja is there any git issue we can subscribe to to get notified about that

Thanks

**Comment by jgrandja** [comment]
@thekalinga You can track the new OAuth work in Spring Security in the [Issues](https://github.com/spring-projects/spring-security/issues?q=is%3Aissue+is%3Aopen+label%3AOAuth2) using the labels: OAuth2, OIDC, Reactive, JWT-JOSE

**Comment by thekalinga** [comment]
@jgrandja Thanks

**Comment by MadeInChina** [comment]
webflux support +1
