### ISSUE TITLE
no check on redirect_uri

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-security-oauth#1308]
Open ID Connect specification requires the redirect_uri in the authentication request. spring-security-oauth does no checks on this though. This is violation of the specification contract.

**Comment by vpavic** [comment]
@Captain-P-Goldfish Note that this project, namely its `spring-security-oauth2` module, does not provide OpenID Connect support.

The next generation OAuth2 support (which includes OpenID Connect support) is a part of [Spring Security project](https://github.com/spring-projects/spring-security) with Client support already being available in 5.0 release. You might find [this blog post](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) useful.

**Comment by jgrandja** [comment]
Thanks @vpavic!
@Captain-P-Goldfish I'm going to close this issue as answered by @vpavic.

**Comment by Captain-P-Goldfish** [comment]
thx for the update
