### ISSUE TITLE
Document the status of this project vs. Spring Security 5.0 OAuth 2.0 support

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-security-oauth#1330]
From https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M5-Release-Notes#oauth-20-support :

> ### OAuth 2.0 Support
> Functionality from the [Spring Security OAuth project](http://projects.spring.io/spring-security-oauth/) is being migrated to core [Spring Security](https://projects.spring.io/spring-security/). OAuth 2.0 client support has already been added and additional features will be migrated in due course.
>
> If you depend on Spring Security OAuth features that have not yet been migrated you will need to add `org.springframework.security.oauth:spring-security-oauth2` and configure things manually. If you only need OAuth 2.0 client support you can use the auto-configuration provided by Spring Boot 2.0. We're also continuing to support Spring Boot 1.5 so older applications can continue to use that until an upgrade path is provided.

Should this be mentioned in the project page or in `README.md`? Does this mean that this project will eventually be deprecated once all its functionality is migrated into core Spring Security?

**Comment by jgrandja** [comment]
@imgx64 The status of this project has been announced in this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security#future-of-legacy-spring-security-oauth-project).

Correct, this project will go into the attic as soon as [feature parity](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) is reached within Spring Security 5.x.
