### ISSUE TITLE
Client id in tokenrequest object is null when tokenrequest is constructed with clientid passed in

### ISSUE THREAD

**Issue by codestudiosupport** [spring-projects/spring-security-oauth#1336]
I have setup instagramClientRegistration after following facebook and google client registration code,

I get {"error_type": "OAuthException", "code": 400, "error_message": "You must provide a client_id"}
when I debug to step httpRequest.send() in NimbusAuthorizationCodeTokenResponseClient class, 

I have found the client id is null when you construct TokenRequest object ,but the client id has already been passed into clientAuthentication.

**Comment by jgrandja** [comment]
@codestudiosupport Can you please log this issue in the Spring Security [Issues](https://github.com/spring-projects/spring-security/issues).

Also, please provide more detail in the new issue, specifically, your `application.yml` or Client Registration properties OR a GitHub repo that reproduces the issue.
Thank you.
