### ISSUE TITLE
Pre-registered redirect_uri should be optional

### ISSUE THREAD

**Issue by jbiblio** [spring-projects/spring-security-oauth#1337]
The change in #1331 introduces a check on pre-registered redirect_uri
```
	Set<String> registeredRedirectUris = client.getRegisteredRedirectUri();
	if (registeredRedirectUris == null || registeredRedirectUris.isEmpty()) {
		throw new InvalidRequestException("At least one redirect_uri must be registered with the client.");
	}
```

This breaks existing implementations for clients without a pre-registered redirect_uri, e.g. newly created clients for test purposes in controlled environments.

Although such doing is discouraged for a good reason, it's still valid by RFC 6749, at least for confidential clients:
> The authorization server MUST require public clients and SHOULD require confidential clients to register their redirection URIs. 
> - https://tools.ietf.org/html/rfc6749#section-10.6, last paragraph.

Please revise the `InvalidRequestException`. TIA

**Comment by jgrandja** [comment]
@jbiblio I understand this update was not passive, however, the original implementation had a major issue as it opened things up to a potential _Invalidated (Open) Redirect_ vulnerability.

Given the original implementation:

```
Set<String> redirectUris = client.getRegisteredRedirectUri();

if (redirectUris != null && !redirectUris.isEmpty()) {
	return obtainMatchingRedirect(redirectUris, requestedRedirect);
}
else if (StringUtils.hasText(requestedRedirect)) {
	return requestedRedirect;
}
else {
	throw new InvalidRequestException("A redirect_uri must be supplied.");
}
```

For the use case where the client **does not** have a registered redirect-uri but passes in the `redirect_uri` parameter in the Authorization Request, the above logic would cause the Authorization Server to issue the Authorization Response redirect using an **invalidated** `redirect-uri` which opens up one or more potential vulnerabilities, for example, leaked Authorization Code.

> The authorization server MUST require public clients and SHOULD require confidential clients
   to register their redirection URIs.  **If a redirection URI is provided
   in the request, the authorization server MUST validate it against the
   registered value.**

Note the highlighted, if the `redirect_uri` is provided in the request than the authorization server **MUST validate it against the registered value**.

For the implicit grant, a redirect-uri MUST be registered. Although it's optional for the authorization code grant, it is required if the `redirect_uri` is provided in the request in order for the matching to be performed.

The only change required on your end to resolve this is to configure your client(s) with a `registered-redirect-uri`.

Apologies for this non-passive change but this is needed for protection.

**Comment by jbiblio** [comment]
@jgrandja  Thank you very much for your feedback. I appreciate the more secure handling, as it prevents a severe security leak. (IIRC some major companies were harmed by this issue a few years ago...)

**Comment by jgrandja** [comment]
@jbiblio Thanks for your understanding.

**Comment by btkousil** [comment]
For the implicit grant, a redirect-uri MUST be registered. **Although it's optional for the authorization code grant**, it is required if the redirect_uri is provided in the request in order for the matching to be performed.
