### ISSUE TITLE
Invalid JWT triggers HTML HTTP 500 error response with JWK verification

### ISSUE THREAD

**Issue by andreas-schilling** [spring-projects/spring-security-oauth#1339]
If JWK verification is used (`JwkVerifyingJwtAccessTokenConverter`) and an invalid token is sent along (i.e. a rubbish token that doesn't even decode) then the error response is HTML with a HTTP 500 error code.
This is due to line 121 within the `JwkVerifyingJwtAccessTokenConverter`:

```
L119 // Verify signature
L120 SignatureVerifier verifier = jwkDefinitionHolder.getSignatureVerifier();
L121 Jwt jwt = JwtHelper.decode(token);
L122 jwt.verifySignature(verifier);
```
A decoding exception is not handled here using an `InvalidTokenException`.

**Comment by andreas-schilling** [comment]
Ah, I was not 100% exact in my description.
The token is not complete rubbish, you can trigger the problem bei taking a valid token (may also be an expired one) and breaking either the payload or the signature part by removing one or more of the Base64 string characters. Then you'll run into the exception at the point in code I described and it'll generate the HTML response.
It might be not the biggest of all issues, but we found this out when checking security event logging using both valid tokens and broken ones.

**Comment by jgrandja** [comment]
@andreas-schilling It's still not clear to me on how to reproduce this issue.

> you can trigger the problem by **taking a valid token** and breaking either the payload or the signature part by removing one or more of the Base64 string characters

What exactly do you mean as far as breaking either the payload or signature part from a valid token?

Are you able to provide a test that reproduces this issue or sample JWT?

**Comment by andreas-schilling** [comment]
I'll try to set up a small app with tests that shows what I mean. Might not be able to do so before next week.

**Comment by jgrandja** [comment]
@andreas-schilling I'm closing this due to lack of feedback re: sample
