### ISSUE TITLE
check of redirect_uri is too late

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-security-oauth#1341]
in case that the client sends an invalid redirect_uri the user has first to go through the login process and if that was successfull the application fails due to the invalid redirect_uri.
In our case the login process is a somewhat long story for the user and this behaviour is very inconvenient and undesirable. The check should be done before the authentication.

**Comment by jgrandja** [comment]
@Captain-P-Goldfish As per [Section 4.1. Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1):

> (B)  The authorization server authenticates the resource owner (via
        the user-agent) and establishes whether the resource owner
        grants or denies the client's access request.

The Authorization Server **must authenticate the user first** before the validation of the Authorization Request  parameters, which includes the `redirect_uri`. The current implementation is implemented to conform to the spec and we cannot deviate from it.

I'm going to close this issue as I feel I have answered your question.

**Comment by dfcoffin** [comment]
@jgrandja The section you quoted [Section 4.1. Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1) is an over simplification of the process and is superceded by [Section 4.1.1 Authorization Request](https://tools.ietf.org/html/rfc6749#section-4.1.1):

   The authorization server validates the request to ensure that all
   required parameters are present and valid.  If the request is valid,
   the authorization server authenticates the resource owner and obtains
   an authorization decision (by asking the resource owner or by
   establishing approval via other means).

**Comment by jgrandja** [comment]
@vpavic @dfcoffin Thanks for the correction. I skimmed over the details so thanks for catching me on that.

**Comment by dfcoffin** [comment]
@jgrandja I've submitted an errata request to modify Section 4.1 Authorization Code Grant (B) to be consistent with the contents of Section 4.1.1 Authorization Request, since I have encountered this mis-interpretation by other OAuth 2.0 Authorization Framework implementations

**Comment by Captain-P-Goldfish** [comment]
thx for the strong support here :-)
