### ISSUE TITLE
"unknown (use) is currently not supported" when PublicKeyUse is not part of JWK

### ISSUE THREAD

**Issue by senkum** [spring-projects/spring-security-oauth#1347]
According to the JWK Spec https://tools.ietf.org/html/rfc7517#section-4.2, PublicKeyUse is optional, but currently spring-security-oauth2 code throws exception when PublicKeyUse is not specified in the JWK

**Comment by Yasinjama** [comment]
I am running into this issue as well. @senkum have you found a workaround until this get's fixed?

**Comment by jgrandja** [comment]
Closing based on [comment](https://github.com/spring-projects/spring-security-oauth/pull/1348#discussion_r191760386)
