### ISSUE TITLE
Getting invalid token using spring boot autoconfigure for the resource server

### ISSUE THREAD

**Issue by brsvpr** [spring-projects/spring-security-oauth#1355]
Hi, 
I am trying to secure my Rest APIs. 
I have created an auth server which is a spring boot project running separately.
I have put the auth server as below. 

public class AuthServerOAuth2Config extends AuthorizationServerConfigurerAdapter {
	
	private static final Logger log = LoggerFactory.getLogger(AuthServerOAuth2Config.class);
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Override
	public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
		clients
			.inMemory()
			.withClient("test")
			.secret("testsecret")
			.authorizedGrantTypes("client_credentials")
			.scopes("write", "read");
	}	
	
	@Override
    public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
        /*
         * Allow our tokens to be delivered from our token access point as well as for tokens
         * to be validated from this point
         */
        security.checkTokenAccess("permitAll()");
    }

	@Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
		endpoints.tokenStore(new InMemoryTokenStore()).authenticationManager(authenticationManager);
	}
}

So auth server code is working and I am able to access a token by using the below end point url.
http://localhost:9092/uaa/oauth/token

I am able to validate the token / get the client info by using the below end point url.
http://localhost:9092/uaa/oauth/check_token?token=08ed1c9c-a371-43cc-b456-407fcde0b315

I have created a resource server which is a spring boot project running separately which has few Rest APIs accessible by end point URLs that needs to be secured. Below are the properties in the application.properties.
security.oauth2.resource.token-info-uri=http://localhost:9092/uaa/oauth/check_token
security.oauth2.resource.token-type=Bearer
security.oauth2.client.client-id=test
security.oauth2.client.client-secret=testsecret
security.oauth2.client.grant-type=client_credentials
security.oauth2.client.scope=write

I would assume that by mentioning the above properties, spring boot will first validate the token against the auth server by calling the token-info-uri mentioned above.

Now I am testing with POSTMAN by passing the "Bearer <TOKEN>" as Authorization header to the one of the APIs in the resource server. I am getting the below error.
{
    "error": "invalid_token",
    "error_description": "08ed1c9c-a371-43cc-b456-407fcde0b315"
}

Though I can validate this token using the individual end point url "oauth/check_token", I am not able to validate this by accessing the APIs in the resource server.
Please help.

Thanks,
Sai

**Comment by brsvpr** [comment]
@here - Hi All, can any one please help me in this issue ? This is a bit urgent for me to bring this to a closure.

Thanks

**Comment by jgrandja** [comment]
@brsvpr Can you also provide the config for your `ResourceServerConfigurerAdapter`? It may not be related to the call to `/oauth/check_token` from the Resource Server.

If you can provide a complete sample that reproduces this issue that would be the most helpful.

**Comment by brsvpr** [comment]
@jgrandja - Hi Joe, Thanks for your response. I don't have any config for ResourceServerConfigurerAdapter.
I just mentioned the above listed properties in the application.properties file in the resource server project.
Can you please suggest if I am missing something or please correct me. Thank you very much.

**Comment by brsvpr** [comment]
@jgrandja - Also you may please help me with ResourceServerConfigurerAdapter config for this case if this is required. Thanks.

**Comment by jgrandja** [comment]
Are you using the annotation `@EnableResourceServer`?

**Comment by brsvpr** [comment]
@jgrandja - Yes, I am using this annotation. Below is the class in the resource server project.

@EnableResourceServer
@SpringBootApplication
public class Application {
	private static final Logger log = LoggerFactory.getLogger(Application.class);

	public static void main(String[] args) throws Exception {
		try {
			SpringApplication.run(Application.class);

			log.info("\n\nCustomer Rest Service Started.................!\n\n");
		} catch (Exception e) {
			e.printStackTrace();
			log.error(e.getMessage());
		}
	}
}

**Comment by brsvpr** [comment]
@jgrandja - Please refer to the attached.

Thanks

**Comment by brsvpr** [comment]
@jgrandja - In the annotations mentioned in the code above, the first letters are in capitals but not why it took in small letter after submitting the comment.

**Comment by jgrandja** [comment]
@brsvpr Take a look at this [sample](https://github.com/jgrandja/spring-security-oauth-sample/tree/opaque-token-support). Checkout the **opaque-token-support** branch which will show you how to setup your oauth2 authz rules, for example:

```.access("#oauth2.hasScope('read')```

**Comment by brsvpr** [comment]
@jgrandja - Thanks Joe. I will take a look at this. However, I have already mentioned the below in the resource server application.properties file. Hope spring boot will identify this.
_security.oauth2.client.scope=write_

**Comment by jgrandja** [comment]
@brsvpr `RemoteTokenServices` is used by the Resource Server to call the `CheckTokenEndpoint` on the Authorization Server and client authentication is performed using HTTP Basic. So the Resource Server uses `client-id` and `client-secret` to create the `Authorization` header with `Basic` credentials.

Your configuration has:

```
...
security.oauth2.client.grant-type=client_credentials
security.oauth2.client.scope=write
...
```

You would only need these 2 properties if the client was performing the `client_credentials` flow, which is not the case for the call to the `CheckTokenEndpoint`. Both of these properties are not used and are not applicable here.

**Comment by brsvpr** [comment]
@jgrandja - Yes Joe. My auth server has configured for the "client_credentials" grant_type.
My requirement is to: 
1) get the bearer token from the auth server
2) validate the token before calling the Rest API in the resource server.

**Comment by brsvpr** [comment]
@jgrandja - Hi Joe,

I have removed the below properties in the resource server.
_security.oauth2.client.grant-type=client_credentials
security.oauth2.client.scope=write_

Also put the code in the resource server by extending ResourceServerConfigurerAdapter.
	_@Override
	public void configure(HttpSecurity http) throws Exception {
		http
			.antMatcher("/customer/**")
			.authorizeRequests()
				.antMatchers("/customer/**").access("#oauth2.hasScope('write')");
        }_

Still I get the below response.
_{
    "error": "invalid_token",
    "error_description": "fc30d553-6c00-421f-9a21-f15ad651a962"
}_

**Comment by jgrandja** [comment]
@brsvpr The sample I provided works so take a look at the closely and follow that setup. If you still can't get it working than publish your app to a GitHub repo and I'll take a look at it.

**Comment by brsvpr** [comment]
@jgrandja - I am mentioning my entire code here. Please help me with any corrections. 

Below is the auth server code.
_@Configuration
@EnableAuthorizationServer
public class AuthServerOAuth2Config extends AuthorizationServerConfigurerAdapter {
	
	private static final Logger log = LoggerFactory.getLogger(AuthServerOAuth2Config.class);
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Override
	public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
		
		log.info("\n\nIn Memory Authorization Server Before Registering Client .................!\n\n");
		
		clients
			.inMemory()
			.withClient("test")
			.secret("testsecret")
			.authorizedGrantTypes("client_credentials")
			.scopes("write", "read");
		
		log.info("\n\nIn Memory Authorization Server After Registering Client .................!\n\n");
	}	
	
	@Override
    public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
        /*
         * Allow our tokens to be delivered from our token access point as well as for tokens
         * to be validated from this point
         */
        security.checkTokenAccess("permitAll()");
    }

	@Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
		endpoints.authenticationManager(authenticationManager).tokenStore(new InMemoryTokenStore()).approvalStoreDisabled();
	}
}_

Below are the application.properties in the auth server.
_server.port=9092
server.contextPath=/uaa
security.user.name=none
security.user.password=none_

Below is the resource server configuration.
_@EnableResourceServer
@SpringBootApplication
public class Application extends ResourceServerConfigurerAdapter {
	private static final Logger log = LoggerFactory.getLogger(Application.class);

	public static void main(String[] args) throws Exception {
		try {
			SpringApplication.run(Application.class);

			log.info("\n\nCustomer Rest Service Started.................!\n\n");
		} catch (Exception e) {
			e.printStackTrace();

			log.error(e.getMessage());
		}
	}
	
	@Override
	public void configure(HttpSecurity http) throws Exception {
		http
			.antMatcher("/customer/**")
			.authorizeRequests()
				.antMatchers("/customer/**").access("#oauth2.hasScope('write')");
	}
}_

Below are the application.properties in the resource server.
_server.port=9091
security.oauth2.resource.token-info-uri=http://localhost:9092/uaa/oauth/check_token
security.oauth2.resource.token-type=Bearer
security.oauth2.client.client-id=test
security.oauth2.client.client-secret=testsecret
#security.oauth2.client.grant-type=client_credentials
#security.oauth2.client.scope=write
spring.security.user.name=none
spring.security.user.password=none_

And I have a rest controller in the resource server that has couple of Rest APIs.

**Comment by brsvpr** [comment]
@jgrandja - FYI, I am testing this using POSTMAN application, so I think I don't need a separate client app.

**Comment by brsvpr** [comment]
@jgrandja - Hi Joe, 
Unfortunately I am not able to access Github from the network where I work. However, I have pasted the code above. Request you to please go through this once you are free and help me out.
Thank you so much.

**Comment by brsvpr** [comment]
@jgrandja - Any help please.

**Comment by jgrandja** [comment]
@brsvpr I've provided you a working sample that aligns with a similar setup as your application. Have you tried it out? Take the time to understand how that sample works as it will help you identify the issues you're having with your application.

As mentioned in this [comment](https://github.com/spring-projects/spring-security-oauth/issues/1355#issuecomment-387104580), if you can provide me a sample that would be the most efficient. Otherwise, I would have to build your sample from the pasted code and try to reproduce on my end which is not effective.

As well, I'm currently working on high priority items so I will get to this as soon as I can and assuming you provide a sample that reproduces the issue.
Thanks.

**Comment by brsvpr** [comment]
Thank you @jgrandja. I will try to find ways to upload the entire project code to the GitHub ASAP. Otherwise I will also try your sample and let you know.

**Comment by SangameswaranRS** [comment]
@brsvpr  Im also facing the same problem. How did you resolve it? It would be a great help if anyone helps me out

**Comment by Clement-Leopold** [comment]
@jgrandja  when I was debugging a demo, which returned the invalid token as well, I find a small problem;
 In RemoteTokenServices  line 116  
`if (!Boolean.TRUE.equals(map.get("active"))) {`   
results in true;
but the map-response  from  the authorization server, which is /oauth/check_token result, contains the value of  'active' is "true";
Then I override the code using stirng.equals,  The response is valid.

**Comment by krestovsky** [comment]
@brsvpr , @Clement-Leopold  i made a workaround in https://github.com/spring-projects/spring-security-oauth/issues/1445

**Comment by BenDol** [comment]
This is also an issue for me, seems like a pretty serious one. Any ideas when a hotfix is coming? If not can someone provide a way to override the existing `RemoteTokenServices` bean with our own fixed version in the mean time? Thanks!

**Comment by krestovsky** [comment]
You could use your custom RestTemplate for RemoteTokenServices. It solves
problem with default RestTemplate serializers order. code snippet is
avaliable in
https://github.com/spring-projects/spring-security-oauth/issues/1445 .

сб, 15 сент. 2018 г. в 12:29, Ben Dol <notifications@github.com>:

**Comment by rusbob** [comment]
The issue with usage of old version of spring oauth dependencies at `UAA` side which does not return back `active` flag and that's why you got at your resource server such error like:
```
{
      "error": "invalid_token",
      "error_description": "08ed1c9c-a371-43cc-b456-407fcde0b315"
}
```
Take a look at [specification](https://tools.ietf.org/search/rfc7662#section-2.2) used in latest Spring oauth implementation versions.

**Comment by jgrandja** [comment]
I'm going to close this issue as I believe it will be resolved via #1533.
If the issue persists I can re-open to discuss further.

**Comment by ramugadde84** [comment]
Hi I have Authorization Server,First i will send request to OAuth Server with /oauth and i will get Access Token and how i can build Resource on top of that in spring boot OAuth

**Comment by rwinch** [comment]
We saw your ticket at gh-1849 Please do not double post
