### ISSUE TITLE
JwkSetConverter should not require PUBLIC_KEY_USE

### ISSUE THREAD

**Issue by Yasinjama** [spring-projects/spring-security-oauth#1365]
Im getting the following error "unknown ( use ) is currently not supported." when the "use" parameter is missing jwks uri. This is a optional according to the spec. 

Use of the "use" member is OPTIONAL, unless the application requires its presence.

**Comment by Yasinjama** [comment]
Can I get an update on this issue?

**Comment by jgrandja** [comment]
Related #1347
