### ISSUE TITLE
Sample App SSO Issue

### ISSUE THREAD

**Issue by royrajiv** [spring-projects/spring-security-oauth#1366]
After logging into tonr2 when I click on "view my sparklr photos" and enter login credentials app is throwing this error:

Sparklr OAuth2 Error
There was a problem with the OAuth2 protocol ( error="invalid_request", error_description="At least one redirect_uri must be registered with the client." )

Please go back to your client application and try again, or contact the owner and ask for support

Browser url:
http://localhost:8080/sparklr2/oauth/authorize?client_id=tonr&redirect_uri=http://localhost:8080/tonr2/sparklr/photos&response_type=code&scope=read%20write&state=B8YlD3

**Comment by rratliff** [comment]
Looks like this broke as a result of changes in #1331
