### ISSUE TITLE
JwkVerifyingJwtAccessTokenConverter 

### ISSUE THREAD

**Issue by evh69** [spring-projects/spring-security-oauth#1368]
`JwtAccessTokenConverter` uses non-standard `client_id` and `scope` claims #1214 was added allowing one to customize the "scopeAttribute" attribute on the DefaultAccessTokenConverter.  A @EnableResourceServer configuration connecting to Azure as an Oauth2/OIDC provider is receiving tokens where the scope claim is set to 'scp'.  I would like to take advantage of the ability to set the "scopeAttribute" attribute on the DefaultAccessTokenConverter and minimize the amount of custom configuration.  

I believe I would do this by creating bean for the TokenStore setting a new  JwkVerifyingJwtAccessTokenConverter (JwtAccessTokenConverter) with a DefaultAccessTokenConverter.  

I am struggling to see how one can adjust the configuration to use the "DefaultAccessTokenConverter" without exposing the JwkVerifyingJwtAccessTOkenConverter as public (or) creating a copy of it and other private classes.

Any reason not to make JwkVerifyingJwtAccessTokenConverter?  Or, is there a better way of injecting a new DefaultAccessTokenConverter?

**Comment by jgrandja** [comment]
@evh69 Have you tried the following `JwkTokenStore` constructor?

 `public JwkTokenStore(String jwkSetUrl, AccessTokenConverter accessTokenConverter)`

Configure `DefaultAccessTokenConverter` and pass it into this constructor should do it.

**Comment by cremersstijn** [comment]
@evh69 do you have a code example on how you fixed this?

**Comment by evh69** [comment]
Super simple, when your looking at the right constructor.

```
@Bean
  public JwkTokenStore jwkTokenStore() {
    DefaultAccessTokenConverter converter = new DefaultAccessTokenConverter();
    converter.setScopeAttribute("scp");
    return new JwkTokenStore(keyseturi, converter);
  }
```
