### ISSUE TITLE
one client_id is used causes redis performance degradation.

### ISSUE THREAD

**Issue by grey-kimtaeyoung** [spring-projects/spring-security-oauth#1369]
**Background : Our service is a service that connects at least 4000 ~ 15000 users at a time in 2 minutes when gcm out.**

The removeAccessToken function exists in the RedisTokenStore class.

This function is used to remove one of the key values in the redis array called lRem

When storing the token in redis client_id_to_access: (client_id) This type of key contains tokens in array form.

If the client_id is set to single, there will be a large number of keys in the list (in our case, 1.1 million keys were included), causing a huge overload during the lRem process.

Therefore, the way to put user information in list form in client_id_to_access: client_id key is not good due to the nature of redis.

We suggest changing the structure so that it can have a hash or other O (logN) speed to match the format of redis.

**Comment by LukasVyhlidka** [comment]
Hi, is this still true? RedisTokenStore uses Set data structure (sAdd and sRem operations) to store access tokens by client_id...

**Comment by grey-kimtaeyoung** [comment]
it solved! thx!
