### ISSUE TITLE
Custom TokenEnhancer does not get called when using JdbcTokenStore, but works when using InMemoryTokenStore

### ISSUE THREAD

**Issue by jmart1** [spring-projects/spring-security-oauth#1371]
We are using a custom TokenEnhancer to add additional properties to our /token response.  It worked as intended when we used InMemoryTokenStore.  But when we switched to JdbcTokenStore, our custom enhancer stopped getting called.  Very strange.

Another side-effect I noticed when using JdbcTokenStore is that the JwtAccessTokenConverter is no longer needed.  That is to say that if I do not include the JwtAccessTokenConverter in the code below, then I still get back a JWT token.  But if I am using the InMemoryTokenStore, then I need to include the JwtAccessTokenConverter to get back JWT tokens, as expected.

Is there something special in the JdbcTokenStore that we are not taking into account?

    @Bean
    public JwtAccessTokenConverter accessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        converter.setSigningKey("secret");
        return converter;
    }
    
    @Bean
    public RwTokenEnhancer customTokenEnhancer(){
        return new RwTokenEnhancer();
    }
    
    @Bean
    public TokenStore tokenStore() {
    	logger.info("init JdbcTokenStore");
    //        return new InMemoryTokenStore();
        return new JdbcTokenStore(dataSource);
    }
    
    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {

        TokenEnhancerChain enhancerChain = new TokenEnhancerChain();
        enhancerChain.setTokenEnhancers(Arrays.asList(customTokenEnhancer(), accessTokenConverter()));

        endpoints
                .authenticationManager(authenticationManager)
                .tokenStore(tokenStore())
                .userDetailsService(robustUserDetailsService)
                .tokenGranter(tokenGranter(endpoints))
                .tokenEnhancer(enhancerChain);
    }

                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.M8</version>

            <artifactId>spring-security-oauth2</artifactId>
            <version>2.3.0.RELEASE</version>

            <artifactId>spring-security-jwt</artifactId>
            <version>1.0.9.RELEASE</version>

**Comment by jmart1** [comment]
This is a none issue.  The custom enhancer does not get called because the token was cached in the DB.  Only when creating a new token does the enhancer get called.

**Comment by kopax** [comment]
Hello, I am having a similar issue. I have added the avatar filename in my jwt, and now it never get returned. It makes a lot of sens of it get cached. 

- How long does the cache last?
- How do I invalidate the cache?
