### ISSUE TITLE
client details information leak

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-security-oauth#1386]
if an attacker manages to figure out a valid client_id and sends an authorization request he will be provided with information about the registered redirect_uris of the client. 

See DefaultRedirectResolver in line 169

```
throw new RedirectMismatchException("Invalid redirect: " + requestedRedirect
				+ " does not match one of the registered values: " + redirectUris.toString());
```

**Comment by jgrandja** [comment]
@Captain-P-Goldfish Good catch! Would you be interested in submitting a PR for this?
