### ISSUE TITLE
Using JSON, but Slack OAuth requires `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by ericis** [spring-projects/spring-security-oauth#1429]
Attempting to create a OAuth `ClientRegistration.Builder` for Slack...

```
ClientRegistration.Builder builder = getBuilder(
    registrationId, 
    ClientAuthenticationMethod.BASIC,
    DEFAULT_LOGIN_REDIRECT_URL);

builder.scope("identify", "users.profile:read");
builder.authorizationUri("https://slack.com/oauth/authorize");
builder.tokenUri("https://api.slack.com/methods/oauth.access");
builder.userInfoUri("https://slack.com/api/users.identity");
builder.userNameAttributeName("id");
builder.clientName("Slack");

return builder;
```

`return SLACK.getBuilder(client).clientId(clientId).clientSecret(clientSecret).build();`

Login fails upon response from Slack to service: http://localhost:8081/login/oauth2/code/slack?code...

... with the error:
`org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_token_response] An error occurred parsing the Access Token response: The HTTP Content-Type header must be application/json; charset=UTF-8`

Per Slack's documentation:

> Present arguments as parameters in application/x-www-form-urlencoded querystring or POST body. This method does not currently accept application/json.

The Nimbus client is hard-coded to send JSON...
https://github.com/spring-projects/spring-security/blob/becff23df15f37835291dd9fba299192902dba76/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/NimbusAuthorizationCodeTokenResponseClient.java#L98

@jgrandja

**Comment by ericis** [comment]
I have tried both methods offered by Slack:
- https://api.slack.com/methods/oauth.access
- https://api.slack.com/methods/oauth.token

**Comment by ericis** [comment]
*Please note that I'm configuring multiple providers, so I can't globally filter/modify the request/response. I would have to target Slack only and I'm not sure how.

**Comment by ericis** [comment]
Code example here:
https://github.com/ericis/spring-slack-oauth-json-issue

**Comment by jgrandja** [comment]
@ericis The main issue here is that Slack is not returning the `Content-Type` header with `application/json` in the Token Response.

This is a required header as defined in the [spec](https://tools.ietf.org/html/rfc6749#section-5.1):

>  The parameters are included in the entity-body of the HTTP response
   using the **"application/json"** media type as defined by [RFC4627].  The
   parameters are serialized into a JavaScript Object Notation (JSON)
   structure by adding each parameter at the highest structure level.
   Parameter names and string values are included as JSON strings.
   Numerical values are included as JSON numbers.  The order of
   parameters does not matter and can vary.

The `NimbusAuthorizationCodeTokenResponseClient` is using the Nimbus HTTP Client, which performs this check on the response.

You can workaround this issue by supplying your own implementation of `OAuth2AccessTokenResponseClient` and configuring it via `httpSecurity.oauth2Login().tokenEndpoint().accessTokenResponseClient(yourClient)`

See the [reference](https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/reference/htmlsingle/#oauth2login-advanced-token-client) for more details.

Also, this issue should have been logged in the [Spring Security repo](https://github.com/spring-projects/spring-security/issues) so I'm going to close this and if you have additional questions please log a new issue there.

**Comment by ericis** [comment]
Thanks. I will try this

**Comment by ericis** [comment]
I can confirm that creating a custom version of `NimbusAuthorizationCodeTokenResponseClient` did indeed do the trick. I'm not satisfied with the custom code that we'll need to maintain and have reached out to Slack support to fix on their side. They're piloting a beta for "workspace apps" that includes a proper response per spec (I haven't tried it) and they have an issue on their backlog to add the missing `token_type` to the response (we had to read the token response inside the custom client, mutate the JSON payload and reset it back in the client to get it to work).
