### ISSUE TITLE
[SECOAUTH-440] Add support for token revocation proposed standard

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth#146]
> **Priority**: Minor
> **Original Assignee**: Dave Syer
> **Reporter**: Harleen Sahni
> **Created At**: Tue, 7 Jan 2014 21:19:50 +0000
> **Last Updated on Jira**: Wed, 8 Jan 2014 14:47:05 +0000

Add support for the proposed standard for oauth2 revocation, basically support requests such as:

```
POST /revoke HTTP/1.1
     Host: server.example.com
     Content-Type: application/x-www-form-urlencoded
     Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

     token=45ghiukldjahdnhzdauz&token_type_hint=refresh_token
```

to revoke tokens.  
See http://tools.ietf.org/html/rfc7009

**Comment by miyamoto-daisuke** [comment]
+1

**Comment by doom777** [comment]
+1

**Comment by efc-michaelwiezik** [comment]
+1

**Comment by raoofm** [comment]
+1

**Comment by alexisgayte** [comment]
+1

**Comment by dfcoffin** [comment]
+1

**Comment by malaki12003** [comment]
+1

**Comment by artificialintellect** [comment]
Is this on the roadmap yet?

**Comment by bas-velthuizen** [comment]
+1

**Comment by bas-velthuizen** [comment]
A DELETE method on the /auth/token endpoint would also be elegant

**Comment by jgrandja** [comment]
@dfcoffin As an FYI, we are limiting new features and only accepting bug fixes and minor enhancements as this project is in maintenance mode. Our efforts are focused on the new OAuth support we are building into Spring Security core project. We just released 5.0.0.M1 which provides support for the client-side and we hope to get to the server-side support soon.

**Comment by thepowrhouse** [comment]
Do we have any timelines on implementation of RFC 7009 in the near future?

**Comment by OrangeDog** [comment]
@bas-velthuizen no it wouldn't. You cannot delete the `/auth/token` resource. It would need to be `/auth/token/{token}`.
