### ISSUE TITLE
Spring security oauth2 related questions. (social )

### ISSUE THREAD

**Issue by cheese10yun** [spring-projects/spring-security-oauth#1473]
social google, facebook question.

I want to be authenticated in social and save members in our database.

Should I create a class that extends the AbstractAuthenticationProcessingFilter class?

Can I implement a class similar to OAuth2ClientAuthenticationProcessingFilter?

Is it right to write code to store membership information here?

```java
@Override
protected void successfulAuthentication(HttpServletRequest request, HttpServletResponse response,
                                        FilterChain chain, Authentication authResult) throws IOException, ServletException {
    super.successfulAuthentication(request, response, chain, authResult);
    // Nearly a no-op, but if there is a ClientTokenServices then the token will now be stored

    //
    restTemplate.getAccessToken();
}
```

**Comment by jgrandja** [comment]
@cheese10yun Have you seen this [sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login)?

We've been building the [Next Generation of OAuth](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) support the past year and half. I would highly recommend that you look at the sample and [reference doc](https://docs.spring.io/spring-security/site/docs/5.0.7.RELEASE/reference/htmlsingle/#jc-oauth2login) for further information.

**Comment by cheese10yun** [comment]
@jgrandja Thank you.
