### ISSUE TITLE
Setting a custom UserDetailsService on the token endpoint

### ISSUE THREAD

**Issue by Gabology** [spring-projects/spring-security-oauth#1475]
Related to https://github.com/spring-projects/spring-security-oauth/issues/620, https://github.com/spring-projects/spring-security-oauth/issues/774

It is not currently easy to use a custom `UserDetailsService` with the token endpoint if it is configured with the `@EnableAuthorizationServer` annotation. This is because a `ClientDetailsUserDetailsService` is configured directly on the HttpSecurity.

```java
@Override
	public void init(HttpSecurity http) throws Exception {

		registerDefaultAuthenticationEntryPoint(http);
		if (passwordEncoder != null) {
			ClientDetailsUserDetailsService clientDetailsUserDetailsService = new ClientDetailsUserDetailsService(clientDetailsService());
			clientDetailsUserDetailsService.setPasswordEncoder(passwordEncoder());
			http.getSharedObject(AuthenticationManagerBuilder.class)
					.userDetailsService(clientDetailsUserDetailsService)
					.passwordEncoder(passwordEncoder());
		}
		else {
			http.userDetailsService(new ClientDetailsUserDetailsService(clientDetailsService()));
		}
       ...
       }
```

My use case for this is to add some extra information on the `Authentication.principal` which I believe is quite a common use case, and the recommended way of doing it in Spring Security is through implementing the `UserDetailsService`.

**Comment by jgrandja** [comment]
Closing as duplicate of #620
