### ISSUE TITLE
OAuth2TokenRelayFilter not forwarding the token

### ISSUE THREAD

**Issue by pparasnis** [spring-projects/spring-security-oauth#1502]
I am using spring security with Micorsoft Azure AD as the provider, Zuul as the Gateway service and 
 spring boot based other microservices.
I am having issues passing the authentication token from Zuul Gateway to microservice. The microservice had `@EnableResourceServer`

Below are the configuration options for WebSecurityConfigurerAdapter for the Zuul Gateway Service
`@Override
	protected void configure(HttpSecurity http) throws Exception
	{

		http
		.authorizeRequests()
		.antMatchers("/login/**").permitAll()
		.and()
		.authorizeRequests()
		.anyRequest()
		.authenticated()
		.and()
		.oauth2Login()
        .userInfoEndpoint()
        .oidcUserService(oidcUserService);
	}`

The Zuul Gateway service is able to extract the token -
`2018-10-09 17:47:55 [http-nio-8500-exec-5] DEBUG o.s.s.o.c.w.OAuth2LoginAuthenticationFilter - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken@9213d5be: Principal: Name: [xxxx], Granted Authorities:`

But the spring security authentication Relay Filter `(org.springframework.cloud.security.oauth2.proxy.OAuth2TokenRelayFilter)` is not passing the token forward as the code checks if the authentication is an instance of `OAuth2Authentication` where as the Authentication object created by `OAuth2LoginAuthenticationFilter` above is of the type `OAuth2AuthenticationToken`

`@Override
	public boolean shouldFilter() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		if (auth instanceof OAuth2Authentication) {`

**Comment by jgrandja** [comment]
@pparasnis Please log this issue to the [spring-cloud-security](https://github.com/spring-cloud/spring-cloud-security/issues) repo
