### ISSUE TITLE
Known high severity security vulnerability detected in github email

### ISSUE THREAD

**Issue by cheese10yun** [spring-projects/spring-security-oauth#1509]
![2018-10-19 4 21 23](https://user-images.githubusercontent.com/12086692/47203656-066e3b80-d3bc-11e8-88e9-76f9f96adf7b.png)

I received the above email from Github.

2.3.3.Is using RELEASE version, is there a problem with security?

**Comment by jgrandja** [comment]
@cheese10yun Please see this [blog post](https://spring.io/blog/2018/10/16/spring-security-oauth-2-3-4-2-2-3-2-1-3-2-0-16-released) for more details. I would recommend upgrading to 2.3.4.

**Comment by cheese10yun** [comment]
@jgrandja I always appreciate Spring Open Soft.
