### ISSUE TITLE
SSO  based on  Google and  WebFlux 

### ISSUE THREAD

**Issue by ayudovin** [spring-projects/spring-security-oauth#1530]
I used SSO based on Google and WebFlux and I don't know how to add own role in authentication. Now I have only `ROLE_USER` which was provided by google. 
Can you give me any advice ?

**Comment by ayudovin** [comment]
no, I didn't add this ticket to Spring Security.
This reference provides information only webmvc but not for webflux and their advice doesn't work for webflux

**Comment by jgrandja** [comment]
@ayudovin Yes, you are right the reference is only for Servlet based applications. Can you please log this ticket to [Spring Security repo](https://github.com/spring-projects/spring-security/issues) so we can track it there. I'll close this one. Thanks.
