### ISSUE TITLE
 java.lang.ClassNotFoundException: org.springframework.security.oauth2.provider.token.UserAuthenticationConverter

### ISSUE THREAD

**Issue by maxiwu** [spring-projects/spring-security-oauth#1537]
I use Eclipse to search, it appears in spring-security-oauth2.jar, version 2.3.4.RELEASE
however, my effective POM is using 2.0.15.RELEASE. It is from the spring-security-oauth2-autoconfigure 2.1.1.RELEASE.

If I upgrade the version to 2.0.16.RELEASE, it will complain another class not found
`java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.Bindable`

How do I fix this issue? which version of which is compatible with JWK token info ?

**Comment by raut-sushant** [comment]
I am facing same issue, any solution for this?
