### ISSUE TITLE
user A get the user B info by access_token

### ISSUE THREAD

**Issue by whucsfzf** [spring-projects/spring-security-oauth#1559]
my system is based on springcloud Dalston.SR3, springboot 1.5.6.RELEASE, oauth2 
When user login in, the auth server generate the access_token to the user. The token info is stored in the redis store. Then i found a strange thing, user A use A's access_token to access the web system, but get the user B's info。
The system architecture is ：
nginx -> zuul gateway -> app(->access auth to get user's info by access_token)
What a terrible thing，help me to find the reason , thank you!

**Comment by jgrandja** [comment]
@whucsfzf It would be very helpful if you could provide a complete and minimal sample that reproduces the issue and share it via a GitHub repository. This will allow us to efficiently troubleshoot and help resolve the issue. The sample should contain the minimum amount of code to reproduce the issue along with detailed steps on how to reproduce. Please see the following references for what a complete and minimal sample should consist of.

- http://sscce.org/
- https://stackoverflow.com/help/mcve

After you provide this, I'll help resolve your issue.

**Comment by whucsfzf** [comment]
> @whucsfzf It would be very helpful if you could provide a complete and minimal sample that reproduces the issue and share it via a GitHub repository. This will allow us to efficiently troubleshoot and help resolve the issue. The sample should contain the minimum amount of code to reproduce the issue along with detailed steps on how to reproduce. Please see the following references for what a complete and minimal sample should consist of.
> 
> * http://sscce.org/
> * https://stackoverflow.com/help/mcve
> 
> After you provide this, I'll help resolve your issue.

Thank you for your help. It's hard to give a complete sample now, it is in a big project. Also the problem appear sometime. I will find the situation to reproduce the problem. Then provide the complete sample.It may cost some time.

**Comment by jgrandja** [comment]
@whucsfzf It's difficult to troubleshoot issues that are intermittent. I will wait for a sample that can reproduce the issue. Thanks.

**Comment by jgrandja** [comment]
@whucsfzf I'm closing this due to lack of feedback re: sample.
