### ISSUE TITLE
Clarification on when to use spring-security-oauth2-* vs this library

### ISSUE THREAD

**Issue by pulse00** [spring-projects/spring-security-oauth#1562]
Since spring security version 5.x contains various oauth2 related features i'd like to ask someone with more insights: When should someone use this library over spring security 5.x? 

What separates these 2 libraries? It's really hard to find facts on this. 

We're migrating from spring security 4.x to 5.1 and use spring-security-oauth2 and are unsure whether to keep using it or migrate to the built-in spring security oauth2 features.

What's especially confusing is that the latest version of this library ([`2.3.4-RELEASE`](https://mvnrepository.com/artifact/org.springframework.security.oauth/spring-security-oauth2/2.3.4.RELEASE)) has a dependency on spring security `3.2.10-RELEASE` - being 2 major version behind the latest spring security version.

**Comment by jgrandja** [comment]
@pulse00 Please see this [announcement](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for more details.

For Client and Resource Server support, use Spring Security 5.x. If you require Authorization Server support, use Spring Security OAuth 2.3.x - until we [support Authorization Server](https://github.com/spring-projects/spring-security/issues/6320) in Spring Security 5.x.
