### ISSUE TITLE
Add AuthenticationProvider like interface for client authentication

### ISSUE THREAD

**Issue by RubenJG** [spring-projects/spring-security-oauth#1615]
In one the projects I was working on, I had a requirement to authenticate clients against a 3rd party provider which required me to send both client id and client secret.

I had previously done this for users by adding a custom `AuthenticationProvider` and I thought, there should be a similar mechanism for clients. I was wrong 😅.

From what I can tell, this is similar to #620 in the sense that I also wanted to override the `DaoAuthenticationProvider ` coupled with the `ClientDetailsUserDetailsService` bean provided by the library, but no matter how I tried, I wasn't able to get it to work.

Furthermore, I found that the `ClientDetailsService` interface is used across the project in multiple classes, so even if I had been able to add my own `AuthenticationProvider` for clients, it would have been incompatible with the rest of the library.

Maybe this is by design and what I was trying to do was simply not meant to be done, but I figure there is no harm in leaving the idea here.

**Comment by jgrandja** [comment]
Closing as duplicate of #620
