### ISSUE TITLE
'active' attribute is not returned by CheckTokenEndpoint

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-oauth#1616]
Actual Behavior
------

When using `@EnableAuthorizationServer`, the check token endpoint will not return the `active` attribute by default. Instead, it's necessary to supply a custom `AccessTokenConverter` bean.

Expected Behavior
------

By default, the `check_token` endpoint, as enabled by `@EnableAuthorizationServer`, would include the `active` attribute in the response.

Version
------
2.3.5.RELEASE

Sample Configuration
------
https://github.com/spring-projects/spring-security-oauth2-boot/tree/master/samples/spring-boot-sample-secure-oauth2-provider

(Note that the sample is on 2.3.4.RELEASE, so if you don't mind, you can change the dependency in your local copy to 2.3.5.RELEASE before you run the tests.)

**Comment by vicykie** [comment]
+1
any solution?

**Comment by jgrandja** [comment]
Related #1591
