### ISSUE TITLE
DefaultRedirectResolver fails with NPE if URI has no host

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-security-oauth#1618]
The `DefaultRedirectResolver` fails with a `NullPointerException` if the registered redirect URI has no host, e.g. `mymobileapp:/oauthredirect`.

This type of URI can be used to redirect the user to a mobile app. The OAuth2 specs require the redirect URI to be an absolute URI, which this is.

The problem in the current implementation is that the redirect URI is expected to have a host component. If fails with an NPE if it doesn't. To fix it, the `hostMatches` method should assume that the provided host arguments can be null.

This problem is observed in version 2.0.16 and 2.0.17.

**Comment by shawnz** [comment]
As a workaround, you could use for example "mymobileapp:///oauthredirect" as the redirect URL. This seems to work fine with AppAuth.
