### ISSUE TITLE
Customizing authorities granted by authorization / resource server

### ISSUE THREAD

**Issue by totof3110** [spring-projects/spring-security-oauth#162]
Related to:
http://stackoverflow.com/questions/22417780/using-scopes-as-roles-in-spring-security-oauth2-provider
https://github.com/spring-projects/spring-security-oauth/issues/161
https://github.com/spring-projects/spring-security-oauth/commit/22b4be814443543957177535961ae8e227bc5576

In my authorization server, I am trying to have the user authorize a grant of a subset of their authorities, based on the approved scopes.

e.g., the authorization flow would prompt the user which of their autorities to "delegate". Then, the OAuth2 client would be able to use to access token to call APIs on behalf of the user, but would only be able to gain the authorities approved by the user.

@dsyer recommended approach on StackOverflow (above) is to have a custom ResourceServerTokenServices (or TokenStore), which I understand as putting the logic in the `OAuth2Authentication loadAuthentication(String accessToken)` method.

However, these 2 classes are strongly tied to the OAuth2Authentication class, which always copies over all authorities from the current user authentication without any room for customization (at least I can't see anything straightforward). Even by extending it, I would have to call the OAuth2Authentication constructor which blindly copies all the authorities:

``` java
super(userAuthentication == null ? clientAuthentication.getAuthorities() : userAuthentication.getAuthorities());
```

The solution that seems to work best for me currently, is to create a new Authentication class, used only in the authentication manager, that allows for authorities filtering:

``` java
public class CustomOAuth2Authentication extends AbstractAuthenticationToken {
    private static final long serialVersionUID = 7527734076633525176L;

    private final OAuth2Request storedRequest;
    private final Authentication userAuthentication;

    public CustomOAuth2Authentication(OAuth2Authentication authentication) {
        super(authentication.isClientOnly() ? authentication.getAuthorities() : filter(authentication.getAuthorities(), authentication.getOAuth2Request().getScope()));
        this.storedRequest = authentication.getOAuth2Request();
        this.userAuthentication = authentication.getUserAuthentication();
        setDetails(authentication.getDetails());
        setAuthenticated(authentication.isAuthenticated());
    }

    /**
     * Retains only the authorities from the set of approved scopes.
     */
    private static Collection<GrantedAuthority> filter(Collection<? extends GrantedAuthority> authorities, Set<String> scope) {
        Collection<GrantedAuthority> result = Sets.newHashSet();
        for (GrantedAuthority authority : authorities) {
            if (scope.contains(authority.getAuthority())) {
                result.add(authority);
            }
        }
        return result;
    }
}
```

and then my custom authentication manager:

``` java
OAuth2AuthenticationManager authenticationManager = new OAuth2AuthenticationManager() {
    @Override
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        return new CustomOAuth2Authentication((OAuth2Authentication) super.authenticate(authentication));
    }
};
```

This does the trick but feels quite "hacky".

Commit https://github.com/spring-projects/spring-security-oauth/commit/22b4be814443543957177535961ae8e227bc5576 adds a new checkUserScopes flag on the DefaultOAuth2RequestFactory. While this seemed promising at first, I find it a little too restrictive (when turned on, all the scopes _have_ to be authorities, which prevents "heterogenous" scopes like mixing authority-based scopes and "other" types of scopes). Also turning on this flag doesn't have any impact out of the box on the authorities granted to the OAuth2Authentication by the authentication manager, so in the end, I would not be using it (and rather stick to the custom auth manager).

Would it be possible to have a supported way of customizing the authorities or should I stick with my current custom authentication / manage classes?

PS: thanks for all the effort you've already put in this project. It keeps getting better and better every day!

**Comment by diego-d5000** [comment]
I'm sorry for posting here after 3 years, but this is the first google result after search about authorities modification in OAuth2 server in spring.

How to modify authorities of `userAuthentication` using a wrapper? based on the answer:

```
On second thoughts I'm not sure a new strategy really adds anything. You can do all the manipulation
 you want in anResourceServerTokenServices implementation, or in an AccessTokenConverter if you are
 using JwtTokenServices, or TokenStore if you are using DefaultTokenServices. If you can propose a
 sensible default behaviour we can switch it on with an optional flag if you want.
```

**Comment by dsyer** [comment]
Normally one of the provided `Authentication` implementations is adequate. But you can implement it yourself if you need to. That's not really relevant to modifying authorities. The real question is "modifying, when?" I don't think there's a single answer - it depends on what you need to do. Try going further down the list in Google?
