### ISSUE TITLE
How to use HS256 algrithom to decode the id_token

### ISSUE THREAD

**Issue by throwind** [spring-projects/spring-security-oauth#1648]
In OidcAuthorizationCodeAuthenticationProvider class, the createOidcToken method can't specify the algrithom.

in 5.2.0.BUILD-SNAPSHOT(master) version:

 it seems the OidcIdTokenDecoderFactory was hard code NimbusJwtDecoder.withJwkSetUri to build a jwtDecoder，and NimbusJwtDecoder default algrithom is RS256。

in 5.1.4.RELEASE version:

the getJwtDecoder method hard code 'new NimbusJwtDecoderJwkSupport(jwkSeturl)'
but not the 'new NimbusJwtDecoderJwkSupport(jwkSeturl, jwsAlgorithm)' constructor

### Version

5.1.4.RELEASE and 5.2.0.BUILD-SNAPSHOT(master)

**Comment by jgrandja** [comment]
@throwind This issue should have been logged with the Spring Security project [issues](https://github.com/spring-projects/spring-security/issues).

Also, support for symmetric key (eg. HS256) is currently in the works. You can track the progress in [spring-security#6495](https://github.com/spring-projects/spring-security/pull/6495)
