### ISSUE TITLE
check_token return no 'active' ,but i change to 2.3.4.RELEASE, it will return this  

### ISSUE THREAD

**Issue by vicykie** [spring-projects/spring-security-oauth#1650]
https://github.com/spring-projects/spring-security-oauth/blob/bbae0027eceb2c74a21ac26bbc86142dc732ffbe/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/CheckTokenEndpoint.java#L48

**Comment by vicykie** [comment]
version 2.3.5.RELEASE

**Comment by jgrandja** [comment]
@vicykie This is a duplicate of #1616
