### ISSUE TITLE
Possible CSRF detected - state parameter was required but no state could be found

### ISSUE THREAD

**Issue by singharunkumar83** [spring-projects/spring-security-oauth#1651]
### Summary

I have a typical Spring Boot OAuth2 SSO Application integrated with external IdP.  I am running this application as docker container in ECS cluster.  It works as expected whenever I run single instance of this application but fails whenever I run more than one instance.
### Actual Behavior
It fails with message "**Possible CSRF detected - state parameter was required but no state could be found**" whenever tried to run with more than one instance.

Looks like problem as described in [822](https://github.com/spring-projects/spring-security-oauth/issues/822#issuecomment-437588031)

### Expected Behavior
Success.

### Configuration
Spring SSO Configuration -
`security:
    oauth2:
    client:
      client-id: appid
      client-secret: seceret
      access-token-uri:  idpaccesstokenuri
      user-authorization-uri: authuri
      scope: openid
    resource:
      user-info-uri: userinfouri
      filter-order: 3
  basic:
    enabled: false
`

### Version
Spring-boot: 2.0.6.RELEASE
spring-security-oauth2: 2.2.3.RELEASE

### Sample
`
@EnableOAuth2Sso
@SpringBootApplication
@EnableAutoConfiguration
public class SSOServiceApplication {}
`

**Comment by TomaszBelina** [comment]
I've notice the same error using keycloak as authorization server. In my case keycloak and spring application works on the same host but on different ports. Simple scenario is like follows:
1. user logins in into application in the first tab
2. user open the same page on the second tab 
3. on the first tab user clicks logout and is redirected back to keycloak. On the keycloak side session is destroyed
4. users clicks logout on the second tab and is redirected to login page on keyloack
5. users go back to first tab and provides username and password
6. application fails with message "Possible CSRF detected - state parameter was required but no state could be found" 

Interesting thing is if user in set 5 uses second tab there is no error.

org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.5.RELEASE
org.springframework.boot:spring-boot:2.1.5.RELEASE
keycloak:8.0.0

**Comment by jgrandja** [comment]
@singharunkumar83 or @TomaszBelina Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (via GitHub repo) that reproduces the issue and I'll take a look.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
