### ISSUE TITLE
Spring Boot 2 upgrade causes "At least one redirect_uri must be registered with the client."

### ISSUE THREAD

**Issue by smitchell** [spring-projects/spring-security-oauth#1656]
### Summary

After upgrading an existing authentication server to Spring Boot 2, the shared custom login page in the authentication service no longer redirects the user back to the original protected URI.

### Actual Behavior

1) The user attempts to access a protected, proxied web resource.
2) The user is redirected to the shared, custom login page in the authentication service.
3) The user posts her credentials.
4) Instead of being redirected back to the original website, the error below displays on the page.
```
OAuth Error
error="invalid_request", error_description="At least one redirect_uri must be registered with the client."
```
### Expected Behavior

Upon successful authentication, the browser should be redirected back to the original website.

### Configuration

We use a custom ClientDetails object, and its getRegisteredRedirectUri() method always returns an empty Set. Despite that, users get redirected to the original URI after Login. That is no longer the case after upgrading to Spring Boot 2.

I have not been able to recreate the "At least one redirect_uri must be registered with the client." error with a unit test. I would like to be able to do that so I could set a breakpoint and step through what is happening.

Our Zuul/Ribbon proxy server is still 1.5.13.RELEASE. I think the answer to how I can write a unit test in the authentication service lies in understanding the interaction with Zuul, or more specifically, the Spring Security 4 @EnableOAuthSso annotation on our proxy service.

```
  @Configuration
  @EnableOAuth2Sso
  @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
  @Slf4j
  protected static class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    @Value("${proxy.permitAll.matches}")
    private String[] matches;
    @Value("${proxy.logoutSuccessUrl}")
    private String logoutSuccessUrl;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
      http
          .logout()
          .invalidateHttpSession(true).permitAll()
          .logoutSuccessUrl(logoutSuccessUrl)
          .and()
          .authorizeRequests()
          .antMatchers(matches).permitAll()
          .anyRequest().authenticated()
          .and()
          .csrf().disable(); //TODO turn this back on
    }
  }
```

### Version

The working production code is running 1.5.13.RELEASE. The updated code is running 2.1.3.RELEASE.

### Sample

See the AuthenticationTests class. I would like to be able to recreate the problem there. You can run it and go to https://localhost:8080/login, but it isn't really set-up to test like that. I may see if I can prime my userdetail service with some ids.

https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server

**Comment by jzheaux** [comment]
See if https://github.com/spring-projects/spring-security-oauth/issues/1331 is what you are looking for with regards to your redirect_uri question.

**Comment by jzheaux** [comment]
As for testing it, I think you could do it by hitting the `/oauth/authorize` endpoint in a test, with a logged in user. I've submitted [a PR to your sample](https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server/pull/2) that illustrates.

Note that when I removed the registered uri from the test `Consumer` instance, this test failed appropriately, given #1331.

**Comment by smitchell** [comment]
@jzheaux I don't think that setting a redirect URI will work with EnableOAuth2Sso enabled on the proxy server. The Consumer instance for the Zuul proxy-service is always the same, but it, in turn, redirects the browser to different resources, like our internal website or our external website. 

I see in the Zuul proxy service logs where it cached the requested resource uri

## ZUUL PROXY
```
2019-04-08T14:07:07.941-05:00 [APP/PROC/WEB/0] [OUT] 2019-04-08 19:07:07.939 DEBUG [proxy-service,true] [80-exec-10] o.s.s.w.s.HttpSessionRequestCache :60 : DefaultSavedRequest added to Session: DefaultSavedRequest[http://[domain]/[context]/]
```

## AUTHORIZATION SERVER

In the authentication server logs I see a successful post with a 302, but it has the login url

```
[2019-04-08T19:07:25.686+0000] "POST /login HTTP/1.1" 302 135 0 "https://auth-test-cfapps.io/login" 
```

Then I see the 400 error further down
```
[2019-04-08T19:07:26.592+0000] "GET /oauth/authorize?client_id=proxy-service&redirect_uri=http://[test.domain]/login&response_type=code&state=GZCpHY HTTP/1.1" 400 0 179 "https://auth-test.cfapps.io/login" 
```

**Comment by smitchell** [comment]
I redeployed the Spring Boot 1.5.13 version of the authentication server and saw a 302 is normal for POST /login

```
2019-04-08T15:03:06.061-05:00 [RTR/10] [OUT] auth-test.cfapps.io - [2019-04-08T20:03:05.538+0000] "POST /login HTTP/1.1" 302 85 0 "https://auth-test.cfapps.io/login" 
```
This is the final message logged:

```
[2019-04-08T20:03:07.642+00:00] \"POST /oauth/token HTTP/1.1\" 200 
```

Does that mean the problem I am trying to fix, "At least one redirect_uri must be registered with the client." is actually on the Zuul Proxy server? The Zuul Proxy server was not upgraded to Spring Boot 2 and has not changed. If that is the source of the problem, then the quesiton is why?

**Comment by jzheaux** [comment]
@smitchell, I'm not sure that I'm following. In your 1.5 deployment, the Authorization Server redirects to some location. Hypothetically, why would it not work to supply that location for each client registered on the Authorization Server? (Even if it's the same location for every client)

> The consumer instance for the Zuul proxy-server is always the same, but it, in turn, redirects the browser to different resources

This is actually a very common setup even without a proxy server. Generally, it's preferred that the redirect uri be a dedicated OAuth endpoint. For example, a Client application might register a `redirect_uri` of http://myclientapplication/oauth for the Authorization Server to redirect to. That endpoint is in charge of continuing the Authorization Code flow.

Since you are using `@EnableOAuth2Sso`, I think that endpoint by default is `https://${zuul}/login`.

**Comment by jzheaux** [comment]
> Does that mean the problem I am trying to fix, "At least one redirect_uri must be registered with the client." is actually on the Zuul Proxy server? 

No, that error message was added to the Authorization Server in #1331.

**Comment by smitchell** [comment]
@jzheaux This might help. Here is the series of errors on the auth server.

```
2019-04-09 11:37:30.221 DEBUG o.s.s.w.a.i.FilterSecurityInterceptor :243 : Authorization successful
2019-04-09 11:37:30.225 DEBUG o.s.s.w.a.i.FilterSecurityInterceptor :256 : RunAsManager did not change Authentication object
2019-04-09 11:37:30.225 DEBUG o.s.security.web.FilterChainProxy :313 : /oauth/authorize?client_id=proxy-service&redirect_uri=http://test.medzero.com/login&response_type=code&state=HCskVj reached end of additional filter chain; proceeding with original chain
2019-04-09 11:37:30.239 DEBUG o.s.o.p.e.FrameworkEndpointHandlerMapping:420 : Mapped to public org.springframework.web.servlet.ModelAndView org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.authorize(java.util.Map<java.lang.String, java.lang.Object>,java.util.Map<java.lang.String, java.lang.String>,org.springframework.web.bind.support.SessionStatus,java.security.Principal)
2019-04-09 11:37:30.733 INFO  o.s.s.o.p.e.AuthorizationEndpoint :574 : Handling OAuth2 error: error="invalid_request", error_description="At least one redirect_uri must be registered with the client."
2019-04-09 11:37:30.767 DEBUG o.s.o.p.e.FrameworkEndpointHandlerMapping:420 : Mapped to public org.springframework.web.servlet.ModelAndView org.springframework.security.oauth2.provider.endpoint.WhitelabelErrorEndpoint.handleError(javax.servlet.http.HttpServletRequest)
2019-04-09 11:37:30.202 "GET /oauth/authorize?client_id=proxy-service&redirect_uri=http://test.com/login&response_type=code&state=HCskVj HTTP/1.1" 400 0 179 "https://auth-test.cfapps.io/login"
```

**Comment by smitchell** [comment]
@jzheaux Regarding "why would it not work to supply that location for each client registered on the Authorization Server? " We didn't have to do that plumbing before the upgrade, and the problem is that there is only one client involved:

1) browser -> external site -> proxy service -> auth service Login page
2) browser -> internal site -> proxy service -> auth service Login page

We don't do any security on the sites. Those are simply protected routes on the proxy service. In both cases, the proxy service ClientDetails gets used for calling the auth service. The ClientDetails getRegisteredRedirectUri() method says it is "The pre-defined redirect URI for this client to use during the "authorization_code" access grant." I don't understand how we could "pre-define" it to conditionally return the external or internal site URL. The Spring Security OAuth2 client on the proxy server must be passing a URI to the authentication server for it to know which URI to use, right? I just assume that magic is what "@EnableOAuth2Sso" on the Proxy service gets us.

**Comment by smitchell** [comment]
@jzheaux To eliminate the proxy version as the problem, I upgraded it to Spring Boot 2 running spring-cloud-starter-netflix-zuul. The Authentication server and the proxy server are both now at Spring Boot 2.1.4.RELEASE. I still get the"error "At least one redirect_uri must be registered with the client."

```
o.s.s.w.a.i.FilterSecurityInterceptor :243 : Authorization successful
o.s.s.w.a.i.FilterSecurityInterceptor :256 : RunAsManager did not change Authentication object
o.s.o.p.e.FrameworkEndpointHandlerMapping:420 : Mapped to public org.springframework.web.servlet.ModelAndView org.springframework.security.oauth2.provider.endpoint.WhitelabelErrorEndpoint.handleError(javax.servlet.http.HttpServletRequest)
"GET /oauth/authorize?client_id=proxy-service&redirect_uri=http://[domain]/login&response_type=code&state=wV5mrX HTTP/1.1" 400 0 179 "https://auth-test.cfapps.io/login"
```

**Comment by smitchell** [comment]
The DefaultRedirectResolver is doing what it coded to do. 

```
if (registeredRedirectUris == null || registeredRedirectUris.isEmpty()) {
			throw new InvalidRequestException("At least one redirect_uri must be registered with the client.");
}
```

We didn't have a custom redirect resolver with Spring Boot 1.5, so for this to be working in Prod today either the DefaultRedirectResolve is being overwritten, or the registeredRedirectUri is being set on the proxy's ClientDetail. There must be a redirect_uri query paramter coming from the proxy service oauth2 client that triggering that behavor in the authentication server on Spring Boot 1.5.

**Comment by smitchell** [comment]
I verified that the unit test below works the same in our 1.5.13.RELEASE authentication server project as it does in the 2.1.3.RELEASE project linked to this Issue. I ran a query on our consumer table to confirm that the registered redirect uris column is always null.There has to be a parameter passed in by the SSO oauth2 client in the Zuul proxy service that is causing the DefaultRedirectResolver bean to be overwritten, or is used to set the proxy's ClientDetail registeredRedirectUri property.

```
  @Test
  @WithMockUser
  public void authorizationRedirectsAfterLogin() throws Exception {
    mockMvc.perform(get("/oauth/authorize")
        .param("client_id", "dummy-client")
        .param("response_type", "code")
        .with(user("username")))
        .andExpect(forwardedUrl("/oauth/confirm_access"));
  }
```

**Comment by jzheaux** [comment]
@smitchell Spring Boot 2.1.x Authorization Server requires a `redirect_uri` be registered for each client in order to defend against Open Redirect attacks. You can see the details in #1331. You didn't need this in 1.5 because that feature didn't exist until 2.1.

Upgrading the client won't fix it as this complaint is coming from the Authorization Server. Either the client registrations on the Authorization Server need to have `redirect_uri`s supplied (say, via your database), or you'll need to register a redirect resolver that skips that check (not advised).

As you know, the way OAuth 2.0 works is a client redirects to `/authorize` on an Authorization Server. The Authorization Server logs the person in and then redirects them back to the client. As of #1331, this redirect location must be registered to the Authorization Server. You'll see in the test I added to your sample that whether or not the client sends a `redirect_uri` in the initial `/authorize` call is immaterial.

The test confirms that if a `redirect_uri` is added to the consumer, then 2.1 passes, but if removed, then it fails. So my question for you is, have you tried the steps I advised yet and what were the results?

**Comment by jzheaux** [comment]
The test I wrote is not intended to fail on Spring Boot 1.5. It passes on 2.1 because the Consumer in the test as a redirect uri specified.

**Comment by smitchell** [comment]
@jzheaux Almost there! Sorry, I didn't understand what you wanted me to see in 1331, now I get it. I committed changes to the linked project.

1) I updated the authorizationRedirectsAfterLogin() test to have a redirect_uri.
2) I updated the ClientDetails Registered Redirect Uris to have a set of values.
3) The test still passes.

Next, I updated our "proxy-service" ClientDetails database record with registered URIs for our protected websites. We should probably close this issue as the solution was to assign registeredRedirectUris. I no longer get the error.

Now I get redirected back to the login page and go into a redirect loop. Would you agree that should be addressed separately?

**Comment by petrdvorak** [comment]
Hello @jzheaux, this change surprised us a bit as well... Could you make this as a regexp check? So that we are able to specify:

- "We want an exact redirect address pattern."
- "We want a pattern on a given domain, for example, all redirects to https://my.domain.com/ are good."
- "We don't care about all this, let's use `.*`..."
