### ISSUE TITLE
Ability to have immortal refresh tokens

### ISSUE THREAD

**Issue by collinpeters** [spring-projects/spring-security-oauth#166]
Currently the refresh token support in DefaultTokenServices is built as an int and must have a value which is either the default in the class (30 days), or injected globally. Then it can be overridden per OAuth client. What I don't see is a way to set them to live forever. This would be useful for trusted clients.

**Comment by shlomicthailand** [comment]
Hi 
i absolutely agree with totof3110  - this is exactly our case  , a server that sync with our service after the user has put his refresh token in there.
please consider this feature - its a must.

**Comment by jricher** [comment]
We've implemented optionally immortal refresh tokens in our own service, [MITREid Connect](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server). To do this with SECOAUTH, we have our own implementation of token services and token classes that give us the flexibility we need to make it work.

**Comment by shlomicthailand** [comment]
jricher  - thats impressing , and i'm sure the feature list that differ from original spring is long, but i would try to contribute this instead of making my own fork. if this is one class or 2 then its ok and one  can wait for a version upgrade but from my experience when you do more , after 2 spring versions it would not be easy to upgrade.

**Comment by jricher** [comment]
We haven't officially forked the Spring component, but we're overriding the majority of its functionality at this point. We'd welcome your input over on our own project, but note that it's an implementation more than it is a general-purpose library. I doubt you'd be able to get this one piece of functionality by pulling just a couple of classes.

**Comment by shlomicthailand** [comment]
Dave i think there is a problem with the refresh token grant. looks like it would not be recreated while getting new access token , which mean the client cannot use it forever. 
I looked closely in the code code in DefaultTokenServices and looks like in the createAccessToekn method there are remarks and also code that indicate if the refresh token expired a new one is created. but this code is not called when user refresh an access token (only the first time the access token is requested in authorization_code grant for example) 
when user call refresh token - the code in refreshAccessToken method check the refresh token expiration and throws exception if it does. this somehow contradict the policy of the previous method to recreate refresh token.
hope you managed to understand me :-)

**Comment by gerar2** [comment]
It seems that when creating immortal refresh tokens is not working when using JWT.
I have a client configured with refreshTokenValiditySeconds(0) but when using JwtAccessTokenConverter the token expire at the same time as the access token.

Could it be a bug or am I missing something?

Thanks

**Comment by dsyer** [comment]
This issue is closed. If you have a new issue, please open a new ticket.
