### ISSUE TITLE
No 'active' found in the response of CheckTokenEndpoint

### ISSUE THREAD

**Issue by hpq86zllw** [spring-projects/spring-security-oauth#1663]
### Actual Behavior

When using `@EnableAuthorizationServer`, no `active` found in the response of CheckTokenEndpoint.
In 2.2.2.RELEASE, it is returned.

### Expected Behavior

Include `active` in the response of CheckTokenEndpoint

### Configuration

Enable @EnableAuthorizationServer with default setting

### Version

2.2.4.RELEASE

**Comment by jgrandja** [comment]
This is a duplicate of #1616
