### ISSUE TITLE
Attribute ifAllGranted invalid for tag authorize

### ISSUE THREAD

**Issue by xj20305** [spring-projects/spring-security-oauth#1672]
so gb what,,,
i just clone and follow the readme step, 
execute tonr2   tomcat7:run ,then open url for login
http://localhost:8080/sparklr2/
jus press login button,then problem coming.
信息: Initializing Spring FrameworkServlet 'dispatcher'
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://www.springframework.org/security/tags is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://www.springframework.org/tags is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://www.springframework.org/tags/form is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/core_rt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/core is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/core is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/fmt_rt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/fmt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/fmt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/functions is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/permittedTaglibs is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://jakarta.apache.org/taglibs/standard/scriptfree is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/sql_rt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/sql is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/sql is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/xml_rt is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jstl/xml is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.startup.TaglibUriRule body
信息: TLD skipped. URI: http://java.sun.com/jsp/jstl/xml is already defined
五月 04, 2019 11:17:12 上午 org.apache.catalina.core.ApplicationContext log
信息: 1 Spring WebApplicationInitializers detected on classpath
五月 04, 2019 11:17:12 上午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring FrameworkServlet 'dispatcher'
五月 04, 2019 11:17:15 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-bio-8080"]
五月 04, 2019 11:17:39 上午 org.apache.jasper.compiler.TldLocationsCache tldScanJar
信息: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
五月 04, 2019 11:17:40 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [jsp] in context with path [/sparklr2] threw exception [/index.jsp (line: 29, column: 2) Attribute ifAllGranted invalid for tag authorize according to TLD] with root cause
org.apache.jasper.JasperException: /index.jsp (line: 29, column: 2) Attribute ifAllGranted invalid for tag authorize according to TLD
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:237)
 
i dont hnow whey the tld skipped,(http://www.springframework.org/security/tags )

**Comment by glitchcube** [comment]
It seems to be a problem when updating version spring.security.version from 3.2.10.RELEASE to 4.2.11.RELEASE.

Perhapse the tag ifNotGranted is deprecated?
