### ISSUE TITLE
SSO/w JWT Tokens not redirecting after upgrade to Spring Boot 2

### ISSUE THREAD

**Issue by smitchell** [spring-projects/spring-security-oauth#1676]
### Summary

After upgrading our authentication server from Spring Boot 1.5.13 to 2.1.3 it stopped redirecting after successful logins. There is a Zuul Proxy Server that sits in front of our microservices.  Spring Security 5 tries to reload the /login page again after successfully loging in instead of allowing the request to go back to the protected resource behind the proxy server as it does with Spring Boot 1.5.13. 

It is my understanding that the root cause is that only the oauth2 client has been ported from its Spring Security extension codebase to Spring Security Oauth2 and that in the meantime the authentication server must build the JWT token and put it in the Authorization header. I did that by adding custom filters, but the redirect after successful login still does not work.

### Actual Behavior

1. User tries to access the Angular site via an SSO-enabled proxy server.
2. Spring Security on the proxy server redirects the user's browser to the Login page on the authentication server.
3. The user signs in and posts the Login form to the authentication server.
4. The authentication server forwards the user back to the Login page.

### Expected Behavior

1. User tries to access the Angular site via an SSO-enabled proxy server.
2. Spring Security on the proxy server redirects the user's browser to the Login page on the authentication server.
3. The user signs in and posts the Login form to the authentication server.
4. The authentication server creates a JWT oauth2 token, puts it in the Authorization header, and then forwards the request to the original target URI, in this case, the Angular Example site.

### Configuration

The auth server configuration can be found https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server. The[ proxy server](https://github.com/smitchell/spring-boot-netflix-zuul-proxy) uses EnableOAuth2Sso. I added custom filters to create and verify JWT tokens using this example: https://github.com/keysh/jwt-security.

### Version

Spring Boot 2.1.3.RELEASE.

### Sample

- **Angular Example** - If you bypass the proxy and go to the angular example route the page loads. [TRY IT](https://angular-example.test.medzero.cfapps.io/).
- **Authentication Example** - If you bypass the proxy and go to the authentication server root you can sign in and access a protected page. [TRY IT](https://auth-example.test.medzero.cfapps.io/)
- **Zuul Proxy Example** - If you try to access the angular example via the proxy, then you do not get forwarded to the angular example after logging in. [TRY IT](https://zuul-proxy-example.test.medzero.cfapps.io/angular-example/)

All source code is in Github:
- **Angular example Github**: https://github.com/smitchell/cloud-foundry-angular-example
- **Proxy Server Github**: https://github.com/smitchell/spring-boot-netflix-zuul-proxy
- **Auth Server Github**: https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server

**Comment by sunshixiong789** [comment]
yes,I want to konw too

**Comment by HJK181** [comment]
Any updates?

**Comment by smitchell** [comment]
It is my understanding that only the OAuth2 client has been ported from the OAuth2 extension to Spring Security core. The rest is being ported now, but I don’t what release. We opted to leave are authentication server at Spring Security 4 until they finish. It works fine with the Spring Security 5 OAuth2 clients running on all our resource servers.

**Comment by jgrandja** [comment]
@smitchell I started looking into this for you but startup failed for `spring-boot-netflix-zuul-proxy`. I'd prefer to run this locally (instead of PCF) for debugging purposes. Can you please update the app/config(s) to ensure it starts up locally.

Also, I wasn't able to run `cloud-foundry-angular-example` as well. Please provide detail instructions on what I need to do to get that up and running as well. Looks like I might need to install some Angular components?

> It is my understanding that only the OAuth2 client has been ported from the OAuth2 extension to Spring Security core

Spring Security 5.1 have both client and resource server features and with the soon to be releases 5.2, both client and resource server features will be at feature parity with Spring Security OAuth legacy features. We are targeting 5.3 for initial release of Authorization Server.

**Comment by smitchell** [comment]
@jgrandja - I did this on a Linux machine and had all kinds of difficulty with pcfdev, which is why I fell back to PWS. 

1. I will review the PWS instructions. I'm guessing the problem is the routes, which must be changed.
2. I will try again to get it to work with pcfdev, but this time, on my Mac. The problem I had was with pcfdev Cloud Services. The service registration did not work. 

I will let you know how it goes.

**Comment by smitchell** [comment]
@jgrandja - I updated the readme, application.yml, and manifest files on GitHub (projecte links are above):

1. Deploy all three projects with the routes commented out so new routes get mapped.
2. Update the application.yml and manifests with the routes that were mapped per instructions on README page.
3) Re-push the apps.
4) Follow the testing instructions.

The only glitch is that after a successful login to [proxy route]/angular-example/, you get a permission denied on the second reload of the /login page. That still shows the bug. It should have redirected you to [proxy route]/angular-example/ after the successful login. I'll mess around with pcfdev on my Mac next.

**Comment by smitchell** [comment]
@jbiblio - I can't run pcfdev. cf 6.46 says that pcfdev-pas.v.2.0.22.0-build.0.0.71-darwin.tgz is not compatible. I don't know what I'm supposed to do with pcfdev_2.1_osl.txt. pcfdev on Linux: fail. pcfdev on Mac: fail. I don't have a Windows machine. If you have have a working pcfdev environment then you should be able to follow my instructions above there too.

**Comment by jgrandja** [comment]
@smitchell Maybe I wasn't clear in my last comment? My preference is to run the 3 apps on my locally machine - NOT in PCF. It's easier for me to debug and troubleshoot and it takes environment related complexities out of the equation.

So if you can update the app configs so it works in a local setup that would be helpful.

**Comment by smitchell** [comment]
@jgrandja - please follow the updates i made to the readme files yesterday.

**Comment by jgrandja** [comment]
@smitchell I just cloned `spring-boot-netflix-zuul-proxy` and when I run `Application` I get the following error:

```
2019-08-22 15:13:58.933 ERROR 79878 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='https://eureka-6e9cd6de-58b7-4b08-a10e-5e176a7a7cea.cfapps.io:8761/eureka/}
```

What I'm looking for is an easy/quick setup to a point where I can reproduce the issue you are having. I do not want to make application configuration changes to make this work locally on my laptop. Your sample and instructions are based on deploying to PCF which is what I'm trying to avoid here.

It would be a lot more efficient if you can setup these 3 applications (possibly in separate branch) so they startup on my local machine. This will allow me to be the most effective in troubleshooting. I will wait until you're able to provide this.

**Comment by jgrandja** [comment]
@smitchell I'm not sure if there is a PCF distribution that can be installed locally? Regardless if it's possible, **I do not want to run these in a PCF env**. I simply want to start the 2 Spring Boot apps - auth server and proxy - and the Angular app.

**Comment by smitchell** [comment]
Got it. I'll work on that.

**Comment by smitchell** [comment]
@jgrandja - I committed changes to the projects to run on localhost:4200, 4201 and 4202. I could use your help in understanding why that changed the behavior of Spring Security. Going through the proxy (http://localhost:4201/angular-example/) it now shows the 3-legged OAuth2 dialog.

**Comment by jgrandja** [comment]
@smitchell I was able to start up proxy and auth-server on my local machine but SSO did not work.

I first tried accessing the proxy via http://localhost:4201 and this triggered the SSO (`authorization_code`) flow with the auth-server on http://localhost:4202. After I authenticate with the auth-server, the browser gets redirected back to the proxy with the `code` but the oauth-client fails to complete the Authorization  Code grant flow. The reason for the failure is because it cannot correlate the previous Authorization Request with the incoming Authorization Response containing the `code`. This is because the `Cookie` name used for both the auth-server session and proxy session is the same `UISESSION`:

```yaml
server:
  servlet:
    session:
      cookie:
        name: UISESSION
```

So essentially what happens here is that the **auth-server session cookie overwrites the previously generated proxy session cookie with the same name `UISESSION`**.

After I make the following change to the auth-server `application.yml`:

```yaml
server:
  servlet:
    session:
      cookie:
        name: PROVIDER
```

it works as expected. This may be related to the issue you are having in PCF?

**Comment by smitchell** [comment]
@jgrandja - I'm not having the same experience. I updated the application.yml, but instead of going to the angular site after login I am presented with the 3-legged oauth page "Do you authorize "zuul-proxy-example" to access your protected resources?" I'm going to update to 2.18-RELEASE and retest.

**Comment by smitchell** [comment]
@jgrandja - After a lot of testing this weekend I understand what is happening, but I don't know why. After you sign-in, the user is redirected to the proxy /login page instead of /angular-example. That is why I get the "Do you authorize "zuul-proxy-example" page.

**Setup**
1) Clone https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server
2) mvn spring-boot:run
3) Clone https://github.com/smitchell/cloud-foundry-angular-example
4) mvn spring-boot:run
5) Clone https://github.com/smitchell/cloud-foundry-angular-example
6) ng serve  --baseHref=/angular-example/ 

**Steps to Reproduce:**
1) Navigate to http://localhost:8085/angular-example/
2) Login as "user" / "password"
3) The third-party auth page appears. Click Agree.
4) The Angular home page is displayed.

**Reason for third-party auth page appearing** 
To see the unnecessary redirect to proxy /login page (http://localhost:8085/login) remove "http://localhost:8085/login" from the registered redirects by commenting out line 25 and uncommenting line 26 in AuthClientDetailsService.java. Restart the Auth server and try the steps above. You now get this message:

`error="invalid_grant", error_description="Invalid redirect: http://localhost:8085/login does not match one of the registered values."`

I am back to my original question in this Issue, why does using @EnableOAuth2Sso on a Zuul proxy, not redirect the user back to the originally requested URI after successfully logging in?

**Comment by smitchell** [comment]
@jgrandja - I apologize for not catching this in my previous comment (see below). I assume this means that the problem is in the proxy configuration since it passes a redirect URL of "&redirect_uri=http://localhost:8085/login" instead of "&redirect_uri=http://localhost:8085/angular-example." Is that correct, and if so, why isn't /angular-example being passed?

1. GET http://localhost:8085/angular-example/ 302
2. GET Location: http://localhost:8085/login 302
3. GET Location: http://localhost:8084/oauth/authorize?client_id=zuul-proxy-example&redirect_uri=http://localhost:8085/login&response_type=code&state=pgAptw 302
4) GET http://localhost:8084/login 200
5) POST http://localhost:8084/login 302
6) GOT Request URL: http://localhost:8084/oauth/authorize?client_id=zuul-proxy-example&redirect_uri=http://localhost:8085/login&response_type=code&state=aFcXyH 200
7) POST http://localhost:8084/oauth/authorize
8) GET http://localhost:8085/login?code=9jlmH7&state=aFcXyH 302
9) GET http://localhost:8085/angular-example/ 200

**Comment by smitchell** [comment]
@jgrandja - In Prod, with a Spring Security 5 client on the Zuul proxy calling a Spring Security 4 Authentication Server, there is 301 on the proxy login page that is missing when I run my code locally. Is it because of Cloudflare and not related? The extra 301 is returned for https://hostname/login before and after the custom login page. Note that on step 9, the proxy server redirects to the originally requested URI. That is what is missing after upgrading the auth server to Spring Security 5.

1. GET https://[hostname]/[context-path] 200
2. GET https://[hostname]/login 301 Moved Permanently Location: https://hostname/login
3. GET https://[hostname]/login 302 
4. GET https://[auth server host]/oauth/authorize?client_id=[a client]&redirect_uri=http://[hostname]/login&response_type=code&state=5FYUGh 302
5. GET https://[auth server host]/login 200
6. POST https://[auth server host]/login 302 (custom login with user/password)
7. GET https://[auth server host]/oauth/authorize?client_id=[a client]&redirect_uri=http://[hostname]/login&response_type=code&state=5FYUGh 302
8. GET http://[hostname]/login?code=dzJlPi&state=5FYUGh 301
9. GET http://[hostname]/login?code=dzJlPi&state=5FYUGh 302 location: https://[hostname]/[context-path]
10. https://[hostname]/[context-path] 200

**Comment by smitchell** [comment]
There were two places to disable the 3rd party popup:

**ON THE CLIENT / CONSUMER IN THE AUTH SERVICE**
`  public ClientDetails loadClientByClientId(String clientId) {
    // Return this no matter what clientId is passed in.
    Consumer consumer = new Consumer();
    consumer.setScopeCsv("read,write,trust");
    consumer.setAutoApproveCsv("true"); // <---- THIS FIXED THE PERMISSION POPUP
    consumer.setAuthorizedGrantTypesCsv("password,refresh_token,authorization_code");
    consumer.setAccessTokenValiditySeconds(100);
    consumer.setRefreshTokenValiditySeconds(100);
    consumer.setClientId(clientId);
    consumer.setRegisteredRedirectUrisCsv("http://localhost:8085/login,");
    consumer.setClientSecret(new BCryptPasswordEncoder().encode("client-secret"));
    return  consumer;
  }`

**IN THE CLIENT CONFIG IN THE PROXY SERVICE**
`security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8084/oauth/token
      userAuthorizationUri: http://localhost:8084/oauth/authorize
      clientId: zuul-proxy-example
      clientSecret: client-secret
      auto-approve-scopes: '.*' # <--- DISABLES THE PERMISSION POPUP`
