### ISSUE TITLE
User credentials saved in TokenStore

### ISSUE THREAD

**Issue by dciarniello** [spring-projects/spring-security-oauth#1678]
I just noticed that when an access token is stored in the token store, the user authentication object still contains the user's credentials (i. e. password).  According to https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#core-services-erasing-credentials, credentials are cleared by default after authentication but the clearing happens after the access token is placed in the token store.  That means that in the case of JdbcTokenStore, client credentials are persisted to the database.  That is inconsistent with the statement, "This prevents information like passwords being retained longer than necessary".

Is this not a security problem?  If not, why not?  Is there a way, without writing a custom implementation of JdbcTokenStore, to prevent credentials from being stored in the DB?

**Comment by dciarniello** [comment]
No response?  An obvious security hole is ok?

**Comment by jgrandja** [comment]
@dciarniello Thanks for the report. Can you please provide more details around...

> credentials are cleared by default after authentication but the clearing happens after the access token is placed in the token store

What authentication mechanism are you using? `@EnableOAuth2Sso`, `formLogin()`?

Are you able to put together a minimal sample that demonstrates the issue?

> Is there a way, without writing a custom implementation of JdbcTokenStore, to prevent credentials from being stored in the DB?

Unfortunately no. If you need to customize what is stored and what is not stored, you will need to supply a custom persistent `TokenStore`.

**Comment by dciarniello** [comment]
Hi, @jgrandja 

I was not able to replicate the issue with a sample app which led me to discover a bug in the app I'm working on.  I subclassed AbstractAuthenticationToken but did not override the eraseCredentials() method which, going by UsernamePasswordAuthenticationToken, is necessary to ensure that credentials are properly erased.

This issue can be closed.
