### ISSUE TITLE
Unsafe deserialization in RedisTokenStore

### ISSUE THREAD

**Issue by artem-smotrakov** [spring-projects/spring-security-oauth#1682]
(after discussing on security@pivotal.io, it was decided to consider the below as a defense in depth improvement)

Making a long story short, compromising a Redis server may lead to compromising the whole application. It can happen due to unsafe deserialization. Of course, compromising a Redis server looks like a serious issue by itself. Redis servers should be protected and configured in a secure way. But nevertheless I am wondering if spring-security-oauth should be updated a bit to prevent arbitrary code execution in the application in case the Redis server is hacked.

Here are some details. An application can use `RedisTokenStore` which stores and reads auth info from a Redis server. `RedisTokenStore` uses the default Java serialization mechanism to prepare data to be stored in the Redis server. Here is how `ObjectInputStream` can be called:

```
  RedisTokenStore.getAccessToken()                       (spring-security-oauth)
    RedisTokenStore.deserializeAccessToken()             (spring-security-oauth)
      JdkSerializationStrategy.deserializeInternal()     (spring-security-oauth)
        JdkSerializationRedisSerializer.deserialize()    (spring-data-redis)
          DeserializingConverter.convert()               (spring-framework)
            DefaultDeserializer.deserialize()            (spring-framework)
              ConfigurableObjectInputStream.readObject() (spring-framework)
```

--- content deleted ---

You can see there are two pre-requisites to make this attack work:
- An attacker should be able to modify data in Redis.
- Application's classpath should contain classes to build a deserialization gadget.

The pre-requisites above may be quite hard to meet which makes it harder to successfully implement the attack. Nevertheless it may be better to update the framework and libs to mitigate it.

I have several patches which can address this issue. The patches update Spring Framework, Spring Data Redis and Spring Security OAuth. The main idea is to introduce whitelisting in `ConfigurableObjectInputStream` to be able to deserialize only allowed classes, and then, `JdkSerializationStrategy` can set a list of safe classes.

Another way to fix this is to use the filtering mechanism which was introduced in JEP 290 [1].
JEP 290 has been backported to JDK 6u141. So, Spring Framework would require at least JDK 6u141 then.

If the idea sounds okay, I can open pull requests, and we can finalize the solution.

[1] https://openjdk.java.net/jeps/290

**Comment by jgrandja** [comment]
Thanks for the report @artem-smotrakov. Please note that I removed some content (marked) from the main comment so we don't provide details on how to re-produce.

> I have several patches which can address this issue. The patches update Spring Framework, Spring Data Redis and Spring Security OAuth

We would welcome a PR for this improvement but I'm wondering if it's possible to submit changes that are containing only within `spring-security-oauth`?

**Comment by artem-smotrakov** [comment]
> We would welcome a PR for this improvement but I'm wondering if it's possible to submit changes that are contained within `spring-security-oauth` only?

@jgrandja I think it should be possible by adding a custom implementation of `ObjectInputStream` to `spring-security-oauth`. It would probably result to more changes to `spring-security-oauth`. I tried to introduce less changes in the original patches. If it's fine then I'll try to re-work the patch for `spring-security-oauth`.

**Comment by jgrandja** [comment]
@artem-smotrakov Yes, please try containing the changes within `spring-security-oauth`.
Thank you.

**Comment by artem-smotrakov** [comment]
@jgrandja I opened a pull request. Please take a look. Thanks!
