### ISSUE TITLE
API Doc version mismatch

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-security-oauth#1689]
### Summary

The version of API Doc mentioned on the learn page doesn't match the version of the API Doc that I actually arrive at.

### Actual Behavior

When I visit https://spring.io/projects/spring-security-oauth#learn and click the API Doc link fo the current version (2.3.5 at present), I end up on a Javadoc page whose title is "OAuth for Spring Security 2.0.4.RELEASE API".

### Expected Behavior

I would expect the versions to match (or there might be some other indicator to account for the mismatch).

### Configuration

None. Just surfing the Spring Security Oauth site.

### Version

I checked the other versions of Spring Security Oauth that are available on the Learn page (2.3.6 and 2.2.4). They also go to the 2.0.4 RELEASE API.

### Sample

NA

**Comment by DavidSonoda** [comment]
Same question here.

**Comment by philwebb** [comment]
This is also causing issues for Spring Boot as we want to use versioned links from our own docs.

**Comment by jzheaux** [comment]
I'm doing a bit of archaeology to figure out how this project deploys its API docs.

In the meantime, it might be handy to point to https://www.javadoc.io/doc/org.springframework.security.oauth/spring-security-oauth which builds the docs from source, AFAIK. 

It would be better than leaving an out-of-date link up on the site, should this take a bit to unearth.

**Comment by jgrandja** [comment]
I had to re-configure the CI setup. The javadoc now points to the correct version.
