### ISSUE TITLE
TokenEndpoint is always returning application/json in response

### ISSUE THREAD

**Issue by shawly** [spring-projects/spring-security-oauth#1699]
### Summary
We use oauth2 for authorization in our hybris webservice extension.
Problem is, in hybris version 6.5 we still used version 2.0.4, which didn't have this patch https://github.com/spring-projects/spring-security-oauth/issues/1268 by @jgrandja 

One of our third party clients uses this for their application, which sends the Accept request header with application/xml, so the TokenEndpoint returns XML, **BUT** the response header Content-Type is still  application/json which is caused by this patch.
Since our client uses the Jersey API's ClientResponse, which reads the responses Content-Type to determine a matching parser for the given type, this patch causes big problems for our clients which prevents their customers from buying products over the third party application.

The TokenEndpoint needs to know which Content-Type the client actually expects instead of just hardcoding application/json as Content-Type.

### Actual Behavior
Token is requested with request header "Accept: application/xml"
Response body is returned as XML but the response header is still "Content-Type: application/json"

### Expected Behavior
Token is requested with request header "Accept: application/xml"
Response body is returned as XML and the response header is "Content-Type: application/xml"

### Version
2.3.5 & 2.3.6

**Comment by shawly** [comment]
This is still an issue.

**Comment by shawly** [comment]
Still an issue.

**Comment by jgrandja** [comment]
@shawly As per spec, in section [5.1. Successful Response](https://tools.ietf.org/html/rfc6749#section-5.1):

> The parameters are included in the entity-body of the HTTP response
   using the "application/json" media type as defined by [RFC4627].  The
   parameters are serialized into a JavaScript Object Notation (JSON)
   structure by adding each parameter at the highest structure level.

This has been implemented to spec, which is our main goal. If you require XML content to be returned, then you will have to provide this customization.

FYI, please see this [post](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update) in case you are not aware of the status of this project.

**Comment by shawly** [comment]
I can see the reason implementing stuff to spec. But disregarding any logic because the spec says so seems irrational to me.

But when sending a request header with **Accept: application/xml** and the Oauth server IS returning **XML content** with the response header containing **Content-Type: application/json** it doesn't make much sense and I have my doubts that the spec enforces that type of behavior. 
At least you should cut off any XML support then and enforce the formatting of the response to the content-type you are enforcing with the header per spec.

Nonetheless the info about the EOL of spring-security-oauth is indeed valuable, thank you.
