### ISSUE TITLE
How can I reuse refresh_token with JwtAccessTokenConverter uesd?

### ISSUE THREAD

**Issue by pso2yui** [spring-projects/spring-security-oauth#1733]
### Summary
Hey,
I am using spring cloud oauth2 with RedisTokenStore and JwtTokenConverter.
I wanna reuse refresh token. But it still creates a new one after calling access token endpoint at refresh_token mode. 

### Configuration

@Configuration
@EnableAuthorizationServer
@AllArgsConstructor
public class AuthorizationServerConfiguration extends AuthorizationServerConfigurerAdapter {
  private AuthenticationManager authenticationManager;

  private RedisConnectionFactory factory;

  private DataSource dataSource;

  private UserDetailsService baseUserDetailService;

  private PasswordEncoder passwordEncoder;

  @Bean
  public AuthorizationCodeServices authorizationCodeServices() {
    return new InMemoryAuthorizationCodeServices();
  }

  @Bean
  public TokenStore tokenStore() {
    return new RedisTokenStore(factory);
  }

  @Bean("cacheClientDetailsService")
  public ClientDetailsService clientDetailsService() {
    return new CacheClientDetailsService(dataSource);
  }

  @Override
  @SneakyThrows
  public void configure(ClientDetailsServiceConfigurer clients) {
    clients.withClientDetails(clientDetailsService());
  }

  @Override
  public void configure(AuthorizationServerSecurityConfigurer oauthServer) {
    oauthServer
        .tokenKeyAccess("permitAll()")
        .checkTokenAccess("isAuthenticated()")
        .passwordEncoder(passwordEncoder);
  }

  @Bean
  @Primary
  public DefaultTokenServices defaultTokenServices() {
    DefaultTokenServices tokenServices = new DefaultTokenServices();
    tokenServices.setTokenStore(tokenStore());
    tokenServices.setTokenEnhancer(jwtAccessTokenConverter());
    tokenServices.setSupportRefreshToken(true);
    tokenServices.setReuseRefreshToken(true);
    tokenServices.setClientDetailsService(clientDetailsService());
    tokenServices.setAccessTokenValiditySeconds((int) TimeUnit.MINUTES.toSeconds(10));
    tokenServices.setRefreshTokenValiditySeconds((int) TimeUnit.MINUTES.toSeconds(30));
    PreAuthenticatedAuthenticationProvider provider = new PreAuthenticatedAuthenticationProvider();
    provider.setPreAuthenticatedUserDetailsService(
        new UserDetailsByNameServiceWrapper<>(baseUserDetailService));
    tokenServices.setAuthenticationManager(
        new ProviderManager(Collections.singletonList(provider)));
    return tokenServices;
  }

  @Override
  public void configure(AuthorizationServerEndpointsConfigurer endpoints) {
    endpoints
        .authenticationManager(authenticationManager)
        .authorizationCodeServices(authorizationCodeServices())
        .accessTokenConverter(jwtAccessTokenConverter())
        .userDetailsService(baseUserDetailService)
        .reuseRefreshTokens(true)
        .allowedTokenEndpointRequestMethods(HttpMethod.GET, HttpMethod.POST)
        .tokenServices(defaultTokenServices())
        .tokenStore(tokenStore());
  }

  @Bean
  public JwtAccessTokenConverter jwtAccessTokenConverter() {
    JwtAccessToken converter = new JwtAccessToken();
    KeyPair keyPair =
        new KeyStoreKeyFactory(new ClassPathResource("keystore.jks"), "root_pass".toCharArray())
            .getKeyPair("jwt_key");
    converter.setKeyPair(keyPair);
    return converter;
  }
}

### Version
artifactId : spring-cloud-starter-oauth2
version : 2.1.3.RELEASE

As the DefaultTokenServices#setReuseRefreshToken Api says, it should reuse refresh tokens (until expired), however, it does not work. I have no idea how to fix it, do I miss any key configurations?

Regards!

**Comment by jgrandja** [comment]
This is a duplicate of #1109. Please see [comment](https://github.com/spring-projects/spring-security-oauth/issues/1109#issuecomment-546453794)
