### ISSUE TITLE
RemoteTokenServices doesn't check token expiration causing a misleading "Possible CSRF detected" exception + DefaultAccessTokenConverter issue

### ISSUE THREAD

**Issue by zonia3000** [spring-projects/spring-security-oauth#1742]
Hi guys, I debugged this for a bit and I'm proposing a solution.

### Summary

In an OAuth2 authorization code grant flow, if a broken authorization server returns a **negative `expires_in` value** in the Authorization Code Response, the Spring code on the client side produces a `InvalidRequestException: Possible CSRF detected - state parameter was required but no state could be found` instead of `InvalidTokenException: Access token expired`, even if the state parameter is present in the request.

### Actual Behavior

I followed the flow using the debugger, here is a detailed description of all the steps involved.

Starting point: the client send the Authorization Code Request to the authorization server, e.g.:

    http://my-auth-server/auth/oauth2/authorize?client_id=my-client&redirect_uri=http://my-client/login&response_type=code&state=TnfWrS

At this phase, on the client, the `DefaultOAuth2ClientContext` `state` map contains the following pair:

    <TnfWrS, http://my-client/login>

Then, the authorization server returns the Authorization Code Response.

So, on the client, `OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication()` is called.

Then `OAuth2RestTemplate.getAccessToken()` is invoked.
Inside the `OAuth2RestTemplate` class, `context.getAccessToken()` returns null, so the method `acquireAccessToken()` is called and it removes the value from the `DefaultOAuth2ClientContext` state map:

    accessTokenRequest.setPreservedState(oauth2Context.removePreservedState(stateKey));

After this, the token is retrieved. Suppose that in this phase a broken authorization server implementation generates a token with a negative `expires_in` value (this happened to me with a custom authorization server that had a bug caused by a wrong time zone configuration).

    expires_in: -3600

So, the method `OAuth2RestTemplate.getAccessToken()` returns an expired token.

Now we are again in the `OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication()` method and `RemoteTokenServices.loadAuthentication()` is called.
If this class doesn't check if the just received token is already expired, we reach the following line:

    publish(new AuthenticationSuccessEvent(result));

This cause the `OAuth2ClientAuthenticationProcessingFilter.successfulAuthentication()` method getting called. This calls again the `restTemplate.getAccessToken()`. This time the `context.getAccessToken()` returns an expired token, so the `acquireAccessToken()` method is called again, and again it tries to remove the value from the `DefaultOAuth2ClientContext` state map:

    accessTokenRequest.setPreservedState(oauth2Context.removePreservedState(stateKey));

However the value has already been removed, so it looks like the state parameter is missing.

All ends when the `AuthorizationCodeAccessTokenProvider` attempt to retrieve the token again, with the follwing exception: `Possible CSRF detected - state parameter was required but no state could be found`

However the state parameter has been sent into the request, so receiving this exception here is very misleading.

Here the relevant stack trace:

```
org.springframework.security.oauth2.common.exceptions.InvalidRequestException: Possible CSRF detected - state parameter was required but no state could be found
ia2-gms_1  |    at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getParametersForTokenRequest(AuthorizationCodeAccessTokenProvider.java:255) ~[spring-security-oauth2-2.3.6.RELEASE.jar!/:na]
ia2-gms_1  |    at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:209) ~[spring-security-oauth2-2.3.6.RELEASE.jar!/:na]
ia2-gms_1  |    at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221) ~[spring-security-oauth2-2.3.6.RELEASE.jar!/:na]
ia2-gms_1  |    at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173) ~[spring-security-oauth2-2.3.6.RELEASE.jar!/:na]
```

### Expected Behavior

Receiving `InvalidTokenException: Access token expired` should be more appropriate

### Version

Tested on version 2.3.5, 2.3.6 and 2.3.7.

### Sample

I don't have a sample (if you really need it I can set up a demo project), but I'm proposing a solution with some unit tests here: https://github.com/zonia3000/spring-security-oauth/commit/eb175de64427473cdad08dfb54c19aa801d92d4b

If you think this is good I'll open a PR.

Moreover I found an additional issue inside the `DefaultAccessTokenConverter` class:

    token.setExpiration(new Date((Long) map.get(EXP) * 1000L));

should be replaced with this

    token.setExpiration(System.currentTimeMillis() + new Date((Long) map.get(EXP) * 1000L));

as happen for example in `DefaultOAuth2AccessToken` and `DefaultTokenServices`, otherwise the token will be expired.

**Comment by jgrandja** [comment]
@zonia3000 Thank you for the detailed report.

> After this, the token is retrieved. Suppose that in this phase a broken authorization server implementation generates a token with a negative `expires_in` value ... So, the method OAuth2RestTemplate.getAccessToken() returns an expired token.

Yes, the `OAuth2AccessTokenJackson2Deserializer` would create an expired `OAuth2AccessToken`.

> Now we are again in the `OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication()` method and `RemoteTokenServices.loadAuthentication()` is called.
If this class doesn't check if the just received token is already expired, we reach the following line:

```java
publish(new AuthenticationSuccessEvent(result));
```

However, based on what I'm seeing, this line is never reached.

Looking at `RemoteTokenServices.loadAuthentication()`, it will call the `/oauth/check_token` endpoint:

```java
Map<String, Object> map = postForMap(checkTokenEndpointUrl, formData, headers);
```

If your `/oauth/check_token` is configured to call `CheckTokenEndpoint`, then it will [check for access token expiry](https://github.com/spring-projects/spring-security-oauth/blob/c2763adb7202e01d9e87ad9b12cb3692a422caf4/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/CheckTokenEndpoint.java#L86) and fail if expired.

So I'm not seeing an issue here on my end.

The best approach forward is for you to provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the issue to help me troubleshoot your setup/configuration and determine if this is an issue or not. I'll wait on the sample. Thank you.

**Comment by zonia3000** [comment]
Hi @jgrandja,
I prepared a minimal sample here: https://github.com/zonia3000/spring-oauth2-1744-mcve
It contains 2 Spring Boot projects (the client and a fake application server).
Let me know if you have any question about it.

Cheers,
Sonia

**Comment by jgrandja** [comment]
@zonia3000 Thank you for providing a sample.

As I mentioned in my previous [comment](https://github.com/spring-projects/spring-security-oauth/issues/1742#issuecomment-613174719), there is no issue with the default configuration of authorization server, as the `CheckTokenEndpoint` would fail with an expired access token.

However, given that you are using an external authorization server, the check token (introspection endpoint) should fail.

The way I see it is that the authorization server you are using has 2 issues:
- Produces a negative value in the `expires_in` token response parameter
- The check token endpoint does not fail on the expired token

These (major) issues really need to be addressed on the custom authorization server.

I'm going to close this as I don't see any issue on the client end of things.
