### ISSUE TITLE
Support for UMA 2.0

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [spring-projects/spring-security-oauth#1755]
### Summary
Please consider support for UMA 2 that is an authorization protocol built on top of OAuth 2.0.
[link](https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-01.html). This will help satisfy owner to requester authorization needs for most applications. In effect separating a requester and a owner of a resource.

**Comment by jgrandja** [comment]
@sathyakumarseshachalam In case you are not aware, this project is in maintenance mode. Please see this [post](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security).

New features will not be added. We are only supporting bug fixes and minor enhancements.
