### ISSUE TITLE
Why not is configurable? 

### ISSUE THREAD

**Issue by seealex** [spring-projects/spring-security-oauth#1756]
https://github.com/spring-projects/spring-security-oauth/blob/5df8fc1e24261029c7fcb856b7766bcb32c7b98c/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/exceptions/OAuth2ExceptionJackson2Serializer.java#L41

**Comment by jgrandja** [comment]
@seealex This change has been reverted. See commit 9d84370
