### ISSUE TITLE
Add deprecation notice

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-oauth#1775]
Add "Deprecation Notice" throughout all documentation, eg. reference manual, project site, samples, etc.

**Comment by OrangeDog** [comment]
You plan to deprecate everything, even though spring-security doesn't yet have feature parity?

**Comment by jgrandja** [comment]
@OrangeDog Yes, the sole purpose of 2.4.0 is to deprecate everything. We'll be announcing the details in a blog post same day as release this Thur Nov 14.
