### ISSUE TITLE
Make deserialization great again

### ISSUE THREAD

**Issue by artem-smotrakov** [spring-projects/spring-security-oauth#1783]
The updates #1759 and #1682 for deserialization procedures don't allow working with custom implementations. See https://github.com/spring-projects/spring-security-oauth/issues/1759#issuecomment-543114291 for details.

Applications should be able to customize a list of allowed classes for deserialization.

**Comment by OrangeDog** [comment]
Might be a bit late to mention, but did anyone look at [JEP 290](http://openjdk.java.net/jeps/290)?

**Comment by artem-smotrakov** [comment]
@OrangeDog 

Yeah, I thought about it. I think that's the best option but I require the following JDK versions

Java™ SE Development Kit 8, Update 121 (JDK 8u121)
Java™ SE Development Kit 7, Update 131 (JDK 7u131)
Java™ SE Development Kit 6, Update 141 (JDK 6u141)

I am not sure if it's okay to put a requirement for 6u141+

**Comment by OrangeDog** [comment]
Both 6 and 7 are EOL anyway.
If people aren't installing the latest security patches anyway, having another possible flaw here is the least of their worries.
