### ISSUE TITLE
OAuth2Exception isErrorDescriptionValid seems to not do what I would expect

### ISSUE THREAD

**Issue by maccamlc** [spring-projects/spring-security-oauth#1795]
### Summary

I noticed that created a new OAuth2Exception has some unexpected behaviour, due to how `OAuth2Exception#isErrorDescriptionValid` checks the message as an error description

### Actual Behavior

* null = ok
* "" = fail
* "test" = ok

### Expected Behavior

I would have expected empty string to be ok. The logic seems to check only the first char, and if valid, then return true.

I would expect it would be the opposite, in that fail fast by returning false from the for loop when it finds an invalid character. Then at the end of the method, return true.

### Version

2.3.7.RELEASE

**Comment by maccamlc** [comment]
It seems that I am also having trouble when calling DefaultWebResponseExceptionTranslator#translate, with regular exceptions of `error_description contains invalid ASCII characters, it must conform to RFC 6749` but I am not able to work out what is the offending error message.

**Comment by jgrandja** [comment]
@maccamlc Thanks for the report. The logic in `OAuth2Exception#isErrorDescriptionValid` is clearly wrong. However, even if it was correct, it would still cause issues for applications that use characters outside of the ASCII set #1798 

Given this, I decided to revert this commit 0367bec.
