### ISSUE TITLE
Dynamically update JWKS URLs (Multi-tenancy support with Keycloak)

### ISSUE THREAD

**Issue by oridool** [spring-projects/spring-security-oauth#1797]
### Summary
The list of JWKS URLs cannot be updated once initialized.
When working in a multi-tenant system, and upon boarding of a new tenant to the system, there is no option of validating the JWT token signature of the new tenant, because a new JWKS URL is introduced.

### Actual Behavior
I'm working with Keycloak as the IDP. In Keycloak, each tenant (AKA 'realm') has its own URL and KID for validating the JWT token signature. 
The URL contains the public key that is used to validate the token signature.
For example, the URLs for two different tenants can look like:
Tenant1 - https://idpHost/auth/realms/Tenant1/protocol/openid-connect/certs 
Tenant2 - https://idpHost/auth/realms/Tenant2/protocol/openid-connect/certs 

Therefore, I use the option of initializing the token store with a **list** of URLs for all current active tenants:
```
   @Bean("resourceServerTokenStore")
    public JwkTokenStore tokenStore(JwtAccessTokenConverter accessTokenConverter) throws Exception {
        return new JwkTokenStore( List.of(jwkSetUri.split(",")), accessTokenConverter, null);
    }
```
That works great. However, when a new tenant is created in the system, I have no way to update this list of URLs, and I must restart my service for that to take affect.

As you can see in class JwkDefinitionSource, the list is final and there is no way to update it:
```	
private final List<URL> jwkSetUrls;
```

### Expected Behavior

I'd like a way to update the list of URLs dynamically, so if a new token with a new KID (for new tenant) is sent to my server, it will lookup for that KID in an updated list of URLs.

This can be achieved adding a set method to JwkTokenStore class:
For example,  'addJwkUrl (String URL)' will add a single URL to the saved list.
And also 'updateJwkSetUrls (List<String> jwkSetUrls)' will override any URL that is already set with the new list.  

After having this, I will be able to update the list each time I get an event of new tenant in my system.
  

### Version

2.3.5.RELEASE

**Comment by cfpperche** [comment]
Any update on this? thanks

**Comment by oridool** [comment]
> Any update on this? thanks

Hi @cfpperche , please note the deprecation notice on this github repository (check readme.md).
No point on investing on that here.
My solution was to migrate my service to use the new spring security :
https://docs.spring.io/spring-security/site/docs/current/reference/html5/

The new one allows you to use multiple JWK URLs and dynamically update the list when new tenant token is retrieved. 
It is based on NimbusJwtDecoder and allows you to configure the jwtDecoder and also have multiple JWK URLs by using setJWTClaimsSetAwareJWSKeySelector.

Check the multi-tenancy example and usage of TenantJWSKeySelector:  
https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-multitenancy

Here is s code snippet from what I did:

@Override
public JwtDecoder getJwtDecoder() {
    ConfigurableJWTProcessor<SecurityContext> jwtProcessor = new DefaultJWTProcessor<>();
    jwtProcessor.setJWTClaimsSetAwareJWSKeySelector(new KeycloakTenantJWSKeySelector(authenticationServerLocation));
    NimbusJwtDecoder jwtDecoder = new NimbusJwtDecoder(jwtProcessor);
    jwtDecoder.setClaimSetConverter(new KeycloakJwtClaimAdapter());
    SetJwtDecoderValidators(jwtDecoder, audience);
    return jwtDecoder;
}
