### ISSUE TITLE
update to 2.3.7, other language exception message error.

### ISSUE THREAD

**Issue by lizhongyue248** [spring-projects/spring-security-oauth#1798]
### Summary

I try to update spring security oauth to 2.3.7. But I find some differences in `org.springframework.security.oauth2.common.exceptions.OAuth2Exception`.

This class changed, my application have a error when enter error password.

### Expected Behavior

I have an account, the username is `admin`, password is `admin`, and my default locale is China.

I enter a error password, like `123456`.

In last version,  I will get a exception 

```
2019-11-04 18:45:34.733  WARN 11506 --- [nio-8080-exec-1] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: InvalidGrantException, 用户名或密码错误
```

### Actual Behavior

But in 2.3.7, I will get a exception
```
2019-11-04 18:59:51.025  WARN 12605 --- [nio-8080-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [java.lang.IllegalArgumentException: error_description contains invalid ASCII characters, it must conform to RFC 6749]
```

So, I will get a reply from application

```
{
  "error": "server_error",
  "error_description": "Internal Server Error"
}
```

I find this error come from `org.springframework.security.oauth2.common.exceptions.OAuth2Exception#isErrorDescriptionValid`.

See [github](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/exceptions/OAuth2Exception.java#L45).

In last version(2.3.5), do not have this method.

![深度截图_选择区域_20191104192017](https://user-images.githubusercontent.com/29678316/68117417-38572f00-ff38-11e9-93c0-aaeb9f006987.png)

Now , I must change to 2.3.5.

### Version

`org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.2.0.RELEASE`

`org.springframework.security.oauth:spring-security-oauth2:2.3.7.RELEASE`

**Comment by yankejia** [comment]
I have the same question.

**Comment by jgrandja** [comment]
@lizhongyue248 @yankejia Closing as duplicate of #1795.
