### ISSUE TITLE
OAUTH2 failure with java.net.SocketException in RemoteTokenServices...

### ISSUE THREAD

**Issue by breitling** [spring-projects/spring-security-oauth#1819]
### Summary

At times our web service endpoints are getting "Unexpected end of file from server" errors when trying to authenticate with OAUTH2.

(I have a detailed explanation and a solution for this if you are interest...) you can reach out to me at bobb@sg360.com or bob.breitling@gmail.com if you are interested in having a discussion about this situation.

### Actual Behavior

We are getting sporadic failures from the RemoteTokenServices bean which does the actual POST to the security endpoint (in our case Okta's OAuth introspect). The failures are java.net.SocketException on unexpected end of file from server.

### Expected Behavior

We are expecting all the calls to the security endpoint to not fail with this error.

### Configuration

Normal SpringBoot OAUTH2 configuration: clientId, clientSecret, endpoint URL, stuff.

### Version

2.2.1

### Sample

Will supply sample on request -

**Comment by jgrandja** [comment]
@breitling I transferred the issue to the Spring Security OAuth project as it belongs here.

> We are getting sporadic failures from the RemoteTokenServices bean which does the actual POST to the security endpoint (in our case Okta's OAuth introspect).

It seems to me that the issue is likely related to either your network or Okta's OAuth introspect endpoint. It doesn't seem to be an issue with Spring Security OAuth?

**Comment by breitling** [comment]
Joe, actually is seems to be a byproduct of the way TLS1.2 works and the SpringBoot RemoteTokenServices code. I have cloned that calls and made a minor change to it that fixes the issue. I was hoping to have a discussion with someone about what I discovered and I would like to contribute my solution, if it is acceptable/worthy/?, to the project. Can we have a more complete discussion off line? or would you rather just do it via this forum?

**Comment by jgrandja** [comment]
@breitling Let's keep the discussion on here so everyone else could follow.

Since you were able to patch a fix, can you put together a minimal code example that reproduces the issue and than applies the fix. That would be the most effective way.

**Comment by breitling** [comment]
Joe, can I send you a response via email that contains more details? Can I find your email address here somewhere? or you can send me an email to bobb at sg360 dot com and I will respond to that....if your interested.

**Comment by breitling** [comment]
Ok, no problem...here goes...this is what I discovered:

I have a web service that is using SpringBoot OAuth2 to talk to an Okta endpoint is validate an bearer token to allow someone to call my web services endpoint. Obviously the Okta introspect endpoint is an https URL. So enter TLS1.2.

Normally, we call to Okta endpoint the two machine start by doing a TLS1.2 handshake that established the connection and exchanges the keys for the encryption, etc. This is fairly heavy weight in terms of time and data but it has to be done (in TLS1.2 anyway). Once that handshake is complete the RemoteTokenServices bean POSTs an encrypted message to Okta and it sends back its encrypted response and everyone is happy. In order to potentially eliminate another costly handshake the receiving machine keeps the pipe open so if the sending machine has another request, the handshake isn't necessary. Now, everyone is even happier.

The receiving machine will only wait so long for another request before it decides to give up and close the pipe. It does this by sending a TLS Alert type 21 message back up the pipe, the other machine see this and says OK the pipe is closing and send back an Alert and that is that. Any new requests will have to do a TLS handshake again to get things started. It appears that wait time is 5 seconds (maybe Okta can control that, but is what is happening in my situation).

So here where it get interesting. If the sending machine send the next request right at the 5 second, the RemoteTokenServices' POST was throwing a ResourceAccessException with an I/O error on the request for an unexpected end of file from the server. It seems that TLS Alert is telling me the connection closed and this is causing the POST to fail. 

Amazingly, our web service which is called about 25K times a day was generating about 50 failures with this as the error.

My solution was to catch the exception and just do the same POST again. The connection is now closed so the new POST will just go through the TLS hand shake again an all is good. We have added this to our web service and the problems have gone away.

Any thoughts?

**Comment by breitling** [comment]
I'll post some code in a bit showing what I did...

**Comment by jgrandja** [comment]
@breitling I don't see how this is related to OAuth specifically. This issue is obviously happening at the lower network layer and is environment related.

**Comment by jgrandja** [comment]
@breitling I'm closing this due to lack of feedback
