### ISSUE TITLE
Reactivate?

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-security-oauth#1829]
Hi, since the spring-security project decided to abandon the openid connect server support in spring-security 5 will this project be reactivated?

**Comment by jzheaux** [comment]
Note that this is being reevaluated as seen in this comment: https://github.com/spring-projects/spring-security/issues/6320#issuecomment-564151705

Either way, though, no this project will remain deprecated. The decision to deprecate was made in conjunction with the (initial) decision to not do Authorization Server.
