### ISSUE TITLE
How to extract JWT token data on resource server side?

### ISSUE THREAD

**Issue by ovaris** [spring-projects/spring-security-oauth#183]
I'm using JWT based auth server together with resource server (configured pretty much like in this example provided by @dsyer, two separate web app though).

On authorization server side I'm also enhancing the token by using JwtTokenEnhancer (adding some additional info about user etc.)

My question is, what is the recommended way to access that additional data on resource server side? It would be great if for example some filter would decode that data to SecurityContext. I tried to debug the code on auth server side and at least it looked like  additional info is also decoded to token (maybe you can confirm this :)), so it would be great to access that very same data on the "other" side too.

**Comment by mailmeprash** [comment]
Hi, you have to set the verifierkey inside 
```
    @Bean
    public JwtAccessTokenConverter tokenEnhancer() {

            jwtAccessTokenConverter.setVerifierKey(publicKey);
```

**Comment by ctytgat** [comment]
Event after reading all this I still couldn't figure out how to extract the additional info from the authentication object, without having to re-decode the token.

Finally I came up with the following solution: use a custom JWT token store that extracts the info during authentication, and use the Authentication details to store it. (which seemed to remain null anyway)

    /**
     * Custom JWT token store that also reads the additional info and stores it as authentication details.
     */
    public static class CustomJwtTokenStore extends JwtTokenStore {

        public CustomJwtTokenStore(JwtAccessTokenConverter jwtTokenEnhancer) {
            super(jwtTokenEnhancer);
        }

        @Override
        public OAuth2Authentication readAuthentication(OAuth2AccessToken token) {
            OAuth2Authentication oAuth2Authentication = super.readAuthentication(token);
            oAuth2Authentication.setDetails(token.getAdditionalInformation());
            return oAuth2Authentication;
        }
    }
     
Then the resource server config:

    @Configuration
    @EnableResourceServer
    public static class ResourceServer extends ResourceServerConfigurerAdapter {

        @Override
        public void configure(HttpSecurity http) throws Exception {
            http.authorizeRequests().anyRequest().authenticated();
        }

        @Override
        public void configure(ResourceServerSecurityConfigurer config) throws IOException {
            config.tokenServices(tokenServices());
        }

        @Bean
        public JwtAccessTokenConverter accessTokenConverter() throws IOException {
            JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
            Resource resource = new ClassPathResource("publickey.txt");
            String publicKey = IOUtils.toString(resource.getInputStream());
            converter.setVerifierKey(publicKey);
            return converter;
        }

        @Bean
        @Primary
        public DefaultTokenServices tokenServices() throws IOException {
            DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
            defaultTokenServices.setTokenStore(tokenStore());
            return defaultTokenServices;
        }

        @Bean
        public TokenStore tokenStore() throws IOException {
            return new CustomJwtTokenStore(accessTokenConverter());
        }
    }

Example to extract a "user_id" field:

    @Override
    public Optional<Authentication> getAuthentication() {
        return Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication());
    }

    @Override
    public Optional<String> getCurrentUserId() {
        Optional<Authentication> authentication = getAuthentication();
        return authentication.map(a -> {
            OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) a.getDetails();
            return (String) ((Map) details.getDecodedDetails()).get("user_id");
        });
    }

If someone knows a better way, I'd be interested to know!
