### ISSUE TITLE
org.springframework.security.oauth2.provider.client.JdbcClientDetailsService的数据库设计问题

### ISSUE THREAD

**Issue by gaokechen** [spring-projects/spring-security-oauth#1853]
https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/test/resources/schema.sql
其中的oauth_client_details表设计违反了数据库范式
-- used in tests that use HSQL
create table oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);
authorized_grant_types中要存储authorization_code,password,refresh_token等多个数据,在关系型数据库中这样做显然不符合数据库范式的要求

**Comment by jgrandja** [comment]
@gaokechen Is this an issue? Please provide details or there isn't much I can do at this point.

**Comment by gaokechen** [comment]
是的，我在关系型数据库例如MySQL中建立oauth_client_details表时，我发现resource_ids和authorized_grant_types字段可能保存多个值，这不符合数据库范式的要求。
![image](https://user-images.githubusercontent.com/32739652/80670422-6aa5ab80-8ad9-11ea-936d-74c9e631affc.png)
Yes, when I created the oauth_client_details table in a relational database such as MySQL, I found that the resource_ids and authorized_grant_types fields may hold multiple values, which does not meet the requirements of the database paradigm.

**Comment by jgrandja** [comment]
@gaokechen 

> does not meet the requirements of the database paradigm.

I'm not sure what this means? But if you are suggesting that the resource_ids should be stored in a separate table with a primary-foreign key relationship then yes this would be the normalized way of designing databases. However, this would also reduce performance with extra joins. Sometimes denormalized is the intended design choice and I'm guessing that was the decision when this was first implemented.

Either way, the table definition will not change at this point given this project is in maintenance mode and will soon reach EOL. I'm going to close this issue based on that.
