### ISSUE TITLE
DefaultTokenServices should generate url-safe tokens

### ISSUE THREAD

**Issue by torstenkuhnhenne** [spring-projects/spring-security-oauth#1857]
### Summary
With release 2.4.1 the token generation was switched from `UUID` to `SecureRandom`. The secure random byte-array is used as the token value after encoding it with base64.

This can lead to tokens with some special chars, for example `=` or `/`. When a I have a token with `=` and try to send it in an http header, the `=` is treated as a separator and the browser (any maybe also some client libs) removes it. 

### Actual Behavior
The methods `createRefreshToken()` and `createAccessToken()` use the `Base64.encodeBase64` method with default-values for `isChunked` and `urlSafe`:
```
String tokenValue = new String(Base64.encodeBase64(
				DEFAULT_TOKEN_GENERATOR.generateKey()));
```

### Expected Behavior
Use `Base64.encodeBase64( DEFAULT_TOKEN_GENERATOR.generateKey(), true, true )` instead to get a url- and http-header-compatible encoded value.

### Version
spring-security-oauth2 release 2.4.1

See https://github.com/spring-projects/spring-security-oauth/pull/1720/ for the change from `UUID` to `SecureRandom`.

**Comment by jgrandja** [comment]
@torstenkuhnhenne Thank you for reporting this. Would you be interested in submitting a fix for this?
