### ISSUE TITLE
Random problems with some generated access tokens

### ISSUE THREAD

**Issue by bmaehr** [spring-projects/spring-security-oauth#1878]
### Summary

Change #1720 did not only change the generation of the token but also the range of used characters.

So in some cases the token generator generates tokens which are converted during the request flow to tokens containing a space or to other url encoded characters. 
A user getting such a token has problems for some type of request e.g GET requests work, POST request not.

Example for such a token breaking things: n3puPWRHcbe+1JGniRxFqc5mVOU=

### Expected Behavior

Don't use special characters in token.

Perhaps it works without any problems if on all places, where requests are created in a web application and the access_token attached to the request, the access_token is correctly encoded, but I think there are many applications out there where this is not the case and which will suffer from these random problems.

**Comment by jgrandja** [comment]
@bmaehr Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) or test that reproduces the problem and I'll have a look.

**Comment by bmaehr** [comment]
> @bmaehr Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) or test that reproduces the problem and I'll have a look.

For what a minimal sample? For the fact, that the random generator now generates other characters than before?

**Comment by jgrandja** [comment]
If you believe the changes applied in #1720 resulted in a bug then please demonstrate the bug via a sample or test. This is standard process when reporting a bug.

**Comment by bmaehr** [comment]
I try to explain it once more:
The changes in #1720  resulted in changing the access token from e.g. a00ca325-8a76-4380-b18c-62ea960ce6d2 to n3puPWRHcbe+1JGniRxFqc5mVOU=  
These access tokens are transferd in ever application back and forth between backend and frontend. Depending on the typ of transfer special characters like blanks, + or = need to be encoded during the transfer. This was not necessary for the old range of charaters . Due the change many applications will brake randomly, because with #1720 the implicit definition of the format of the access token has been changed.

**Comment by jgrandja** [comment]
@bmaehr Apologies for the delay. Can you confirm which version you are using? If you are using `2.4.1` then please try `2.4.2` and let me know how it goes.

FYI, #1857 (backport #1864 for `2.4.2`) fixed the access token generation to ensure url-safe base64 encoding.

**Comment by bmaehr** [comment]
2.4.1
Sorry, did search for tickets but didn't find #1857

**Comment by jgrandja** [comment]
No worries I'm glad you have the fix now.
