### ISSUE TITLE
Can change access level variables of RemoteTokenServices?

### ISSUE THREAD

**Issue by wryel** [spring-projects/spring-security-oauth#1880]
### Summary

Change access level variables of RemoteTokenService to protected to be possible override methods and reuse same variables.

### Actual Behavior

I tryed override method loadAuthentication with a specific rule (i need change value of checkTokenEndpointUrl dynamicly in some cases) and i cant reuse variables of RemoteTokenService.

### Expected Behavior

Reuse of RemoteTokenService variables.

### Configuration

No special configuration is needed.

### Version

spring-security-oauth2-2.3.4.RELEASE

### Sample

Source of [RemoteTokenService](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/RemoteTokenServices.java)

**Comment by jgrandja** [comment]
@wryel Maybe you are not aware, but this project is scheduled to reach EOL. Please see the [announcement](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth) for further details.

The change you are requesting would require another minor release, however, we recently released the final minor release 2.5.0. Therefore, the requested change cannot be accepted.

I'm going to close this issue based on the above reason.
