### ISSUE TITLE
Add @Configuration annotation to @AuthorizationServer annotation

### ISSUE THREAD

**Issue by hongji3354** [spring-projects/spring-security-oauth#1904]
@EnableWebSecurity has @configuration, so just adding @EnableWebSecurity allows automatic setup, but @EnableAuthorizationServer does not have @configuration, so you need to add @configuration to proceed with the auto setup.

Generally, when using @Enable-related annotations, we think that using only that annotation will lead to automatic setup, so we would also like to add @configuration to @EnableAuthorizationServer

**Comment by jzheaux** [comment]
I think [Spring Security may separate these in the future](https://github.com/spring-projects/spring-security/issues/6613).

**Comment by jgrandja** [comment]
@hongji3354 This change cannot be applied based on [comment](https://github.com/spring-projects/spring-security-oauth/issues/1904#issuecomment-763050737).

**Comment by hongji3354** [comment]
Thank you
