### ISSUE TITLE
Getting "HTTP 400 Bad Request" instead of "HTTP 401 Unauthorized" for incorrect user credentials

### ISSUE THREAD

**Issue by silentsnooc** [spring-projects/spring-security-oauth#1906]
I noticed that Spring security returns HTTP 400 instead of HTTP 401 for a user who gives a wrong password. From what I was reading online it would seem that HTTP 401 is more appropriate than just HTTP 400.

**Comment by falk-stefan** [comment]
@jigneshkhatri Yeah, I've been there as well. 

I don't have a solution for you but you might want to take a look at the `AuthenticationEntryPoint`. No idea if that works but in one of my older projects I have tried it with the code below. Might be a dead end though. ^^ 

```java
@Component
public class AuthFailureHandler implements AuthenticationEntryPoint {

    @Override
    public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException, ServletException {
        System.out.println("Hello");
        // FIXME We need to return HTTP 401 (s.t. the client knows what's going on) but for some reason it's not working as intended!
        throw authException;
    }
}

@Bean
public AuthenticationEntryPoint customAuthEntryPoint(){
    return new AuthFailureHandler();
}
```

**Comment by jigneshkhatri** [comment]
@falk-stefan thanks for responding. I have tried that solution before, but execution does not reach there, and it throws 400 error. As per my understanding this solution only works with basic login based spring security right? Here I have implemented OAuth2 Spring Security.

**Comment by falk-stefan** [comment]
@jigneshkhatri Ah. Yeah, I think that was the problem.. the code was never really reached and I never revisited it. I never found out why this code is not getting executed to be honest.

**Comment by leo7** [comment]
This is tricky. 

First of all, this is NOT to access a protected resource (like "/user/abc"), which is handled by ExceptionTranslationFilter and its configured authenticationEntryPoint (like OAuth2AuthenticationEntryPoint). For this situation you may need to check the exceptionTranslator of the authenticationEntryPoint (default to DefaultWebResponseExceptionTranslator).

Our situation here is about the oauth2 authorization server and its token endpoints (framework endpoints). So you may need to check the exceptionTranslator of AuthorizationServerEndpointsConfigurer, which can be configured by using `AuthorizationServerConfigurerAdapter`. 

The interesting is the spec mentianed above by @jzheaux (https://datatracker.ietf.org/doc/html/rfc6749#section-5.2), it said
![Selection_076](https://user-images.githubusercontent.com/5884295/126573139-cd5aab9c-0fa3-4624-b449-dad49c1a9607.png), 

However, when username/password does not match, spring DaoAuthenticationProvider throws BadCredentialsException, which is converted to  `InvalidGrantException`.
![Selection_077](https://user-images.githubusercontent.com/5884295/126573926-fc80b225-9165-470f-ab9a-9026d956bc68.png)

Then the InvalidGrantException is translated to 400 by the `DefaultWebResponseExceptionTranslator`
