### ISSUE TITLE
[RedisTokenStore] access_to_refresh and refresh_to_access entries only expire if the refresh token expires

### ISSUE THREAD

**Issue by 0xpablo** [spring-projects/spring-security-oauth#1908]
Hi there!

I was reviewing the `RedisTokenStore` and our Redis database and I'm noticing that we have many stale `access_to_refresh:xxxx` and `refresh_to_access:yyyy` entries. 

Reviewing the code, when an *access* token is stored, it's checking that the associated *refresh* token is an expiring one to set the expiration of those entries.
See here:
https://github.com/spring-projects/spring-security-oauth/blob/ef8d78403d551ca9c23c6de4db0aa6aae2e24d79/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/store/redis/RedisTokenStore.java#L225

Our *refresh* tokens do not expire, but those relationships depend mostly (and are created) when the access token is stored. Shouldn't that implementation always set an expiration time for those two entries, and use the expiration time of the access token (which always expires)?

The only reason that comes to mind why this is being done, is that maybe Spring Security want's to differentiate when a token is expired, and when a token does not exist.

I'm okay to submit a PR if I'm not missing anything.

Thanks in advance!

**Comment by jgrandja** [comment]
@0xpablo What version are you using? A fix #1836 went into the `2.5.0` release that may be related to your issue? Can you try with `2.5.0`?

If the issue still exists in `2.5.0`, then please put together a test or [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue so I can better understand.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
