### ISSUE TITLE
ClientDetailsUserDetailsService cannot anymore support empty secret

### ISSUE THREAD

**Issue by barclay-reg** [spring-projects/spring-security-oauth#1911]
### Summary

up to verion 2.4.0, the method `ClientDetailsUserDetailsService.setPasswordEncoder` was called while initializing DaoAuthenticationProvider (see https://github.com/spring-projects/spring-security-oauth/blob/6234826671d75632d84c524da1dd8818cee1b4c2/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configurers/AuthorizationServerSecurityConfigurer.java#L139)

### Actual Behavior

since 2.5.0 this is not the case anymore. Change was made with https://github.com/spring-projects/spring-security-oauth/commit/b478e803197d84a8054217365e1fa60e4606acba

### Version

2.5.0

**Comment by jgrandja** [comment]
@barclay-reg Can you please provide more detail as it's not clear to me if you're having a specific issue. Can you put together a test or a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
