### ISSUE TITLE
OAuth2AuthenticationProcessingFilter 类如何使用自己的tokenExtractor

### ISSUE THREAD

**Issue by Mirluo1998** [spring-projects/spring-security-oauth#1913]
![image](https://user-images.githubusercontent.com/43629628/110284126-43ced480-801c-11eb-9c54-823e65ae6927.png)

![image](https://user-images.githubusercontent.com/43629628/110284190-5d701c00-801c-11eb-8ec2-df795f7b4966.png)
![image](https://user-images.githubusercontent.com/43629628/110284230-6f51bf00-801c-11eb-887d-dec71c09f806.png)

**Comment by jgrandja** [comment]
@Mirluo1998 Please provide details if you are having an issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
