### ISSUE TITLE
Why not use lua script to implement redis token store ?

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [spring-projects/spring-security-oauth#1915]
Why not use lua script to implement redis token store ?

**Comment by jgrandja** [comment]
@zxf-thingsmatrix This project is scheduled to reach EOL. Please see the [announcement](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth) for further details.

I'm going to close this issue as we are not looking to add any further enhancements.
