### ISSUE TITLE
Bug: Login multi times cause uname_to_access to many hash values

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [spring-projects/spring-security-oauth#1916]
Reason: OAuth2AccessTokenJackson2Serializer and OAuth2AccessTokenJackson2Deserializer not serialize OAuth2AccessToken#expiration or expireIn calculate mistakely, cause uname_to_access sadd different token

**Comment by jgrandja** [comment]
@zxf-thingsmatrix Please provide more details. Either provide a test that reproduces the error or a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) with instructions on how to reproduce.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
