### ISSUE TITLE
Function of oauth_code and oauth_client_token tokenstore tables

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects/spring-security-oauth#194]
What is the function of the oauth_code and oauth_client_token tables within the tokenstore database?  I've converted the tokenstore database to a Jdbc implementation and noticed that neither of these tables ever seem to contain records.  I thought the oauth_client_token table would contain access tokens created using the Oauth Client Credentials flow, but find access tokens using this flow appear in the oauth_access_token table.

**Comment by AbhiRS** [comment]
Would you please explain when oauth_client_token will be populated, I am seeing oauth_client_details as base/master and after token generation oauth_access_token is getting populated but I am unable to understand when oauth_client_token will be populated?

**Comment by shredding** [comment]
It would be really great to get docs for this, as a lot of people suffer from that according to google.

**Comment by chrylis** [comment]
This is sparsely documented and probably orphaned due to the state of the project, but I *believe* that the purpose here is for OAuth2 client applications to be able to save tokens that they've obtained (on behalf of users, primarily) and to look up the right one when needed. For example, an application that consumed the GitHub OAuth2 API could save the token here and look it up by "(GitHub, Bob)" when needed.

**Comment by osbneitor** [comment]
I'm facing the same question as **AbhiRS**. My tables (**oauth_client_details** and **oauth_access_token**) are being populated on token creation but i don't understand when is needed the **oauth_client_token** table. I'd be really useful to have more information about this.

**Comment by paulosotu** [comment]
> I'm facing the same question as **AbhiRS**. My tables (**oauth_client_details** and **oauth_access_token**) are being populated on token creation but i don't understand when is needed the **oauth_client_token** table. I'd be really useful to have more information about this.

+1 here

**Comment by Widiyanto** [comment]
> I'm facing the same question as **AbhiRS**. My tables (**oauth_client_details** and **oauth_access_token**) are being populated on token creation but i don't understand when is needed the **oauth_client_token** table. I'd be really useful to have more information about this.

+1

**Comment by jgrandja** [comment]
As @dsyer mentioned in his initial comments, the `oauth_client_token` table is used by `JdbcClientTokenServices`.

@chrylis [comment](https://github.com/spring-projects/spring-security-oauth/issues/194#issuecomment-418060546) describes the role of `JdbcClientTokenServices`:

> the purpose here is for **OAuth2 client applications** to be able to save tokens that they've obtained (on behalf of users, primarily) and to look up the right one when needed
