### ISSUE TITLE
Add support / documentation for OpenID Connect

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth#220]
**NOTE** Originally reported by @btiernay on https://github.com/spring-projects/spring-security/issues/98

Right now it is unclear how one would implement OpenID Connect using Spring Security. There isn't much on the topic in the documentation or the web. The most popular hit on google for `openid connect spring` is the following:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server

However, it seems pretty heavy weight and full stack, akin to using CloudFoundry's UAA over Spring's OAuth 2.0 support. 

There are the following unanswered questions on SO that get to the heart of the problem:
- http://stackoverflow.com/questions/21701444/how-to-secure-private-soa-webservices-spring-security-oauth-openid-connect
- http://stackoverflow.com/questions/11849148/how-to-implement-openid-connect-and-spring-security

There is also this mention from the Spring blog:

http://spring.io/blog/2014/04/18/spring-security-oauth-2-0-0-rc1-available

> The Authorization Server APIs have been refactored a lot to enable new use cases to be easily added: for example OpenID Connect (OIDC), MAC tokens, or the new Token Revocation standard are easy to add. I know of at least one OIDC implementation that use Spring OAuth2 2.0 already.

However it is unclear what that implementation is, whether or not it comes recommended and if Spring has any plans to support it in the future. 

What would be nice is some guidance from Spring at the very least (in documentation for example). However, first class support for OpenID Connect (much like Spring's OAuth2 support) would be great since it represents the future of federated identity management.

ps. JIRA was down when this ticket was created so I apologize for any duplication.

**Comment by derekjwilliams** [comment]
Any advice on a greenfield implementation?  The thread is a bit old, so apologies in advance for the potentially out of date question.  I did see the Library list on http://openid.net/developers/libraries/ but was unsure of the best fit.  Feel free to tell me to research before asking silly questions.

**Comment by sirianni** [comment]
It looks like there is an outstanding pull request #627 that would (at the least) allow application code to implement returning of `id_token`s from the `AuthorizationEndpoint`.  Can this be pulled upstream?

**Comment by dsyer** [comment]
I'm not sure #627 is the right approach but it's certainly worth a look (I would change the names of the interfaces at least). The bigger picture: we should definitely put this forward as a priority for a 2.1 (or 3.0) release, but there isn't much bandwidth amongst the comitters right now. Pivotal are trying to hire someone to do this, so if you (or anyone you know) has some experience in Appsec and is interested in a job, please reach out.

**Comment by praseodym** [comment]
Also note that [MITREid Connect](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server) provides a perfectly fine client module if you want to provide OIDC login (either for a web application, or to protect a resource with a token).

Implementing the server part quite complex, and not something I'd expect to see in a "plug and play" Spring module -- you'll probably want to run this is as a separate application anyway (akin to OpenAM, CloudFoundry UAA, or the MITREid Connect server).

**Comment by dima767** [comment]
Fresh OIDC server (idp) implementation as a Spring Boot app! Would be nice!

But anyway, for all the interested, here's another ongoing effort on top of Spring Oauth, MITREid and Shibboleth idp: https://github.com/uchicago/shibboleth-oidc

**Comment by DanailMinchev** [comment]
Hi, I can see that support for `OpenID Connect` is planned for `2.1.0` release.
Is there any information when the development of `2.1.0` release will start approximately or when we can expect `OpenID Connect` + `Spring Boot` support?
Thank you!

**Comment by gonzalad** [comment]
Hello, 

From my understanding, OIDC Connect (client-side) support in Spring would need  : 
 * idToken handling (signature verification and idToken claims validation)
 * jwks_uri support (for handling idToken verification)
 * optionally mapping custom claims in idToken to GrantedAuthorities would be a goodie (i.e. role claims).
 * userPrincipal name mapping should be done from name claim (http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.1)

Using idToken render calling userEndpointUri useless in the Application Client side.

**Comment by xtremebiker** [comment]
In the meanwhile, I'm currently using Keycloak as my authorization server, which is fully OIDC compatible and provides a handy set of adapters for this spec. More concretely, the ones implemented are for Spring Boot and Spring Security, while there's the chance to use the Spring Security one with Spring Boot too. Worth to have a look:

https://github.com/keycloak/keycloak/tree/master/adapters/oidc

**Comment by dhiraj65** [comment]
does anyone has sample for OpenId connect with Azure AD. I want to use both of them in my RestAPI(Spring Boot)? In future i am planning to integrete these two on my API Gateway ZUUL.

Thanks

**Comment by hauntingEcho** [comment]
Here's an [additional example](http://www.baeldung.com/spring-security-openid-connect) of an OIDC client built on top of spring-security-oauth, for anyone else stumbling across this thread.

**Comment by stela** [comment]
@dhiraj65 see https://github.com/Microsoft/azure-spring-boot/issues/244#issuecomment-382840920
If possible, use the Azure AD v2.0 URLs, you then need to add `/v2.0/` to the provider URLs in that config, see https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration for the URLs. It's supposed to be easier once spring-security 5.1 is released and supports openid autoconfig, then just point it to the above URL :-)

**Comment by jgrandja** [comment]
Closing as this is a major change that we are no longer accepting.

As you may be aware, this project is in maintenance mode and will reach EOL in the very near future. Please see the [initial announcement](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) and [follow-up announcement](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update) for further details.

At this time, we are only accepting bug fixes and minor enhancements that can be cleanly merged into master.

Please see the OAuth 2.0 / OpenID Connect support in [Spring Security](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2) (since 5.0).
