### ISSUE TITLE
Support for multiple resource in a single app

### ISSUE THREAD

**Issue by totof3110** [spring-projects/spring-security-oauth#224]
I was trying to have multiple resourceIds in a single app. Is it possible?

I tried having multiple classes with `@EnableResourceServer` but only one would be picked up. I also tried to have only one with multiple `@Configuration` that extend `ResourceServerConfigurerAdapter` but that wasn't working either?

Is it supported and if not, could it be? :)

Thanks.

**Comment by jlmehta** [comment]
This does not work for me since only the resource configuration with the higher order is utilized during authentication of the access token. What am I doing wrong? 

`
@Configuration
@EnableWebSecurity
public class OAuth2ResourceServerConfig {

    private static final String CLIENT1_REST_RESOURCE_ID = "client1_api";
    private static final String CLIENT2_REST_RESOURCE_ID = "client2_api";

    @Resource(name = "dataSourceOauth2")
    private DataSource dataSource;

    @Bean
    public JdbcTokenStore tokenStore() {
        return new JdbcTokenStore(dataSource);
    }

    @Bean
    protected ResourceServerConfiguration client2Resources() {
        ResourceServerConfiguration resource = new ResourceServerConfiguration() {
            public void setConfigurers(List<ResourceServerConfigurer> configurers) {
                super.setConfigurers(configurers);
            }
        };
        resource.setConfigurers(Arrays.<ResourceServerConfigurer> asList(new ResourceServerConfigurerAdapter() {
            @Override
            public void configure(ResourceServerSecurityConfigurer resources) {
                resources.tokenStore(tokenStore()).resourceId(CLIENT2_REST_RESOURCE_ID).stateless(false);
                OAuth2AuthenticationEntryPoint authenticationEntryPoint = new OAuth2AuthenticationEntryPoint();

                ExceptionEncodingTranslator translator = new ExceptionEncodingTranslator();
                authenticationEntryPoint.setExceptionTranslator(translator);
                resources.authenticationEntryPoint(authenticationEntryPoint);
            }

            @Override
            public void configure(HttpSecurity http) throws Exception {
                MultiTenantContext.setStrategy(new OAuth2MultiTenantContextStrategy());
                // define URL patterns to enable OAuth2 security

                // @formatter:off
                http.authorizeRequests() //
                        .antMatchers( //
                                "/mainpath/v2/api-docs", //
                                "/mainpath/webjars/**", //
                                "/**/favicon.ico", //
                                "/mainpath/swagger-ui.html", //
                                "/mainpath/swagger-resources/**", //
                                "/mainpath/health/**") //
                        .permitAll() //
                        .antMatchers("/mainpath/subpath5/subsubpath/**", //
                                "/mainpath/subpath4/**", //
                                "/mainpath/subpath3/**") //
                        .access("#oauth2.hasScope('read') or (!#oauth2.isOAuth() and hasRole('CLIENT2'))")
                        .antMatchers("/mainpath/**").denyAll();

                // @formatter:on
            }
        }));
        resource.setOrder(4);
        return resource;
    }

    @Bean
    protected ResourceServerConfiguration client1Resources() {
        ResourceServerConfiguration resource = new ResourceServerConfiguration() {
            public void setConfigurers(List<ResourceServerConfigurer> configurers) {
                super.setConfigurers(configurers);
            }
        };
        resource.setConfigurers(Arrays.<ResourceServerConfigurer> asList(new ResourceServerConfigurerAdapter() {
            @Override
            public void configure(ResourceServerSecurityConfigurer resources) {
                resources.tokenStore(tokenStore()).resourceId(CLIENT1_REST_RESOURCE_ID).stateless(false);
                OAuth2AuthenticationEntryPoint authenticationEntryPoint = new OAuth2AuthenticationEntryPoint();

                ExceptionEncodingTranslator translator = new ExceptionEncodingTranslator();
                authenticationEntryPoint.setExceptionTranslator(translator);
                resources.authenticationEntryPoint(authenticationEntryPoint);
            }

            @Override
            public void configure(HttpSecurity http) throws Exception {
                MultiTenantContext.setStrategy(new OAuth2MultiTenantContextStrategy());
                // define URL patterns to enable OAuth2 security

                // @formatter:off
                http.authorizeRequests() //
                        .antMatchers( //
                                "/mainpath/v2/api-docs", //
                                "/mainpath/webjars/**", //
                                "/**/favicon.ico", //
                                "/mainpath/swagger-ui.html", //
                                "/mainpath/swagger-resources/**", //
                                "/mainpath/health/**") //
                        .permitAll() //
                        .antMatchers("/mainpath/subpath1/**", //
                                "/mainpath/subpath2/**", //
                                "/mainpath/subpath/**") //
                        .access("#oauth2.hasScope('read') or (!#oauth2.isOAuth() and hasRole('CLIENT1'))")
                        .antMatchers("/mainpath/**").denyAll();

                // @formatter:on
            }
        }));
        resource.setOrder(3);
        return resource;
    }
}`

**Comment by Kon007** [comment]
Was @jlmehta 's question ever answered? I'm going to be implementing this soon and following the pattern above. Is this known to still be working @dsyer ?

**Comment by dsyer** [comment]
This is an issue tracker, not a support forum, so I don’t think it’s appropriate to get into much detail here. Stackoverflow would be better. Also the resource server features in this project have been superseded by Spring Security core. Check out the main user guide.

**Comment by ajsevak** [comment]
> Was @jlmehta 's question ever answered? I'm going to be implementing this soon and following the pattern above. Is this known to still be working @dsyer ?

hi what approach did you end up using? need help on this soon
