### ISSUE TITLE
Spring Outh2 Client Authorization Code Flow

### ISSUE THREAD

**Issue by prasadnadendla** [spring-projects/spring-security-oauth#229]
I have my own Authorization Server, and I want to use Spring OAuth2 Client to get token from my authorization server through Authorization code flow.Can you asisst me how to use Spring OAuth2 Client ? 
It's great if you able to provide sample example.

**Comment by gaurav2887** [comment]
@dsyer - oauth2 client is giving the grant code back but not making a token request. Is there any configuration I can do to make the token request followed by authorize request?
