### ISSUE TITLE
Help users avoid duplicated access token under load with JDBC token store

### ISSUE THREAD

**Issue by hezhijun** [spring-projects/spring-security-oauth#276]
I use the JdbcTokenStore, and use the database schema described here https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/test/resources/schema.sql.
And I got the following exception(I checked the database, there are two access_token for the same authentication_id)

```
Request processing failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2] with root cause
org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2
    at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:74)
    at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:735)
    at org.springframework.security.oauth2.provider.token.JdbcTokenStore.getAccessToken(JdbcTokenStore.java:105)
    at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:75)
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:68)
    at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:60)
    at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
    at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.getAccessToken(TokenEndpoint.java:100).
```

**Comment by rhamianiuk** [comment]
Unique constraint prevents from duplicated authentication_id, but cause SQL exceptions in runtime.
Better way to avoid duplicates is to lock (SELECT ... FOR UPDATE) on some rows in database. In our case this is user Account, that can be taken from (or identified by) principal.

**Comment by benkiefer** [comment]
We're seeing this issue as well. The unique constraint just pushes a 500 out to the client, forcing them to retry their request and handle a 500. Is there something better that we can do here as part of the library?

As @dsyer pointed out, synchronized and transactional aren't going to work unless you only have one instance of your application.

We've resolved the issue by thinly extending DefaultTokenServices and building retry logic in around Spring's DuplicateKeyExceptions. Open to other suggestions as well, just hoping to get the ball rolling.

**Comment by 8a8aleo** [comment]
We have determined that using multiple different grant types or altering scope of an authentication with a single client id causes this issue to appear.

**Comment by dsyer** [comment]
This issue is closed. If you still want to make changes, please open another one, and include a complete description of the problem (a test would be super).

**Comment by julicrack** [comment]
> As @dsyer pointed out, synchronized and transactional aren't going to work unless you only have one instance of your application.

Does @dsyer really said this? He said that sync shouldn't work, but transactional should since isolation is at database layer, not application server, isn't it?

**Comment by dsyer** [comment]
Yes, that's what I said. You do need a higher level of isolation (might not be the default), but `@Transactional` ought to be enough.

**Comment by julicrack** [comment]
OK @dsyer, this should work in a clustered environment with ``@Transactional`` but not with synchronized methods.

**Comment by rshakerd** [comment]
Hi @dsyer ,

Consider this test case where we are issuing an access token with refresh token for clientcred (C1) for user (U1) , so we have (c1-U1) mapped to accesstoken/requestoken pair (A1-R1)

Now if the token A1 expires, its removed from the accessToken table while the R1 remains in refresh token.

Now if the clientcred is shared across 2 devices for ex. and one of them authenticates instead of refresh_token, we have the following mappings for the C1-U1 combo
C1-U1-A2-R2
C1-U1-{expired so not presentin table}-R1

and the other device with R1 , refreshes then it leads to
C1-U1-A2-R2
C1-U1-A3-R1
---------------------
It can be solved by placing constraints with relations on the prescribed token store tables, but this should be taken care by the framework ideally

**Comment by dsyer** [comment]
I didn't follow all of that, but the framework does not place constraints on SQL tables. DDL is the responsibility of the user. Does that make sense? Is it relevant to your problem?

**Comment by rshakerd** [comment]
My question is shouldn't we be removing pre-existing refresh tokens for a particular authentication-id on reauthentication?

**Comment by dsyer** [comment]
Refresh tokens are supposed to be long lived, so I'm not sure what you mean yet. Are you saying that in the scenario you describe the R1 token is in some way invalid?

**Comment by rshakerd** [comment]
In the scenario the accessToken's expired and client is supposed to refresh_token but instead reauthenticates** and when this happens R1 should ideally be invalidated?

** ( using password grant in my case and the reauthentication generates a new pair of access& refresh token)

**Comment by dsyer** [comment]
Right, but that's a function of the authentication ID (which is generated by a strategy that you can customize). Also, typically, I would expect a client to have either auth code *or* password grants, but not both, so the default strategy would have kept the tokens separate.

**Comment by talipkorkmaz** [comment]
thanks for solution..

**Comment by Grosskopferter** [comment]
My solution was to synchronize on the refreshTokenValue:

public class CustomTokenService extends DefaultTokenServices {

	@Override
	public synchronized OAuth2AccessToken createAccessToken(OAuth2Authentication authentication)
			throws AuthenticationException {
		return super.createAccessToken(authentication);
	}

	@Override
	public OAuth2AccessToken refreshAccessToken(String refreshTokenValue, TokenRequest tokenRequest)
			throws AuthenticationException {
		synchronized (refreshTokenValue.intern()) {
			return super.refreshAccessToken(refreshTokenValue, tokenRequest);
		}

	}

}

**Comment by rhamianiuk** [comment]
@Grosskopferter, this is poor solution. Better to lock (SELECT ... FOR UPDATE) on database row. This is usually user account, that can be taken from principal.

**Comment by ARAtIntBitTech** [comment]
Any solution to this issue?

**Comment by dsyer** [comment]
Yes (it's closed). Make sure your database is configured to take locks when needed. If you have a new issue open a new ticket, please. If you have a usage question, please post on stackoverflow.

**Comment by ARAtIntBitTech** [comment]
Can you please point me to the solution to this? When you say db is
configured to take locks when needed? What does that mean?

On Sat, Mar 12, 2016 at 2:06 PM, Dave Syer <notifications@github.com> wrote:

> Yes (it's closed). Make sure your database is configured to take locks
> when needed. If you have a new issue open a new ticket, please. If you have
> a usage question, please post on stackoverflow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-security-oauth/issues/276#issuecomment-195792577>
> .
>



-- 
[image: IntBit] <http://intbittech.com>
*Abdul Raqeeb Abdul Azeez (AR) <ar@intbittech.com>*, CTO
IntbitTech.com <http://intbittech.com>, Boston
412.908.9471 <+1-412-90-9471>

Disclaimer: This e-mail message may contain confidential or legally
privileged information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution,
copying or the taking of any action in reliance on the information herein
is prohibited. E-mails are not secure and cannot be guaranteed to be error
free as they can be intercepted, amended, or contain viruses. Anyone who
communicates with us by e-mail is deemed to have accepted these risks.
IntBit Technologies, Inc. is not responsible for errors or omissions in
this message and denies any responsibility for any damage arising from the
use of e-mail. Any opinion and other statement contained in this message
and any attachment are solely those of the author and do not necessarily
represent those of the company.
