### ISSUE TITLE
NoUniqueBeanDefinitionException thrown while initializing DefaultTokenServices with multiple TransactionManagers application

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-security-oauth#310]
#### Versions
- spring-security-oauth2 : 2.0.4
- spring-security: 4.0.0.M2
- spring-fmk: 4.1.1 
- jdk 8

I just updated to latest spring-security-oauth2 and I get the following exception at startup;

> org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.transaction.PlatformTransactionManager] is defined: expected single matching bean but found 3...

Before moving to 2.0.4 it was working fine. I assume it's because `DefaultTokenServices` is now `@Transactional`.
My application project uses 3 different `TransactionManager` to access 3 different datastore *jdbc + NoSql'. Distributed Transaction are not needed.
All OAuth2 related services (`ClientDetailsService`, `TokenStore`...) already define their own `@Transactional(value = "specficTransactionManager")` annotation.

I wonder if `DefaultTokenServices` should drop the `@Transactional` annotation and assume collaborators to be annotated instead.

Or could you point me to a work around so `TransactionAspectSupport.determineTransactionManager()`
does not fail at line 354

> // Lookup the default transaction manager and store it for next call
> this.transactionManager = this.beanFactory.getBean(PlatformTransactionManager.class);

Thanks

**Comment by tpemckiernan** [comment]
"Maybe you can just define a bean of type TransactionManagementConfigurer and specify the correct transaction manager to use in @Transactional by default there?"
Could someone update the vanilla sample to include the TransactionManagementConfigurer then?

**Comment by dsyer** [comment]
Which sample do you mean? Anyway, since this is expected to be a pretty uncommon requirement, I'm not sure we would want it in the existing samples (it clearly isn't needed because they work).

**Comment by dcerecedo** [comment]
Could you please elaborate on the solution. I'm having the exact same problem. I'm using InMemoryAuthorizationCodeServices and the rest of oauth specific services are also in memory. No database by now. I want to make this sample work and then move on to using a database. If you have already solved this can you elaborate on the solution? Thanks in advance!

**Comment by jaygarala** [comment]
@dcerecedo I am in the same boat as you but I use Mongo not Hibernate/ORM. So, I ended up importing spring-integration... 

```java
@Configuration
@EnableTransactionManagement
public class TransactionManagement implements TransactionManagementConfigurer {
    @Override
    public PlatformTransactionManager annotationDrivenTransactionManager() {
        return new PseudoTransactionManager();
    }
}
```

**Comment by rafaeldcfarias** [comment]
An easy workaround to this issue is to mark your "main" PlatformTransactionManager as Primary 
as explained on [the related issue](https://jira.spring.io/browse/SPR-12541?focusedCommentId=111032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-111032)?
  ```
@Primary
  @Bean(name = POSTGRE_TRANSACTION_MANAGER_BEAN_ALIAS)
  @Qualifier(POSTGRE_TRANSACTION_MANAGER_BEAN_QUALIFIER)
  public JpaTransactionManager transactionManagerPostgres(
      @Qualifier(POSTGRE_MANAGER_FACTORY_BEAN_ALIAS) EntityManagerFactory entityManagerFactory) {
    JpaTransactionManager transactionManager = new JpaTransactionManager();
    transactionManager.setEntityManagerFactory(entityManagerFactory);
    return transactionManager;
  }
```
or like @jaygarala  says 

```
@Configuration
@EnableTransactionManagement
@Lazy(true)
@DependsOn(value = POSTGRE_TRANSACTION_MANAGER_BEAN_QUALIFIER)
public class TransactionManagement implements TransactionManagementConfigurer {

  @Autowired
  @Qualifier(POSTGRE_TRANSACTION_MANAGER_BEAN_QUALIFIER)
  JpaTransactionManager transactionManager;

  @Override
  public PlatformTransactionManager annotationDrivenTransactionManager() {
    return transactionManager;
  }
}
```

**Comment by chmaheshkrishna** [comment]
First work around work's for me. Thanks for that.
