### ISSUE TITLE
Decouple token value generation from DefaultTokenServices

### ISSUE THREAD

**Issue by palmgren** [spring-projects/spring-security-oauth#333]
Currently, DefaultTokenServices generates new access and refresh token values using UUID.randomUUID() directly in two private methods that do a bunch of other stuff.  This makes it very hard for users to customize token key generation if they want to.  I propose that either (a) a new strategy interface is created for key generation, or (b) it gets pulled into its own protected method so that subclasses can override it.

It appears to be possible to edit the generated access token value in a roundabout way with the accessTokenEnhancer field by casting the token to its subclass.  However, even this is impossible for the refresh token.

**Comment by dsyer** [comment]
P.S. the `JwtAccessTokenConverter` is a `TokenEnhancer` and it modifies the refresh token value, so I don believe all the strategies you need are available.
