### ISSUE TITLE
Do not disable csrf by default in Resource Server

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth#339]

**Comment by dsyer** [comment]
I decided to go with CSRF off by default (still), but also add `SessionCreationPolicy.STATELESS` so that there are no sessions at all on OAuth2 resources by default (i.e. not much change from 2.0.5). See also #360.

**Comment by paskos** [comment]
That's our settings in all our resource servers. No session and CSRF disabled.

**Comment by SangameswaranRS** [comment]
I want to enable csrf in resource server
what to do. Changing 

security.enable-csrf: true

in resource server application.properties did not help

**Comment by SangameswaranRS** [comment]
@paskos can you help me to enable CSRF in resource server?
