### ISSUE TITLE
Make computeExpiry() protected in ApprovalStoreUserApprovalHandler

### ISSUE THREAD

**Issue by garyfleming** [spring-projects/spring-security-oauth#341]
It's often useful for Approvals to be relatively long-lived (months/years). The current `ApprovalStoreUserApprovalHandler` does not, as best as I can see, support this. 

`setApprovalExpiryInSeconds(...)` uses ints, which are multiplied by 1000 to get milliseconds. The problem is that `Integer.MAX_VALUE` means that the maximum approval time possible using this method is 24 to 25 days.

If `computeExpiry()` were made protected (or turned into a strategy), then subclasses of ApprovalStoreUserApprovalHandler would be able to keep much of the same behaviour and just override the relatively simple date calculation. Currently they have to reimplement/copy all of `updateAfterApproval()`.

**Comment by dsyer** [comment]
I don't like increasing the visibility of methods, but there was no reason to be using long internally here so I changed that instead. Thanks for the analysis.
