### ISSUE TITLE
How to customize error handling?

### ISSUE THREAD

**Issue by fengyapeng** [spring-projects/spring-security-oauth#343]
This is our doc write
 " 
Customizing the Error Handling

Error handling in an Authorization Server uses standard Spring MVC features, namely @ExceptionHandler methods in the endpoints themselves. Users can also provide a WebResponseExceptionTranslator to the endpoints themselves which is the best way to change the content of the responses as opposed to the way they are rendered. The rendering of exceptions delegates to HttpMesssageConverters (which can be added to the MVC configuration) in the case of token endpoint and to the OAuth error view (/oauth/error) in the case of teh authorization endpoint. A whitelabel error endpoint is provided, but users probably need to provide a custom implementation (e.g. just add a @Controller with @RequestMapping("/oauth/error")).
"
I have  try create a WebResponseExceptionTranslator by spring  for TokenEndpoints, but I failed.
The TokenEndPoints is dynamic create, There is no attribute for authorization-server to set this.

So How to custom the  WebResponseExceptionTranslator .

**Comment by dsyer** [comment]
To use a custom `WebResponseExceptionTranslator` you would have to create the endpoints yourself as `@Bean` definitions (i.e. not use the `@Enable*` annotations).

**Comment by neko1991** [comment]
Hi, is there some convenient way to set WebResponseExceptionTranslator for endpoints in xml configuration, and I find it in java configuration. 
Did you completely abandon xml configuration support at some point in this project?
Thank you very much for your reply.

**Comment by nklnandu** [comment]
what is the way to configure in java configuration? I am also looking in xml .. any way just curious how to set in java config?

**Comment by MyGitUserAcc** [comment]
Is there some convenient way to set WebResponseExceptionTranslator for endpoints in xml configuration????
