### ISSUE TITLE
Parameters are duplicated when AcceptsAuthorizationHeader is switched off in OAuthClientHttpRequestFactory

### ISSUE THREAD

**Issue by Jerbell** [spring-projects/spring-security-oauth#345]
(spring-security-oauth version 2.0.5)
Hi,

In the OAuthClientHttpRequestFactory class, createRequest method - if you have AcceptsAuthorizationHeader set to false then it generates a queryString correctly (which includes all custom query parameters).

However, at the line:
uri = URI.create(uriValue.contains("?") ? uriValue + "&" + queryString : uriValue + "?" + queryString);
It correctly checks whether there are existing params, but then it goes and adds on to the end, rather than just after the question mark.

As an example:
"http://localhost/oauth/duplicate/bug?param=DUPLICATE"

Will get converted to the url:
http://localhost/oauth/duplicate/bug?param=DUPLICATE&oauth_consumer_key=key&oauth_nonce=8d854b67-a189-429d-985f-e9e8c02c4398&oauth_signature=hQx35gpqOPcchGwrzUv3OJAW8Wo%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1419954873&oauth_version=1.0&param=DUPLICATE

On the other end, "param" will be received twice, and if it's a Spring controller the value will be "DUPLICATE,DUPLICATE".

Unless I'm doing something wrong?
Thanks,
Julian

**Comment by dsyer** [comment]
Fixed in #403 (I believe).
