### ISSUE TITLE
Spring redirect-uri contains double encoded value.

### ISSUE THREAD

**Issue by barbaraj7** [spring-projects/spring-security-oauth#349]
If an OAuth2 authorize with `response_type=code` is done with a redirect-uri with a encoded character, that character is double encoded in the result redirect. 

Ex: `redirect_uri=http://myhost/authorized?test=special%3Dvalue`
The authorize-call looks like: `/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Fmyhost%2Fauthorized%3Ftest%3Dspecial%253Dvalue&client_id=myid`

With spring oauth2 version 2.0.2.RELEASE: the redirect-uri is `http://myhost/authorized?test=special%253Dvalue&code=xyz`, so the %3D is replaced by %253D.
While with 1.0.5.RELEASE this worked as expected: the redirect-uri was `http://myhost/authorized?test=special%3Dvalue&code=xyz`

Code where the redirect gets the double encoding: `AuthorizationEndpoint#getSuccessfulRedirect`
Input: `authorizationRequest.getRedirectUri() = http://myhost/authorized?test=special%3Dvalue`
Returns = `http://myhost/authorized?test=special%253Dvalue&code=xyz`
This code was changed to fix issue: `https://github.com/spring-projects/spring-security-oauth/issues/152`
But now if the original redirect-uri already contains an encoded character, then the updated redirect-uri contains a double-encoding, which is a bug?

**Comment by barbaraj7** [comment]
Is there an ETA for the 2.0.6 milestone?  Thanks.

**Comment by dsyer** [comment]
> Is there an ETA for the 2.0.6 milestone? Thanks.

No. It will happen when it's ready. Help would be much appreciated.

**Comment by dsyer** [comment]
I couldn't reproduce this problem. Maybe you could provide some more detailed steps? Here's what I did:

```
$ curl -v user:password@localhost:8080/oauth/authorize -d client_id=my-trusted-client -d response_type=token -d redirect_uri=http://example.com?foo%3Dbar
$ curl -H "Cookie: JSESSIONID=<VALUE>" -v user:password@localhost:8080/oauth/authorize -d user_oauth_approval=true -d scope.read=true
```

(where the cookie value has to be copied and pasted from the previous response).

What I see is that when the `AuthorizationRequest` is first created it is given the request parameters, which contain the redirect_uri already decoded. Hence if it needs to be encoded to send back to the client it all works out as expected. You can even do some pretty whacky things with partially encoded inputs (like yours is, since it contains some unencoded "/" and ":" for instance) and it all seems to work fine.

**Comment by barbaraj7** [comment]
Do you know where the redirect_uri should get decoded?  So I can check why
in my case the request_parameters contain the original redirect_uri.
I'm not an expert on this but for sending the redirect_uri throught curl
you shouldn't be using --data-urlencode
<http://curl.haxx.se/docs/manpage.html#--data-urlencode>?

Thanks.

**Comment by dsyer** [comment]
The decoding gets done by your container (Tomcat etc.) so I can't point at the exact code. You should see the `HttpServletRequest` with request parameters already decoded when it comes in.

For the record `--data-urlencode` works for me as wel

**Comment by barbaraj7** [comment]
For instance if I use such a redirect on the update tests of sparklr2 AuthorizationCodeProviderTests
```
	@Test
	@OAuth2ContextConfiguration(resource = MyLessTrustedClient.class, initialize = false)
	public void testUserDeniesConfirmation() throws Exception {
		approveAccessTokenGrant("http://anywhere?t=a%3Db", false);
		String location = null;
		try {
			assertNotNull(context.getAccessToken());
			fail("Expected UserRedirectRequiredException");
		}
		catch (UserRedirectRequiredException e) {
			location = e.getRedirectUri();
		}
		assertTrue("Wrong location: " + location, location.contains("state="));
		assertTrue("Wrong location: " + location, location.startsWith("http://anywhere?t=a%3Db"));
		assertTrue(location.substring(location.indexOf('?')).contains("error=access_denied"));
		// It was a redirect that triggered our client redirect exception:
		assertEquals(HttpStatus.FOUND, tokenEndpointResponse.getStatusCode());
	}
```

Then the location is returned as: 
Wrong location: http://anywhere?t=a%253Db&error=access_denied&error_description=User%20denied%20access&state=Fcvmiv

**Comment by dsyer** [comment]
I think that change should be good for all existing use cases and yours. Please test a snapshot.

**Comment by rcpeters** [comment]
I've tested the snapshot locally. Fixes the encoding issue. Is there an official release? Just trying to figure out what do with with our production deployments.

**Comment by dsyer** [comment]
Thanks for testing. 2.0.6 is readyish. This week sometime probably.

**Comment by rcpeters** [comment]
For other that might be seeing the same issue I've created a patched 2.0.5 (2.0.5.RELEASE_DOUBLE_ENCODE_PATCH_SNAPSHOT) release that you can use. To use it add the following:

        <repository>
            <id>orcid-spring-oauth-copy</id>
            <name>copy of spring security oauth</name>
            <url>https://raw.github.com/ORCID/spring-security-oauth/mvn-repo/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

and change the spring-security-oauth2 version:

        <version>2.0.5.RELEASE_DOUBLE_ENCODE_PATCH_SNAPSHOT</version>

Should this should allow more time to test when migrating to the soon to be released 2.0.6.

**Comment by barbaraj7** [comment]
Hi,
It looks like redirect's with an escaped = or & in a query-parameter-value still have an issue with 2.0.6.
For instance: 
Using redirect-uri <code>http://anywhere?t=a%3Db%26ep%3Dtest%2540test.me</code>
is returned as       <code>http://anywhere?t=a%3Db&ep=test%2540test.me&error=...</code>

**Comment by dsyer** [comment]
Can you open a new issue for that (this one is closed and all tests are passing)?
