### ISSUE TITLE
How to set headers  AccessTokenRequest

### ISSUE THREAD

**Issue by nhrdl** [spring-projects/spring-security-oauth#353]
I am not able to call setHeaders method of AccessTokenRequest. Also trying asking question at https://stackoverflow.com/questions/27852278/how-to-set-headers-spring-oauth-accesstokenrequest

Following code does not compile - entirely possible I am doing something wrong. Tried searching for example, but could not find any.

    final Map<? extends String, ? extends List<String>> headers = accTknReq.getHeaders();
    final List<String> lst1 = headers.get("MyHeader");
    final ArrayList<String> lst2 = new ArrayList<>();
    headers.put("MyHeader", lst1);
    headers.put("MyHeader", lst2);

**Comment by dsyer** [comment]
As indicated on Stackoverflow, all you need to do is construct a `Map` with the right type and call the setter on the `AccessTokenRequest`. E.g.

```
final Map<String, List<String>> headers = new HashMap<>(accTknReq.getHeaders());
final List<String> lst1 = headers.get("MyHeader");
final ArrayList<String> lst2 = new ArrayList<>();
headers.put("MyHeader", lst1);
headers.put("MyHeader", lst2);
accTknReq.setHeaders(headers);
```

The signature of the getter is unfortunate, but it's not difficult to work with.
