### ISSUE TITLE
Requests Rejected Because Of Lowercase Bearer

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-projects/spring-security-oauth#354]
Some OAuth providers (Google and Facebook) will reject the access token if you use "bearer" in the authorization header.  They only accept a token type of "Bearer" with an uppercase B.  `DefaultOAuth2AccessToken` will set the token type to "bearer" by default.  I think by default it should be Bearer since the more common OAuth providers accept that (Google, Facebook, GitHub).

On a related note `DefaultOAuth2RequestAuthenticator` will set the token type to "Bearer" if the value in the access token is not set, so it seems to be inconsistent as to what the right approach is anyways.

**Comment by dsyer** [comment]
Note that those providers support tokens in the form body as well (which is supported already in Spring OAuth). My preferred fix fro this is to use the declared "tokenName" from the `OAuth2ProtectedResourceDetails` in the `DefaultOAuth2RequestAuthenticator`.

**Comment by dsyer** [comment]
BTW github works with "bearer" for me. The spec says the header is case-insensitive so it ought not to matter.

**Comment by ryanjbaxter** [comment]
Agree I saw the same thing, GitHub does not seem to care.  Facebook and Google are more strict.

**Comment by dsyer** [comment]
I would also expect the others to work if you use the token type that the provider gives you. I think the problem here is actually that we (e.g. in Spring Cloud) were using the token value without the type
