### ISSUE TITLE
Client user authentication not required in @Async method?

### ISSUE THREAD

**Issue by mariubog** [spring-projects/spring-security-oauth#357]
When we try to request reource that requires acces token, before we aquire token, requirement is we have to be authenticated on client side unless request is associated with the client rather than user and we override clientOnly()  method on OAuth2ProtectedResourceDetails. 
If we dont and we try to obtain token InsufficientAuthenticationException is beeing thrown. And we are required to authenticate.
But when  I use asynch method this requirement seems to be bypassed even when clientOnly() returns false.
Is this desired behavior?
I created example of what I mean here 
https://github.com/mariubog/oauth-client-sample
If  you try to connect with  /results-nonauthorized and token has not been obtained earlier you'll get exception. In asych method it is not a case.

**Comment by dsyer** [comment]
The `@Async` annotation is not a Spring Security feature. To secure those methods you would have to use the async support added in Spring Security 3.2. That means either using Spring MVC async support (like here: http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#mvc-async), or with a special `TaskExecutor` (http://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/reference/htmlsingle/#delegatingsecuritycontextexecutor).

**Comment by dsyer** [comment]
I'm closing this because I don't see the relation to OAuth2. If you want to continue the discussion please re-open, and we can see if that was wrong. Or go and ask or search for a question about Spring Security async on Stackoverflow.
