### ISSUE TITLE
Add option to resource server to remove security context if no access token is presented

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth#360]
The default behaviour of `OAuth2AuthenticationProcessingFilter` is to pass requests on to the filter chain if there is no access token. Some applications might mix OAuth2 and cookie-based authentication, and you might not want the cookie to allow access to OAuth2 resources.

**Comment by sourcekick** [comment]
This change breaks a test in my project where I am using SecurityMockMvcRequestPostProcessors from Spring Security Test 4.0.0.M2 by Rob Winch to mock the Security Context in Tests of a REST API based on MockMvc.

see http://spring.io/blog/2014/05/23/preview-spring-security-test-web-security#populating-a-test-user-with-a-requestpostprocessor

The mocked Security Context is naturally not based on an OAuth2 Access Token and the Authorization Header is not present in the request. Rather the Security Context it is just installed within the test runtime using the new MockMvc with(user(...)) and with(authentication(...)) patterns.

Therefore the code introduced by c5d6f1f660... and 3e015a9b... clears any non-anonymous Security Context populated via Spring Security Test and leads to a 401.

I think setting stateless to false is not a good way to solve this in tests.

**Comment by praseodym** [comment]
I'm not sure why this change is needed when `SessionCreationPolicy.STATELESS` can be set on the filter chain, which has the same effect.

Furthermore, enabling this by default breaks our application, since we create an authentication object in the filter chain before `OAuth2AuthenticationProcessingFilter`, which will then delete this object. Because of #455, we cannot disable the stateless option.

**Comment by dsyer** [comment]
I don't think `SessionCreationPolicy.STATELESS` is the same thing at all. If you need to leave a comment about this, putting it on a closed issue isn't going to help much though. If #455 is what interests you now, I suggest maybe you could comment there (or send a pull request).

**Comment by praseodym** [comment]
Please elaborate what use case wouldn't be covered by `SessionCreationPolicy.STATELESS`?

**Comment by dsyer** [comment]
Session creation policy only affects session creation. Clearing the security context affects the security context (only). It's different. If you want to discuss this feature please don't use a closed issue.

**Comment by abccbaandy** [comment]
For anyone find this issue from google, I use this code to "prevent" OAuth2AuthenticationProcessingFilter remove my Authentication.
````java
httpSecurity.addFilterAfter(new MyCustomFilter(), AbstractPreAuthenticatedProcessingFilter.class)
````

I don't know if this is misuse or something, but it work well.
