### ISSUE TITLE
OAuth2ExpressionParser class should be public to be instantiable

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-security-oauth#362]
`org.springframework.security.oauth2.provider.expression.OAuth2ExpressionParser` has a public constructor but is currently package protected.

I'd like to use it in my project but without using the associated OAuth2 `AbstractSecurityExpressionHandler` subclasses.

right now I have a hack where my code is in the same `org.springframework.security.oauth2.provider.expression` package but it would be nice if I simply could instantiate it from outside that package.

**Comment by paskos** [comment]
Pull request can be found [here!](https://github.com/spring-projects/spring-security-oauth/pull/365)

**Comment by dsyer** [comment]
What's your use case? I don't think it's always a good idea to make internal implementation details public.

**Comment by paskos** [comment]
I work on a large project where security access rules are dynamic (not in config classes or files), complex (not role based) and shared among many "protocols" (http only, oauth2 over http, jms, websocket).

We wrote a generic `org.springframework.security.access.expression.SecurityExpressionHandler` usable in all those protocol with very little customization (overriding of some targeted methods) in "protocol" sub-classes (PureHttp, OAuth2, SimpMessage....).

One of those customization is the ability to provide a "native" (not implemented by us) `org.springframework.security.oauth2.provider.expression.ExpressionParser`.
 `OAuth2ExpressionParser` being one of them because we like ` "#oauth2.throwOnError(" + expressionString + ")";`).

Unfortunately `OAuth2ExpressionParser` is package protected so our `OAuth2SecurityExpressionHandler`has to be declared in `org.springframework.security.oauth2.provider.expression` to be able to see it.

**Comment by dsyer** [comment]
That's useful to know. More code would help though. Is there any reason you can't use the public API (`OAuth2WebSecurityExpressionHandler`)?

**Comment by paskos** [comment]
`OAuth2WebSecurityExpressionHandler extends DefaultWebSecurityExpressionHandler` which assumes `FilterInvocation` is used.

That forces `OAuth2MethodSecurityExpressionHandler` to be used when `MethodInvocation` is the "security context".

`OAuth2MethodSecurityExpressionHandler` and `OAuth2WebSecurityExpressionHandler` both assume you will need `OAuth2SecurityExpressionMethods` which we don't in our case because we have other security methods.

Our `OAuth2SecurityExpressionHandler` is extended to support `FilterInvocation`,  `MethodInvocation` and `Message< ? >`(for spring-messaging security) and ensure our project "security Methods" are the same as the ones used in all protocols.

It gives us security methods and dynamic access settings re-usability in multiple protocol and security "scheme" (Oauth2 or not) context:
* Without OAuth2
  * Http
  * Message (jms, websocket)
  * Method 

* With OAuth2
  * Http 
  * Message (jms, websocket)
  * Method

I hope you understand I'm not in a position to publish details about our implementation.

**Comment by dsyer** [comment]
Nice (I like the messaging idea - saw that once before but good to see it again). I still don't get the details exactly. Do you just need that class to be public? Is it OK to be final?

**Comment by paskos** [comment]
If you come to Montréal one day give me a shout we'll discuss the details. 
I'll organize a Beer Modeling Langage session. After 2-3 pints it's clear as IPA.

`public final` is fine. 
I just need to be able to write `new OAuth2ExpressionParser( getExpressionParser() )` in a class not in `package org.springframework.security.oauth2.provider.expression;`

**Comment by paskos** [comment]
It's indeed great to be able to pass OAuth2 access tokens into `Message< ? >` headers and have a `ResourceServer` capable of validating them beyond HTTP.
Thanks to `spring-security-galaxy` we were able to implement all this in less then 2 months (less then 2 weeks for the spring part, the bulk was spent implement the dynamic security access checks).
