### ISSUE TITLE
JWT refresh tokens valid as access tokens

### ISSUE THREAD

**Issue by ronaldheft** [spring-projects/spring-security-oauth#363]
I've noticed the refresh tokens generated by JwtAccessTokenConverter are also valid as access tokens.

Upon digging into this issue more, I've come to the following conclusions:
- Since JWT does not store tokens in memory or a db, the only way to differentiate a refresh token from an access token is via the decoded JWT payload.
- By default, the JWT payload does not include any information in the payload to indicate it's a refresh token.
- At the moment, there does not appear to be a way to alter just the refresh token via configuration (for example, a refresh token specific ClientDetailsServiceBuilder.additionalInformation or unique refresh token scopes).

I don't think this is a security flaw, but it's odd behavior.

**Comment by Dredalious** [comment]
+1 Noticed this today as well.
I have my doubts about it not being a security risk. As I understand you keep the access tokens on a short lifetime and the refresh tokens on a (extremely) long lifetime. This to not annoy your user with login screens (refresh token with long lifetime), but still enable revocation (access tokens with short lifetime).
So allowing the long lived refresh tokens to double as access tokens without the intermediary step (getting access token) might be harmful.

I could be completely off as I'm a bit new to this, so apologies in advance...
