### ISSUE TITLE
sparklr2 example OAuth2ServerConfig question

### ISSUE THREAD

**Issue by mariubog** [spring-projects/spring-security-oauth#364]
In `OAuth2ServerConfig` you configure `HttpSecurity` with order(10) in method of class `UiResourceConfiguration`, now when does this configuaration actually come into play, I run the example and I can not see how this `httpSecurity` config really works, especially that it overlaps same endpoints that are handled by Oauth autorization, is it suppose to handle direct requests from the browser to the resource and redirect to login in case of lack of authorization, because I do not think it does ? could you please shed some light on this
here is the link
https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/sparklr/src/main/java/org/springframework/security/oauth/examples/sparklr/config/OAuth2ServerConfig.java

**Comment by dsyer** [comment]
I think it's probably redundant. I just copied it from the old XML, so it was probably the same there.
