### ISSUE TITLE
Support for Keycloak Oauth2

### ISSUE THREAD

**Issue by NickPadilla** [spring-projects/spring-security-oauth#366]
Hello,

I have been working with Keycloak and Spring (Cloud) Security Oauth2.  I have found that Keycloak has different keys to the JWT so the current AccessTokenConverter.AUD only ever gets what Keycloak calls the REALM - for the Resource Id's it uses 'resource_access'.  UserAuthenticationConverter.USERNAME used is 'preferred_username'.    Right now both of the keys are defined as FINAL.  I would think that because of other providers not using the same keys for parts of the JWT we would need to be able to change those via configuration.  Before I go down that rabbit hole, I'd like to get some input from the team that maintains the project.  However, once all is done I'll be sure that Keycloak is a "supported" solution.

**Comment by NickPadilla** [comment]
Actually it seems that the 'resource_access' field is a HashMap.  That hashmap has the resource id's as the keys with the values being a List of the 'roles' for the resource.  They are strings.  So that each resource can have a different set of 'authorities'.  I am just guessing that these two things are equal, 'roles' and 'authorities'.  So how we setup the stored authorization will have to be modified as well, unless i am missing something here. What we can do is look at the current resourceId and only set that one resource and use its role mappings as the authorities.  This way it will only ever have to know about itself and we can keep the current logic. Thoughts?

**Comment by NickPadilla** [comment]
Or we have a translation layer that allows the map to be translated into something that spring security can know about.  I'm starting to think this layer is going to be the best route, so that custom support can be added without changes to the core codebase. If something like this already exists, please do tell - I haven't found anything like it - but again, I could have missed it.

**Comment by NickPadilla** [comment]
@dsyer Thoughts on this topic?  I am currently working on a fast paced project and would like to work out something as fast as possible.

**Comment by dsyer** [comment]
Isn't `AccessTokenConverter` "a translation layer that allows the map to be translated into something that spring security can know about"? I don't know why KeyCloak (or anyone else) would use non-standard keys in their JWT, but if they do you can always get them out and translate them to something sensible using an `AccessTokenConverter` (I believe). `JwtAccessTokenConverter` implements that interface by a delegate pattern so you can just plug one in. The `DefaultAccessTokenConverter` also has strategies in it for convenient extension. Have a look at the way `JwtAccessTokenConverter` is used in `JwtTokenStore`.

**Comment by NickPadilla** [comment]
Hey @dsyer - I agree, I just thought there might be an easier way to get to the proper outcome.  In a perfect world i'd just like to override the `JwtAccessTokenConverter.decode` method and perform the translation there.  I have tried to provide my own configuration, like this. 
```
    @Configuration
    @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
    protected static class JwtTokenServicesConfiguration {

        private static final Log LOG = LogFactory.getLog(JwtTokenServicesConfiguration.class);

        @Autowired
        private ResourceServerProperties resource;

        @Bean
        @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
        @ConditionalOnMissingBean(ResourceServerTokenServices.class)
        public ResourceServerTokenServices jwtTokenServices() {
            DefaultTokenServices services = new DefaultTokenServices();
            services.setTokenStore(jwtTokenStore());
            return services;
        }

        @Bean
        @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
        public TokenStore jwtTokenStore() {
            return new JwtTokenStore(jwtTokenEnhancer());
        }

        @Bean
        @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
        public JwtAccessTokenConverter jwtTokenEnhancer() {
            CustomJwtAccessTokenConverter converter = new CustomJwtAccessTokenConverter();
            String keyValue = resource.getJwt().getKeyValue();
            if (!StringUtils.hasText(keyValue)) {
                try {
                    keyValue = (String) new RestTemplate().getForObject(
                            resource.getJwt().getKeyUri(), Map.class).get("value");
                } catch (ResourceAccessException e) {
                    // ignore
                    LOG.warn("Failed to fetch token key (you may need to refresh when the auth server is back)");
                }
            } else {
                if (StringUtils.hasText(keyValue) && !keyValue.startsWith("-----BEGIN")) {
                    converter.setSigningKey(keyValue);
                }
            }
            if (keyValue != null) {
                converter.setVerifierKey(keyValue);
            }
            return converter;
        }
    }
```
Here is the `CustomJwtAccessTokenConverter`. 
```
public class CustomJwtAccessTokenConverter extends JwtAccessTokenConverter {
    @Override
    protected Map<String, Object> decode(String token) {
        Map<String, Object> map = super.decode(token);
        return map;
    }
}
```
However this doesn't override the default implementation.  I am just looking to see that it gets called, I can then work out the details. Ideas on how to override? 

Also, it is possible that keycloak's oauth2 implementation is before the contents of the identity had been hashed out.

**Comment by dsyer** [comment]
I don't understand why you need to do that. Can't you just plug an `AccessTokenConverter` (as a delegate) into the existing `JwtAccessTokenConverter`?

**Comment by NickPadilla** [comment]
Hey @dsyer - Thanks for the quick response!  I am not sure how I would plug in a different converter, given it is created this way `private AccessTokenConverter tokenConverter = new DefaultAccessTokenConverter();` inside the `JwtAccessTokenConverter`.  The `JwtAccessTokenConverter` is initialized by using the `ResourceServerTokenServicesConfiguration` and using a new operator.  So i figured overriding the configuration class, where the `JwtAccessTokenConverter` is created would be the place to override.  If i could override then all i really needed was to update the map to be what is expected, by overriding the decode method.  

However, if I need to create an `AccessTokenConverter` that is fine.  How exactly would I set it on the `JwtAccessTokenConverter` created by the `ResourceServerTokenServicesConfiguration`?  I'd rather not have to have duplicate code in a custom `AccessTokenConverter` just to change the keys in a map.  Which also means that updates or changes that are needed to the code would have to be copied to the custom implementation, assuming we/I noticed there were changes.  Maybe I am missing something important here, if so please advise. 

Thanks for your help!

**Comment by dsyer** [comment]
`JwtAccessTokenConverter` has a setter for its delegate. You have to create one anyway to get JWT working so I don't think there's anything else to do here. 

`ResourceServerTokenServicesConfiguration` is not  in this project (I think you have been looking at Spring Cloud Security?).

**Comment by NickPadilla** [comment]
I have been working with Spring Cloud Security, yes.  I asked the question here b/c I figured I could just override `JwtAccessTokenConverter` which is in this project.  I am sorry I should have made greater emphasis that I am using Spring Cloud Security.   Should I ask a more pointed question in Spring Cloud Security?

**Comment by dsyer** [comment]
To be clear (again) there's no need to override `JwtAccessTokenConverter` (just create your own `AccessTokenConverter` and inject it).

An issue in spring-cloud-security to cover that bit seems appropriate.

**Comment by NickPadilla** [comment]
Understood, just trying to fill ya in on my thought process on why this was topic was here.  I'll create an issue in spring cloud security. 

Thanks for your time!
