### ISSUE TITLE
Add RedisTokenStore

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-security-oauth#367]
It would be nice if we could add a test scoped dependency to the tests in this project so that we could extends TokenStoreBaseTests for our own custom TokenStore.

Something like:

    <dependency>
        <groupId>org.springframework.security.oauth</groupId>
        <artifactId>spring-security-oauth2-tests</artifactId>
        <scope>test</scope>
    </dependency>

Or, better yet, create an official RedisTokenStore.

**Comment by dsyer** [comment]
Thanks for the interest in the base tests. I actually prefer just to make them public and you can copy the bits you need. If you want to contribute a `RedisTokenStore` please go ahead.

**Comment by efenderbosch** [comment]
I have a ``RedisTokenStore`` working using RedisTemplates, but because of the mixed nature of the objects, I can't use pipelining. I'll see if I can refactor it to just use ``RedisConnection`` so I can take advantage of pipelining the mixed objects.

**Comment by efenderbosch** [comment]
Here's my ``PipelinedRedisTokenStore``. It could be cleaned up a bit to allow a custom ``RedisSerializer`` and ``AuthenticationKeyGenerator``, but it passes all tests in ``TokenStoreBaseTests``.

https://gist.github.com/efenderbosch/a91633773955ab458549

**Comment by dsyer** [comment]
That certainly looks interesting. Why is it "Pipelined"?

If you could tidy it up a bit (fix the TODOs, maybe add a serialization strategy for the `OBJECT_SERIALIZER`) we could put it in Spring OAuth. A pull request would be awesome (please do the contributor's agreement thing from the README).

**Comment by efenderbosch** [comment]
My original implementation used multiple ``RedisTemplate`` objects, so I couldn't use pipelining across the different ``OAuth`` objects. This implementation uses pipelines, but I manage the serialization manually.

I think I'm going to rework it to use a single ``RedisTemplate`` so i can get rid of some of the boilerplate that goes along w/ using the raw ``RedisConnection``, but this should allow me to use pipelining.

I'll incorporate your suggestions and submit a pull request some time in the near future.

**Comment by mundodojava** [comment]
I would like try to create a spring-security-oauth2-redis module with a default implementation of RedisTokenStore, if dsyer agree with this.

**Comment by dsyer** [comment]
I think we're still waiting for the PR for the `RedisTokenStore`. Why would we need a new module?

**Comment by mundodojava** [comment]
My idea is to create a module to `spring-security-oauth2-redis`, (not necessarily for the actual PR), because to handle with `RedisTokenStore` will be necessary to use `spring-data-redis` to build the repositories and the process to store the token. So I think will better to separate the module because his dependencies. Please correct me if I'm wrong or if I'm complicating a simple thing. I'm open to other opinions and ready to learn.

**Comment by dsyer** [comment]
I'm not sure we need a new module (we don't have one for other `TokenStore`  implementations). That's all.

**Comment by mundodojava** [comment]
Okay, I understand this point. Thank you.

**Comment by efenderbosch** [comment]
I had forgotten about this. We've been using our Redis token store in prod for a few months now. I've contacted the right folks at my company to find out if I can contribute this back. I'll update soon.

**Comment by efenderbosch** [comment]
Just waiting for approval from company officers, I've got the pull request ready.
