### ISSUE TITLE
/oauth/token_key returns 404

### ISSUE THREAD

**Issue by Dredalious** [spring-projects/spring-security-oauth#370]
Based on the JWT integration test and config as per docs: 
`oauthServer.tokenKeyAccess("isAnonymous() || hasAuthority('ROLE_TRUSTED_CLIENT')").checkTokenAccess("hasAuthority('ROLE_TRUSTED_CLIENT')");`

Tomcat logs show a log line for oauth/check_token but not for oauth/token_key:
`INFO: Mapped "{[/oauth/check_token],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public java.util.Map<java.lang.String, ?> org.springframework.security.oauth2.provider.endpoint.CheckTokenEndpoint.checkToken(java.lang.String)`
Nothing in log for token_key, got entries for /oauth/authorize, /oauth/token, /oauth/error, /oauth/confirm_access. Everything else seems to work.

Servlet mapping should be ok:
```
    <servlet>
        <servlet-name>rest-dispatcher</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>dispatchOptionsRequest</param-name>
            <param-value>true</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>rest-dispatcher</servlet-name>
        <url-pattern>/oauth/token</url-pattern>
        <url-pattern>/oauth/token_key</url-pattern>
        <url-pattern>/oauth/check_token</url-pattern>
    </servlet-mapping>
```

Edit: Also this shows up in the tomcat logs:
`WARNING: Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)`
I would expect that everything simply works with the default value's? I haven't specified a keystore to use.

**Comment by Dredalious** [comment]
Update: It seems to work better when I set a signing key (giving authentication errors now, but that will be something at my end)
```
@Bean
public JwtAccessTokenConverter tokenEnhancer(){
    final JwtAccessTokenConverter jwtAccessTokenConverter = new JwtAccessTokenConverter();
    jwtAccessTokenConverter.setSigningKey("secret");
    return jwtAccessTokenConverter;
}
```

**Comment by dsyer** [comment]
You're not allowed to use anonymous authentication to access a shared key (it's supposed to be secret), so the only error your end is that (either authenticate fully or use a symmetric key). That doesn't really explain the 404, but it seems like you have something working as expected now.

**Comment by Dredalious** [comment]
The 404 is indeed the error and why i created the ticket. In the documentation and examples no explicit key is set, so I assume this should simply work - which it doesn't. 

After setting a signing key explicitly (wasting hours finding that out...) I can access it with Authorization: Basic base64(client_id:secret).

PS: you probably meant 'either authenticate fully or use an *a*symmetric key'? since per the docs, using public/private key should return the public there with no security (no reason for it).

**Comment by dsyer** [comment]
> you probably meant 'either authenticate fully or use an _a_symmetric key

Thanks. Corrected.

**Comment by dsyer** [comment]
But I can't reproduce your original problem (see commit 395f263).

**Comment by Dredalious** [comment]
I've put a minimal application on this repo: https://github.com/Dredalious/spring-oauth I'm quite new to configuring Spring by code, so maybe something is off there.

I run it in a jetty container, latest with just plain defaults, haven't tried tomcat but shouldn't matter I think.

**Comment by dsyer** [comment]
The 404 is cause by the fact that your `@Bean` for the `JwtAccessTokenConverter` has the wrong type. If you just declare it (like in your update) as a `JwtAccessTokenConverter` (not an `AccessTokenConverter`) you will see the /token_key endpoint.

There are a few other problems with that app, like you have a `@ComponentScan` in the default package (will scan all the packages in all the jar files on the classpath). Also you have to declare the OAuth2 endpoints in the servlet context (not the "root" context). I prefer to use a single application context for that reason (O don't see any point in just having one). If you fix your web.xml up it should work (or switch to using Spring Boot), e.g.

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">

	<filter>
		<filter-name>springSecurityFilterChain</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
		<init-param>
			<param-name>contextAttribute</param-name>
			<param-value>org.springframework.web.servlet.FrameworkServlet.CONTEXT.spring</param-value>
		</init-param>
	</filter>

	<filter-mapping>
		<filter-name>springSecurityFilterChain</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<servlet>
		<servlet-name>spring</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextClass</param-name>
			<param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
		</init-param>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>be.dimy.oauth.ApplicationConfig</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>

	<servlet-mapping>
		<servlet-name>spring</servlet-name>
		<url-pattern>/</url-pattern>
	</servlet-mapping>

</web-app>
```

**Comment by Dredalious** [comment]
You are compeletely right, changing the type to `JwtAccessTokenConverter` fixes the issue.

As for the config: I quickly copied and edited the setup, so the spring config and web.xml are not 100% I've fixed the major things on the repo above as per your suggestions, I'll leave it on github if this handy for anyone.

Thanks for the quick and extended support on this issue!
