### ISSUE TITLE
spring-security-oauth2 prevents ActiveMQAutoConfiguration from running

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-security-oauth#371]
We just integrated Spring Security with a Spring Boot app that use AMQ to publish events. As soon as we add spring-security-oauth2 to our pom.xml, AMQ will not stand up.

I'll try to get supporting docs/test cases ASAP, but we are pushing for prod next week.

I think it has something do with with the ``@AutoConfigureAfter({ JtaAutoConfiguration.class, JndiConnectionFactoryAutoConfiguration.class })`` annotation in ``ActiveMQAutoConfiguration``.

We have a workaround by standing up our own with:

```java
	@Bean
	public ActiveMQConnectionFactory connectionFactory(@Value("${spring.activemq.brokerUrl}") String brokerUrl) {
		return new ActiveMQConnectionFactory(brokerUrl);
	}
```

I've duplicated this issue in both the spring-boot and spring-security-oauth projects.

**Comment by dsyer** [comment]
Adding a dependency on spring-security-oauth2 has no effect (literally) on Spring Boot autoconfiguration, and there is no knowledge of Spring Boot in Spring OAuth2, so I really don't see how it can be a problem here. Can you provide more details and a link to the other issue for tracking?

**Comment by dsyer** [comment]
Appears unrelated to OAuth (closing).
