### ISSUE TITLE
Support sessionless load balancer.

### ISSUE THREAD

**Issue by shlomicthailand** [spring-projects/spring-security-oauth#373]
i started to implement the authorization code flow, and looking at the tests and source code i saw there is a note about the use of SessionAttributes which will not work even if you set all your service and stores to work with JDBC, another sessionattributes needs to be provided so the setup could work in stateless or non stick session load balancer.

this is quite disappointing as i don't want to implement a clusterable sessionattributes in such case.
maybe implementation can be session less ?

**Comment by dsyer** [comment]
You need state for the auth code and implicit grants. I don't see any reason not to use the session for that, but if you don't like it you can implement and install a `SessionAttributeStore` (standard Spring feature). [Spring Session](https://github.com/spring-projects/spring-session) is also super easy to set up if you can't do the `SessionAttributeStore` and you don't want to use sticky sessions.

**Comment by shlomicthailand** [comment]
The constraint for non sticky sessions is coming from our operations team, they decided that the app servers should be stateless. this is why i can't use the session

thanks
Shlomi

**Comment by dsyer** [comment]
Bad luck (they are wrong IMO). You still have the other 2 options if you can't use sticky sessions.
