### ISSUE TITLE
No way to get original token from OAuth2Authentication

### ISSUE THREAD

**Issue by mikeroda** [spring-projects/spring-security-oauth#376]
OAuth2Authentication.getCredentials always returns ""
OAuth2Authentication.getUserAuthentication().getCredentials() always returns "N/A"

Shouldn't one or both of these return the original access token?

**Comment by dsyer** [comment]
Depends on where you get the token. Try grabbing the `details` and casting to `OAuth2AuthenticationDetails` if you are in a resource server. If you are in a client the token is always in the `OAuth2ClientContext`.

**Comment by mikeroda** [comment]
I should have mentioned that I'm referring to JwtTokenStore.readAuthentication(String). The details is null on the authentication returned returned as well as the contained userAuthentication.

**Comment by dsyer** [comment]
If you call `JwtTokenStore.readAuthentication(String)` then you have the String you passed in. So I guess your scenario has more to it?

**Comment by mikeroda** [comment]
I am giving ResourceServerSecurityConfigurer a JwtTokenStore to avoid the remote userinfo callbacks. DefaultTokenServices.loadAuthentication calls JwtTokenStore.readAuthentication. Yes, I can get the String by subclassing JwtTokenStore and overriding readAuthentication, but I would like to be able to get it from the spring security context anywhere in my code by doing something like this:
        SecurityContext securityContext = SecurityContextHolder.getContext();
        OAuth2Authentication oauth = (OAuth2Authentication)securityContext.getAuthentication();
        String token = (String)oauth.getCredentials();
I plan to reuse the token for calling other resources.

**Comment by dsyer** [comment]
I don't really get the full picture yet I think. If you have a resource server then it has an `OAuth2AuthenticationProcessingFilter` and the filter will add the token value to the `AuthenticationDetails`. What are you doing that prevents that from happening (or is it happening and you don't realize)?

**Comment by mikeroda** [comment]
Ok I see it now.  I guess the filter was setting the details after calling the token store so I wasn't seeing it yet. I'm good now. Thanks.
