### ISSUE TITLE
OAuth2AuthenticationProcessingFilter prevents access to endpoints that don't require authentication

### ISSUE THREAD

**Issue by fkowal** [spring-projects/spring-security-oauth#378]
I have 2 endpoint
/needToken
/noTokenRequired
```java
   @Configuration
    @EnableResourceServer
    @EnableWebSecurity
    public class MyResourceServerConfigurer implements ResourceServerConfigurer {
        @Override
        public void configure(HttpSecurity http) throws Exception {
            http.csrf().disable().
                sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .authorizeRequests().antMatchers("/needToken") // I only require authorization to this endpoint
                .authenticated();
        }
}
```
curl -H "Authorization: Bearer invalidToken" localhost/noTokenRequired

OAuth2AuthenticationProcessingFilter run this part
```java
catch (OAuth2Exception failed) {
			SecurityContextHolder.clearContext();

			if (debug) {
				logger.debug("Authentication request failed: " + failed);
			}

			authenticationEntryPoint.commence(request, response,
					new InsufficientAuthenticationException(failed.getMessage(), failed));

			return;
		}
chain.doFilter(request, response);
```
Correct me if i am wrong.
shouldn't the filter created an Authentication with setAuthenticated(false)
and continue the chain.doFilter ?

And the some other class checks /noTokenRequired if authorization is not required, and since it's not my endpoint logic gets executed?

How can i get this behaviour ?

**Comment by dsyer** [comment]
You haven't set any request matchers, so you are matching all requests in the `ResourceServerConfigurer`. Normally if you have some resources that are not protected with OAuth2 you would have an `http.requestMatchers()` (or equivalent).

**Comment by fkowal** [comment]
I've added an extra antMatcher / changed the order, and it worked
```java
http.csrf().disable().
                sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .antMatcher("/needToken").authorizeRequests().anyRequest().authenticated();
```

Thank you.
This builder is powerful but hard and the same time. I had trouble finding docs / use case examples that would ease my learning curve.

**Comment by dsyer** [comment]
Good. You don't need the csrf or session creation policy (with 2.0.6 definitely and even with 2.0.5 I doubt they have any effect).
