### ISSUE TITLE
JdbcClientDetailsService not allowing filters on clients

### ISSUE THREAD

**Issue by shlomicthailand** [spring-projects/spring-security-oauth#379]
there is only 1 method `listClients()` which take no param. and actually pass empty param map to jdbctemplate. 
we have a situation where we want to customize the SQLs but don't have anyway to pass params to the sql. for example we added a tenant_id column so separate tenant clients but we don't have any way to filter by tenant.

all jdbc services - just made us spoiled :-) we don't want to write code anymore just use it
(specially not copy paste cause there is no other way here, jdbctemplate is private and so is listFactory)

**Comment by dsyer** [comment]
If I were you I'd just write my own `ClientDetailsRepository`. If you control teh schema you will want to control the queries as well.

**Comment by shlomicthailand** [comment]
thanks - so the question is why all the queries are still customizable , also insert and update .
but i take the advice for the short run - again , as less code i need to write the better.
