### ISSUE TITLE
How do I change default access_token duration when using client credentials

### ISSUE THREAD

**Issue by knoxor** [spring-projects/spring-security-oauth#381]
Hi,

Currently our access_token is set to default to 12hrs. After this the client needs to re-authenticate. I want to change the access_token either programatically or the default value but am not sure how to go about this. I've been researching for a couple of days and have ended up here.

I'm extending the ClientCredentialsTokenGranter and have the following method. I assume I have to persist the new token somewhere but am not sure what table this needs to be persisted in.

Can someone give me a few pointers?

thanks

    @Override
    public OAuth2AccessToken grant(String grantType, TokenRequest tokenRequest) {
        OAuth2AccessToken token = super.grant(grantType, tokenRequest);
        if (token != null) {
            OAuth2RefreshToken refreshToken = token.getRefreshToken();
            DefaultOAuth2AccessToken expiryToken = new DefaultOAuth2AccessToken(token);
            expiryToken.setExpiration(new Date(Long.MAX_VALUE));
            token = expiryToken;
        }
        return token;
    }

**Comment by dsyer** [comment]
Can't you just set the `accessTokenValidity` in the client details (or globally in the token services)?

**Comment by knoxor** [comment]
Thanks, that fixed my issue. I'm not familiar with oAuth2 yet and was under the impression that I had to somehow persist the value to a DB, but you're answer has pushed me in the right direction and I'm able to configure it. Thanks.

**Comment by knoxor** [comment]
Sorry, just as a followup. Setting the accessTokenValidity in tokenServices worked for me. It didn't work setting it on the ClientDetails implementation. thanks again.
