### ISSUE TITLE
OAuth2RestTemplate never delegates to custom error handlers

### ISSUE THREAD

**Issue by mressler** [spring-projects/spring-security-oauth#387]
While testing my Spring OAuth2 implementation (thank you!) I noticed that if my server returned a 403 Forbidden, my `OAuth2RestTemplate` would only ever throw `OAuth2Exceptions` instead of the expected `HttpClientErrorException`.  Further, the custom error handler that I had set up was never being called.

It looks like the `setErrorHandler` call in the `OAuth2RestTemplate` wraps my error custom error handler in an `OAuth2ErrorHandler`.  By itself, this is fine and I'm glad that there are standard errors that can be sniffed out and handled in this way.  My problem is on line 127 of `OAuth2ErrorHandler`:https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/http/OAuth2ErrorHandler.java#L127

```
OAuth2Exception body = extractor.extractData(bufferedResponse);
if (body != null) {
```

Looking at the `OAuth2ExceptionJackson2Deserializer`, it looks like line 127 will always return a non-null body object.  In my particular case, I'm returning my own custom JSON error content for the 403 result, but I'm still getting the `OAuth2Exception` deserialized from that line 127.  And, since the body object is non-null, the error handler never delegates to my custom error handler (line 148).

It seems like line 128 should be doing something a little more specific than just making sure it's non-null.  In my case, the resulting JSON was not intended to be turned into an `OAuth2Exception`.  Shouldn't line 128 looks for a return value that is a subclass of `OAuth2Exception`?

**Comment by mressler** [comment]
Also fun, even though the server returns status code 403 the exception's error code is never set and always returns the constant 400.  So now I can't even catch the `OAuth2Exception` and verify that the server's response is what I'm expecting.

Should I split this into two issues?  One for the status code and one for not playing nice with 403's?

The spec doesn't seem to specify the status codes as much as it specifies the resulting error content.  And at that it seems to only specify the resulting content on missing or invalid redirects.  In this case, the user and client are already authenticated, the response was received, understood, and then rejected because the client was attempting to access an object that it doesn't have permission to - hence the 403.  Should the server be sending a different result code in this situation or should the client not be so aggressive at handling those errors?

**Comment by dsyer** [comment]
The spec is very bad at being explicit with status codes, so we had to guess a few times (you will find traces of changes in the git logs I'm sure). Let's fix the custom error handler thing first and then decide if the response status codes in a normal scenario are correct.

**Comment by dsyer** [comment]
If you are returning custom JSON content in your 403, maybe you could just make it serializable to `OAuth2AccessDeniedException` (all you need is a field `"error":"access_denied"`) and catch that in your caller?

> it looks like line 127 will always return a non-null body object

Not really. It only is non-null if it can be converted to `OAuth2Exception` (so it has to be JSON or XML and have some structure). Also look at line 151 (where the `OAuth2Exception` is caught and handled) - so there is some logic to allow the custom error hander to proceed, but not (it seems) if the status code is 403 or 401 (so you are just unlucky in come ways that you want to process a 403 not a 400). I'm sure there was a reason for that, but it's going to be hard to re-create the thought process that led to it, so we'd better try and preserve as much of the existing behaviour as we can.

I can see the problem. I just don't know the best way round it (unless you can work with `OAuth2AccessDeniedException`).

**Comment by mressler** [comment]
For the time being I'm just checking that I get an `OAuth2Exception` and ignore the status code.  Perhaps if we didn't hardcode the status code in the `OAuth2Exception`?  Allowing for the status code to be modified in the `OAuth2ErrorHandler` would mean I could verify that at least the status code is correct.

I could send a pull request that would add that functionality if you think it's a good workaround.

That doesn't fix the custom error handler though.

For that, I'd suggest that if the `bufferedResponse.getRawStatusCode()` doesn't match the caught exception's `getStatusCode()` then the machinery has picked up an error that it shouldn't have and the `errorHandler` should get called instead of rethrowing the exception.

**Comment by dsyer** [comment]
> if the bufferedResponse.getRawStatusCode() doesn't match the caught exception's getStatusCode() then the machinery has picked up an error that it shouldn't have and the errorHandler should get called instead of rethrowing the exception

Sounds reasonable. But since people use this mechanism with 3rd party OAuth2 providers, we have to do something sensible on a 403 or 401 by default as well. Not everyone will have a custom error handler and it should work out of the box if the response only means that we have to try again and get a new access token.

**Comment by mressler** [comment]
Gotcha.  Then if the exception status doesn't match the response status AND there is an errorHandler set, then forward to the custom errorHandler.  How does that sound?

I know you mentioned it would be hard to get back to the thinking around the 403 or 401 rules - is there a test case that might highlight the existence of this rule?

This might be too idealized of an approach, but here's my thinking: if we make this change and something breaks with a third party OAuth2 provider, then the proper fix would be to add a new `messageConverter` so that an `OAuth2AccessDeniedException` is deserialized appropriately from the response.  This feels a little "breaky" to me, but if there aren't any test cases for this particular bit of code, then perhaps it's the best way forward?

**Comment by dsyer** [comment]
>  is there a test case that might highlight the existence of this rule?

Probably. Remove the test for 403 and 401 and see what fails? It might be an integration test.

> Then if the exception status doesn't match the response status AND there is an errorHandler set, then forward to the custom errorHandler. How does that sound?

Good.

**Comment by mressler** [comment]
Planning on working on this this evening.  Just forked, read through the GSG, and then ran the `mvn install -P bootstrap` command.  Surprisingly, the integration tests failed.

Here's the log: https://www.dropbox.com/s/6xo0tp7wdl1278i/build.txt?dl=0

Any pointers?  Where did I go wrong?

**Comment by dsyer** [comment]
Java 8? Try with Java 7.

**Comment by dsyer** [comment]
I've been playing with this a bit and I probably could stand to allow the custom error handler to handle everything "odd" if it is provided. But isn't a 401 or a 403 more likely to legitimately best handled by throwing an appropriate `OAuth2Exception` (e.g. `InvalidTokenException` for a 401 and `OAuth2AccessDeniedException` for a 403)? Those would be caught and correctly handled by the caller (e.g. a filter chain).

I think the intention with `OAuth2ExceptionHandler` is to manage everything that can be translated into a sensible `OAuth2Exception` and let everything else fall through to the default. A 401 or a 403 from a remote OAuth2 resource sounds to me like it should be sensibly converted to an `OAuth2Exception` even if we don't know how to populate the details accurately. What do you think?

**Comment by mressler** [comment]
In my scenario, the client and the user have done everything correctly, but the request was to access a resource that the user or client didn't have access to.  I don't know if that's really an `OAuth2AccessDeniedException` or not (But certainly throwing that would be better than the generic `OAuth2Exception`.

It's just unexpected that the same exception handed back by the server with a standard `RestTemplate` is an `HttpClientErrorException` and with an `OAuth2RestTemplate` it's an `OAuth2Exception` - especially after all of the OAuth2 handshaking has already been completed for this template.

**Comment by dsyer** [comment]
I hear you. But `HttpClientErrorException` is too generic, so the design (from before I got involved with this project) was to throw special exceptions and catch them so they can cause the OAuth2 protocols to be initiated. It kind of makes sense to me. And I think you want your 403 to behave the same as any other 403 in an `OAuth2RestTemplate`, so we might be able to agree on a way forward (even if you don't like the design).

**Comment by mressler** [comment]
I'll probably end up liking the design :)  I haven't jumped back into working on this since the integration tests were failing.  I'll try changing Java versions and see if that fixes the errors.

It makes sense that the OAuth2 machinery is hanging off of those OAuth2 specific exceptions.  Just seems like after the handshaking has occurred and the Bearer tokens are being passed, it should act like a standard `RestTemplate` at that point.

**Comment by dsyer** [comment]
I can see that point of view (the 403 is just a 403, but the 401 is special). It remains to be seen if that can be accommodated without breaking anything too badly. I think it might be fine since the `OAuth2Exceptions` that encode 403s are really focused on the server not the client.

**Comment by dsyer** [comment]
There are a couple of problems with that idea. One is that the spec is unclear on what status code should be returned in quite a few situations where an access token could still be acquired, so 3rd party providers are almost guaranteed to be inconsistent (e.g. you might get a 400 when actually all you need to do is redirect to the authorization endpoint).  Another problem is that even with the native provider, a 403 might very well be something you want to react to by asking for a new token (e.g. to widen the scope).

I don't see a really obvious way of resolving this, except to add a flag to the error handler (or the `OAuth2RestTemplate`) to allow the user to decide that he wants to handle all errors, instead of guessing an `OAuth2Exception` to throw. That seems like it would put too much boilerplate logic in the users custom error handler, or else he would miss out completely on the OAuth2 flows.

**Comment by mressler** [comment]
Interesting.  I hadn't considered the case of widening the authorized scope.  In that case, wouldn't the implementing client be looking for the 403, no matter what type the exception is?  We're not adding any value by making it an `OAuth2AccessDeniedException` instead of a standard `HttpClientErrorException`.  Either way, as a client, I'm still looking for the 403 so that I can go back and start the scope widening process.  My understanding, coming into this pretty fresh, is that the `OAuth2AccessDeniedException` is meant more for Spring Security OAuth2 machinery, than for client consumption and handling.  At least it "feels" that way, if that makes sense.

Coming into this, I had a high level understanding of OAuth generally and quickly got myself oriented to OAuth2.  My mind set was that the `OAuth2RestTemplate` would do the magic of interacting with a resource that I described to it, but then it would be pretty hands off after the magic had faded.  In this way, my testing code can be handed a `RestTemplate` (OAuth2 or vanilla) and then interact with the resources as normal.  The unexpected part is that now the resource interaction code needs to be aware of the `OAuth2Exception` hierarchy.

**Comment by dsyer** [comment]
> it would be pretty hands off after the magic had faded

That is the intention, but I think you are missing the fact that `OAuth2RestTemplate` is part of the magic in the call chain, and a) it has the right to deal with exceptions on its own if it can (and it does), b) it has to send the right signals to its caller, and c) it's not your responsibility as a user to start the scope widening process. A 403 from a remote resource could be interpreted as an opportunity to re-invoke the magic (and that's what is happening by default right now). We will have a hard time distinguishing a 403 that can be handled with magic and one that can't (and sometimes it will be a 400, or some other confusing response). `OAuth2AccessDeniedException` most definitely *is* adding value (IMO) if it leads to a transparent `RestTemplate` call that just grabs a new access token and tries the original request again (that's the most straighforward outcome, and it isn't always that easy, but something useful usually happens in response to `OAuth2Exceptions`).

**Comment by mressler** [comment]
Ah, sweet.  I did not know that it would be responsible for widening scope.  Nifty.  Well, this certainly is a tricky spot then.

**Comment by dsyer** [comment]
Can we go back your original use case? What is it about this 403 that makes it something you can handle and Spring OAuth can't?

**Comment by mressler** [comment]
The user can not perform the request on the object specified.  That's the essence of what the server is trying to communicate.  Whether it's an view, edit, or deletion, the user making the request - or the client making the request on behalf of the user - can not take that action on this object.  Scope widening won't help here.  

Some other action might help though - perhaps the user could request permissions from the object's owner.

**Comment by dsyer** [comment]
How would your client react then? How would it know what information this response was trying to convey? (Usually the answer is in the WWW-Authenticate header. Maybe we need to focus on that, or some generalization of it, so we can weed out the requests that you can handle, or that we can't?)

**Comment by mressler** [comment]
It's nothing that the client can specifically react to, it's a present limitation of the users actions.  The user can attempt to request permission through other means, but my server is informing the client that their action is not allowed.  How they came to perform this action is another story, but we do need to inform the client that they aren't authorized for that request.

How the server communicates to the client about an automatically recoverable exception via OAuth2 scope widening is your area of expertise.  As an app developer though, I definitely want to test that my server doesn't allow users to take arbitrary actions - that's what sparked the discussion.

**Comment by dsyer** [comment]
I think your custom handler should behave as expected with commit 6ae6b0f. Can you try  snapshot?
