### ISSUE TITLE
JWT - @AuthenticationPrincipal is String

### ISSUE THREAD

**Issue by bmcustodio** [spring-projects/spring-security-oauth#389]
I've successfully set up Spring Security OAuth + Spring Security JWT and it is working smoothly. However, when I try to inject an `@AuthenticationPrincipal` on a given mapping, I always get a `String`:

```java
@RequestMapping(method = RequestMethod.GET, value = "/me")
public ResponseEntity<User> getCurrentUser(@AuthenticationPrincipal Object userDetails) {
  // userDetails is a String.
}
```

I was expecting `userDetails` to be an instance of `UserDetails` or of a custom `User` class I could define. Is this supposed to be like this, or am I missing something in my setup?

**Comment by dsyer** [comment]
If you inject the `Principal` instead it will be an instance of `OAuth2Authentication` with more details, so you can probably use that. You can change the way it is structured by changing the `JwtAccessTokenConverter` (e.g. injecting a new `DefaultAccessTokenConverter` into it with a `UserAuthenticationConverter` that does what you prefer).
