### ISSUE TITLE
Problems getting facebook client to work

### ISSUE THREAD

**Issue by pashtika** [spring-projects/spring-security-oauth#390]
It seems that Spring MVC OAuth2 example for facebook not working and throwing exception. I'm referring code from https://github.com/spring-projects/spring-security-oauth

Just to be more clear on my query - Spring OAuth2 is not working properly as Client (don't find any working client code) in order to connect the Cloud API's (like Misfit etc..) or Social Networks (like Google, Facebook, Linkedin etc,) to follow proper OAuth2 mechanism, But on other hand, I see Apache Oltu (earlier Apache Amber) is useful enough to work as a OAuth2 client and its working fine in my sample example. Why such implementation can't be developed using Spring OAuth2 (or developed already not working). Please someone look at this following code which is causing problem from above mentioned location?

FacebookController.java:

```
ObjectNode result = facebookRestTemplate .getForObject("https://graph.facebook.com/me/friends", ObjectNode.class);
ArrayNode data = (ArrayNode) result.get("data")

**Comment by dsyer** [comment]
What is the `facebookRestTemplate` in your snippet? If you post more code we might be able to see what you are trying to do. There is a facebook sample that works (last time I checked) in [github here](https://github.com/spring-projects/spring-security-oauth/tree/master/samples/oauth2/tonr). The client is configured [here](https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/tonr/src/main/java/org/springframework/security/oauth/examples/config/WebMvcConfig.java#L155).

BTW, general questions about how to use the framework are often better posed at [stackoverflow](http://stackoverflow.com/questions/tagged/spring-security-oauth2) (more people look at those, and they provide better search tools for people looking for similar help).

**Comment by pashtika** [comment]
@dsyer - As I said, I'm using same code https://github.com/spring-projects/spring-security-oauth and when I'm clicking on find facebook friend its giving me an exception. Could you please double check this example? As your saying its working, but in my case it's giving exception. Do we need to change anything in order to make it workable? Please guide me on this. 

I've created a App in Facebook Developer site and using generated App ID and App Secret.
hope you got the problem.

@Bean
	public FacebookController facebookController(@Qualifier("facebookRestTemplate")
	RestOperations facebookRestTemplate) {
		FacebookController controller = new FacebookController();
		controller.setFacebookRestTemplate(facebookRestTemplate);
		return controller;
	}

@Bean
		public OAuth2ProtectedResourceDetails facebook() {
			AuthorizationCodeResourceDetails details = new AuthorizationCodeResourceDetails();
			details.setId("facebook");
			details.setClientId("970222193006255");
			details.setClientSecret("27aae52935369b43710e6e8bacc7f2d7");
			details.setAccessTokenUri("https://graph.facebook.com/oauth/access_token");
			details.setUserAuthorizationUri("https://www.facebook.com/dialog/oauth");
			details.setTokenName("oauth_token");
			details.setAuthenticationScheme(AuthenticationScheme.query);
			details.setClientAuthenticationScheme(AuthenticationScheme.form);
			return details;
		}

@Controller
public class FacebookController {

	private RestOperations facebookRestTemplate;

	@RequestMapping("/facebook/info")
	public String photos(Model model) throws Exception {
		ObjectNode result = facebookRestTemplate
				.getForObject("https://graph.facebook.com/me/friends", ObjectNode.class);
		ArrayNode data = (ArrayNode) result.get("data");
		ArrayList<String> friends = new ArrayList<String>();
		for (JsonNode dataNode : data) {
			friends.add(dataNode.get("name").getTextValue());
		}
		model.addAttribute("friends", friends);
		return "facebook";
	}

	public void setFacebookRestTemplate(RestOperations facebookRestTemplate) {
		this.facebookRestTemplate = facebookRestTemplate;
	}
}

**Comment by dsyer** [comment]
I can't see anything wrong there but we haven't see how the `facebookTemplate` is created, and you haven't shown the stack trace from your exception yet.

**Comment by pashtika** [comment]
I'm getting following error:-

Could not complete request <org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval>org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval
at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getRedirectForAuthorization(AuthorizationCodeAccessTokenProvider.java:349)
    at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:194)
    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:142)
    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:118)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:547)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:512)
    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by dsyer** [comment]
That's normal: "A redirect is required to get the users approval". You need to redirect the request. Did you forget to install the `OAuth2ClientContextFilter`? From the [user guide](http://projects.spring.io/spring-security-oauth/docs/oauth2.html):

> The filter has to be wired into the application (e.g. using a Servlet initializer or web.xml configuration for a DelegatingFilterProxy with the same name).

**Comment by pashtika** [comment]
I've downloaded latest code from git and I though it should have to be there. I can't see web.xml file tonr2 module. Could you please guide?

**Comment by dsyer** [comment]
It's a servlet 3.0 app (no web.xml) so it has this instead: https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/tonr/src/main/java/org/springframework/security/oauth/examples/config/ServletInitializer.java

**Comment by pashtika** [comment]
@dsyer - Many Thanks for your support. Its working now. I think required bean configuration was missing. Right?
How same App ID and Client Secret is working in my case? It should not be my facebook Developer App details?

**Comment by dsyer** [comment]
> One or more of the given URLs is not allowed by the App's settings

You registered a redirect URI when you created your app in facebook. The one in tonr2 is on localhost so it always works for testing. Yours must be different.

> I think required bean configuration was missing. 

No idea. But I'm happy you fixed it.

**Comment by pashtika** [comment]
Hello Dave, 
I see Apache Oltu has a client (request and response API) through which I can get authorization code and then we can get details about profile etc.., whatever we want and able to get those details in response client API.
Please refer the code below:-
OAuthClientRequest request = OAuthClientRequest
                .authorizationLocation("https://api.misfitwearables.com/auth/dialog/authorize")
                .setClientId("xxxxxxxxx")
                .setRedirectURI("http://localhost:8080/OAuth2Example/misfit/redirect")
                .setResponseType("code")
                .setScope("public,birthday,email")
                .buildQueryMessage();

The expected response I'm getting is 
{"userId":"54c4d56fc00ae73be70a32434","name":"ABC","birthday":"1988-12-05","gender":"male","email":"abc@gmail.com"}

I'm looking similar approach to do in "Spring OAuth2" and I learn that "OAuth2RestTemplate" helps in that, but when I look at API I don't find a way to build a request. I'm referring to site (http://stackoverflow.com/questions/23486186/access-tokens-using-2-legged-oauth-2-0-and-apache-oauthclient/28341073#28341073)

I understand you're OAuth2 expert and can definitely guide / help on my query. Could you please provide your help / guidance?

**Comment by dsyer** [comment]
Isn't that the response from the facebook /me endpoint? All you need to do is change the URL in the sample and ask for a response of type `Map`.

**Comment by pashtika** [comment]
Yes, I've set -  Valid OAuth redirect URIs to http://localhost:8080/tonr2/facebook/ under the advance tab, but I'm not getting say list of friends nor any error. What should be the correct URL and where to configure it?

I wish to implement Spring OAuth2 for other cloud sites and Social Sites. Could you please address to my above comments query as well?

**Comment by dsyer** [comment]
I don't really know what else I can say other than "look at the sample and copy it".

**Comment by pashtika** [comment]
OK. It's fine if you're not aware how to use "OAuth2RestTemplate" API to use with other sites as well. I'm trying to make following link provided method #2 approacg from last couple of weekd but does not able to make it workable...
http://stackoverflow.com/questions/23486186/access-tokens-using-2-legged-oauth-2-0-and-apache-oauthclient/28341073#28341073

**Comment by dsyer** [comment]
I answered all the questions (even though this is an issue tracker, not a forum). There is at least one sample that uses Facebook and it works (I checked). If that isn't enough to get you started you'll have to ask somewhere else - please go to StackOverflow for usage questions. Closing.

**Comment by pashtika** [comment]
Hello,

I'm using following file and getting the error:

<?xml version="1.0" encoding="UTF-8" ?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:oauth="http://www.springframework.org/schema/security/oauth2"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:sec="http://www.springframework.org/schema/security" 
	xmlns:mvc="http://www.springframework.org/schema/mvc"
	xsi:schemaLocation="http://www.springframework.org/schema/security/oauth2 
	http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd
	http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.2.xsd
	http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-3.2.xsd 
	http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
	http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.1.xsd ">


	
	<http pattern="/oauth/token" 
		create-session="stateless"
		authentication-manager-ref="clientAuthenticationManager"
		xmlns="http://www.springframework.org/schema/security">
		
		<intercept-url pattern="/oauth/token" access="IS_AUTHENTICATED_FULLY" />
		<anonymous enabled="false" />
		
		<http-basic entry-point-ref="clientAuthenticationEntryPoint" />
		
		
		
		<custom-filter ref="clientCredentialsTokenEndpointFilter" after="BASIC_AUTH_FILTER" />
		<access-denied-handler ref="oauthAccessDeniedHandler" />
	</http>

	
	<http pattern="/api/**" 
	    create-session="never"
		entry-point-ref="oauthAuthenticationEntryPoint"
		access-decision-manager-ref="accessDecisionManager"
		xmlns="http://www.springframework.org/schema/security">
		
		<anonymous enabled="false" />
		<intercept-url pattern="/api/**" access="ROLE_APP" />
		<custom-filter ref="resourceServerFilter" before="PRE_AUTH_FILTER" />
		<access-denied-handler ref="oauthAccessDeniedHandler" />
	</http>


	<bean id="oauthAuthenticationEntryPoint"
		class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint">
		<property name="realmName" value="test" />
	</bean>

	<bean id="clientAuthenticationEntryPoint"
		class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint">
		<property name="realmName" value="test/client" />
		<property name="typeName" value="Basic" />
	</bean>

	<bean id="oauthAccessDeniedHandler"
		class="org.springframework.security.oauth2.provider.error.OAuth2AccessDeniedHandler" />

	<bean id="clientCredentialsTokenEndpointFilter"
		class="org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter">
		<property name="authenticationManager" ref="clientAuthenticationManager" />
	</bean>

	<bean id="accessDecisionManager" class="org.springframework.security.access.vote.UnanimousBased"
		xmlns="http://www.springframework.org/schema/beans">
		<constructor-arg>
			<list>
				<bean class="org.springframework.security.oauth2.provider.vote.ScopeVoter" />
				<bean class="org.springframework.security.access.vote.RoleVoter" />
				<bean class="org.springframework.security.access.vote.AuthenticatedVoter" />
			</list>
		</constructor-arg>
	</bean>

	<authentication-manager id="clientAuthenticationManager" xmlns="http://www.springframework.org/schema/security">
		<authentication-provider user-service-ref="clientDetailsUserService" />
	</authentication-manager>


	
	<authentication-manager alias="authenticationManager" xmlns="http://www.springframework.org/schema/security">
		<authentication-provider>
			<user-service>
				<user name="test" password="test" authorities="ROLE_APP" />
			</user-service>
		</authentication-provider>
	</authentication-manager>

	<bean id="clientDetailsUserService"
		class="org.springframework.security.oauth2.provider.client.ClientDetailsUserDetailsService">
		<constructor-arg ref="clientDetails" />
	</bean>


	
	
	
		
	
	<bean id="tokenStore" class="org.springframework.security.oauth2.provider.token.store.InMemoryTokenStore" />

	
	<bean id="tokenServices" class="org.springframework.security.oauth2.provider.token.DefaultTokenServices">
		<property name="tokenStore" ref="tokenStore" />
		<property name="supportRefreshToken" value="true" />
		<property name="accessTokenValiditySeconds" value="120" />
		<property name="clientDetailsService" ref="clientDetails" />
	</bean>
	
	

	
	
	
	
	
	<bean id="userApprovalHandler"
		class="org.springframework.security.oauth2.provider.approval.TokenStoreUserApprovalHandler">
		<property name="tokenServices" ref="tokenServices" />
	</bean>
	

	<oauth:authorization-server
		client-details-service-ref="clientDetails" 
		token-services-ref="tokenServices"
		user-approval-handler-ref="userApprovalHandler">
		<oauth:authorization-code />
		<oauth:implicit />
		<oauth:refresh-token />
		<oauth:client-credentials />
		<oauth:password />
	</oauth:authorization-server>

	<oauth:resource-server id="resourceServerFilter"
		resource-id="test" 
		token-services-ref="tokenServices" />

	<oauth:client-details-service id="clientDetails">
		
		<oauth:client client-id="restapp"
			authorized-grant-types="authorization_code,client_credentials"
			authorities="ROLE_APP" 
			scope="read,write,trust" 
			secret="secret" />

		<oauth:client client-id="restapp"
			authorized-grant-types="password,authorization_code,refresh_token,implicit"
			secret="restapp" 
			authorities="ROLE_APP" />
	</oauth:client-details-service>
	
	

	<sec:global-method-security pre-post-annotations="enabled" proxy-target-class="true">
		<sec:expression-handler ref="oauthExpressionHandler" />
	</sec:global-method-security>

	<oauth:expression-handler id="oauthExpressionHandler" />
	
	<oauth:web-expression-handler id="oauthWebExpressionHandler" />
	
</beans>
_____________________
The error I'm getting is:-
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userApprovalHandler' defined in ServletContext resource [/WEB-INF/spring-security.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'tokenServices' of bean class [org.springframework.security.oauth2.provider.approval.TokenStoreUserApprovalHandler]: Bean property 'tokenServices' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1494)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:706)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)

Can anyone please help?

**Comment by dsyer** [comment]
Did you look at the `TokenStoreUserApprovalHandler`? It has no property called "tokenServices" (just as it says in the error). Perhaps you meant to inject a `TokenStore`?

If you go to Stackoverflow and search for similar errors in questions tagged "spring" I'm sure you will find a wealth of information to help you get started using Spring.

**Comment by pashtika** [comment]
Thanks for reply, I did lots of searching on google but xml configurations are not present for <spring-security-oauth2-version>2.0.6.RELEASE</spring-security-oauth2-version> family and its only present for <spring-security-oauth2-version>1.0.5.RELEASE</spring-security-oauth2-version> and it's working fine.

If you look at the xml file which I've pasted it has entry for TokenStore

<bean id="tokenStore" class="org.springframework.security.oauth2.provider.token.store.InMemoryTokenStore" />

Spring xml file showing error:
Multiple annotations found at this line:
	- No setter found for property 'tokenServices' in class 'org.springframework.security.oauth2.provider.approval.TokenStoreUserApprovalHandler' [config set: mp-oauth2rest/web-
	 context]
	- No setter found for property 'tokenServices' in class 'org.springframework.security.oauth2.provider.approval.TokenStoreUserApprovalHandler'
