### ISSUE TITLE
RemoteTokenServices should publish an event when check_token returns invalid_token

### ISSUE THREAD

**Issue by theonlyguills** [spring-projects/spring-security-oauth#393]
I'm looking for the proper mechanism to audit web services that get called with invalid tokens, IP of the caller, etc.

I was thinking RemoteTokenServices could publish an event when that happens, or any other way that I might be missing right now.

If that's a new feature, I don't mind working on it, if you agree it's the right way to proceed.

**Comment by sourcekick** [comment]
Audit Logging is also an important aspect in our application for security and revision reasons.

I customized quite a few of the classes of Spring Security OAuth2 to add log statements, some of them via copy&own, regarding access tokens and refresh tokens. Naturally I also have log statements in application-specific classes such as AuthenticationManager(s) for the same reasons. A default way to go, out-of-the-box, would be nice.

**Comment by dsyer** [comment]
I haven't tried this in detail, but the standard `AuthorizationFailureEvent` (from Spring Security) should contain all that information. If it doesn't we can probably make sure it does without changing the way the `RemoteTokenServices` works (that seems orthogonal to me).

**Comment by theonlyguills** [comment]
Hi

Maybe I'm missing a configuration but I'm not getting any application events when check_token returns invalid token. I stepped through the code and I can see a debug line being printed and the code that reports the error back in the response... but I fail to see where the event would be generated.

That event would definitely solve my problem.

Thanks for the help with this issue.

**Comment by dsyer** [comment]
No, you're not missing anything. You only get `AuthorizationFailureEvent` from access denied decisions (e.g. insufficient scope). The events you are talking about are authentication errors, and neither the `OAuth2AuthenticationProcessingFilter` nor the `OAuth2AuthenticationManager` hooks into the standard event publisher in the `ProviderManager`. We can add it though.
