### ISSUE TITLE
Where do I report issues with the tutorial?

### ISSUE THREAD

**Issue by lvonk** [spring-projects/spring-security-oauth#395]
I am following the [spring-security-oauth tutorial](http://projects.spring.io/spring-security-oauth/docs/tutorial.html) and came across some issues like incorrect instructions, broken links. Is this the place to post them? If so would you like me to raise them as individual issues, or separate? Or are the docs in github somewhere so I can make a PR?

**Comment by dsyer** [comment]
The docs are in github (so this is the right place to send a pull request): https://github.com/spring-projects/spring-security-oauth/blob/master/docs/tutorial.md
