### ISSUE TITLE
Transaction in DefaultTokenServices

### ISSUE THREAD

**Issue by peruzzo** [spring-projects/spring-security-oauth#399]
In class DefaultTokenServices  the method loadAuthentication removes the token when it has expired, but the line below the InvalidTokenException exception is thrown and it only rollback the transaction.

Should have something @Transaction(noRollbackFor=InvalidTokenException.class) in this method or in the class because the same bug for example happens in other methods as refreshAccessToken.

**Comment by dsyer** [comment]
I think it's possible that only the `createAccessToken()` method needs to be `@Transactional`.

**Comment by peruzzo** [comment]
@dsyer  I believe that other methods also need to be @Transaction, but persistence in jdbc only occur when the connection has autoCommit = true or @Transaction is placed in JdbcTokenStore class.

**Comment by dsyer** [comment]
Autocommit is the default in most cases. Why the "but"?

**Comment by peruzzo** [comment]
Is that when autoCommit is false the persistence does not occur in the other methods.

**Comment by dsyer** [comment]
I doubt if autoCommit would ever be false in practice.

**Comment by jirutka** [comment]
> I doubt if autoCommit would ever be false in practice.

I thought that auto-commit should be disabled when using transaction manager (and that one should always use it). Isn’t that true?

**Comment by dsyer** [comment]
Sorry, yes, the auto commit on the connection will be true by default unless you are in a transaction. In other words it's transparent for users anyway.
