### ISSUE TITLE
Upgrade spring-security-jwt to jackson2

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-security-oauth#400]
Is there any reason spring-security-jwt uses 'old' jackson1 dependency?

E.g. Spring Boot uses jackson2 meaning both dependencies are needed in an app.

**Comment by dsyer** [comment]
> Is there any reason spring-security-jwt uses 'old' jackson1 dependency?

It's old.

**Comment by marceloverdijk** [comment]
You mean Spring Security JWT is old?
I think there are indeed newer libraries which can do more :-)

**Comment by dsyer** [comment]
Does it need to do more (that wasn't the issue)?

**Comment by marceloverdijk** [comment]
No you are that's not related to this issue.
What I meant is that there are other JWT libraries around that can do more. Like Auth0's Java-JWT library that can verify a token and return the claims as Map<String, Object> instead of just a JSON string containing the claims.

**Comment by dsyer** [comment]
We don't really need any library to parse the headers. 1.0.3.RELEASE is out now with no dependency on Jackson.
