### ISSUE TITLE
Add ability to check account details during refresh grant

### ISSUE THREAD

**Issue by skampa** [spring-projects/spring-security-oauth#401]
Hi,
I'm using Oauth2 with JWT as Access Token. At the moment I try to find a way to invalidate a “Refresh Token” before it expires. I use a JdbcUserDetailsService with the possibility to enable/disable a user.  Requesting a new Access Token with a disabled user by password grant leads to an error with the message “User is disabled”. So far, so good. Now I would expect that Access Token requests via Refresh Token by users that got disabled during their “session” (maybe because of bad behavior) will also lead to an error, but that is not the case. A disabled user is able to get new tokens as long as the Refresh Token does not expire (and this new Token may also contain a new Refresh Token that is able to create even more Access Tokens and so on). I think even if I delete the user from database it would have no effect because there is no kind of user validation.
My question is, is this kind of validation missing and valid for Refresh Tokens or is my approach wrong?

**Comment by dsyer** [comment]
Good catch. Arguably this should also be a feature of the `DefaultTokenServices` (i.e. you shouldn't have to rely on the `TokenStore` being up to date to decide on whether a user account is still active). I would also like to have been able to do something in an `OAuth2RequestFactory`, but it looks like the user id is not directly available there.

**Comment by skampa** [comment]
I’m glad that I was able to help. 
To fix the “disabled user” problem, I added some additional lines to the `DefaultTokenServices` in `refreshAccessToken(…)`, but unfortunately I used some of my own custom classes, so I can’t deliver my solution to you. 
Anyway there is one more question that I have very similar to the one above. My JWT stores some additional information about the user in it (e.g. e-mail address etc.). These information are added to the Access Token in the `enhance(…)` method of a class that overrides the `JwtAccessTokenConverter`. Here I have an issue similar to the one above. User data that got changed during the “Access Token session” won’t be updated in the JWT, if I use the refresh_token grant, because the user information `authentication.getUserAuthentication().getPrincipal()` comes from the Refresh Tokens content.
So I need two different enhance flows. One for the refresh_token grant that reloads the user data from database and another one for all other grant types using the user data loaded by the `UserDetailsService`. 
My Problem is that I have no information about the current grant type in the `AccessTokenConverter`. I think this information gets lost in `createRefreshedAuthentication(…)` in `DefaultTokenServices`.
At the moment I temporary store the grant type in the additional information of the new created Access Token so I can access it in the enhance flow. But I don’t think that this is the way to go. 
Is there any other way to access the grant type in `AccessTokenConverter` or is reloading user data there (via `UserDetailsService`) placed wrong?

**Comment by dsyer** [comment]
> Anyway there is one more question that I have very similar to the one above.

In general, can you ask questions about usage in Stackoverflow (or create a new issue here if it's not appropriate on SO)?

The grant type is usually available `OAuth2Request.getGrantType()`. If it is getting lost in `createRefreshedAuthentication()` please open a new issue.

> One for the refresh_token grant that reloads the user data from database and another one for all other grant types using the user data loaded by the `UserDetailsService`. 

What's the difference? Isn't the `UserDetailsService` a database?

**Comment by skampa** [comment]
>The grant type is usually available  OAuth2Request.getGrantType() . If it is getting lost in  createRefreshedAuthentication()  please open a new issue.

Done.

>>One for the refresh_token grant that reloads the user data from database and another one for all other grant types using the user data loaded by the  UserDetailsService . 

>What's the difference? Isn't the  UserDetailsService  a database?

The `UserDetailsService` is a database, but the refresh_token grant needs to reload the data from database (to load potential updates) whereas the other grant types already loaded the data from database. So if I don’t check for the grant type, I would end up loading user data twice from database (e.g. for the password grant).

**Comment by dsyer** [comment]
> So if I don’t check for the grant type, I would end up loading user data twice from database (e.g. for the password grant).

So that's just a symptom of you having chosen the `TokenEnhancer` as the place to reload the user details. I still think this issue is worth fixing, but I'm not sure if we had the right hooks for reloading users you would need to do it that way.

**Comment by dsyer** [comment]
Having added this feature for 2.0.7 I remembered what we did in Cloudfoundry (back in 1.0), so you can still do that in 2.0.6 I reckon: use a physical `ApprovalStore` and link it to user account changes (e.g. so all approvals are revoked when an account is disabled).

**Comment by skampa** [comment]
Thanks for providing this information, but the workaround I implemented for 2.0.6 works quite smooth. So I will wait for release 2.0.7 to replace it with your great “AuthenticationManager” solution. But anyway, it’s good to know.

**Comment by dsyer** [comment]
Re-opened because of some issues with Spring Boot (see JDBC integration test project).

**Comment by ArthurasJ** [comment]
Are there any ways to skip this AuthenticationManager check? Maybe it should have an option to turn it off?

**Comment by dsyer** [comment]
Everything is possible, but that sounds like a bad idea, so I wouldn't look too hard for a solution if I were you.

**Comment by ArthurasJ** [comment]
My authentication server uses only external identity providers as in your example [https://github.com/spring-guides/tut-spring-boot-oauth2](url) and issues its own JWT access tokens (using authorization_code flow) that I want to refresh using refresh_token flow - authenticationManager  can't find (and therefore - authenticate) the users that came from external identity providers. I am not sure whether my approach is wrong or I am missing something?

**Comment by dsyer** [comment]
That might be a new feature in the sample. Best not to discuss it here. Why not open a new issue in the tutorial and we can discuss it there until we decide if a new feature is also needed here?

**Comment by meghnamishraa** [comment]
where should we authenticate for refresh token?because I am using customauthentication for generating access token but when I generate access token from refresh token It is saying UserDetailsService is required.So how to write custom authentication for using refresh token ?
