### ISSUE TITLE
Jdbc client details not inserted?

### ISSUE THREAD

**Issue by hanswesterbeek** [spring-projects/spring-security-oauth#407]
I have a pretty simple Authorization Server setup, that uses Jdbc for token and client persistence. At startup, I would like to use this interface to add a couple of clients at startup.

In the sample app, [an in-memory version is used](https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/sparklr/src/main/java/org/springframework/security/oauth/examples/sparklr/config/OAuth2ServerConfig.java#L113), and the API leads me to believe that I can just swap `clients.inMemory()` with `clients.jdbc(dataSource)`, and add clients much in the same way.

So I end up with this:

```java
@Override
  public void configure(ClientDetailsServiceConfigurer configurer) throws Exception {
    configurer.jdbc(dataSource).withClient("foo")
      .secret("secret")
      .authorities("ROLE_TRUSTED_CLIENT");
  }
```

However, my client is not inserted and I can't trace any invocation of the code that should [trigger the insertion of the clients](https://github.com/spring-projects/spring-security-oauth/blob/7c3eafb50f525c5a01745e4d9275fcc4144c4af2/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/builders/JdbcClientDetailsServiceBuilder.java#L57).

What am I doing wrong?

**Comment by dsyer** [comment]
The insert happens here: https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/builders/JdbcClientDetailsServiceBuilder.java#L66. Works for me, so any other data you think of would be good to know.

**Comment by hanswesterbeek** [comment]
Exactly, I spotted that code as well. But like I said, in my setup, it does not get invoked (i've put in a breakpoint).

I will try to isolate...

**Comment by dsyer** [comment]
It should be called the first time it is needed (e.g. if you load a client from the `ClientDetailsService`). See the `@Lazy @Scope(proxyMode=ScopedProxyMode.INTERFACES)` annotations on the `@Bean` definition for `ClientDetailsService` if you want to know how that happens.

**Comment by hanswesterbeek** [comment]
Ah ok, didn't realize there was lazy initializing involved here. 
Thanks!
