### ISSUE TITLE
HTTP requests to the token endpoint other than POST return HTTP 500 instead of HTTP 405

### ISSUE THREAD

**Issue by ccampo133** [spring-projects/spring-security-oauth#408]
As part of Spring Security OAuth2 2.0.6, the token endpoint prohibits all request methods other than POST by default. Any requests other than POST to the token endpoint *should* return an HTTP status 405 "Method Not Allowed". Instead, HTTP 500 "Server Error" is returned.

This "bug" was actually introduced by my pull request (PR #334) to initially limit the token endpoint to POST by default. I'll see if I can create another PR to fix this behavior.

**Comment by dsyer** [comment]
Thanks. That would be great.
