### ISSUE TITLE
The /oauth/confirm_access endpoint response should be styleable/i18n-able

### ISSUE THREAD

**Issue by nucatus** [spring-projects/spring-security-oauth#411]
The /oauth/confirm_access endpoint response is hardcoded in a template in the `org.springframework.security.oauth2.provider.endpoint.WhitelabelApprovalEndpoint` controller. 

There are no hooks provided so this template can be internationalized or styled.

**Comment by dsyer** [comment]
Normally you just provide your own controller to handle that path and you can do whatever you want there. How is that not a "hook"?

**Comment by dsyer** [comment]
Updated docs in 2682654.

**Comment by nucatus** [comment]
That is an intergalactic hook, I have to admit. In the meanwhile, I was able to hack it the same way, but now, thank to you, my hack is valid. Thanks!
