### ISSUE TITLE
Support for additional/custom parameter in the Redirect for Authorization?

### ISSUE THREAD

**Issue by eugenp** [spring-projects/spring-security-oauth#415]
Some non-standard implementations out there - such as the Reddit implementation (https://github.com/reddit/reddit/wiki/OAuth2#authorization) - require additional parameters on the redirect URI for authorization. 
Reddit for instance has a `duration` param that can be set to either `temporary` or `permanent` - for the kind of token. 
So - it would probably be good to have a mechanism in `getRedirectForAuthorization` similar to #123 - but for these parameters as well. 
Does that make sense, or am I missing something? Cheers. 
Eugen.

**Comment by dsyer** [comment]
You might be missing something if I understand correctly, and I already answered your question on stackoverflow. Here's what I said there:

> You can add query parameters to the authorization request using a RequestEnhancer. You can inject one into the AccessTokenProvider and the DefaultRequestEnhancer includes a list of parameters to include (empty by default).

Isn't that what you need?

**Comment by dsyer** [comment]
Duplicate on SO: http://stackoverflow.com/questions/28704247/spring-security-oauth2-with-reddit-how-to-set-duration
