### ISSUE TITLE
Unable to set custom TokenGranter after update to version 2.0.6 from 2.0.3

### ISSUE THREAD

**Issue by sckoh** [spring-projects/spring-security-oauth#422]
I failed to set custom TokenGranter for version >= 2.0.4
It still use the default ResourceOwnerPasswordTokenGranter even I have set my own custom TokenGranter.

I'm able to use my custom TokenGranter in version 2.0.3 by

     @Override
	 	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			endpoints.tokenGranter(tokenGranter);
		}

**Comment by dsyer** [comment]
Works for me (see the test in that last commit). Can you provide a minimal sample project?

**Comment by coco1979ka** [comment]
With the update to 2.0.7 I have the same problem. After registering my custom granter, the ClientDetailService is overridden and I cannot use any other grant. I get: error="invalid_client", error_description="Bad client credentials". In previous versions I could manage this by adding clientService manually to endpoints. But with 2.0.5 something has changed, so it does not work anymore.

I think the AuthorizationEndpointsConfigurer should have a method to simply add a custom granter (without overriding the default granters).
