### ISSUE TITLE
Check token endpoint: response format inconsistent between password and client credentials grants.

### ISSUE THREAD

**Issue by chornyi** [spring-projects/spring-security-oauth#424]
The `DefaultAccessTokenConverter` serializes authorities differently for client credential and password access tokens.

Client Credentials:

	{
		"scope" : [
			"DEFAULT"
		],
		"exp" : 1426177086,
		"authorities" : [{
				"authority" : "ROLE_SERVICE"
			}
		],
		"client_id" : "service_1"
	}

Password:

	{
		"exp" : 1425954926,
		"user_name" : "user@example.com",
		"authorities" : [
			"ROLE_USER"
		],
		"client_id" : "client_1",
		"scope" : [
			"DEFAULT"
		]
	}

The source of discrepancy: https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/DefaultAccessTokenConverter.java#L65-L72

I understand that a workaround would be to implement a custom access token converter. However I wonder if this would break things like `RemoteTokenServices`. So before doing a workaround I'd like to check if this is a bug that should be fixed in `spring-security-oauth` instead.

**Comment by dsyer** [comment]
I don't think that can be the source of the discrepancy because it adds a collection of String to the response in both cases. Do you have a custom `UserAuthenticationConverter` and is that what is causing the difference?

**Comment by chornyi** [comment]
Thanks for the response. I do not have a custom `UserAuthenticationConverter`. 

If I follow the code that I referenced, this is how authorities are written for the user ([source](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/DefaultUserAuthenticationConverter.java#L66)):

	if (authentication.getAuthorities() != null && !authentication.getAuthorities().isEmpty()) {
	    response.put(AUTHORITIES, AuthorityUtils.authorityListToSet(authentication.getAuthorities()));
	} 

`authorityListToSet` returns a `Set<String`, hence we get the response:

	"authorities" : [
		"ROLE_USER"
	]

This is how authorities are written for the client ([source](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/token/DefaultAccessTokenConverter.java#L68-L71)): 

	if (clientToken.getAuthorities()!=null && !clientToken.getAuthorities().isEmpty()) {
		response.put(UserAuthenticationConverter.AUTHORITIES, clientToken.getAuthorities());
	}

Where `clientToken.getAuthorities()` returns `Collection<? extends GrantedAuthority>`, which has the sole method `String getAuthority()`, which leads to the following serialization:

	"authorities" : [{
			"authority" : "ROLE_SERVICE"
		}
	]

**Comment by dsyer** [comment]
It looks different in master. Maybe try a snapshot.

**Comment by chornyi** [comment]
Thanks, looks like it was fixed between 2.0.5.RELEASE and 2.0.6.RELEASE.

Is there an easy way to re-enable GET /token (for backwards compatibility with existing clients?)

**Comment by dsyer** [comment]
You can grab the `TokenEndpoint` and add "GET" to its list of allowed methods (they are only checked at runtime).

**Comment by chornyi** [comment]
Thanks, this works:

	@Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints)
	throws Exception {
		endpoints.allowedTokenEndpointRequestMethods(HttpMethod.POST, HttpMethod.GET);
	}

Verified that my problem is fixed.
