### ISSUE TITLE
Spring OAuth2 client_credentials in combination with preauthenticated user

### ISSUE THREAD

**Issue by JohanBas** [spring-projects/spring-security-oauth#425]
My app uses [preauthentication][1] 

I want to consume OAuth2 protected resources using `ClientCredentialsResourceDetails` (signed fetch). 

When using this in combination with an preauthenticated `UserDetails`, spring does not store the OAuth token:

    DEBUG o.s.s.w.a.AnonymousAuthenticationFilter - SecurityContextHolder not populated with anonymous token, as it already contained: 'org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@4662f11e: Principal: User = ***

  [1]: http://docs.spring.io/autorepo/docs/spring-security/4.0.0.M1/apidocs/org/springframework/security/config/annotation/web/configurers/JeeConfigurer.html

**Comment by dsyer** [comment]
Duplicate stackoverflow therad: http://stackoverflow.com/questions/28941692/spring-oauth2-client-credentials-in-combination-with-preauthenticated-user
