### ISSUE TITLE
Jwt AccessTokenConverter Verifier is null on decode

### ISSUE THREAD

**Issue by nandhusriram** [spring-projects/spring-security-oauth#426]
I am running on a version 2.0.6 oauth2 with jwt , with separate auth and resource server , I am getting InvalidTokenException with an error message Cannot convert access token to JSON. If I include the private keystore on the resource server   and set the key pair with private key alias and password , everything works . I really dont want to include private keystore on the resource server .

```
	protected Map<String, Object> decode(String token) {
		try {
			Jwt jwt = JwtHelper.decodeAndVerify(token, verifier);
			String content = jwt.getClaims();
			@SuppressWarnings("unchecked")
			Map<String, Object> map = objectMapper.readValue(content, Map.class);
			if (map.containsKey(EXP) && map.get(EXP) instanceof Integer) {
				Integer intValue = (Integer) map.get(EXP);
				map.put(EXP, new Long(intValue));
			}
			return map;
		}
		catch (Exception e) {
			throw new InvalidTokenException("Cannot convert access token to JSON", e);
		}
	}
```

My jwt client config
-- loading the key factory from private keystore works and setting the key pair , then all good

```
   @Bean
    @Qualifier("jwtAccessTokenConverter")
    protected JwtAccessTokenConverter jwtAccessTokenConverter()
{
        JwtAccessTokenConverter converter =  new JwtAccessTokenConverter();
        KeyStoreKeyFactory keyStoreKeyFactory = new KeyStoreKeyFactory(new ClassPathResource("test.jks"), "assurant".toCharArray()); 
 converter.setKeyPair(keyStoreKeyFactory.getKeyPair("test","testpassword".toCharArray()));

        Resource resource = new ClassPathResource("test.pem");
        String publicKey = null;
        try {
            publicKey = new String(FileCopyUtils.copyToByteArray(resource.getInputStream()));
          
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        converter.setVerifierKey(publicKey);
       
        return converter;
    }
```

Any ideas greatly appreciated .

**Comment by dsyer** [comment]
You don't need a signing key for a resource server. What's the exception?

**Comment by dsyer** [comment]
Are you sure your `JwtAccessTokenConverter` is a  Spring bean? I can see the `@Bean` annotation, but that only works if it is in a `@Configuration` (for instance).

**Comment by nandhusriram** [comment]
That makes sense , I had my code without @Configuration like I mentioned below, didnt work, but when I added  @Autowired JwtAccessTokenConverter jwtAccessTokenConverter;  to the class , it worked .
    

	@Bean
    @Qualifier("tokenStore")
    public TokenStore tokenStore() throws Exception{

        System.out.println("Created JwtTokenStore");
        return new JwtTokenStore(jwtTokenEnhancer());--didn't work
   return new JwtTokenStore(jwtAccessTokenConverter);(worked with autowired)


    }

    @Bean
    @Qualifier("jwtAccessTokenConverter")
    protected JwtAccessTokenConverter jwtTokenEnhancer() throws Exception{

        JwtAccessTokenConverter converter =  new JwtAccessTokenConverter();
        Resource resource = new ClassPathResource("mypublic.pem");
        String publicKey = null;
        try {
            publicKey = new String(FileCopyUtils.copyToByteArray(resource.getInputStream()));
          
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        converter.setVerifierKey(publicKey);
        return converter;
    }

**Comment by nikhilabhiman** [comment]
Hi All, Every now and then I get this issue, as "Cannot convert access token to JSON" . It works in morning / afternoon I start getting this error. I refresh gradle dependencies, sometimes it goes off, again it comes in. There is on-off behavior? What is the root cause for this

**Comment by alexandr-efimov** [comment]
Found the same issue! It is really actual that` jwtAccessTokenConverter.setVerifierKey(); ` doesn't really set verifier that is used in - 
```
JwtAccessTokenConverter
...protected Map<String, Object> decode(String token) {
		try {
			Jwt jwt = JwtHelper.decodeAndVerify(token, verifier);
```

as workaround helped:
` private JwtAccessTokenConverter jwtAccessTokenConverter() {
        JwtAccessTokenConverter jwtAccessTokenConverter = new CustomTokenEnhancer();
        jwtAccessTokenConverter.setSigningKey(jwtSigningKey);
        jwtAccessTokenConverter.setVerifier(new RsaVerifier(jwtPublicKey));
        log.info("Set JWT signing key to: {}", jwtAccessTokenConverter.getKey());

        return jwtAccessTokenConverter;
    }`

**Comment by nikhilabhiman** [comment]
Thanks a ton Alex for response and the help. Helped to fix the issue

**Comment by rpernavas** [comment]
Alex, I'm struggling with the same issue here.  Could you pad out your example code some more so I can see how you fixed the problem?  My issue seems to be that my auth / resource server work perfectly well until I apply SSL to the configuration.  

Then the key verifier gets lost and is no longer an instance of RsaKeyVerifier, which subsequently throws the annoying 'cannot decode JSON' exception.  I've been stuck on this for days now!

Thanks for any feedback!

**Comment by sniederb** [comment]
Had the same issue, the solution seems to be marking the token converter as @Bean. I guess somewhere in the framework a token converter is injected from the context, and created new if none is present.

    @Bean
    public JwtAccessTokenConverter accessTokenConverter() {
    ...
    }

**Comment by acmitch** [comment]
@sniederb @alexandr-efimov There is an interface on the JwtAccessTokenConverter object called ```InitializingBean```. 

```java
public interface InitializingBean {
    void afterPropertiesSet() throws Exception;
}
```

This is likely the magic code being called "somewhere in the framework". If you don't want this to be a ```@Bean``` call the method manually after setup, for example:

```java
private JwtAccessTokenConverter  accessTokenConverter() {
        val converter = new JwtAccessTokenConverter()

        converter.setSigningKey("123")

        converter.afterPropertiesSet()

        return converter
}
```

**Note:** If you trace the code inside the afterPropertiesSet method, you will see it sets the ```verifier``` property.
