### ISSUE TITLE
Image resonse error 

### ISSUE THREAD

**Issue by jacky1122** [spring-projects/spring-security-oauth#427]
I tried the example, but failed. 
The code loaded image from remote succeeded when use `sparklrService.loadSparklrPhoto(id)`, 
but response to the browser in `AbstractMessageConverterMethodProcessor.writeWithMessageConverters(T returnValue, MethodParameter returnType, ServletServerHttpRequest inputMessage, ServletServerHttpResponse outputMessage)`, `selectedMediaType` is "image/vnd.wap.wbmp;q=0.8", 
it got exception in `BufferedImageHttpMessageConverter.write(BufferedImage image, MediaType contentType, HttpOutputMessage outputMessage)`, because it chose `WBMPImageWriter` to write data.

**Comment by jacky1122** [comment]
Add this code in photo(@PathVariable String id, HttpServletRequest request) can resolve the problem. 

HashSet<MediaType> set = new HashSet<MediaType>(); 
		set.add(MediaType.IMAGE_JPEG); 
		request.setAttribute(HandlerMapping.PRODUCIBLE_MEDIA_TYPES_ATTRIBUTE,set);

**Comment by dsyer** [comment]
Sorry, I'm not quite following. Can you provide some detailed steps to reproduce, and maybe refer to the method you want to change with a class name? I'm also not sure if you are talking about sparklr or sparklr2.

**Comment by gadams00** [comment]
I'm getting this error when trying to run tonr2 from samples/oauth2/tonr. Run the sample, log into tonr2 as marissa, click view my sparklr photos, approve the permission requests and hit submit, and you get back a page with 3 image placeholders, but they fail to load. I get the following in the tomcat log for tonr2:

```
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/tonr2] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Only integral single-band bilevel image is supported.] with root cause
java.lang.IllegalArgumentException: Only integral single-band bilevel image is supported.
	at com.sun.imageio.plugins.wbmp.WBMPImageWriter.checkSampleModel(WBMPImageWriter.java:313)
	at com.sun.imageio.plugins.wbmp.WBMPImageWriter.write(WBMPImageWriter.java:171)
	at org.springframework.http.converter.BufferedImageHttpMessageConverter.write(BufferedImageHttpMessageConverter.java:225)
	at org.springframework.http.converter.BufferedImageHttpMessageConverter.write(BufferedImageHttpMessageConverter.java:67)
```

**Comment by dallasvaughan** [comment]
Having this problem as well. Looks like it's using the first media type in the default media type list (which is `image/vnd.wap.wbmp`) and so it attempts in the return handler of the SparklrController.photo method to convert the JPEG to WBMP unsuccessfully.

**Comment by x1wins** [comment]
I have same status. but solved.
thank you @jacky1122

**Comment by dsyer** [comment]
How did you solve it? I opened an issue here: https://jira.spring.io/browse/SPR-10250.

**Comment by rstoyanchev** [comment]
bq. I fixed it using the trick from @jacky1122 (see 49bdbab)

Setting the request attribute merely emulates what the produces condition does, so why not just use the produces condition?
````java
@RequestMapping(path="/sparklr/photos/{id}", produces=MediaType.IMAGE_JPEG)
````
