### ISSUE TITLE
JWT refresh-token contains former base64 encoded refresh-token in JTI

### ISSUE THREAD

**Issue by skampa** [spring-projects/spring-security-oauth#429]
I have an issue using JWT refresh-tokens. As you know, the JWT refresh-token contains two IDs (`jti` and `ati`). Using the “password” grant-type for authorization returns two tokens (access-token and refresh-token). The access-token contains a `jti` and the refresh-token contains another `jti` and an `ati`. Both `jti`’s are strings like `“e2492e9c-ae6e-474c-ba2d-bebd14bb8b4f”` and the `ati` of the refresh-token equals the `jti` of the access-token. Here is everything as it is supposed to be. But if I use the refresh-token grant-type the `jti` of the refresh-token is not a random string anymore, it’s the base64 encoded JWT value of the former refresh-token. I can’t imagine that this is the intended behavior.
Since I don’t use the `jti` in my project, I just recognized this behavior because of a `HeadersTooLargeException`. Using the refresh-token multiple times in a row nests all the encoded former refresh-tokens in the new tokens `jti`. So it grows extremely large and becomes too large for the webresponse. 
The `jti` is set by `refreshTokenInfo.put(TOKEN_ID, encodedRefreshToken.getValue());` in the `enhance(OAuth2AccessToken accessToken, OAuth2Authentication authentication)` method of the `JwtAccessTokenConverter`.

**Comment by fkowal** [comment]
+1 this is a problem for me to

**Comment by rubenski** [comment]
I ran into this problem when I had multiple JwtAccessTokenConverters in the enhancer chain. I haven't investigated very deeply, but after bringing the number of converters down to 1 the problem disappeared.
