### ISSUE TITLE
JWT: Client credentials token authorities lost on conversion from JSON

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth#431]
A client credentials token encodes authorities but these are lost when the `DefaultAccessTokenConverter.extractAuthentication()` is applied to the token claims.

**Comment by ebrigand** [comment]
Still not working...
See: http://stackoverflow.com/questions/30728760/token-authorities-construction-change-between-spring-security-oauth2-2-0-5-relea

**Comment by dsyer** [comment]
I'm not sure what that means. This issue is closed and now you have a new one? Can you open a new issue, please?

**Comment by ebrigand** [comment]
It was just to alert you :) ok I create the bug
