### ISSUE TITLE
Unable to use spring-security-oauth in osgi environment

### ISSUE THREAD

**Issue by enflout** [spring-projects/spring-security-oauth#432]
Is it possible to use spring-security-oauth in osgi environment?
It seems not to be the case, MANIFEST.MF doesn't contain any Bundle-directives so osgi is not supported I guess. May be there are some re-pack for this library? Or I should use other lib? May be some spring-security bundle exports this package? I have searched on 

http://mvnrepository.com/artifact/org.apache.servicemix.bundles

but there are no spring-security-oauth and no repacked security jars.

**Comment by dsyer** [comment]
We don't maintain OSGi metadata for Spring jars any more. If you want to you could create some,  re-bundle the jars and submit them to a public repository yourself (you get your reward in heaven). See the FAQ here: http://ebr.springsource.com/repository/app/faq.
