### ISSUE TITLE
ResourceOwnerPassword grant loses authentication details (like remote IP)

### ISSUE THREAD

**Issue by fkowal** [spring-projects/spring-security-oauth#438]
```
curl -i --basic -u client_id:secret -d 'grant_type=password&username=someuser&password=somepass'  localhost:8080/auth/oauth/token
```

in `TokenEndpoint.getAccessToken` `principal.getDetails()` has remoteIp

but this information is lost by `ResourceOwnerPasswordTokenGranter.getOAuth2Authentication()`
which creates a `UsernamePasswordAuthenticationToken` that is passed to
my custom implementation of `AuthenticationProvider`.

I require access to the incoming requests details (remoteIp for example) during the authentication procedure.

**Comment by dsyer** [comment]
Maybe you just need to use a `TokenEndpointAuthenticationFilter`?

**Comment by dsyer** [comment]
Ping. Did you try that?

**Comment by fkowal** [comment]
I ended up using SecurityContextHolder.getContext().getAuthentication() to get access to the WebAuthenticationDetails
