### ISSUE TITLE
InMemoryTokenStore doesn't remove access token properly

### ISSUE THREAD

**Issue by TimShi** [spring-projects/spring-security-oauth#439]
After calling 

```
//token is the access token generated for clientId = "clientId" and username = "username"
defaultTokenServices.revokeToken(token.getValue());
```

calling

```
tokenStore.findTokensByClientIdAndUserName("clientId", "username")
```

Should return null. But it actually returns the token again.

I think this is caused because In InMemoryTokenStore.storeAccessToken, the userNameToAccessToken is populated by these lines

```
		if (!authentication.isClientOnly()) {
			addToCollection(this.userNameToAccessTokenStore, getApprovalKey(authentication), token);
		}
```

And in InMemoryTokenStore.removeAccessToken, the userNameToAccessTokenStore is cleared by these line:

```
			tokens = this.userNameToAccessTokenStore.get(authentication.getName());
			if (tokens != null) {
				tokens.remove(removed);
			}
```

The key used in these two methods are different. One is clientId plus username, the other is just user name.

Can you confirm that this is a bug? If yes I can create a pull request for this.

**Comment by dsyer** [comment]
Looks like a bug to me. Pull request more than welcome.

**Comment by imp14a** [comment]
Hi! dsyer, I have the same problem trying to remove acces token, I'm seeing that the problem is solved now, did you know when this will be released??
Best regards!

**Comment by dsyer** [comment]
As soon as all the 2.0.8 issues are resolved. Can't say when exactly, sorry. Hopefully soon.
