### ISSUE TITLE
<oauth2:password disabled="false"/> is not work well

### ISSUE THREAD

**Issue by asfeixue** [spring-projects/spring-security-oauth#443]
Hi, I'm use spring-oauth.2.0.7.RELEASE.when I config the security.xml for this:

    <oauth2:authorization-server
            client-details-service-ref="clientDetailsService" token-services-ref="tokenServices"
            user-approval-handler-ref="oauthUserApprovalHandler"/>
        <oauth2:password disabled="false"/>
       <oauth2:custom-grant token-granter-ref="resourceOwnerPasswordTokenGranter" disabled="false"/>
    </oauth2:authorization-server/>

I want disabled default password grant but to use my password grant。
but，when do the xml parser, it is not right.
see this in `AuthorizationServerBeanDefinitionParser`:

```
Element clientPasswordElement = DomUtils.getChildElementByTagName(element, "password");
if (clientPasswordElement != null&& !"true".equalsIgnoreCase(clientPasswordElement.getAttribute("disabled"))) {
```

in `clientPasswordElement.getAttribute("disabled")` is return "", not false. 
so, please help me, how to fix it.thank you .

**Comment by dsyer** [comment]
I'm not sure I follow. If you want to disable the "default password grant" you need `disabled="true"` surely?

**Comment by asfeixue** [comment]
I think we recognize that some deviation, I tried a true & false, but without any effect. I checked the code and found "clientPasswordElement.getAttribute (" disabled ")" is return "", whether it is true or false.

**Comment by dsyer** [comment]
I'm still not clear on the problem. If you explicitly set `disabled="true"` it will disable the password grant. Is that not working for you? You might have to supply a test case because it definitely works for me (and `clientPasswordElement.getAttribute ("disabled")` does not return "").

**Comment by asfeixue** [comment]
Ah, I tried, but whether or not I add password support, or set disable true or false. the password grant is not prohibited out. I want to make the default password grant a modification, but xml configuration does not prohibit the default password grant. Currently I pass code to configure, you can not add a default password grant and put my custom.

**Comment by dsyer** [comment]
Since it works for me we probably can't make progress unless you can supply a test case. Can you manage that (e.g. via a pull request, or inline here if it's simple)?

**Comment by asfeixue** [comment]
my authorization-server set password grant disabled config is:
    <oauth2:authorization-server client-details-service-ref="clientDetailsService" token-services-ref="tokenServices"
                                 user-approval-page="oauth_approval"
                                 error-page="oauth_error">
        <oauth2:authorization-code/>
        <oauth2:implicit/>
        <oauth2:refresh-token/>
        <oauth2:client-credentials/>
        <oauth2:password disabled="true"/>
    </oauth2:authorization-server>

other is:
    <oauth2:authorization-server client-details-service-ref="clientDetailsService" token-services-ref="tokenServices"
                                 user-approval-page="oauth_approval"
                                 error-page="oauth_error">
        <oauth2:authorization-code/>
        <oauth2:implicit/>
        <oauth2:refresh-token/>
        <oauth2:client-credentials/>
    </oauth2:authorization-server>

No matter what I use, they can not give up the default password grant support.Is not I use the wrong?

**Comment by asfeixue** [comment]
my authorization-server set password grant disabled config is:

    <oauth2:authorization-server client-details-service-ref="clientDetailsService" token-services-ref="tokenServices"
                                 user-approval-page="oauth_approval"
                                 error-page="oauth_error">
        <oauth2:authorization-code/>
        <oauth2:implicit/>
        <oauth2:refresh-token/>
        <oauth2:client-credentials/>
        <oauth2:password disabled="true"/>
    </oauth2:authorization-server>

other is:

    <oauth2:authorization-server client-details-service-ref="clientDetailsService" token-services-ref="tokenServices"
                                 user-approval-page="oauth_approval"
                                 error-page="oauth_error">
        <oauth2:authorization-code/>
        <oauth2:implicit/>
        <oauth2:refresh-token/>
        <oauth2:client-credentials/>
    </oauth2:authorization-server>

No matter what I use, they can not give up the default password grant support.Is not I use the wrong?

**Comment by dsyer** [comment]
It works for me either way (e.g. if I modify the "vanilla" XML integration test app the tests fail). Without some actual code demonstrating the problem I can't really help more than that.

**Comment by asfeixue** [comment]
Thank you very much, I've given up oauth2 xml to configure, and encountered this problem, I do not have a backup code.

**Comment by dsyer** [comment]
Why don't you at least try what I did then (modify the code at https://github.com/spring-projects/spring-security-oauth/blob/master/tests/xml/vanilla/src/main/resources/context.xml#L13, run the tests, and verify that password grant is not enabled)? What's a "backup code"?

**Comment by asfeixue** [comment]
I tried, I look for my previous question, you're right.
