### ISSUE TITLE
Any plans to support gradle ?

### ISSUE THREAD

**Issue by whgibbo** [spring-projects/spring-security-oauth#445]
Any plans to include gradle build files?

**Comment by dsyer** [comment]
No. Why?

**Comment by whgibbo** [comment]
Just thought it would be a good addition,  as there seems to be more people moving to it.

**Comment by dsyer** [comment]
I don't care for it personally, and it's a headache to maintain 2 sets of build files. Especially with Groovy scripting now available in Maven.
