### ISSUE TITLE
Authenticate client programmatically

### ISSUE THREAD

**Issue by qinfchen** [spring-projects/spring-security-oauth#447]
Hi, 

We have a legacy client app that does a POST to the /auth/token endpoint to exchange the `auth code` for an `access token` without the authorization header. The TokenEndpoint cannot authenticate the client app without the authorization header, so we need to some how authenticate it using client_id and client_key contained in the query params. 

I tried to do something like below, but the authenticationManager only has the `AnonymousAuthenticationProvider` and fails to authenticate the client. Any help or suggestion on how to authenticate the app client is appreciated.

```
    @Autowired
    private TokenEndpoint tokenEndpoint;

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    ClientDetailsService clientService;

    @RequestMapping(value = "/oauth/token", method=RequestMethod.POST)
    public ResponseEntity<OAuth2AccessToken> postAccessToken(
        Principal principal,
        @RequestParam Map<String, String> parameters) throws HttpRequestMethodNotSupportedException {
            String clientId = parameters.get("client_id");
            String clientSecret = parameters.get("client_secret");
            UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(clientId,
				clientSecret);
            Authentication auth =  authenticationManager.authenticate(token);

            return tokenEndpoint.postAccessToken(auth, parameters);
    }
```

**Comment by dsyer** [comment]
Client authentication from request parameters is supported out of the box (see `AuthorizationServerSecurityConfigurer.allowFormAuthenticationForClients()`). isn't that what you need?

**Comment by qinfchen** [comment]
Yes, that is what I need. Thank you!
