### ISSUE TITLE
Is "spring-security-jwt" vulnerable to this?

### ISSUE THREAD

**Issue by bmcustodio** [spring-projects/spring-security-oauth#448]
Recently, [this](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) has been published. I didn't have enough time yet to check it for myself, but perhaps someone has heard of this and can shed some light as to whether `spring-security-jwt` is vulnerable to this kind of attack?

**Comment by dsyer** [comment]
I don't think Spring OAuth was ever vulnerable to that. There's only one `SignatureVerifier` instance per `JwtAccessTokenConverter` so it's either symmetric or asymmetric, but never "none". I remember patching the ruby library for the UAA though.
