### ISSUE TITLE
Token endpoint prints stacktrace with ERROR level when nonexistent client_id is used

### ISSUE THREAD

**Issue by primIl** [spring-projects/spring-security-oauth#449]
When calling token endpoint with improper input, other than client_id, for example bad grant_type, it properly shows the message with INFO level, without any stack trace:

`$ curl "http://localhost:8090/oauth/token?grant_type=bad&scope=read%20write"`

`INFO 5820 --- [nio-8090-exec-6] o.s.s.o.provider.endpoint.TokenEndpoint  : Handling error: UnsupportedGrantTypeException, Unsupported grant type: bad`

But when putting the bad client id:

`$ curl "http://localhost:8090/oauth/token?grant_type=bad&scope=read%20write&client_id=bad"`

we get an internal error and stacktrace with ERROR log level:

`2015-04-02 11:35:49.373 ERROR 5820 --- [nio-8090-exec-7] p.c.ClientCredentialsTokenEndpointFilter : An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: No client with requested id: aaa_bad
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:110)
etc...`

**Comment by dsyer** [comment]
I can't reproduce your problem. You seem not to have authenticated the requests you are sending so maybe your server isn't secure properly? Can you try with the integration test samples and/or link to a sample project that demonstrates your problem more clearly, please?

**Comment by primIl** [comment]
Here is the the sample project:

    @SpringBootApplication
    @EnableWebSecurity
    @EnableAuthorizationServer
    public class DemoApplication extends WebSecurityConfigurerAdapter  {    
        public static void main(String[] args) {
            SpringApplication.run(DemoApplication.class, args);
        }

      public void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
            .withUser("user").password("password").roles("USER");
      }
      
      protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                   .antMatchers("/oauth/authorize").authenticated().and().httpBasic();
      }
      
      @Bean AuthorizationServerConfigurer ac() {
        return new AuthorizationServerConfigurerAdapter() {
          @Autowired
          AuthenticationManager authenticationManager;
          
          public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
            endpoints.authenticationManager(authenticationManager);
          }
          
          public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
            clients.inMemory()
              .withClient("client1")
                      .authorizedGrantTypes("authorization_code")
                      .scopes("read");
          }
          
          public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
            oauthServer.allowFormAuthenticationForClients();
          }
        };
      }
    }

After getting an authorization code (via `localhost:8080/oauth/authorize?client_id=client1&response_type=code&redirect_uri=localhost`), we call access token endpoint - if we pass the correct client id (and correct code), we get the token as expected:
    
    curl "localhost:8080/oauth/token?grant_type=authorization_code&redirect_uri=localhost&client_id=client1&code=Iq2DR3"
    {"access_token":"214a637f-0368-401e-8885-7d1e9cefb8c8","token_type":"bearer","expires_in":43199,"scope":"read"}

If we pass the incorrect client id, this will cause the exception with stack trace and error level as described before:

    curl "localhost:8080/oauth/token?grant_type=authorization_code&redirect_uri=localhost&client_id=client_bad&code=Iq2DR3"
    {"error":"unauthorized","error_description":"No client with requested id: client_bad"}


So the issue is that the error should not be shown as internal server error, since it is just incorrect client input. Of course this is not a major issue, but it is important for server logs not to have error level messages (with stack traces) for things that are not server errors.

**Comment by dsyer** [comment]
With your little sample app I get a 401 and no exception logged (at INFO or above). The stacktrace you posted initially seems to indicate a problem with the `UserDetailsService` containing the clients. Is it really the same app?

**Comment by primIl** [comment]
It is. However it was using 2.0.2, I tried now with 2.0.7 and it works properly!
