### ISSUE TITLE
Denying access to a resource after successful authentication will give a HTTP 500 status

### ISSUE THREAD

**Issue by nucatus** [spring-projects/spring-security-oauth#456]
If a user will deny a client the access to the protected resource after a successful login,  `UserDeniedAuthorizationException` will be thrown in the client code, resulting in a 500 HTTP response status code being returned instead of a 4xx.

~~This will make the flow skip a custom error handler.~~ The oauth default error handler is not even invoked. In other words, how can these errors, specifically this one, be handled by the client?

**Comment by dsyer** [comment]
You have to handle it in the client. It's an exception thrown by your `OAuth2RestTemplate`. I don't really see why it should be a 4xx (it's just an uncaught exception in the client app).

**Comment by nucatus** [comment]
Yeah. It seems I missed the forest for the trees. Tzz tzz tzz!
