### ISSUE TITLE
Why does AuthorizationServerConfiguration need to be static?

### ISSUE THREAD

**Issue by qinfchen** [spring-projects/spring-security-oauth#468]
I am using the sparklr example to set up my authorization server and resource server and I want to separate them into two separate configuration files. I noticed that AuthorizationServerConfiguration needs to be static in order for the authorization endpoint to get hit. This means I have to create a nested static class like below for the authorization server to work properly. Can someone explain why AuthorizationServerConfiguration needs to be static?
```
@Configuration
public class AuthorizationServerConfigurer {
    @Configuration
    @EnableAuthorizationServer
    private static class AuthorizationServerConfiguration extends AuthorizationServerConfigurerAdapter {
        ...
    }
}
```

**Comment by dsyer** [comment]
It doesn't have to be static if it's not nested. If it is nested it does because it needs a default public  constructor so that a proxy can be created for it in Spring's configuration class processing.

**Comment by qinfchen** [comment]
Sorry, reopening this ticket. If I do something like below, it won't work. 
```
@Configuration
@EnableAuthorizationServer
public class AuthorizationServerConfiguration extends AuthorizationServerConfigurerAdapter {
...
}
```

**Comment by dsyer** [comment]
What do you mean by "it won't work"? I doubt very much if it's the same question.

**Comment by qinfchen** [comment]
If i move the AuthorizationServerConfiguration class out of the AuthorizationServerConfigurer class, the authorization endpoints do not get hit.

**Comment by dsyer** [comment]
Maybe your `AuthorizationServerConfiguration` isn't a Spring bean any more? It rather depends on how you construct your `ApplicationContext`. It isn't enough to just write the code - you have to tell Spring where to find it as well.
