### ISSUE TITLE
Custom ErrorController in ResourceServer returns 500 for unknown resources

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-security-oauth#471]
Hi,

While implementing our own custom error format on the resource server side, we found out that a custom `ErrorController` cannot parse correctly resources not found.
We use spring-security-oauth along with Spring Boot.

To sum up our goal, we wanted to have the same error format for :
 1) Authorization errors (both OAuth and HTTP basic)
 2) Technical errors (uncaught exceptions, 404, etc)
 3) Business errors

We managed to override the various error formats (thanks to [this useful hint](http://stackoverflow.com/a/29525147/2187110) by @dsyer ), the only remaining problem occurs for resource not found (should be 404) : we end up with an HTTP status code 500 + "No message available".

After some debugging, the problem is that our custom ErrorController's `error` method does not receive the same `HttpServletRequest` when "resource not found" occurs :

 * When an internal server error is caught, the request received by the custom ErrorController is an instance of `org.apache.catalina.core.ApplicationHttpRequest`. We can successfully process the error using `DefaultErrorAttributes`, and get an adequate status code.
 * When a request for an unknown resource is handled, the custom ErrorController receives a spring security request wrapper : `HttpServlet3RequestFactory$Servlet3SecurityContextHolderAwareRequestWrapper`, toString -> `SecurityContextHolderAwareRequestWrapper[ FirewalledRequest[ org.apache.catalina.connector.RequestFacade@39f39de4]]`

In the second case, Spring Boot's `DefaultErrorAttributes` do not return anything helpful, and we cannot even parse the status code as the following method returns null :
```java
    // Copied from Spring Boot's default BasicErrorController
    request.getAttribute("javax.servlet.error.status_code"); // null
```

For some strange reason, when we remove our custom ErrorController, Spring Boot's default `BasicErrorController` receives an `ApplicationHttpRequest` for "resource not found", not a weird wrapper.
Our custom ErrorController is basically a copy of the default BasicErrorController that returns a different response entity body.

I hope my description of the issue makes sense.

**Comment by dsyer** [comment]
It makes sense up to a point (I don't understand the behaviour). A sample project would help to debug probably. Also can you open a different issue with Spring Boot (unless you believe it is really something to do with OAuth2)?

**Comment by michaeltecourt** [comment]
I thought about posting the issue on Spring Boot issue tracker but this issue is really specific to [Spring Boot + Spring Security OAuth].
I'll be back Monday (May 18th) to push the code sample.

**Comment by michaeltecourt** [comment]
I'm sorry, while I was extracting the narrowest example possible from our complex setup, it turned out that you were right, this issue is in fact related to Spring Boot. Spring Security only added some confusion, but spring-security-oauth is not involved. It's really simple in the end : registering a custom `ErrorController` leads to HTTP 500 responses for unexisting resources instead of 404.
Created a new issue here : https://github.com/spring-projects/spring-boot/issues/2965
