### ISSUE TITLE
JWT token client authorities are null 

### ISSUE THREAD

**Issue by beku8** [spring-projects/spring-security-oauth#474]
I've a client configured 
```
clients.inMemory()
				.withClient("acme")
				.secret("acmesecret")
				.authorizedGrantTypes( "client_credentials")
				.accessTokenValiditySeconds(tokenValiditySeconds)
				.authorities("ROLE_NATIVE")
				.scopes("openid")
```
If I ```base64 --decode``` the token generated from Authorization server:

```
{"scope":["openid"],"exp":1462604171,"authorities":["ROLE_NATIVE"],"jti":"3a065688-f4a1-4596-ac0d-a785a0fc7678","client_id":"acme"}
```

So apparently, token has authorities set, but when I try to use the expression ```#oauth2.clientHasRole('ROLE_NATIVE')``` would return false, because ```(((OAuth2Authentication) authentication).getOAuth2Request()).getAuthorities()``` is an empty set.

Am I missing something here?

**Comment by beku8** [comment]
Should it be different property than ```authorities``` for the token, because otherwise how does it separate between the user authorities & client authorities?

**Comment by beku8** [comment]
Ok I think I found out why authorities are null, ```DefaultAccessTokenConverter```:
```
public OAuth2Authentication extractAuthentication(Map<String, ?> map) {
// unnecessary parts omitted
// this line is creating oauth2Request with null authorities(3rd parameter).
		OAuth2Request request = new OAuth2Request(parameters, clientId, null, true, scope, resourceIds, null, null, null);
		return new OAuth2Authentication(request, user);
	}
```
I guess I have to override this section if want the client to have authorities, but what is the reason its setting null for the authorities?

**Comment by tlachy** [comment]
Maybe you should see this video https://skillsmatter.com/skillscasts/5398-the-state-of-securing-restful-apis-with-spring#video before deciding for JWT token. In short it says that session is necessary if you want to have secured authentication.

**Comment by dsyer** [comment]
That code looks old to me anyway. What version is it?

**Comment by beku8** [comment]
oauth2 version is 2.0.6.RELEASE which is pulled transparently from spring-cloud 1.0.0.RELEASE. I will try with later version
