### ISSUE TITLE
OAuth2Authentication equals() does not consider authentication details

### ISSUE THREAD

**Issue by pborbas** [spring-projects/spring-security-oauth#478]
Equals only works if we compare the same object reference. The cause of the problem is the OAuth2AuthenticationDetails which does not override equals. When OAuth2Authentication.equals() delegates the call to AbstractAuthenticationToken.equals() and it calls equals on the details attribute Object.equals() gets executed.

This causes a problem with Spring Websocket support when used in long polling mode, since each request is authenticated and a new OAuth2Authentication is created. The Websocket implementation uses a Map<Authentication, Session> to find the Websocket session of the authenticated users. Since equals fails, the session is lost.

**Comment by dsyer** [comment]
I guess that wouldn't be a problem if you used a cookie (which would explain why no-one else had the problem)?

**Comment by pborbas** [comment]
You're right. With cookie there's no problem, but
1. This is still a bug which is easy to fix (I gladly do it)
2. I didn't want to use a cookie to keep authentication stateless. Thats why I use the oauth access token and @EnableResourceServer. Since Spring's Websocket feature also relies on sticky sessions I'll have to go with the cookies :(

**Comment by jmnarloch** [comment]
This also affects the Websocket setup through SockJS with enable ResourceServer. The TransportHandlingSockJsService is comparing the Principal instance, in this case: OAuth2Authentication which fails to details comparision: https://github.com/spring-projects/spring-framework/blob/master/spring-websocket/src/main/java/org/springframework/web/socket/sockjs/transport/TransportHandlingSockJsService.java#L288

**Comment by jmnarloch** [comment]
I downloaded the snapshot for testing, but it does not reflect this additional equals method, you do not have nightly builds? So instead I've build the snapshot from the source and this looks good.

I don't know what are the release plans, so I might be asking for a lot. @dsyer Would you consider releasing maintenance 2.0.8 version? Also the included Redis token store looks promising, I would like to check it out.

**Comment by dsyer** [comment]
I pushed some new snapshots from master manually. The CI build is unreliable and I haven't had time to investigate. 2.0.8 is blocked on a few remaining issues, and no-one else seems to be working on them right now.

**Comment by jmnarloch** [comment]
Cool, thanks!
