### ISSUE TITLE
Auto approval of scopes inconsistency

### ISSUE THREAD

**Issue by oharsta** [spring-projects/spring-security-oauth#479]
When you use the JdbcClientDetailsService to add ClientDetails and you want to auto approve all scopes for a client (e.g. skip the consent page) then you need to add a autoApproveScope collection containing one String "true". See JdbcClientDetailsService#getAutoApproveScopes

The BaseClientDetails#isAutoApprove also uses the String value "true" to determine if all scopes should be auto approved.

However the ApprovalStoreUserApprovalHandler#checkForPreApproval uses the magic String "all" to decide if all scopes should be auto approved. This is inconsistent. It still works if you use an auto approve scope of "true" because ApprovalStoreUserApprovalHandler#checkForPreApproval also calls ClientDetails#isAutoApprove, but then the check for auto approve scope "all" is not needed / confusing. Note that when you use JdbcClientDetailsService to add ClientDetails then the autoapprove scope "all" does not even end up in the database, because it does not match "true"

If this is confirmed as a (very minor) bug I'm more then happy to  create a pull request with the introduction of a static final field that is used by JdbcClientDetailsService, BaseClientDetails and ApprovalStoreUserApprovalHandler to determine if all scopes should be auto approved as opposed to the current implementation where this magic String is inconsistently coded in all three related classes.

**Comment by dsyer** [comment]
I think the auto approve scopes are patterns so "*" probably works in any case. Pull request welcome if you want to standardize on "true" or "all" as well.

**Comment by oharsta** [comment]
https://github.com/spring-projects/spring-security-oauth/pull/482
