### ISSUE TITLE
Allow user to configure secure channels in /token endpoint in a more fine-grained way

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security-oauth#480]
There are some useful coarse-grained features in `AuthorizationServerSecurityConfigurer` but users have to replace the `AuthorizationServerSecurityConfiguration` completely (i.e. not use `@EnabelAuthorizationServer`) if they want to configure secure channels, for instance. It might be that just adding secure channels will be all that is needed.

**Comment by brubin-blurb** [comment]
am I doing something wrong in my usage?  When I call AuthorizationServerSecurityConfigurer.sslOnly() I get an error about not being able to apply the configurer to already built object:

2015-11-17 05:48:48 ERROR [localhost-startStop-1] [DirectJDKLog.java:182] Exception starting filter springSecurityFilterChain
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: Cannot apply org.springframework.security.config.annotation.web.configurers.ChannelSecurityConfigurer@442ceb64 to already built object
