### ISSUE TITLE
Running the client app leads to: java.lang.ClassNotFoundException: demo.Application

### ISSUE THREAD

**Issue by miikeat** [spring-projects/spring-security-oauth#485]
When I try to run the Client app unter ```\tests\annotation\client\``` as described in  ```\tests\annotation\readme.md``` last section, I get the following error message after i try to run the jar
```java.lang.ClassNotFoundException: demo.Application```

**Comment by miikeat** [comment]
Adding the correct start-class property to the pom that overwrites the property form the parent solved the issue.
```XML
    <properties>
        <start-class>client.ClientApplication</start-class>
    </properties>
```

**Comment by dsyer** [comment]
Thanks for the analysis. Fixed.
