### ISSUE TITLE
Reusing test classes

### ISSUE THREAD

**Issue by miguelfgar** [spring-projects/spring-security-oauth#486]
Hi,

Which license do this code has: https://github.com/spring-projects/spring-security-oauth/tree/master/tests/annotation/jdbc ?  Is it Apache 2.0 license also?

I would like to reuse some of the classes Dave uses for the tests in my OSS project, for instance:
HttpTestUtils.java, AbstractImplicitProviderTests.java, AbstractIntegrationTests.java as this makes writing OAuth2 tests much easier. Can I add them to my project?

Thank you,

Miguel

**Comment by dsyer** [comment]
If it's in github it's Apache 2.0.
