### ISSUE TITLE
OAuth2Authentication deserialize error

### ISSUE THREAD

**Issue by yage99** [spring-projects/spring-security-oauth#489]
I tried to use jdbcTokenStore to do the authentication stuff. The problem is when I try to get logged in user information, I got null for all object fields. 

{"id":null,"name":null,"login":null,"password":null,"status":null

I tracked back to jdbcTokenStore and found the Oauth2Authentication object can't be deserialized correctly. I think it may be an issue since the OAuth2AccessToken object is successfully been deserialized.

I use mysql as database token store. The oauth_access_token table does have my credential records.

**Comment by dsyer** [comment]
Why is it not deserializable? Are you using a token store with objects from an old version of Spring OAuth or something?

**Comment by yage99** [comment]
Sorry for this wrong report. I have tested the deserialize method manually. There is no problem with it.

-----Original Message-----
