### ISSUE TITLE
Multiple Redirect URIs?

### ISSUE THREAD

**Issue by bjfish** [spring-projects/spring-security-oauth#493]
Can multiple redirect URIs be specified for a single client?

**Comment by dsyer** [comment]
Yes. See `ClientDetails.getRegisteredRedirectUri()` on the server. On the client it only makes sense to have one really (or one per request anyway).

**Comment by jameskhedley** [comment]
Sorry to bump a dead question, but what is the intention of having multiple redirect URIs? As far as I can see the behaviour is not defined to which of the URIs will be used. Does it try each one, or preflight them? 

If I want to support multiple domains, do I need to create a custom RedirectStrategy? Or is the default one smart enough to always redirect back to the requesting host?
