### ISSUE TITLE
JwtAccessTokenConverter class implementation scalability constrains

### ISSUE THREAD

**Issue by isalgado** [spring-projects/spring-security-oauth#495]
In the current implementation a random verification key is created for each application instance.

private String verifierKey = new RandomValueStringGenerator().generate();

So, from my understanding, this limits the scalability capacity that using JWT provides since an access token valid in one application instance is not valid in another. Another mechanism might be used, based on the certificate in order to have the same verifier in all the app instances.

**Comment by dsyer** [comment]
That's just the default value (so that something works out of the box). Of course in a real app you would set the key to something from a persistent store (there's a setter for the key as a `String` or as a `KeyPair`).
