### ISSUE TITLE
Accessing resource with expired bearer token sometimes throws exceptions and/or returns different response

### ISSUE THREAD

**Issue by saintcoder** [spring-projects/spring-security-oauth#505]
The issue is fully described at stackoverflow http://stackoverflow.com/questions/30735890/accessing-resource-with-expired-bearer-token-fails-with-500-http-code

Let me know if I need copy all those details here.

**Comment by dsyer** [comment]
My comment on SO: 

> The error is coming from UserInfoTokenServices in Spring Cloud. I suggest you raise an issue there. Spring Boot 1.3 has those features too if you want to anticipate the future a bit (i.e. Spring Cloud will be removing it at some point).
