### ISSUE TITLE
Add additional information in JWT to request header

### ISSUE THREAD

**Issue by ffazil** [spring-projects/spring-security-oauth#510]
In a resource server, how do I extract additional information in JWT and add it to request header so that I can inject the value in the controller method. 

    public Organization findAll(@RequestHeader("tenantId") String tenantId){
        findOrganizationsForTenant(tenantId); 
    }

At the moment I have to fetch the tenant ID in every controller by fetching the `SecurityContext`. 

    protected Map<String, Object> getTenantInformation(){
        OAuth2Authentication authentication = (OAuth2Authentication) SecurityContextHolder.getContext().getAuthentication();
        OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) authentication.getDetails();
        return tokenStore.readAccessToken(details.getTokenValue()).getAdditionalInformation();
    }

Any ideas?

**Comment by mailuser41** [comment]
Override the enhance JwtAccessTokenConverter and add the additional information.

@Override
	public OAuth2AccessToken enhance(OAuth2AccessToken accessToken,
			OAuth2Authentication authentication) {
		OAuth2AccessToken enhancedToken = super.enhance(accessToken,
				authentication);
		User user = (User) authentication.getUserAuthentication()
				.getPrincipal();
		enhancedToken.getAdditionalInformation().put("username",
				user.getUsername());
		enhancedToken.getAdditionalInformation().put("userId", user.getId());
		return enhancedToken;
	}

**Comment by Chumper** [comment]
That does not solve the question, the question is how to do this on the resource server side.
To enhance the token with additional properties on the authorization side is not hard, just as you said override the token enhancer.

But on the ResourceServer or the SSo Side there is currently no way to extract this additional information. 
If you use `@EnableOAuth2Sso` there is no way as everything will be autoconfigured.
If you use `@EnableResourceServer` you can try to override the token converter with `ResourceServerConfigurer` but that did not work out.

Is there any easy way to extract the additional information?

**Comment by Chumper** [comment]
Ok, i found a way to override the extraction of information for the JWT token:

First create a new class the implements `UserAuthenticationConverter`.
I just copied the `DefaultUserAuthenticationConverter` because i could it not extend it without copying to much code, bceause most members are private instead of protected.

My changed code looks like this:
```java
public Authentication extractAuthentication(Map<String, ?> map) {
        if (map.containsKey(USERNAME)) {
            Object principal = map.get(USERNAME);
            String accountId = map.get("accountId");
            Object additionalInformation = map.get("additionalInformation");
            principal = new AuthenticatedCasUser(principal as String, accountId, additionalInformation as Map<String,String>)

            Collection<? extends GrantedAuthority> authorities = getAuthorities(map);
            if (userDetailsService != null) {
                UserDetails user = userDetailsService.loadUserByUsername((String) map.get(USERNAME));
                authorities = user.getAuthorities();
                principal = user;
            }
            return new UsernamePasswordAuthenticationToken(principal, "N/A", authorities);
        }
        return null;
    }
```
Here i also check for `accountId` and `additionalInformation` and wrap that in an custom `AuthenticatedCasUser`:
```java
@Immutable
class AuthenticatedCasUser {
    String userName
    String accountId
    Map<String, String> additionalInformation
}
```
Finally add a new configuration file:
```java 
@Slf4j
@Configuration
@EnableOAuth2Sso
class SsoConfig implements JwtAccessTokenConverterConfigurer {

    @Override
    void configure(JwtAccessTokenConverter converter) {
        def c = new DefaultAccessTokenConverter()
        c.setUserTokenConverter(new CustomUserAuthenticationConverter())
        converter.setAccessTokenConverter(c)
    }
}
```

implement `JwtAccessTokenConverterConfigurer` so you can enhance the token converter.
So now i can access the information, as the `AuthenticatedCasUser` is my principal.

**Comment by Bessonov** [comment]
@Chumper thank you for provided workaround! But I can't inject AuthenticatedCasUser as Principal.

@dsyer Please reopen the ticket because the problem isn't solved. Copy&paste classes isn't desired way to work with spring.

**Comment by dsyer** [comment]
> Copy&paste classes isn't desired way to work with spring.

That's just a convenient way to create a custom extension from some existing code. It's totally acceptable IMO, especially for such a small amount of code. I don't know what you mean about the "can't inject" thing. Maybe you should open a new issue?
