### ISSUE TITLE
DefaultTokenServices fail to store enhanced refresh token when refreshAccessToken method is invoked.

### ISSUE THREAD

**Issue by marcolenzo** [spring-projects/spring-security-oauth#511]
In contrast to the `createAccessToken` method where the enhanced version of the refresh token is saved, the `refreshAccessToken` method saves the refresh token without enhancements.

I believe the behaviour should be something on these lines:

    OAuth2AccessToken accessToken = createAccessToken(authentication, refreshToken);
		tokenStore.storeAccessToken(accessToken, authentication);
		// In case it was modified
		refreshToken = accessToken.getRefreshToken();
		if (refreshToken != null) {
			tokenStore.storeRefreshToken(refreshToken, authentication);
		}
		return accessToken;

**Comment by Blackbaud-SriniHasti** [comment]
After debugging DefaultTokenServices, we figured we are running into this issue. With TokenEnhancer set, refresh works first time, but fails second time through. Is this fix planned for a release soon ?

**Comment by Blackbaud-SriniHasti** [comment]
Any update on this ?

**Comment by rickykit130** [comment]
I have also encountered this problem, I create a class extended the DefaultTokenServices and modify as __marcolenzo__ said, it works now. Hope the code can be updated as soon as possible.

**Comment by marcolenzo** [comment]
I thought it was fixed in later versions. I'll have a check this weekend and make a PR eventually.

**Comment by jgrandja** [comment]
Thanks for reporting this @marcolenzo and I apologize for the wait on this. Our resourcing has been a little tight lately but we are good to go now. I have reviewed your PR, applied some polish to the test and merged to master. Thanks again for your patience.

**Comment by marcolenzo** [comment]
Thanks to you :)
