### ISSUE TITLE
Where is filter bean with ID oauth2ClientContextFilter wired for tests?

### ISSUE THREAD

**Issue by paboulos** [spring-projects/spring-security-oauth#519]
It states in the Spring OAuth developer's guide that the client configuration needs to wire in a filter bean with ID oauth2ClientContextFilter. So why was it not needed in the spring-security-oauth/tests/annotation/client/src/main/java/client/ClientApplication.java?

**Comment by dsyer** [comment]
That client app uses uses Spring Boot. It has a bean of the right type because of the `@EnableOAuth2Client`, and Spring Boot wires it into the container for you.
