### ISSUE TITLE
OAuth2 Schema doesn't work in MySQL

### ISSUE THREAD

**Issue by johnosorio** [spring-projects/spring-security-oauth#528]
Hi, 

I'm trying to work with JdbcTokenStore but that implementation doesn't work with BLOB data types.

Could you give some light?

**Comment by johnosorio** [comment]
Hi,

I'm using org.springframework.boot:1.2.3 and spring-security-oauth2:2.0.7.

Thanks

**Comment by dsyer** [comment]
Note that we don't publish schemas for any database platforms: it's up to users to find the best way to create the DDL. But I'm happy to help you find the best way if you can provide more information. What is it that doesn't work about BLOB types for you?

**Comment by johnosorio** [comment]
Hi dsyer,

After debugging the source code I have discovered that BLOBs weren't the problem, the problem was that I had changed the grant type from "password" to "client_credentials" and the OAuth API can't recover the user name.

Thanks for your answer.
