### ISSUE TITLE
Support Bouncycastle 1.5x

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security-oauth#531]
There are an increasing number of libraries that depend on Bouncycastle 1.5x which, unfortunately, breaks backwards compatibility. Crashub recently made a change to support both 1.47 and 1.5x. It'd be useful if `spring-security-jwt` could do the same as it would reduce the chances of classpath conflicts.

**Comment by jgrandja** [comment]
Thanks for the heads up @vkennke. We're actually on 1.60 now via 5d806e1 so this issue has been invalidated as a result.
