### ISSUE TITLE
Overriding AuthorizationEndpoint

### ISSUE THREAD

**Issue by almalki** [spring-projects/spring-security-oauth#549]
Part of OpenID Connect Session Management spec is to return a new parameter (session_state) as part of the authorization response. To do this we apparently need to override AuthorizationEndpoint bean. This where I am trying to add this param:

https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/AuthorizationEndpoint.java#L350

We are using the oauth:authorization-server XML schema to configure the authorization server. I could not find a way to replace the default AuthorizationEndpoint. Creating a bean with the id oauth2AuthorizationEndpoint did not work and it actually caused to whole authorization endpoint to return HTTP 404. I appreciate any help to resolve this problem.

Thanks.

**Comment by boris8479** [comment]
Not quite clean solution. You can return the session_state by manipulating the redirect URI. I hope this will get prioritized and completed.
