### ISSUE TITLE
What is the license of the sparklr project?

### ISSUE THREAD

**Issue by nakulcg** [spring-projects/spring-security-oauth#550]
I found a license file in the webapp directory of the sparklr project.  Link - https://github.com/spring-projects/spring-security-oauth/blob/master/samples/oauth2/sparklr/src/main/webapp/LICENSE.txt

Does this mean sparklr project is under CC-SA license or just the web forms are under that license? Is the java config part under Apache 2.0 license?

Also I m not entirely sure about the license, the above linked license file is indeed CC-SA, right? And it also means that any derivative products should be also CC-SA?

**Comment by dsyer** [comment]
That file has been there since the year dot, and I'm pretty sure it's an error (everything in this project is Apache 2.0, just like any other Spring project). I'm going to just remove that file and see if anyone squawks.
