### ISSUE TITLE
First class support for issuer claim

### ISSUE THREAD

**Issue by william-tran** [spring-projects/spring-security-oauth#553]
This issuer claim (iss in a JWT) is optional in the [JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.1) and required for ID Tokens in the [OpenID Connect spec](http://openid.net/specs/openid-connect-core-1_0.html#IDToken). As a developer, I should be able to set a property for what the expected value is, and if the property is set, access tokens will be validated to ensure they contain this claim value, similar to how resourceId is used to validate the aud claim.

**Comment by eschizoid** [comment]
@willtran- You are completely right, that is one of the main reason I was not able to use the OOF provided by `org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter`

**Comment by willtran-** [comment]
My approach is to override the ResourceServerTokenServices created by Spring Cloud Security but centralizing this behaviour in another @Configuration that can be pulled in by multiple projects is difficult due to https://github.com/spring-cloud/spring-cloud-security/blob/1.0.2.RELEASE/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L256

There's an ```@ConditionalOnMissingBean(ResourceServerTokenServices.class)``` but this only works if my configuration is parsed before this one, and guaranteeing this is tough because ResourceServerTokenServicesConfiguration is not an auto-configured configuration.

**Comment by willtran-** [comment]
I ended up using a ```JwtAccessTokenConverterConfigurer``` which can replace the ```DefaultAccessTokenConverter``` that ```JwtAccessTokenConverter``` uses, which gets called [here](https://github.com/spring-cloud/spring-cloud-security/blob/1.0.2.RELEASE/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/resource/ResourceServerTokenServicesConfiguration.java#L296-L298)

```
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.security.oauth2.resource.JwtAccessTokenConverterConfigurer;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.oauth2.common.exceptions.InvalidTokenException;
import org.springframework.security.oauth2.provider.OAuth2Authentication;
import org.springframework.security.oauth2.provider.token.DefaultAccessTokenConverter;
import org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter;

@Configuration
public class IssuerValidationAccessTokenConverterConfigurer implements JwtAccessTokenConverterConfigurer {

	@Value("${spring.oauth2.resource.issuer}")
	private String issuer;

	@Override
	public void configure(JwtAccessTokenConverter converter) {
		converter.setAccessTokenConverter(new DefaultAccessTokenConverter() {
			@Override
			public OAuth2Authentication extractAuthentication(Map<String, ?> map) {
				Object issuerClaim = map.get("iss");
				if (issuerClaim == null) {
					throw new InvalidTokenException("token does not contain issuer (iss) claim");
				} else if (!issuer.equals(issuerClaim)) {
					throw new InvalidTokenException("invalid issuer");
				}
				return super.extractAuthentication(map);
			}
		});
	}
}

```
AccessTokenConverter.extractAuthentication(Map<String, ?> map) does't explicitly throw exceptions as part of its contract but this seems to have the desired result of a 401 response. Sorry, maybe this issue belongs in spring-cloud-security.

**Comment by ilipkind** [comment]
This is pretty bad that issuer is not validated and we only rely on signing key validation. Signing keys sharing can be disastrous then. Looks like this already opened for 2 years. 👎

**Comment by jgrandja** [comment]
Hi @ilipkind, in case you are not aware, the `iss` claim is optional and processing/validation of it is application specific.

As per spec, in section [4.1.1.  "iss" (Issuer) Claim](https://tools.ietf.org/html/rfc7519#section-4.1.1)

> The "iss" (issuer) claim identifies the principal that issued the
>    JWT.  The processing of this claim is generally application specific.
>    The "iss" value is a case-sensitive string containing a StringOrURI
>    value.  Use of this claim is OPTIONAL.
> 

The OpenID Connect Core 1.0 specification requires the `iss` claim in the ID Token and UserInfo response, however, the framework _does not_ have built-in support for OIDC. It only implements the standard OAuth 2.0 Authorization Framework.

That being said, we are adding the capability for the user to provide their own implementation of a _"Claims Verifier"_. This [PR](https://github.com/spring-projects/spring-security-oauth/pull/1114) contains this new feature and will soon be merged to master.

**Comment by jgrandja** [comment]
Duplicate of #1114
