### ISSUE TITLE
Authorization header contains lowercase bearer authorization scheme

### ISSUE THREAD

**Issue by vandepitte** [spring-projects/spring-security-oauth#558]
As https://tools.ietf.org/html/rfc6750#section-2.1 states,

Clients SHOULD make authenticated requests with a bearer token using
the "Authorization" request header field with the "Bearer" HTTP
authorization scheme.

Unfortunately, DefaultOAuth2AccessToken lowercases the Bearer authorization scheme ( BEARER_TYPE.toLowerCase())
This causes the OAuth2RestTemplate to insert an authorization header with lowercase bearer authorization scheme. Some server implementations fail on the lowercase bearer authorization scheme

**Comment by dsyer** [comment]
If the server sends "Bearer" in it's access token response then Spring OAuth will honour that I believe. This seems like a duplicate of #457 in any case.
