### ISSUE TITLE
Redis - make the dependencies optional

### ISSUE THREAD

**Issue by jmnarloch** [spring-projects/spring-security-oauth#561]
I thinks that the https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/pom.xml#L148 redis depedencies should be marked as optional, otherwise the Spring Boot autoconfiguration will catch that and try to initiate the default connection:

```
redis: {
status: "DOWN",
error: "org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool"
},
```

**Comment by dsyer** [comment]
Fixed in #562
