### ISSUE TITLE
ResourceServer security does not work with Spring MVC security

### ISSUE THREAD

**Issue by maxiwu** [spring-projects/spring-security-oauth#565]
detail reference http://stackoverflow.com/questions/32264605/spring-http-security-stop-working-after-adding-oauth2

I am trying to build a project with minimum function, a mvc web application with oauth2. Some view/rest service is protected by mvc security. and some resource like "/photos" protected by oauth2, just like sparklr2 example.

When I turn off oauth2 (removing oauth classes), my mvc security works as expected. if I enable oauth2, it takes control of the filter and my mvc security act as it wasn't there, no protection to my view/rest services. If I add Order(1) to mvc security, it works, but then my resources becomes unprotected, like oauth2 wasn't there.

I've tested this by adding a new .jsp to sparklr2 example, and it is not protected by spring security too, even if the setting is there.

Is there something wrong with oauth and spring security work together?

**Comment by maxiwu** [comment]
more test result.

oauth security is at order 3. I tried both mvc security order <3 and >3, the tomcat log reveal some information.

case 1, order <3
the filter FilterSecurityInterceptor will match the request with mvc security, which will find a match, for exmaple /home, and redirect me to login page.
14:37:34.441 [http-nio-8080-exec-4] DEBUG o.s.security.web.FilterChainProxy - /home at position 13 of 13 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
14:37:34.442 [http-nio-8080-exec-4] DEBUG o.s.s.w.u.m.AntPathRequestMatcher - Checking match of request : '/home'; against '/home'

case 2 order >3
the filter FilterSecurityInterceptor will match the request against oauth, like /photos, /me, but will not found any match, then the request reach the end of chain. this request is response as if there is no security filter, since it does not find any match.
14:32:51.635 [http-nio-8080-exec-5] DEBUG o.s.security.web.FilterChainProxy - /home reached end of additional filter chain; proceeding with original chain
14:32:52.458 [http-nio-8080-exec-5] DEBUG o.s.web.servlet.DispatcherServlet - DispatcherServlet with name 'dispatcher' processing GET request for [/Dragonfly/home]
14:32:52.458 [http-nio-8080-exec-5] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Looking up handler method for path /home
14:32:52.458 [http-nio-8080-exec-5] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Returning handler method [public java.lang.String com.umedia.Dragonfly.controller.HomeController.home()]
14:32:52.458 [http-nio-8080-exec-5] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'homeController'

so, the order does not prevent these two to over write each other in FilterSecurityInterceptor. but why?

**Comment by dsyer** [comment]
There's nothing special about OAuth2. It's just another part of Spring Security really. I suggest you read the Spring Security docs really carefully and look at everything to do with request matching and filter chains. It's really just going to be about your configuration.

**Comment by maxiwu** [comment]
thank you dsyer. I am reading spring security docs really carefully right now. 
my configuration is just like sparklr2, the only difference is my mvc url instead of sparklr2 /xxx.jsp.
I have tested this in sparklr2, the page which I created (e.g. home.jsp) is not protected too, same result. I have added the rule http.authorizeRequests().antMatchres("/home.jsp").authenticated() concat to antMatchers("/login.jsp").permitAll().

my library version
spring core 4.1.7 (from spring boot web starter)
spring security config, core 4.0.1
spring security oauth2 2.0.7
java 1.8
tomcat v8.0

**Comment by maxiwu** [comment]
Sorry Dave, it is my fault.
the problem is caused by my project setting, I am packaging it as a jar, but I should use war instead.
and my web content path is not correct, it should be /src/main/webapp, not /WebContent.

**Comment by maxiwu** [comment]
it is a configuration problem, but I still could not figure out why.
java 1.7 + maven tomcat7:run -> works fine
java 1.8 + eclipse debug on server -> fail

the problem could be caused by either java 1.8 or eclipse plugin (WTP, M2Eclipse, maybe)
