### ISSUE TITLE
Inconsistent ids being generated by DefaultAuthenticationKeyGenerator

### ISSUE THREAD

**Issue by alvinpb** [spring-projects/spring-security-oauth#569]
There is a bug on line 49 in org.springframework.security.oauth2.provider.token.DefaultAuthenticationKeyGenerator

```
values.put(SCOPE, OAuth2Utils.formatParameterList(authorizationRequest.getScope()));
```

authorizationRequest.getScope() returns a Set<String>. This can (and likely) will be an un-ordered set of strings. Calling this multiple times can therefore return different values for the same set of scopes. This causes issues further down-stream where the same authentication can be given different ids.

The fix for this is to sort the scopes being fed into OAuth2Utils.formatParameterList.

e.g.
```
List<String> scopesList = new ArrayList<>();
scopesList.addAll(authorizationRequest.getScope());
Collections.sort(scopesList);			
values.put(SCOPE, OAuth2Utils.formatParameterList(scopesList));
```

**Comment by dsyer** [comment]
Agree there's probably a bug. It's low impact because the `AuthorizationRequest` actually sorts the scopes in the `setScope()` method, so mostly you will find they are sorted already.

**Comment by jgrandja** [comment]
Hi @alvinpb, I have looked into this and as @dsyer has mentioned, the scopes are sorted in the `AuthorizationRequest.setScope()` method (which delegates to `super.setScope()` of `BaseRequest`). The scopes will be _naturally ordered_ (upon construction) using a `TreeSet` and will always preserve that same order when calling `AuthorizationRequest.getScope()`.

I don't see a bug here so I'm going to close this issue. However, if you can provide a test reproducing the issue you are having than please re-open this issue and I will look into this further.

Also, you may want to look at our existing test for scope ordering at `AuthorizationRequestTests.testScopeSortedOrder`.

**Comment by alvinpb** [comment]
The issue came about when I was testing OAuth which Serializes/Deserializes the Authentation object. I have written a json serializer/deserializer which did this but then found that there were issues with scope  because it was always generating new keys.

Looking at BaseRequest - it looks to be using LinkedHashSet which would AFAIK use the original order of the collection being passed in - which is indeterminate.

**Comment by jgrandja** [comment]
@alvinpb If you're able to reproduce this issue with a test that you can provide me that would be very helpful.
