### ISSUE TITLE
Revoke tokens in Redis Token Store

### ISSUE THREAD

**Issue by coco1979ka** [spring-projects/spring-security-oauth#572]
I'm using the Redis Token Store from 2.0.8 SNAPSHOT and there seems to be some inconsistency when revoking access tokens:

When I use the removeAccessToken method, I can see in my Redis Store, that the token has been deleted. But if I query for all tokens by its client_id (findTokensByClientId) I still get the revoked token in the result set. Investigating further I still see the keys client_id_to_access and name_to_access in the Redis store. They only get removed, when the token (which has been revoked before) expires.

It's not a major bug, because I can't access protected resources after revoking the token, but still it is a little bit confusing that the token is still listed when I search for it by its clientId.

**Comment by coco1979ka** [comment]
Second problem: REFRESH_AUTH keys are never deleted.

**Comment by coco1979ka** [comment]
Further investigation: The REFRESH_AUTH keys are deleted, when the refresh token is expired. It's the same behavior as the access tokens auth. So with a correct configuration of the refresh token validity, the refresh_auth is cleaned up.
But there is still a problem left: If the refresh token is not an expiring refresh token, and the user revokes access, the REFRESH_AUTH key stays in the Redis store forever.

**Comment by alchemistgo87** [comment]
Hi @coco1979ka, did you find any solution to this problem?

**Comment by coco1979ka** [comment]
Hi @alchemistgo87 

my only solution at the moment is to use expiring refresh tokens (which is okay in my case). You can configure it in your OAuth Clients config:

    .refreshTokenValiditySeconds(604800) //one week 

Otherwise you have to implement some kind of scheduled TokenCleaner, which can delete REFRESH_AUTH keys if a refresh token does not exist anymore.

Regards

**Comment by alchemistgo87** [comment]
Thank you @coco1979ka 
Let me warn of one more problem with the expiry of auth tokens. You might already have faced this problem: #595

**Comment by jgrandja** [comment]
Hi @coco1979ka. Thanks for the very detailed report. I've resolved the bug related to REFRESH_AUTH never being deleted (when the refresh token in non-expiring).

However, I was not able to reproduce your issue related to `removeAccessToken()` and then fetching it with `findTokensByClientId()`. I've written a test related to your scenario and it passes. Please see `RedisTokenStoreTests.storeAccessTokenWithoutRefreshTokenRemoveAccessTokenVerifyTokenRemoved` AND `RedisTokenStoreMockTests.storeAccessTokenWithoutRefreshTokenRemoveAccessTokenVerifyKeysRemoved`.

If you are able to reproduce this issue with a test that you can provide me I will look into this further. Closing this issue for now but will re-open if you can reproduce it.

**Comment by a8t3r** [comment]
Hi @jgrandja 
I found the same behaviour  with `removeAccessToken()`
Each time re-storing the access token creates a new entry for client_id_to_access list, whereas token deletion removes only a single entry:

```java
DefaultTokenServices.createAccessToken:
// Re-store the access token in case the authentication has changed
tokenStore.storeAccessToken(existingAccessToken, authentication);
```

```java
RedisTokenStore.removeAccessToken:
if (authentication != null) {
...
  conn.lRem(clientId, 1, access);
```

Sorry I can't write a test to proof my assumption
