### ISSUE TITLE
eraseCredentials() in OAuth2Authentication does not erase the credentials stored in the Authentication instance

### ISSUE THREAD

**Issue by octurion** [spring-projects/spring-security-oauth#573]
The behavior of `eraseCredentials()`, which `OAuth2Authentication` inherits from `AbstractAuthenticationToken`, is to only erase the credentials from the principal, the details object and the authentication itself.

As such, because the principal's credentials are also stored in the accompanying `UsernamePasswordAuthenticationToken` in `OAuth2Authentication` (assuming the principal is a user and not a machine), calling `eraseCredentials()` will not erase the credentials from the `Authentication` as well, which forces you to use the following workaround:

```
authentication.eraseCredentials();
if (authentication.getUserAuthentication() instanceof CredentialsContainer) {
    ((CredentialsContainer) authentication.getUserAuthentication()).eraseCredentials();
}
```

**Comment by jgrandja** [comment]
Thanks for the report @octurion. This has been fixed and is now in master.
