### ISSUE TITLE
redirect_uri needs to be url encoded

### ISSUE THREAD

**Issue by mikeroda** [spring-projects/spring-security-oauth#574]
#430 removed the encoding of the redirect_uri parameter. But it has to be encoded, otherwise query parameters in the redirect_uri are seen by the authorization server as query parameters to the authorize endpoint and not part of the redirect_uri, and therefore lost when the authorization server redirects the user agent back to the redirect_uri.

**Comment by jgrandja** [comment]
@mikeroda I've done some investigation here and found that the `redirect-uri` is being url encoded. The `redirect-uri` that is ultimately used when the redirect is performed to the auth server is initially saved at the start of the request in [OAuth2ClientContextFilter](https://github.com/spring-projects/spring-security-oauth/blob/a0e2591163a9c2991648473b8f503dde11fff18c/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/filter/OAuth2ClientContextFilter.java#L57).

Are you able to reproduce this issue with a sample test? If so please provide this to me so I can look into this further. I'll close this for now but will re-open if this issue persists with your use case.

**Comment by mikeroda** [comment]
Yes, thanks. This was happening on an earlier version of spring-security-oauth2 and was fixed I believe.

**Comment by jgrandja** [comment]
Appreciate the update @mikeroda

**Comment by yonchev** [comment]
I still have this problem with latest 2.3.4 release

**Comment by pkrajanand** [comment]
Noticed the same issue with "state" parameter too. "state" parameter contents too not url-encoded.

Send an /oauth/authorize Request with state=4tQ95mcCXWuzKmDwUz/ygzPx798TqfG12CTljHUf%2BrxkSS3fdkGcjuoGgmi81zJJbQS%2By2TaBoeI5

But The Location header of the 302 response after successul login did contain state parameter as follows:-

state=4tQ95mcCXWuzKmDwUz/ygzPx798TqfG12CTljHUf+rxkSS3fdkGcjuoGgmi81zJJbQS+y2TaBoeI5

If you notice, "+" are not encoded, as how I did while sending the request.
