### ISSUE TITLE
Send query string parameters to login.jsp. 

### ISSUE THREAD

**Issue by thor-silver-light** [spring-projects/spring-security-oauth#584]
I am using the aouth 2 link /oauth/authorize  to login and send the token to my application. The problem is that I am not able to send parameters to the login.jsp 
I would like to retrieve the  the client_id or another custom parameter in the login.jsp

For example:
http://localhost:8080/identity-service/oauth/authorize?startPoint=register&response_type=token&client_id=insights-app&redirect_uri=https://myApllication.com

Any help would be appreciated

**Comment by dsyer** [comment]
I'm not really sure what the question is. Can't you redirect to whatever URI you want by changing the `redirect_uri`?
