### ISSUE TITLE
Remaining "code" and "state" parameters in URL

### ISSUE THREAD

**Issue by makkes** [spring-projects/spring-security-oauth#597]
In the Tonr 2 application (that uses the OAuth 2 authorization code flow) I access http://localhost:8080/tonr2/sparklr/photos. I am redirected to Sparklr for authorizing Tonr to access Sparklr resources and am eventually redirected to http://localhost:8080/tonr2/sparklr/photos?code=CODE&state=STATE.

This is a bug IMHO and the user should eventually be redirected to http://localhost:8080/tonr2/sparklr/photos (without code and state parameters) because when he e.g. bookmarks the URI with code/state parameters this may result in errors later on.

**Comment by makkes** [comment]
I believe that there should be an additional 302 redirect to the original URI that the user requested after AuthorizationCodeAccessTokenProvider has obtained the access token from the authorization server.

**Comment by dsyer** [comment]
I guess I see the point here, but there is nothing in the spec that helps us decide what to do. Also AFAIK the URL in question *is* bookmarkable (did you try it?).

**Comment by makkes** [comment]
Actually, the URL is not practically bookmarkable, since the `state` parameter is invalidated (implicitly) as soon as you e.g. restart the application server. In that case, the user sees the `Possible CSRF detected` message, because the server doesn't know the state that was passed via the URL.

Some sites, e.g. https://packagist.org/login/, just redirect the user after the OAuth authorization server sends the user to the redirect URI (with the `code` and `state` parameters) to some URL that doesn't contain those parameters.

RFC 6749 (esp. section 4.1) doesn't mention what to do after the user-agent has been redirected to the client application. I believe, it's totally up to the implementing client what to do next.

**Comment by dsyer** [comment]
Any change has to be implemented on the client app unless I'm missing something, and some users and developers don't like the "flicker" that comes from redirecting, so we'd have to make it optional. I suppose with those constraints maybe the `ClientContextFilter` could be modified to do a redirect after obtaining the token. Would that be the best way? Or maybe a forward would work just as well?

**Comment by makkes** [comment]
When investigating possible places where to implement this, I was a bit confused by the way the preserved state is used in OAuth2ClientContext. Eventually, I added a `throw new UserRedirectRequiredException(...)` at the end of `OAuth2RestTemplate#getAccessToken` (after the catch block, inside the `if (accessToken == null || accessToken.isExpired()) { ... }` block.

The problem is, where do we store the original URL that the user tried to access?

**Comment by dsyer** [comment]
> where do we store the original URL that the user tried to access?

In the `OAuth2ClientContext` (https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/OAuth2ClientContext.java#L45), which is normally in the HTTP session (https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/OAuth2ClientConfiguration.java#L65).

**Comment by makkes** [comment]
As I understand it, `OAuth2ClientContextFilter` cannot simply redirect the user to the original URL since the filter would do this before `OAuth2RestTemplate` had a chance to fetch the `code` and `state` from the URL. Did I get this right?

**Comment by dsyer** [comment]
Correct I think, although the rest template doesn't really need the URL, it only needs the `AccessTokenRequest` to be initialized, which you can achieve by injecting it into the filter and calling a method on it. Maybe something along those lines, with a forward (not a redirect because then you would definitely lose the state) would work?

**Comment by awonline-net** [comment]
Hi, this issue is still open. Is there any chance that Spring will provide a solution in the future, maybe as an option as @dsyer suggested?

**Comment by mmairs9** [comment]
+1 also having the same issue where code=CODE&state=STATE parameters are intermittently flowing through to the client with a 200 status code, instead of resolving to a 302 redirect. This is causing oauth2 authorization flows to not be completed.

**Comment by devajani** [comment]
When refresh token expires for the first time and I click on a request then I can see state and code being appended to the url. When I wait enough for the refresh token to expire for the second time and click on refresh I am redirected to http://localhost:8080/?state=MLw32A&state=7oFEYr&code=JNoIOl.
I have debugged a found that the preservedState was http://localhost:8080/?state=MLw32A (which is not correct). Here MLw32A is state of the old request and thus I get a csf error. Is it an open bug ? Is it a desirable behaviour? Is there a way to modify the preserved state ?

**Comment by eyuel4** [comment]
@devajani Did you find any work around for this? Am getting the same issue.

**Comment by devajani** [comment]
> @devajani Did you find any work around for this? Am getting the same issue.

We solved it by removing the state from the url onload of the page. Sounds like a dirty solution :/ but it was a quick fix.

**Comment by destan** [comment]
> Correct I think, although the rest template doesn't really need the URL, it only needs the `AccessTokenRequest` to be initialized, which you can achieve by injecting it into the filter and calling a method on it. Maybe something along those lines, with a forward (not a redirect because then you would definitely lose the state) would work?

What about such flow:

1. Before redirecting to `AuthorizationUri` we save the _original URI_ 
  1.1. We can do this by overriding `OAuth2ClientContextFilter.redirectStrategy`
2. Then in the callback method we get the access token with available `code` & `state` information.
3. After the access token is cached in `OAuth2ClientContext` we can redirect to the _original URI_ **without**  `code` & `state` query parameters.

Here is my implementation:

```java
@Bean
OAuth2ClientContextFilter oAuth2ClientContextFilter(OAuth2ClientContextFilter oAuth2ClientContextFilter) {
	oAuth2ClientContextFilter.setRedirectStrategy(new DefaultRedirectStrategy() {

		@Override
		public void sendRedirect(HttpServletRequest request, HttpServletResponse response, String url) throws IOException {

			final String currentUri = (String) request.getAttribute("currentUri");
			final HttpSession session = request.getSession(false);

			if (session != null) {
				// SPRING_SECURITY_SAVED_REQUEST = org.springframework.security.web.savedrequest.HttpSessionRequestCache#SAVED_REQUEST
				// Making it SimpleSavedRequest instead of DefaultSavedRequest makes HttpSessionRequestCache ignore it (matchesSavedRequest returns false)
				//so it lands on our callback smoothly.
				session.setAttribute("SPRING_SECURITY_SAVED_REQUEST", new SimpleSavedRequest(currentUri));
			}

			super.sendRedirect(request, response, url);
		}
	});

	return oAuth2ClientContextFilter;
}
```

```java
@Controller
@RequiredArgsConstructor
class CallbackControllerController {

	private final OAuth2RestTemplate restTemplate;

	@GetMapping("/callback")
	String callback(HttpSession httpSession) {

		if (httpSession != null) {
			final SavedRequest savedRequest = (SavedRequest) httpSession.getAttribute("SPRING_SECURITY_SAVED_REQUEST");
			httpSession.removeAttribute("SPRING_SECURITY_SAVED_REQUEST");

			// This gets an access token using the code and state values which are in the query parameters and
			//stores the access token in OAuth2ClientContext automatically. Hence, we can redirect to previous URL without
			//code & state params.
			restTemplate.getAccessToken();

			// Recall that savedRequest.redirectUrl is set from currentUri which is stripped off of its query parameters
			//in OAuth2ClientContextFilter#calculateCurrentUri
			return "redirect:" + savedRequest.getRedirectUrl();
		}

		throw new RuntimeException("No session!");
	}
}
```

**Comment by makkes** [comment]
I'll close this now since we don't seem to make any progress here.
