### ISSUE TITLE
Why the Mongodb queries become slowly

### ISSUE THREAD

**Issue by vkea95** [spring-projects/spring-security-oauth#600]
I setup a Java web application project which is based on MongoDB. The DAO of the this project is implemented by MongoDB Java driver; I didn't use the Spring Data for MongoDB.

I'm getting a performance problem. If the application sends a query to the database, the response time is about 17ms. But if I used the Jmeter -- which mocked about 300 users -- the response time of 90%Line is about 1300ms. The response time is intolerable. I tried to find the reason, but I don't know.

Also, there is the MongoUri String:

"mongo.uri=mongodb://192.168.1.172:27017,192.168.1.172:22222,192.168.1.172:33333/?replicaSet=yyyy&maxPoolSize=100&ssl=false&readPreference=secondaryPreferred&connectTimeoutMS=10000&socketTimeoutMS=10000&safe=false&
mongo.database=iostTest"
MongoCollectionDao.java
        
    public class MongoCollectionDao {
        public ResultPage<Document> findFirst( String id) {
            Document queryDoc = new Document("_id",id);
            Document document = MongoCollectionDao.mongoCollection.find(queryDoc).first();
            ResultPage<Document> result = new ResultPage<Document>();
            List<Document> listDoc = new ArrayList<Document>();

            if (document != null) {
                result.setRows(1);
                listDoc.add(document);
                result.setData(listDoc);
            }
            return result;
        }
        public MongoCollectionDao(MongoClient mongoClient, String mongoDatabaseName) {
            MongoCollectionDao.mongoClient = mongoClient;
            MongoCollectionDao.mongoDatabase =  MongoCollectionDao.mongoClient.getDatabase(mongoDatabaseName);
            MongoCollectionDao.mongoCollection = mongoDatabase.getCollection("staff");
        }
    }

mongo.xml
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="......">
        <context:property-placeholder location="classpath:mongo.properties" ignore-unresolvable="true"></context:property-placeholder>
        <bean id="uri" class="com.mongodb.MongoClientURI">
            <constructor-arg value="${mongo.uri}"></constructor-arg>
        </bean>
        <bean id="mongoClient" class="com.mongodb.MongoClient">
            <constructor-arg ref="uri"></constructor-arg>
        </bean>
        <bean id="mongoCollectionDao"
            class="com.xxx.api.domain.dao.impl.MongoCollectionDao" lazy-init="false">
            <constructor-arg name="mongoClient" ref="mongoClient"></constructor-arg>
            <constructor-arg name="mongoDatabaseName" value="${mongo.database}"></constructor-arg>
        </bean>
    </beans>

Also, "90%Line" is the part of Jmeter test result which means 90% user.
for example, There are 1000 users to test my application. the value of "90%Line" is 1300 ms, this means 900(1000 * 0.9) users can get result in 1300 ms.

**Comment by dsyer** [comment]
Is this anything to do with Spring OAuth (this project)?

**Comment by vkea95** [comment]
sorry for that. I posted it in the wrong place.
