### ISSUE TITLE
Spring sparklr2 maven build failing

### ISSUE THREAD

**Issue by egov-systems** [spring-projects/spring-security-oauth#611]
[ERROR] Failed to execute goal on project sparklr2: Could not resolve dependencies for project org.springframework.security.oauth:sparklr2:war:2.0.9.BUILD-SNAPSHOT: Could not find artifact org.springframework.security.oauth:spring-security-oauth2:jar:2.0.9.BUILD-SNAPSHOT in spring-milestone (http://maven.springframework.org/milestone) -> [Help 1]

This error was thrown while executing mvn install or package

**Comment by dsyer** [comment]
Did you build the dependencies first (e.g. `git clone ... && cd $_ && mvn install`)?

**Comment by dsyer** [comment]
The Spring Boot Maven plugin works for me and in tests and for everyone else that uses it. If you need help with building an executable jar, here are some hints to help others to help you

* look at existing samples and compare them carefully with your own code

* use start.spring.io to create a new project and look at how that is configured

* put a simple sample project in github and posting the link (66MB of Dropbox is totally unnecessary)

* post on Stackoverflow and listen to what people tell you there about how to ask a question. Read their documentation on how to ask questions, e.g. http://meta.stackoverflow.com/questions/261592/how-much-research-effort-is-expected-of-stack-overflow-users?lq=1.
