### ISSUE TITLE
https request to Authorize endpoint redirects to http login

### ISSUE THREAD

**Issue by SlimeQ** [spring-projects/spring-security-oauth#612]
as of iOS 9, all app requests are required to be ssl. everything in my api is on ssl, and my view resolver is set up correctly... but authorize still redirects to login on http. this would not be a huge deal since our server is forcing ssl anyways, but it confuses iOS 9 and is therefore a problem

**Comment by dsyer** [comment]
I don't think this is anything to do with Spring Security or OAuth2. Is your app behind a proxy? Who is terminating the SSL?

**Comment by SlimeQ** [comment]
it is behind a proxy and we resolved it by configuring upstream ssl properly. apologies for cluttering your issue queue
