### ISSUE TITLE
How JWT refresh tokens work?

### ISSUE THREAD

**Issue by bitsofinfo** [spring-projects/spring-security-oauth#614]
Hi,
So when I request a token from /oauth/token i get back something like this:

Where is the 'refresh_token'? Is that the JTI value? I also notice that my expiry of 30s does not seem to be enforced. These tokens are valid forever on other oauth2 secured URLs

```
{
  "access_token": "eyJhbGciOiJSUzI1NiJ.....sBhKk8uJUNwtgVfjjHm38XmgcTco5273vP6g",
  "token_type": "bearer",
  "expires_in": 29999,
  "scope": "execute",
  "jti": "3b517512-368d-4bbf-92ed-8771661bb093"
}
```

**Comment by bitsofinfo** [comment]
cancel my question about expiry of 30s, my value is way.... off.. 

refresh token question still stands

**Comment by bitsofinfo** [comment]
So if I call /oauth/token with grant_type=refresh_token I am not sure what to pass for the refresh_token body parameter. if I pass the old token I get back

```
{
  "error": "invalid_token",
  "error_description": "Encoded token is not a refresh token"
}
```

if I pass the jti value i get back

```
{
  "error": "invalid_token",
  "error_description": "Cannot convert access token to JSON"
}
```

**Comment by ShamimKarimi** [comment]
Have you added `refresh_token` to `authorizedGrantTypes` in your authorization server config?

` clients.inMemory()....
                .authorizedGrantTypes("password", "refresh_token")...; `

**Comment by dsyer** [comment]
I second that. It looks like you didn't enable refresh tokens (otherwise you would get one in the response from the token endpoint).
