### ISSUE TITLE
Using JWT along with refresh tokens in Spring OAuth2

### ISSUE THREAD

**Issue by ShamimKarimi** [spring-projects/spring-security-oauth#615]
Consider we want to use `JWT` along with refresh tokens in Spring.
We have to use `JWTTokenStore`, and we should "store" refresh tokens somewhere, right?

But if `JWTTokenStore` isn't a real database and doesn't store anything, where and how should we store refresh tokens?

(We prefer to store refresh tokens in database rather than store them in memory)

**Comment by dsyer** [comment]
If you want to you can probably customize the default behaviour by extending `JwtAccessTokenConverter`. I believe the default suits most people (the reason you use JWTs is that you don't want to have state in the auth server).
