### ISSUE TITLE
spring-security-oauth2: DefaultRedirectResolver does not check port in redirection endpoint

### ISSUE THREAD

**Issue by stromnet** [spring-projects/spring-security-oauth#616]
Not sure if this is intentional or not, but there are no doc (at least not in code) that indicates that the port part of the URI is ignored:

https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/DefaultRedirectResolver.java#L117

This means that http://somesite.com:8080/rdr may be the only registered endpoint, but http://somesite.com:1234/rdr will still work.

Probably not an issue in real-world deployments but..

**Comment by dsyer** [comment]
It's been that way for a long time as far as I can tell. We match the protocol and the host and path, but not the port. I added a sentence to java docs.
