### ISSUE TITLE
OAuth2ErrorHandler - When there is more information in the reponse, the class is OAuth2Exception

### ISSUE THREAD

**Issue by cguZZman** [spring-projects/spring-security-oauth#618]
When there is more information in the response about an error (other than the simple error code), the exception instance is OAuth2Exception. 
Right now there is a validation in OAuth2ErrorHandler trying to identify this, but for some reason it ends coded the opposite, assuming that if the instance is NOT an OAuth2Exception then it has more info.

**Comment by dsyer** [comment]
This is intentional I think: it is not an "instanceof" match, it is a match of the precise concrete class. If the concrete class is `OAuth2Exception` I think you will find that there is actually no more information there. Here's the relevant code for reference:

```
			catch (OAuth2Exception ex) {
				if (!ex.getClass().equals(OAuth2Exception.class)) {
					// There is more information here than the caller would get from an HttpClientErrorException so
					// rethrow
					throw ex;
				}
				// This is not an exception that is really understood, so allow our delegate
				// to handle it in a non-oauth way
				errorHandler.handleError(bufferedResponse);
			}
```

**Comment by cguZZman** [comment]
Looks like it is not intentional. Take a look at the comment in line 132 and 133, just after getting the OAuth2Exception object:
```
					OAuth2Exception body = extractor.extractData(bufferedResponse);
					if (body != null) {
						// If we can get an OAuth2Exception already from the body, it is likely to have more information
						// than the header does, so just re-throw it here.
						throw body;
					}
```
It's creating the OAuth2Exception from the body of the response, and when that's the case, the understanding is that there is more information of the error in the body.
I already test it, and that's why I came up with this.
I wasn't getting the extra information of the error, so I followed up the problem until here.

**Comment by dsyer** [comment]
That's different. There is an instanceof check in that location, then a regrow, and in the catch we selectively rethrow only the concrete instances whose class is precisely `OAuth2Exception`. So it is definitely intentional, and as far as I can tell, correct.

**Comment by cguZZman** [comment]
Dave, may be I missing something, but there is no instanceof check there. And I don't see where you are rethrowing those concrete instances whose class is precisely ```OAuth2Exception```. In fact, you are doing exactly the opposite. You are rethrowing only those instances whose original class are NOT (!) ```OAuth2Exception```.
See the negation at the beginning of this if:
```
if (!ex.getClass().equals(OAuth2Exception.class)) {
                    // There is more information here than the caller would get from an HttpClientErrorException so
                    // rethrow
                    throw ex;
                }
```
