### ISSUE TITLE
Support for other response types then code & token.

### ISSUE THREAD

**Issue by oharsta** [spring-projects/spring-security-oauth#626]
The current codebase already provides many hooks for customizing the behaviour like enhancing tokens, allow custom grant types, pre-approval of authorization requests and so on. What it currently does not support is hooking in custom behaviour for handling other response-types then code & token in the Authorization endpoint. 

The oauth 2.0 authorization framework specification has a [section](https://tools.ietf.org/html/rfc6749#section-8.4) about new authorization endpoint response types. 

Allowing for custom response types handlers would enable users of the framework to easily implement features like the id_token & none response types defined in the [openid oauth2 specification](http://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token) without having to change the actual spring oauth2 framework.

All the needed hooks are already there in the AuthorizationEndpoint and a minimalistic implementation would mean introducing a CustomResponseTypesHandler that is capable of handling custom response types other then code & token.

I would like to write a pull request for this, but before putting in the effort I was wondering if this is something the core committers would consider viable?

**Comment by oharsta** [comment]
After googling - probably should have done that first - this issue is linked to #619 and #220

**Comment by oharsta** [comment]
The https://travis-ci.org/spring-projects/spring-security-oauth/builds/91321307 build fails, but it seems totally unrelated to my code. Also locally when running `mvn clean test -P bootstrap` everything is green. False negative?

**Comment by dsyer** [comment]
Duplicates #619
