### ISSUE TITLE
Securing OAuthClientDetails.clientSecret with PasswordEncoder

### ISSUE THREAD

**Issue by vicmosin** [spring-projects/spring-security-oauth#632]
There is a OAuth server based on `spring-security-oauth2` with two clients. First one for `password` grant_type, second one for `client_credentials`. It worked without any issues. At some point we decided to add a secret's encryption, so every time user obtains the token, spring should decrypt the password. 
Due to your recommendations, I added the following (this was the only config change, btw):
```
@Override
public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
        security
                .passwordEncoder(bcryptPasswordEncoder) // added encoder
                .tokenKeyAccess("permitAll()")
                .checkTokenAccess("permitAll()");
}
```
After a couple of tests I noticed that `password` grant don't provide any authorities information which were stored in db. `client_credentials` continued to work fine. At debugging I found out that `AuthenticationManagerBuilder` calls the `DaoAuthenticationProvider` in order to retrieve the user. And once I add the line above to config, `DaoAuthenticationProvider.userDetailsService` contains the instance of `ClientDetailsService` rather then `UserDetailsService`. Which means that spring tries to retrieve the user from `oauth_client_details` table, but not from `users` and of course can't find anything.. In case of `client_credentials` this is normal behavior, but `password` expects security's user object. So I came to that [snippet](https://github.com/spring-projects/spring-security-oauth/blob/00afb535ce8736f26a2ac270fabb8dc62943b0cb/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configurers/AuthorizationServerSecurityConfigurer.java#L131). So I am wondering is it really a bug, or some default behavior and my app's logics should be reviewed?

**Comment by dsyer** [comment]
The samples work. It seems like your `HttpSecurity` for the token endpoint somehow got its wires crossed and grabbed the user details instead of the client details. Can you provide a simple sample project that reproduces the problem (or add a test to the existing samples that shows they have the same behaviour)?

**Comment by vicmosin** [comment]
Yes. I found the issue. I was using `@Order(-1)` for security configuration and somehow those two services swapped places.
