### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by michaeltecourt** [spring-projects/spring-security-oauth#636]
XSS vulnerability found during an audit led by an external contractor specialized in security.

When an invalid parameter is sent to the authorize endpoint by clients, the white label error page does not escape the input before rendering it.

**Fix submitted in PR** #635.

For example this request :
`http://localhost:8080/oauth/authorize?response_type=code&client_id=client-x&redirect_uri=<script>alert('XSS');</script>&scope=read_elec_consumptions`

Leads to the following screen :

![capture d ecran_2015-11-19_11-02-42](https://cloud.githubusercontent.com/assets/7481254/11267690/17849308-8ead-11e5-850f-88a685829f93.png)

It could be used by attackers to obtain user credentials with a fake login form imitating the original one.

**Comment by dsyer** [comment]
Thanks for the analysis. I wouldn't expect any "real" application to use the whitelabel error page, so I won't rush to release 2.0.9 unless anyone objects.

**Comment by michaeltecourt** [comment]
:+1:
