### ISSUE TITLE
Bias in RandomValueStringGenerator Authorization Code Generation 

### ISSUE THREAD

**Issue by rlubbat** [spring-projects/spring-security-oauth#639]
The transformation of random bytes to alphanumeric characters using the modulo operator in the RandomValueStringGenerator#getAuthorizationCodeString() method introduces a bias such that the first 8 elements in the character array are 25% more likely to be selected than the other elements.

This is because the length of DEFAULT_CODEC is 62, which does not evenly divide into 256. The bias prevents the the random value strings from being uniformly random, which may allow an attacker to recover nonrandom, predictable values using brute force methods.

A simple fix is to add two more characters to DEFAULT_CODEC, bringing its length to 64. Recommend adding URL safe characters hyphen (-) and underscore (_).

**Comment by dsyer** [comment]
Interesting analysis. I don't think anyone should panic, but we can discuss some more if you want. The degree of non-uniformity introduced is not significant enough to give an attacker much of an advantage. If there is an attack we should worry about here I would think it is much more important to ensure that the auth codes are short lived, than to worry much about small wrinkles in the random generator.

**Comment by jgrandja** [comment]
@dsyer based on your comment here do you recommend we close this issue?

**Comment by jgrandja** [comment]
Interesting find @rlubbat. Would you be interested in sending a PR for your recommended change?

**Comment by rlubbat** [comment]
Honestly, I don't think I'm going to have the time. Should be pretty easy for someone to add the two characters as described in the issue. Thanks for looking at it.
