### ISSUE TITLE
Immortal refresh tokens not working when using JWT

### ISSUE THREAD

**Issue by gerar2** [spring-projects/spring-security-oauth#641]
It seems that creating immortal refresh tokens is not working when using JWT.
I have a client configured with refreshTokenValiditySeconds(0) but when using JwtAccessTokenConverter ([like here](https://github.com/spring-projects/spring-security-oauth/blob/master/tests/annotation/jwt/src/main/java/demo/Application.java)) the token expire at the same time as the access token.

Could it be a bug or am I missing something?

Thanks

**Comment by houssemzaier** [comment]
Hi ,
this is so cool ! I want to  have this new feature "Immortal Refresh Token" in my project 
Can anyone tell how can I get  the last build 2.1.0 / or 2.9 witch has fixed the bug .
 I want to include it in my POM file this way
<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			
			<version>2.1.0.BUILD-SNAPSHOT</version>
</dependency>
.... I am getting an error "Missing artifact org.springframework.security.oauth:spring-security-oauth2:jar:2.0.9.BUILD-SNAPSHOT" 
I am a newbie so I need you help . 
Thanks in advance  
Any advice is more than appreciated

**Comment by houssemzaier** [comment]
I got it I have used this file as an example: 
https://github.com/spring-projects/spring-security-oauth/blob/master/tests/annotation/pom.xml
