### ISSUE TITLE
Oauth2 Spring, both refresh_token and access token expired deadlock situation

### ISSUE THREAD

**Issue by foomoto** [spring-projects/spring-security-oauth#644]
I have a situation where I for some reason set the refresh token to a short expiry date.

The client did not refresh the token before the refresh token expired and the access token was also expired.

I tried to,

Get a new token using 'oauth/token' endpoint, basic auth login for the client, and the user credential in application/x-www-form-urlencoded with grant_type password. But I get a null token.

To resolve this, I had to delete the expired access tokens from the authentication server for the client and user before a new access token was issued.

Can the client resolve this issue of both refresh_token expired, and access token expired without such manual intervention if I were to deploy Spring Oauth2 in production. 

My recommendation will be that a new access token is issued when the oauth/token is called.

**Comment by dsyer** [comment]
If your auth server supports password grants then sending the user credentials gets a new token. What do you mean by "null" token? What do you mean by "manual intervention" (if the tokens expire you obviously need to re-authenticate)? Do you have some code that reproduces the problem, maybe?

**Comment by foomoto** [comment]
Hi Dave,

I'm a bit new to this, but allow me to explain what i think is going on.

My Auth server does support "authorization_code, password, and refresh_token in my CustomClientDetails provider. and I set the access token and refresh token to expire in 180000 seconds. Below is my code.

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.provider.ClientDetails;

public class CustomClientDetails implements ClientDetails {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String id;

	private String secret;

	public CustomClientDetails() {
		// TODO Auto-generated constructor stub
	}

	public CustomClientDetails(Client client) {
		id = client.getClientId();
		secret = client.getPassword();
	}

	@Override
	public Integer getAccessTokenValiditySeconds() {
		return 180000;
	}

	@Override
	public Map<String, Object> getAdditionalInformation() {
		return Collections.emptyMap();
	}

	@Override
	public Collection<GrantedAuthority> getAuthorities() {
		return Collections.emptyList();
	}

	@Override
	public Set<String> getAuthorizedGrantTypes() {
		return new HashSet<String>(Arrays.asList("authorization_code",
				"password", "refresh_token"));
	}

	@Override
	public String getClientId() {
		return id;
	}

	@Override
	public String getClientSecret() {
		return secret;
	}

	@Override
	public Integer getRefreshTokenValiditySeconds() {
		return 180000;
	}

	@Override
	public Set<String> getRegisteredRedirectUri() {
		return Collections.emptySet();
	}

	@Override
	public Set<String> getResourceIds() {
		// TODO Auto-generated method stub
		return Collections.emptySet();
	}

	@Override
	public Set<String> getScope() {
		return new HashSet<String>(Arrays.asList("read", "write"));
	}

	@Override
	public boolean isAutoApprove(String arg0) {
		return true;
	}

	@Override
	public boolean isScoped() {
		return true;
	}

	@Override
	public boolean isSecretRequired() {
		return true;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}

180000 seconds after I obtained my access token. AuthServer rejects access token, and refresh token because they have both expired.

So I try to login again with my client details to obtain a new access token but I get the error message, "access token returned cannot be null"

So I had a client lock-out situation.

What was the manual intervention? I suspected the expired access token was preventing the new one from being issued since spring-oauth checks if there is an existing access token for a client and returns the same token if you reauthenticate. 

So I deleted the old tokens directly from database and reauthenticated which  returned a new access token that wasnt null.

**Comment by dsyer** [comment]
So when you get this "cannot be null" thing that's in the client right? What happened in the server? Can you maybe get some debug logs (or better still send a link to a complete project)?

**Comment by foomoto** [comment]
Bug spotted not in Spring but in my code. 

I reduced the access token and refresh token expiry to 1 second so they expire immediately and i was able to test my assumptions better. A new token was released each time as expected when client reauthenticates. 

The issue was in a custom database object converter which was buggy (MongoDB to Java stuff).

Thanks Dave.

Now closing issue.
