### ISSUE TITLE
How to get a refresh_token with granttype implicit

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-security-oauth#648]
I've got a minimal sample project here: https://github.com/spring-projects/spring-security-oauth
It has a OAuth2 server setup to use JWT tokens, with a single client and user to test with.

When I request an implicit access_token, I used to get a refresh_token as well. I'm unable to find out what version is was using at the time, but [this test illustrates the issue](https://github.com/timtebeek/implicit-refresh-token/blob/master/src/test/java/com/github/timtebeek/irt/DemoApplicationTests.java#L78) currently.

Could anyone tell me how I can update my token request to get a `refresh_token` included in my implicit token response as well?

**Comment by dsyer** [comment]
From the spec: "The implicit grant type is used to obtain access tokens (it does not support the issuance of refresh tokens)". Can you explain why you would need it otherwise?

**Comment by timtebeek** [comment]
Thanks & sorry for the confusion; I must have had things confused with a custom guest user token controller I wrote a while ago that did return a refresh_token. I'll find a way around the issue, that's not the problem. From my confusion I thought it was a regression, that's all.

For those interested, it's mentioned in [RFC6749](https://tools.ietf.org/html/rfc6749) section 4.2.  Implicit Grant:

>   The implicit grant type is used to obtain access tokens (it does not
   support the issuance of refresh tokens) and is optimized for public
   clients known to operate a particular redirection URI.  These clients
   are typically implemented in a browser using a scripting language
   such as JavaScript.
