### ISSUE TITLE
Best way to configure login page so it can be bookmarked

### ISSUE THREAD

**Issue by eschizoid** [spring-projects/spring-security-oauth#656]
After the oauth authorize endpoint gets executed, something like the folwing (redirect flow):

````
oauth/authorize?response_type=A&client_id=B&redirect_uri=C&scope=debug
```` 

If the user was not previously authenticated he will be redirected to the login page or main entry point of the application.

At this point the user can bookmark the page. However the next time he tries to access this bookmark login page, spring last request is not going to be stored in the session and will be login to whatever action is configured in the form login page.

My question would be what is the best practice to avoid this specific behavior and force the user to start the complete oauth flow.

Thanks

**Comment by 9you** [comment]
My opinion (not tested):
You may try to subclass `LoginUrlAuthenticationEntryPoint` and override method `determineUrlToUseForThisRequest(...)` to append redirect_url to login page URL from `Session`.

You need to do something with your login page or implement a `Filter` to save redirect_url from query string of login page to `Session` in case of use returning from a bookmark.

And you may have to customize `RedirectStrategy` and pass it to `AuthenticationFailureHandler`, it help append redirect_url to the query string of login URL in case of login fail.

**Comment by eschizoid** [comment]
@9you I ended up implementing a `SimpleUrlAuthenticationSuccessHandler` and injecting it into a `WebSecurityConfigurerAdapter`. That way I can execute a controller after a successful login and validate the oauth query string.

````
@Bean
public SimpleUrlAuthenticationSuccessHandler simpleUrlAuthenticationSuccessHandler() {
	final SimpleUrlAuthenticationSuccessHandler authenticationSuccessHandler = new SimpleUrlAuthenticationSuccessHandler("/validate");
	authenticationSuccessHandler.setAlwaysUseDefaultTargetUrl(false);
	authenticationSuccessHandler.setTargetUrlParameter("spring-security-redirect");
	return authenticationSuccessHandler;
}  
````

````
.formLogin()		
	.usernameParameter("username")
	.passwordParameter("password")
	.loginPage( "/login.jsp")
	.loginProcessingUrl("/login.do" )
	.successHandler(simpleUrlAuthenticationSuccessHandler())
````
