### ISSUE TITLE
Session scoped OAuth2ClientContext, handling missing JSESSIONID upon redirect back to client.

### ISSUE THREAD

**Issue by nicodewet** [spring-projects/spring-security-oauth#661]
In OAuth2ClientContextConfiguration, the OAuth2ClientContext is session scoped, so unless my understanding of the fundamentals is incorrect, when a service provider (WSO2 Identity Server in my case) grants authorization and redirects back to the client, if it does not pass back the relevant JSESSIONID then you'll ultimately get an InvalidRequestException in AuthorizationCodeAccessTokenProvider since there will be no preserved state (see http://stackoverflow.com/questions/34219911/why-is-accesstokenrequests-preservedstate-perpetually-null-with-a-resultant-csr) since state is stored in the OAuth2ClientContext.

Now, my question is whether it is appropriate, in terms of the OAuth2 spec, to rely on the JSESSIONID being sent back, i.e. if it not enough for the service provider, upon granting authorization, to just send the code and state in the redirect back to the client. In my mind this means that the client must maintain state based on the very same state query parameter.

Hope I'm not barking up the wrong tree.

**Comment by dsyer** [comment]
The spec requires clients to store state. We have chosen to do that using Spring MVC `@SessionAttribute` support (which uses the HttpSession by default). I don't see any problem with that, and you appear to be a bit confused about the role of the provider (who will never know your client app's cookie). So probably, in summary, the wrong tree.

If you have a more specific scenario where something actually doesn't work, we can analyse it a bit to work out why, but nothing seems wrong to me on the face of it.

**Comment by jgrandja** [comment]
@nicodewet I'm going to close this issue but if you feel there is more discussion required please re-open. Thanks.

**Comment by alexis0890** [comment]
Hello,

following this issue we have encountered a problem in our application. We decided to be stateless and because of that we have the exception "Possible CSRF detected - state parameter was required but no state could be found".

For stateless application it seems that there is an issue. Instead of storing the state in session it would be great if the api allows use to define a "SessionStore" class, in order to implements our own session management, for example in a cookie.

Instead of using the httpsession we will then use a cookie acting as session.

Regards,

**Comment by dsyer** [comment]
There is already a strategy in spring for `@SessionAttribute` (so there shouldn't be any need to do anything here).

**Comment by SUGE2016** [comment]
https://spring.io/blog/2015/02/03/sso-with-oauth2-angular-js-and-spring-security-part-v#adding-the-oauth2-dependencies metioned if you launch both auth-server and ui-server on same host, need to set a context-path avoid the cookie be overrided by other

this resolved the same problem i faced.
