### ISSUE TITLE
Memory abuse - OAuthAuthenticationDetails recursive references.

### ISSUE THREAD

**Issue by shlomicthailand** [spring-projects/spring-security-oauth#666]
Hi

we are looking into some memory issues and this object came on top as a memory consumer.
looking into the code we found something very strange that is referencing an old authentication details with new authentication details, when these are kept in some kind of cache, there is a memory problem. here is the code. (from Oauth2AuthenticationManager.authenticate) 
considering that before calling authentication , Authentication details were constructed from request .
so basically its the same data but still passed from old (token services) to new (request).

	OAuth2Authentication auth = tokenServices.loadAuthentication(token);
		if (auth == null) {
			throw new InvalidTokenException("Invalid token: " + token);
		}

		Collection<String> resourceIds = auth.getOAuth2Request().getResourceIds();
		if (resourceId != null && resourceIds != null && !resourceIds.isEmpty() && !resourceIds.contains(resourceId)) {
			throw new OAuth2AccessDeniedException("Invalid token does not contain resource id (" + resourceId + ")");
		}

		checkClientDetails(auth);

		if (authentication.getDetails() instanceof OAuth2AuthenticationDetails) {
			OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) authentication.getDetails();
			// Preserve the authentication details if any from the one loaded by token services
			details.setDecodedDetails(auth.getDetails());
		}
		auth.setDetails(authentication.getDetails());

**Comment by 9you** [comment]
I have the problem here too!

**Comment by shlomicthailand** [comment]
we in the meantime override the Oauth2AuthenticationManager and just overrided the setDecodedDetails() with null setDecodedDetails(null)
this way no chain of objects is created and our heap is happy :-)

**Comment by dsyer** [comment]
Can you explain a bit more how this chain of objects arose in the first place? Typically `Oauth2AuthenticationManager.authenticate()` will be called with a `PreAuthenticatedAuthenticationToken` that just contains the token and some information about the incoming request. It wouldn't have a long chain of details in it.

**Comment by shlomicthailand** [comment]
look at the comment in the code, it say you want to preserve the details that came from the token services, 
now we cache the results of token services, so auth is coming from cache (with details).
then do this details.setDecodedDetails(auth.getDetails()) - which does not replace the details but chain them (decoded is a different prop). 
afterward you do this
 auth.setDetails(authentication.getDetails());
which point the cached object to the new details which are chained to the old auth details.

**Comment by dsyer** [comment]
This code was added in #285. There is a clear danger that it will lead to a cycle, but I'm not sure I understand the memory consumption issue yet. Hopefully that last change fixes it.
