### ISSUE TITLE
Chaining custom requestMatchers with NotOAuthRequestMatcher by OrRequestMatcher leads to incorrect request filters behaviour

### ISSUE THREAD

**Issue by SkivPragma** [spring-projects/spring-security-oauth#667]
I have next config:
http.requestMatchers()
            .antMatchers(
                    "/rest/**", 
                    "/rest_data/**",
                    "/upload")
        .and()
...
inside ResourceServerConfigurerAdapter annotated by @EnableResourceServer

I have application with 2 authentication mechanisms. Most endpoints use form-based authentication and oauth2 authentication used for 3 endpoints only.
 
This configuration worked fine until I updated spring security from 3.2.7 to 4.0.3.
It seems that there was a bug related to mulitple invocations of http.requetMatchers(). See https://github.com/spring-projects/spring-security/commit/fbf3672ecaf0497a52c557b7d3a05951be30c7ef
After update the filter chain configured for oauth2 secured resources used always for all paths except "/oauth/check_token", "/oauth/authorize", "/oauth/confirm_access", "/oauth/error", "/oauth/token". NotOAuthRequestMatcher returns true in conjunction with OrRequestMatcher used in HttpSecurity.RequestMatcherConfigurer. This leads to incorrect filter chain application. antMatchers passed in config ignored.

**Comment by jebeaudet** [comment]
Duplicate of https://github.com/spring-projects/spring-security-oauth/issues/634, will be fixed in the next version.

**Comment by jgrandja** [comment]
@SkivPragma Looks like this has been resolved in #634. I'm going to close this issue. Please re-open if this has not solved your issue.
