### ISSUE TITLE
 set WebResponseExceptionTranslator for endpoints

### ISSUE THREAD

**Issue by nklnandu** [spring-projects/spring-security-oauth#668]
Hi, is there some convenient way to set WebResponseExceptionTranslator for endpoints in xml configuration, I find it in java configuration?

Thank you very much for your reply.

![image](https://cloud.githubusercontent.com/assets/518394/12190966/685655ce-b594-11e5-80ae-efb5a932b8fd.png)

**Comment by jgrandja** [comment]
@nklnandu Doesn't look like there is a element defined for`WebResponseExceptionTranslator ` in _spring-security-oauth2-2.0.xsd_.

**Comment by jgrandja** [comment]
@nklnandu I'm going to close this issue. If you have further questions please re-open this issue. Thanks.
