### ISSUE TITLE
How to customize my own exception handler in token endpoint?

### ISSUE THREAD

**Issue by nklnandu** [spring-projects/spring-security-oauth#670]
I do see some where it mentioned we need to implement  the WebResponseExceptionTranslator . 
I have created CustomWebResponseExceptionTranslator that implements WebResponseExceptionTranslator . But the translator is never called from spring. 
I may be missing something . Please help me what will be the configuration to make it success. 

fyi

![image](https://cloud.githubusercontent.com/assets/518394/12190969/77018abc-b594-11e5-9a6f-9f2183bc08ba.png)

**Comment by jebeaudet** [comment]
How do you inject your ExceptionTranslator into the TokenEndpoint? More infos is needed here

**Comment by nklnandu** [comment]
Here is my current code 
	 @Bean(name = "exceptionRenderer")
	 public  CustomExceptionRenderer getCustomExceptionRenderer() {
		 CustomExceptionRenderer customExceptionRenderer = new CustomExceptionRenderer();
	        return customExceptionRenderer;
	    }
	 
	
	 @Bean(name = "exceptionTranslator")
	 public  CustomExceptionTranslator getWebResponseExceptionTranslator() {
	        CustomExceptionTranslator customExceptionTranslator = new CustomExceptionTranslator();
	        return customExceptionTranslator;
	    }
	 
	 
	 
	@Bean(name = "clientAuthenticationEntryPoint")
	public CustomOAuth2AuthenticationEntryPoint getClientAuthenticationEntryPoint() throws Exception {
		CustomOAuth2AuthenticationEntryPoint customOAuth2AuthenticationEntryPoint =  new CustomOAuth2AuthenticationEntryPoint();
		customOAuth2AuthenticationEntryPoint.setExceptionTranslator(getWebResponseExceptionTranslator());
		customOAuth2AuthenticationEntryPoint.setExceptionRenderer(getCustomExceptionRenderer());
		return customOAuth2AuthenticationEntryPoint;
	}


How to inject my CustomExceptionTranslator in the TokenPoint during runtime ?

I am always getting the DefaultWebResponseExceptionTranslator class . 
Help me to configure my custom translator and set my own error messages in the response.

**Comment by jebeaudet** [comment]
If you're using Java config, this should do it : 
```
    @Configuration
    @EnableAuthorizationServer
    public static class AuthorizationServerConfigurer extends AuthorizationServerConfigurerAdapter
    {
        @Override
        public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception
        {
            endpoints.exceptionTranslator(getWebResponseExceptionTranslator());
        }
    }
```

**Comment by nklnandu** [comment]
Good. How about If i use the XML config?

Or this is the open issue right now?

**Comment by jebeaudet** [comment]
There doesn't seem to have a way to configure this in xml. If you really don't want to use Java config, I guess you're stuck with a `BeanPostProcessor`, something like this : 
```
public class TokenEndpointExceptionRenderingPostProcessor implements BeanPostProcessor
{
    @Override
    public Object postProcessBeforeInitialization(Object bean,
                                                  String beanName) throws BeansException
    {
        return bean;
    }

    @Override
    public Object postProcessAfterInitialization(Object bean,
                                                 String beanName) throws BeansException
    {
        if (bean instanceof TokenEndpoint) {
            TokenEndpoint tokenEndpoint = (TokenEndpoint) bean;
            tokenEndpoint.setProviderExceptionHandler(new CustomExceptionTranslator());
        }
        return bean;
    }
}
```

**Comment by nklnandu** [comment]
Do we need to specify anywhere this class TokenEndpointExceptionRenderingPostProcessor ?

How this class will be called ? or we have to mention as bean or something?

**Comment by jebeaudet** [comment]
I edited my post, read the end of it

**Comment by nklnandu** [comment]
Thanks for your tips to inject the CustomExceptionTranslator. Still I am looking any better way or common place to handle all types of exception and set the error code accordingly. 

Once again thanks for reply my post .

**Comment by jgrandja** [comment]
Duplicate of #668. Closing this issue as a solution has been provided by @jebeaudet. Thanks @jebeaudet!

**Comment by MyGitUserAcc** [comment]
@jebeaudet  How to call TokenEndpointExceptionRenderingPostProcessor from xml configuration.Which is the  @Configuration class in xml configuration??

**Comment by MyGitUserAcc** [comment]
@nklnandu  How can i configure TokenEndpointExceptionRenderingPostProcessor in xml file??
