### ISSUE TITLE
OAuth2AccessTokenJackson2Deserializer and NULL JSON token_type

### ISSUE THREAD

**Issue by tkmtwo** [spring-projects/spring-security-oauth#676]
I am forced to use a misbehaving OAuth token provider - it gives me null as a token_type.  Sad, but true, and I have to work around it in the short term.

During development of my client, I've noticed that OAuth2AccessToken.getTokenType() is returning the literal string of "null" after retrieving the token.

I believe the root issue is in OAuth2AccessTokenJackson2Deserializer, where I see this:

``` java
else if (OAuth2AccessToken.TOKEN_TYPE.equals(name)) {
              tokenType = jp.getText();
          }
```

And perhaps it should check for the null value like this:

``` java
else if (OAuth2AccessToken.TOKEN_TYPE.equals(name)) {
              if (jp.getCurrentToken() != JsonToken.VALUE_NULL) {
                  tokenType = jp.getText();
              }
          }
```

because the JsonParser will interpret null as "null" in a getText() context.

I have worked around this by implementing my own OAuth2RequestAuthenticator (as has been done for #457) which checks explicitly for the literal null token type.

**Comment by jgrandja** [comment]
@tkmtwo Thanks for your feedback here. Your suggestion makes sense. Would you be interested in submitting a PR for this?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
