### ISSUE TITLE
null collection of ClientDetails.getAuthorities() should work

### ISSUE THREAD

**Issue by tungox6** [spring-projects/spring-security-oauth#680]
I implements ClientDetails and in the method getAuthorities() I return null then my code doesn't get work. However when I return an empty collection (new ArrayList<GrantedAuthority>()) then the code works well. I think there are no differences between a null list and an empty one (from user side).

**Comment by jgrandja** [comment]
It's a common best practice to return an empty list to prevent NullPointerException, however, I do see your point that it should still work. I'll look into this.

**Comment by jgrandja** [comment]
Document javadoc for `getAuthorities` to return non-null.

**Comment by jgrandja** [comment]
@tungox6 I've updated the javadoc for `ClientDetails.getAuthorities()` and is now in master. Thanks for the report.
