### ISSUE TITLE
How to handle user credential change

### ISSUE THREAD

**Issue by WeipingGuo** [spring-projects/spring-security-oauth#681]
I am building web component which uses JwtTokenStore for token management. When user login, the service calls another backend using user name and password to authenticate the user. Once authenticated, access token and refresh token are returned for subsequent API calls.

When refresh_token is called later on, I am using UserDetailsService to check the user by loadUserByUsername. If user is found, a new pair of access and refresh tokens are returned.

The problem I am facing: if the user changed his/her password from the backend, how can I handle it since the refresh_token only calls loadUserByUsername? 

Any suggestions or comments are appreciated!

**Comment by jgrandja** [comment]
Please ask questions on StackOverflow or Gitter. Thank you. I'm going to close this issue.
