### ISSUE TITLE
Sending a wrong token to an unprotected resource?

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-security-oauth#682]
It seems that if you add an "Authorization" header with an invalid access token in a request for an unprotected resource, you get a 401 back. Is this the intended behaviour or not?

For example: 

    curl -I http://localhost:8080/partials/login.html

Response: HTTP/1.1 200 OK

Use the password flow to get an access token:

    curl -X POST -vu clientapp:123456 http://localhost:8080/oauth/token -H "Accept: application/json" -d "password=user&username=user&grant_type=password&scope=read%20write&client_secret=123456&client_id=clientapp"

Then use the correct access token:

    curl -I -H "Authorization: Bearer 70eda7ec-a8a2-4209-aece-6740b6546acc" http://localhost:8080/partials/login.html

Response: HTTP/1.1 200 OK

Using a wrong access token:

    curl -I -H "Authorization: Bearer 70eda7ec-a8a2-4209-aece-6740b6546bbb" http://localhost:8080/partials/login.html

Response: HTTP/1.1 401 Unauthorized

This is my config:

    @Override
        public void configure(HttpSecurity http) throws Exception {

            http
                    .authorizeRequests()
                    .antMatchers("/partials/login.html" )
                    .permitAll()
                    .anyRequest().authenticated();
        }

Is the 401 expected or should it return a 200 since the resource is not protected anyway?

**Comment by jebeaudet** [comment]
`permitAll()` doesn't make the path open to anyone, what you're looking for here is `anonymous()`. `permitAll()` is on the authorization level, it says that the request doesn't requires any role (`hasRole('ROLE_ADMIN')`) or any other ACL. The `curl -I` you send here send a HEAD request, it may be handled differently than GET in your app. 

The behavior here is normal, if you try to authenticate with a bad token, the `OAuth2AuthenticationProcessingFilter` will throw and redirect you to the `AuthenticationEntryPoint`.

If you want to completely remove Spring security filter chain (which you should do for static resources like your login page), use this method of the `WebSecurityConfigurerAdapter` : 
```
@Override
public void configure(WebSecurity web) throws Exception
{
     web.ignoring().antMatchers(PUBLIC_RESOURCES_PATH_ANT_MATCHER, ERRORS_PATH_ANT_MATCHER);
}
```
