### ISSUE TITLE
Header parameter "kid"

### ISSUE THREAD

**Issue by plfx** [spring-projects/spring-security-oauth#713]
We are implementing a key rotation strategy for our auth server, and need to be able to specify the `kid` (key id) JWT header parameter. As of 1.0.4 this cannot be set with the spring-security-jwt `JwtHelper`. https://tools.ietf.org/html/rfc7515#section-4.1.4

I notice between 1.0.3 and 1.0.4 the `typ` header parameter was added. Might `kid` also be added in the near future?

Thank you.

**Comment by william-tran** [comment]
I'll add that this is part of the key rotation epic in UAA

**Comment by plfx** [comment]
Thank you @william-tran, it is. Link to the backlog story for interested parties: https://www.pivotaltracker.com/story/show/107773584

**Comment by dsyer** [comment]
I guess you can always put it in the body of the token until the header is available.

**Comment by plfx** [comment]
@dsyer From the perspective of clients that are decoding and verifying JWT tokens themselves, it would be a breaking change for the key ID to first be in the body and then be moved to the header.

**Comment by dsyer** [comment]
Not if they knew about the change. If they could tolerate change, eg. if they were built using this library, they could adapt, surely?

**Comment by plfx** [comment]
@dsyer Our API is provided as a set of JSON endpoints, and we make no assertion that clients should use a particular library.

**Comment by dsyer** [comment]
Adding a new field that the user controls to the header is kind of a bigger deal than the "typ" was ("typ" is read only and optional). I think I managed it without breaking the public API. There's a new method `JwtHelper.encode()` taking a `Map<String,String>` which are added verbatim into the headers. To decode and verify a token you would need to call the `decode()` method, extract the headers and parse them to get the key id and then call `decodeAndVerify()` with the signature verifier.

There is a new 1.0.5.RELEASE with the new features. I put it in repo.spring.io but not in Maven Central yet, so you have a chance to try it out before I push it to the rest of the world if you want.

**Comment by bonhamcm** [comment]
@dsyer Any idea when you'll push the 1.0.5.RELEASE to Maven Central?

**Comment by dsyer** [comment]
Done. Thanks for the reminder.

**Comment by Sherie1988** [comment]
Sherie1988@users.noreply.github.com
