### ISSUE TITLE
DefaultTokenServices.refreshAccessToken not grabbing (maybe) modified access token after enhancer call

### ISSUE THREAD

**Issue by ulisesbocchio** [spring-projects/spring-security-oauth#714]
DefaultTokenServices.refreshAccessToken is not getting the latest version of the refresh token after the access token is created and possibly enhanced. The effect is that if using an enhancer, refresh token stored in the token store is not enhanced, but the one returned to the requestor is. fix is to do this:

```java
refreshToken = accessToken.getRefreshToken();
```

right after this (line 177 in version 2.0.9.RELEASE):

```java
tokenStore.storeAccessToken(accessToken, authentication);
```

**Comment by death-knight** [comment]
I am working with JWT Tokens and am having the same issue if `reuseRefreshToken` is `false`.

**Comment by jgrandja** [comment]
Closing this issue as it's a duplicate of #511
