### ISSUE TITLE
Wrong deserialization of UnauthorizedClientException

### ISSUE THREAD

**Issue by jgdef** [spring-projects/spring-security-oauth#720]
OAuth2ExceptionJackson2Deserializer, when deserializing the following JSON:

`{"error":"unauthorized_client","error_description":"Could not authenticate client"}`

creates an instance of UnauthorizedUserException, and not UnauthorizedClientException. The problem is in the following lines (83-85 in 2.0.9.RELEASE):
`
                else if ("unauthorized_client".equals(errorCode)) {
                        ex = new UnauthorizedUserException(errorMessage);
                }
`

Should change the assignment of ex above to UnauthorizedClientException, and also have another else/if block for UnauthorizedUserException.

**Comment by jgdef** [comment]
OAuth2ExceptionDeserializerTests.java needs to be updated as well of course, it's checking for the wrong deserialized exception type.

**Comment by rwinch** [comment]
Thanks for the report! Do you want to rebase and send this as a PR!

**Comment by jgdef** [comment]
Sorry I missed the earlier rebase request. Thank you for making this fix.

**Comment by jgrandja** [comment]
No worries. Thanks for the report!
