### ISSUE TITLE
Incorrect assignment in OAuth2Request constructor

### ISSUE THREAD

**Issue by tomvandenberge** [spring-projects/spring-security-oauth#724]
In the public constructor of OAuth2Request, the resourceId parameter is not correctly set to the resourceId field:

```
if (resourceIds != null) {
	this.resourceIds = new HashSet<String>(resourceIds);
}
...
this.resourceIds = resourceIds;
```
If an object is provided, a defensive copy is made and assigned to the field, but later on the field is reassigned to the provided object.

I think the last assignment should be removed.

**Comment by jgrandja** [comment]
Thanks for catching that @tomvandenberge! This is now merged to master.
