### ISSUE TITLE
Documenting grant type strings

### ISSUE THREAD

**Issue by sthzg** [spring-projects/spring-security-oauth#731]
Do you think it would make sense to document the strings used to configure the standard flows in the [Configuring Client Details](https://github.com/spring-projects/spring-security-oauth/blob/master/docs/oauth2.md#configuring-client-details) section?

I thought it fits as an extension to the following bullet:

> `authorizedGrantTypes`: Grant types that are authorized for the client to use. Default value is empty.

Something like:

> `authorizedGrantTypes`: Grant types that are authorized for the client to use. Default value is empty. The default grant types as specified in the [RFC Section 1.3](https://tools.ietf.org/html/rfc6749#section-1.3) may be configured as `authorization_code`, `implicit`, `password` and `client_credentials`.

**Comment by rwinch** [comment]
Thanks for the report! I think that would be a great idea. Would you mind sending a PR for this?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
