### ISSUE TITLE
Incorrect reference to Sparklr app in Tonr app pom.xml (OAuth 1 example apps)

### ISSUE THREAD

**Issue by sa1nt** [spring-projects/spring-security-oauth#732]
When running the sample OAuth 1 Tonr app with `mvn tomcat7:run` command, trying to access Sparkl app results in a 404 Not Found error.

The reason, apparently, is that in samples/oauth/tonr/pom.xml file configuration for the tomcat7-maven-plugin reference to the Sparklr app looks like: `<contextPath>/sparklr2</contextPath>`

**Comment by rwinch** [comment]
Thanks for the PR this is now fixed via e30a7af8b1a98fe858fbf1c1448e4b88c3ea6c4a
