### ISSUE TITLE
Consider expires_in: 0 in access token response as token without expiration

### ISSUE THREAD

**Issue by ivan-babiankou** [spring-projects/spring-security-oauth#738]
There are providers who return 0 for tokens without expiration.

Example: https://vk.com/dev/permissions 
For offline(token never expires) access documentation has comment that expires_in will have value 0.

**Comment by rwinch** [comment]
Thanks for the report. We can make this an option to enable for the client

**Comment by ivan-babiankou** [comment]
Sounds good to me. 
Just FYI I've submitted pull request with implementation shortly after created issue. 

Ivan

**Comment by jgrandja** [comment]
Related to [gh-738](https://github.com/spring-projects/spring-security-oauth/pull/739)

**Comment by jgrandja** [comment]
Hi @ivan-babiankou. Thanks for your feedback here. I've reviewed your PR, however, it doesn't provide a way to configure the default **expires_in** (`accessTokenValiditySeconds`) to 0 for newly generated access tokens. I see you made some updates to `OAuth2AccessTokenJackson1Deserializer` and `OAuth2AccessTokenJackson2Deserializer`.

However, if we were to provide a custom value for `accessTokenValiditySeconds` for new access tokens then this would need to be supplied to an implementation of `AuthorizationServerTokenServices`. The default implementation is `DefaultTokenServices` and it may be reused and all you would need to do is call `setAccessTokenValiditySeconds(0)` and this would generate non-expiring access tokens. For example, extend `AuthorizationServerConfigurerAdapter` and override the following method:

```
		@Override
		public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			DefaultTokenServices tokenServices = new DefaultTokenServices();
			tokenServices.setAccessTokenValiditySeconds(0);
			endpoints.tokenServices(tokenServices);
		}

```

Additionally, there is another approach where you can configure individual clients with their own custom value for `accessTokenValiditySeconds`. For example, you can supply the `DefaultTokenServices` with an implementation of `ClientDetailsService` which ultimately returns a `ClientDetails` and has an accessor `getAccessTokenValiditySeconds`. This approach provides the most flexibility as you can configure a specific client to have non-expiring access tokens and another client to have an expiring access token.

```
	@Configuration
	@EnableWebSecurity
	@EnableAuthorizationServer
	public class AuthorizationServerTokenServicesConfig extends AuthorizationServerConfigurerAdapter {

		@Override
		public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			DefaultTokenServices tokenServices = new DefaultTokenServices();
			tokenServices.setClientDetailsService(new ClientDetailsService() {
				@Override
				public ClientDetails loadClientByClientId(String clientId) throws ClientRegistrationException {
					ClientDetails clientDetails = null;
					// Look up the pre-registered client in DB using JdbcClientDetailsService
					// OR
					// Look up the pre-registered client in memory using InMemoryClientDetailsService
					// OR
					// Hard coding but not recommending this approach...just demonstrating
					BaseClientDetails baseClientDetails = new BaseClientDetails();
					baseClientDetails.setAccessTokenValiditySeconds(0);
					// set the other attributes of the client...
					
					return clientDetails;
				}
			});
			
			endpoints.tokenServices(tokenServices);
		}

	}

```
So there are a couple of ways to configure non-expiring access tokens. I hope this helps?
I'm going to close the PR and this issue. I do appreciate you taking the time to put it together.
If you feel there is more discussion here then we can re-open this issue and go from there.
Thanks.

**Comment by justinhrobbins** [comment]
Is this Closed request the same as this Open request?

https://github.com/spring-projects/spring-security-oauth/issues/1172
