### ISSUE TITLE
oAuth : Incorrect result size: expected 1, actual 2 using jdbctokenstore

### ISSUE THREAD

**Issue by priyadevi** [spring-projects/spring-security-oauth#742]
Hi,
We faced an issue duplicate access token in spring oauth, we put  synchronized token service by extending DefaultTokenServices, but its not resolved.

We use  Oauth Version : oauth2:1.0.0
Spring Version:3.2.5.

Sample Data stored in database:
![image](https://cloud.githubusercontent.com/assets/1098585/14854150/2be8edda-0cac-11e6-8eb6-4383583c8c97.png)

Its very urgent , we faced these issue in production server.

**Comment by jebeaudet** [comment]
See https://github.com/spring-projects/spring-security-oauth/issues/276 or https://github.com/spring-projects/spring-security-oauth/issues/463

**Comment by rwinch** [comment]
Closing this as a duplicate of #463 See https://github.com/spring-projects/spring-security-oauth/issues/463#issuecomment-99086491 for a description of how to resolve this. The summary is:

* Set unique contraint on `authentication_id`
* Handle the `DuplicateKeyException`
