### ISSUE TITLE
Allow single "scope" in JWT without need for JSON array format?

### ISSUE THREAD

**Issue by vladimirlapacek** [spring-projects/spring-security-oauth#745]
Similarly to #557, some authorisation servers are producing JWTs with single scope, which is not enclosed in an array. IdentityServer3 using .Net JwtSecurityTokenHandler may be an example. Such tokens make `DefaultAccessTokenConverter.extractAuthentication` and `DefaultAccessTokenConverter. extractAccessToken` throw an exception because it expects only an array. Can we make the `DefaultAccessTokenConverter` to cope with a single scope also?

**Comment by jgrandja** [comment]
Thanks for the report @vladimirlapacek. This support has been added and is now in master.
