### ISSUE TITLE
Subdomain redirect matching in DefaultRedirectResolver accepts domains with same suffix

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-security-oauth#747]
the current implementation of [hostMatches(String,String)](https://github.com/spring-projects/spring-security-oauth/blob/ac142a6ce0c948aeb07837f7e8704dad4d3e3134/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/DefaultRedirectResolver.java#L133) looks like this:

	protected boolean hostMatches(String registered, String requested) {
		if (matchSubdomains) {
			return requested.endsWith(registered);
		}
		return registered.equals(requested);
	}

Assuming that 

* `registered = "example.com"`
* `matchSubdomains = true` (the default)
* `requested = "badexample.com"`

it is `"badexample.com".endsWith("example.com")` which is `true`

the implementation should be

	protected boolean hostMatches(String registered, String requested) {
		if (matchSubdomains) {
			return registered.equals(requested) || requested.endsWith("." + registered);
		}
		return registered.equals(requested);
	}

therefore `"badexample.com".equals("example.com") || "badexample.com".endsWith(".example.com")` which is `false`

**Comment by jgrandja** [comment]
Thanks for catching this @sfussenegger and for the detailed description and solution. This is now merged to master.
