### ISSUE TITLE
Disabling token endpoint security autoconfiguration in java config?

### ISSUE THREAD

**Issue by andreaceccanti** [spring-projects/spring-security-oauth#756]
Is there a way to disable autoconfiguration of security on the token endpoint when configuring an OAuth2  authorization service with AuthorizationServerConfigurer or the AuthorizationServerConfigurerAdapter ?

AFAIU (I may be wrong) this is possible with XML config.

My problem is that I want to have complete control on the AuthenticationManager provided and full access to the httpSecurity configuration. It seems to me this is not possible through AuthorizationServerSecurityConfigurer.

Thanks,
A.

**Comment by rwinch** [comment]
If you want access to the internals, you can always use WebSecurityConfigurerAdapter directly. You can get an idea for what is happening by looking at https://github.com/spring-projects/spring-security-oauth/blob/ac142a6ce0c948aeb07837f7e8704dad4d3e3134/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/annotation/web/configuration/AuthorizationServerSecurityConfiguration.java

**Comment by rwinch** [comment]
Closing this as I believe I have answered it. If you have additional questions, feel free to open a new ticket or reopen this one.

**Comment by andreaceccanti** [comment]
I think my question is still unanswered.

My point is that in AuthorizationServerConfigurer there are three responsibilities tightly bound and either you get everything or you have to do everything by hand. There's no way AFAIU to leverage the endpoints configurer and provide you own custom security config without having a unused spring-security filter chain lying around. 

My changes to the security configuration are minimal: 
- add additional authentication filters (but having control on the ordering not only in relation to the BasicAuthenticationFilter, and AFAIU this cannot be done with AuthorizationServerSecurityConfigurer)
- enable OPTIONS on the token endpoint for unauthenticated clients
- add a CORS filter

I was already doing this in a separate WebSecurityConfigurerAdapter but then I found out that my config was never triggered because the default one created by AuthorizationServerConfigurer was triggered instead.

Is there a way to leverage the  AuthorizationServerConfigurer for configuring the endpoints and disable the automatic security configuration?

If the answer is no, as I expect, are there plans to introduce this possibility in the future?

Thanks
