### ISSUE TITLE
oauth/token - Request method 'POST' not supported",

### ISSUE THREAD

**Issue by ncrajumcad** [spring-projects/spring-security-oauth#757]
Getting below issue when I am using spring-security-oauth2.jar 2.0.8.RELEASE.  Same war file is working fine in other servers. Using 2.0.9.RELEASE works fine in all servers. Don't have clue what is happening
{
  "timestamp" : "2016-05-10T17:57:59.821+0000",
  "status" : 405,
  "error" : "Method Not Allowed",
  "exception" : "org.springframework.web.HttpRequestMethodNotSupportedException",
  "message" : "Request method 'POST' not supported",
  "path" : "/restservicestest/oauth/token"
}

**Comment by rwinch** [comment]
> Using 2.0.9.RELEASE works fine in all servers.

I'm not sure I understand. It sounds as though it is working w/ the latest release? If so, what is the problem?

**Comment by ncrajumcad** [comment]
I need to find out the root cause for the issue with 2.0.8 version.  Same war file working differtly in two servers. Where two servers are running on  same java and tomcat version.

**Comment by rwinch** [comment]
Can't you just update and have it work everywhere?

**Comment by rwinch** [comment]
Closing since it works with 2.0.9

**Comment by dydaniely** [comment]
did you get an answer? why don't you update it
