### ISSUE TITLE
OAuth2 developers guide is down

### ISSUE THREAD

**Issue by SlimeQ** [spring-projects/spring-security-oauth#759]
http://projects.spring.io/spring-security-oauth/docs/oauth2.md
![screenshot from 2016-05-12 16 13 29](https://cloud.githubusercontent.com/assets/3934698/15228944/87a7538a-185c-11e6-91f6-a494490541fa.png)

**Comment by SlimeQ** [comment]
there appears to be a pull request for this, though it is showing an error because CI is borked
https://github.com/spring-projects/spring-security-oauth/pull/729

**Comment by dsyer** [comment]
Should be fixed now. Thanks.
