### ISSUE TITLE
authorization_code redirect sometimes get's enhanced

### ISSUE THREAD

**Issue by fhanik** [spring-projects/spring-security-oauth#766]
A redirect to the authorization server `/oauth/authorize` endpoint happens during two different flows
During a new flow, where [state key is null ](https://github.com/spring-projects/spring-security-oauth/blob/8fe9add8665e92b1a67dc7dca8636b93e086e6dd/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/token/grant/code/AuthorizationCodeAccessTokenProvider.java#L206-L206) a redirect is issued without invoking the request enhancer.

And there is [another flow](https://github.com/spring-projects/spring-security-oauth/blob/8fe9add8665e92b1a67dc7dca8636b93e086e6dd/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/token/grant/code/AuthorizationCodeAccessTokenProvider.java#L183) the redirect is happening with the request enhancer invoked.

One can [add the request enhancer](https://github.com/cf-identity/spring-security-oauth/compare/feature/readme-fixes...cf-identity:feature/auth_code_request_enhancer_during_redirect?expand=1&w=1) to the first call 

or allow the AuthorizationCodeAccessTokenProvider to be [extended](https://github.com/cf-identity/spring-security-oauth/compare/feature/readme-fixes...cf-identity:feature/oidc_during_authcode?expand=1&w=1) by making the `getRedirectForAuthorization` method protected.

There may be some room for consolidation of the two locations that issue the redirect. 
Any thoughts on the issue, and I can create a pull request.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
