### ISSUE TITLE
Unable to set custom AuthenticationEntryPoint when using 'client_credentials' oAuth2 authentication

### ISSUE THREAD

**Issue by romanwozniak** [spring-projects/spring-security-oauth#774]
I want to specify my own AuthenticationEntryPoint for requests to `/oauth/token` with `grant_type=client_credentials` (with Basic or Form authentication). The purpose of this is the ability to customize response, when request was made with invalid credentials.

Currently, when I do request like this:
```
curl -u InvalidClient:client_secret http://localhost:9000/api/external/v1/oauth/token -d 'grant_type=client_credentials'
```
where `InvalidClient` is an invalid client_id,
I get standard response from BasicAuthenticationEntryPoint, which looks like this:
```
<html>
    <head>
        <title>Apache Tomcat/7.0.47 - Error report</title>
        <style>...</style>
    </head>
    <body>
        <h1>HTTP Status 401 - Bad credentials</h1>
        <HR size="1" noshade="noshade">
        <p>
            <b>type</b> Status report
        </p>
        <p>
            <b>message</b>
            <u>Bad credentials</u>
        </p>
        <p>
            <b>description</b>
            <u>This request requires HTTP authentication.</u>
        </p>
        <HR size="1" noshade="noshade">
        <h3>Apache Tomcat/7.0.47</h3>
    </body>
</html>
```

That is because `org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer` creates new BasicAuthenticationFilter with default BasicAuthenticationEntryPoint at the moment of call to `init(HttpSecurity http)`
```java
@Override
public void init(HttpSecurity http) throws Exception {
	registerDefaultAuthenticationEntryPoint(http);
	if (passwordEncoder != null) {
		http.getSharedObject(AuthenticationManagerBuilder.class)
				.userDetailsService(new ClientDetailsUserDetailsService(clientDetailsService()))
				.passwordEncoder(passwordEncoder());
	}
	else {
		http.userDetailsService(new ClientDetailsUserDetailsService(clientDetailsService()));
	}

	// call to .httpBasic creates HttpBasicConfigurer which will create BasicAuthenticationFilter
	http.securityContext().securityContextRepository(new NullSecurityContextRepository()).and().csrf().disable()
			.httpBasic().realmName(realm);
}
```

So the short question is: how to return JSON response in answer to Basic authentication request with `grant_type=client_credentials`, when provided credentials are invalid.

Thanks.

**Comment by romanwozniak** [comment]
Not an issue anymore.
Required behaviour can be achieved by defining customized filter in

```java
@Override
public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
    oauthServer
            .realm(RESOURCE_ID + "/client")
            .accessDeniedHandler(accessDeniedHandler)
            .authenticationEntryPoint(entryPoint);

    // Adding customized filter
    oauthServer.addTokenEndpointAuthenticationFilter(
            new BasicAuthenticationFilter(authenticationManager, entryPoint));
}
```

**Comment by jmart1** [comment]
@romanwozniak  your solution did not work for me.  The problem is that the credentials for the client, end up being used as the credentials for the user.

**Comment by vicykie** [comment]
> Not an issue anymore.
> Required behaviour can be achieved by defining customized filter in
> 
> ```java
> @Override
> public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
>     oauthServer
>             .realm(RESOURCE_ID + "/client")
>             .accessDeniedHandler(accessDeniedHandler)
>             .authenticationEntryPoint(entryPoint);
> 
>     // Adding customized filter
>     oauthServer.addTokenEndpointAuthenticationFilter(
>             new BasicAuthenticationFilter(authenticationManager, entryPoint));
> }
> ```

when i add custom TokenEndpointAuthenticationFilter ,this userdetailsService will be change  from ClientDetailsUserDetailsService to my custom userDetailsService . this will be cause authorization failed from header`s values

**Comment by DoneSpeak** [comment]
> > Not an issue anymore.
> > Required behaviour can be achieved by defining customized filter in
> > ```java
> > @Override
> > public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
> >     oauthServer
> >             .realm(RESOURCE_ID + "/client")
> >             .accessDeniedHandler(accessDeniedHandler)
> >             .authenticationEntryPoint(entryPoint);
> > 
> >     // Adding customized filter
> >     oauthServer.addTokenEndpointAuthenticationFilter(
> >             new BasicAuthenticationFilter(authenticationManager, entryPoint));
> > }
> > ```
> 
> when i add custom TokenEndpointAuthenticationFilter ,this userdetailsService will be change from ClientDetailsUserDetailsService to my custom userDetailsService . this will be cause authorization failed from header`s values

Is there any solution for this? @vicykie @romanwozniak
