### ISSUE TITLE
How to configure request matchers with @EnableResourceServer and @EnableAuthorizationServer

### ISSUE THREAD

**Issue by jtheuer** [spring-projects/spring-security-oauth#789]
Hi, I set up a minimal authorization server:

```
@SpringBootApplication
@RestController
public class OAuth2Application extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication() //... your credentials here
	}

	@Configuration
	@EnableAuthorizationServer
	public static class OAuth2AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {

		@Autowired
		private AuthenticationManager authenticationManager;

		@Override
		public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			endpoints
					.authenticationManager(authenticationManager)
					.accessTokenConverter(accessTokenConverter())
					.tokenStore(tokenStore());
		}

		@Bean
		public TokenStore tokenStore() {
			return new JwtTokenStore(accessTokenConverter());
		}

		@Bean
		public JwtAccessTokenConverter accessTokenConverter() {
			JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
			converter.setSigningKey("foo");
			return converter;
		}

		@Bean
		@Primary
		public DefaultTokenServices tokenServices() {
			DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
			defaultTokenServices.setTokenStore(tokenStore());
			defaultTokenServices.setSupportRefreshToken(true);
			return defaultTokenServices;
		}

		@Override
		public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
			clients.inMemory()
					.withClient("client1")
					.authorizedGrantTypes("access_token", "refresh_token", "authorization_code")
					.authorities("ROLE_CLIENT", "ROLE_TRUSTED_CLIENT")
					.scopes("private-tours", "profile")
					.secret("secret")
					.accessTokenValiditySeconds(60)
					.refreshTokenValiditySeconds(160);
		}
	}

	public static void main(String[] args) {
		SpringApplication.run(OAuth2Application.class, args);
	}
}
```

I could successfully connect with an oauth2 client, e.g. I was redirected to /login as first step.

Now I wanted to add a ```/me``` resource and therefore added ```@EnableResourceServer```:

```
	@Configuration
	@EnableAuthorizationServer
	@EnableResourceServer
	public static class OAuth2AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter 

```

Without any other change, the ```/login``` does not work anymore, I get the message ```Full authentication is required to access this resource```

(1) Did I place the ```@EnableResourceServer``` annotation correctly?
(2) What is the cleanest way to configure the security correctly?
(3) Why does the annotation have this side-effect? As a developer, I would expect that they work together.

**Comment by dsyer** [comment]
In general you might have to configure the request matchers for the app (i.e. `/login`, `/oauth/*` etc.) and the resources (/me etc.). By default the resource server has a matcher for everything except `/oauth/*`, but you have added a `WebSecurityConfigurerAdapter` with default order, which matches all requests, and hence your resource server filter chain is never used. You could change the order of your custom one (or since it is not explicitly configureing HTTP security, just remove it).

**Comment by jtheuer** [comment]
Good explanation, I get the point, now!
Maybe a later version of spring-security finds a cleaner way to "mixin" http security of several modules without interfering with each other. Probably a more difficult part since rules can overlap.
Thanks!
