### ISSUE TITLE
Retrieve Oauth2 additionalInformations while not using JWT

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-security-oauth#797]
Hi, I'm implementing Oauth2 in our applications. I'm using jdbc store for storing tokens.
I would like to add some additional informations to authentication on UAA server so I've implemented [TokenEnhancer](http://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/provider/token/TokenEnhancer.html):

    public class CustomTokenEnhancer implements TokenEnhancer {

	private static final Logger logger = LoggerFactory.getLogger(CustomTokenEnhancer.class);

	@Override
	public OAuth2AccessToken enhance(OAuth2AccessToken accessToken, OAuth2Authentication authentication) {
		if (authentication.getUserAuthentication().getPrincipal().getClass().isAssignableFrom(CustomUserDetails.class)) {
			logger.debug("Enhancing token with custom metadata");
			final Map<String, Object> additionalInfo = new HashMap<>();
			CustomUserDetails customUserDetails = (CustomUserDetails) authentication.getPrincipal();
			additionalInfo.put(C.METADATA_CURRENT_USER_ID, customUserDetails.getId());
			additionalInfo.put(C.METADATA_CURRENT_USER_DEFAULT_LANGUAGE, customUserDetails.getDefaultLanguage());
			((DefaultOAuth2AccessToken) accessToken).setAdditionalInformation(additionalInfo);
		}
		return accessToken;
	}
}

On the client side I'd like to access those informations, but while I'm not using JWT I don't know how to access [OAuth2AccessToken](http://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/common/OAuth2AccessToken.html).

I was trying with this method

    Principal principal = SecurityContextHolder.getContext().getAuthentication();
    if (principal.getClass().isAssignableFrom(OAuth2Authentication.class)) {
    	OAuth2Authentication oAuth2Authentication = (OAuth2Authentication) SecurityContextHolder.getContext().getAuthentication();
    	OAuth2AuthenticationDetails auth2AuthenticationDetails = (OAuth2AuthenticationDetails) oAuth2Authentication.getDetails();
    	OAuth2AccessToken accessToken = remoteTokenServices.readAccessToken(auth2AuthenticationDetails.getTokenValue());
    	Map<String, Object> additionalInformations = accessToken.getAdditionalInformation();
    }

but at the end I realised that [RemoteTokenServices.readAccessToken()](http://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/provider/token/RemoteTokenServices.html#readAccessToken(java.lang.String)) reading is not supported (?due to security reasons?).

So is it possible somehow access additionalInformations through accessToken and remoteServices or do I need to read it through database?
Or is there any other way how can I access CustomUserDetails from Authentication in client application?

Thanks

**Comment by bilak** [comment]
@dsyer can you help me with this? Thanks

**Comment by dsyer** [comment]
Where did the `OAuth2Authentication` come from (probably from a `ResourceServerTokenServices`, possibly already a  `RemoteTokenServices`)? Isn't that where you should be looking to modify something, if anything? I believe there's a `TokenConverter` strategy you can plug in, and you also might have to look at the auth server (if you control it) to see if it is actually sending you the additional info.

**Comment by bilak** [comment]
@dsyer that should work. However currently my RemoteTokenServices is always replaced with one from org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration. Is there any simple way how to "reconfigure" the RemoteTokenServices?

this is my config class on resource application

```
@Configuration
public class Oauth2Configuration {

	@Autowired
	private ResourceServerProperties resource;

	@Bean
	public ResourceServerTokenServices remoteTokenServices() {
		RemoteTokenServices services = new RemoteTokenServices();
		services.setCheckTokenEndpointUrl(this.resource.getTokenInfoUri());
		services.setClientId(this.resource.getClientId());
		services.setClientSecret(this.resource.getClientSecret());
		services.setAccessTokenConverter(docuTokenConverter());
		return services;
	}

	@Bean
	DocuAccessTokenConverter docuTokenConverter() {
		return new DocuAccessTokenConverter();
	}
}
```


```
Overriding bean definition for bean 'remoteTokenServices' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=oauth2Configuration; factoryMethodName=remoteTokenServices; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/github/bilak/test/security/configuration/Oauth2Configuration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration$RemoteTokenServicesConfiguration$TokenInfoServicesConfiguration; factoryMethodName=remoteTokenServices; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$RemoteTokenServicesConfiguration$TokenInfoServicesConfiguration.class]]
```

**Comment by bilak** [comment]
I figured it out by adding `@Import(value = { ResourceServerTokenServicesConfiguration.class })` to the Oauth2Configuration (don't know if this is correct).

**Comment by dsyer** [comment]
That's one way, I guess. If it was me I'd look for a way just switch off the autconfig by *not* configuring the relevant bits of `security.oauth2.*`.
