### ISSUE TITLE
Unchecked exception: ArrayStoreException when thrown from ClientDetailsService.loadClientByClientId is silently lost 

### ISSUE THREAD

**Issue by bitsofinfo** [spring-projects/spring-security-oauth#803]
Had a case where some buggy code I had in a custom implementation of `ClientDetailsService.loadClientByClientId()` threw an unchecked ArrayStoreException. 

Due to this my oauth authorization server was not working and I spent many hours racking my head trying to figure out why this was not working as the logs showed absolutely nothing (was running in debug mode) indicating any error/exception other than a 401 and my auth was simply invalid.... 

Once I got into the debugger, I noticed the code was throwing an ArrayStoreException. Eventually this was bubbling up to `BasicAuthenticationFilter.doFilterInternal` line ~192 https://github.com/spring-projects/spring-security/blob/ce20cfcb9803a6175f6befc9008cadcc4e3b6d72/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java#L194

Its just logged as a generic message (below), no indication of this underlying exception. Maybe I have something configured wrong, but this was a real time consumer.

```o.s.s.w.a.www.BasicAuthenticationFilter  : Authentication request for failed: org.springframework.security.authentication.InternalAuthenticationServiceException```

Now this was ultimately due to a bug in my code, maybe I am missing a config option to get more detail on an auth failure in logs, but I think this logging could be improved.

**Comment by dsyer** [comment]
I think `InternalAuthenticationServiceException` is supposed to tell you to go and test your authentication (usually it's a database error or something). For sure you wouldn't want this to bubble up to the user. But in any case basic auth is a core spring security feature (not OAuth), so I'm afraid it's not relevant here.

**Comment by bitsofinfo** [comment]
Yeah definitely not up to the user, but possibly just a getMessage() on the causal exception would be helpful. But w/ any authn/z system, putting impl sourced messages in logs can be risky, who knows what could show up.
