### ISSUE TITLE
Spring Security OAuth2 Rejects Non-Spring Clients

### ISSUE THREAD

**Issue by DollarCoffee** [spring-projects/spring-security-oauth#806]
The <a href="https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2">Spring OAuth2 sample app on GitHub</a> treats non-Spring clients differently than it treats the Spring `ui` client in its sample configuration. The problem might be in how the filter chain in front of the token endpoint is configured.  Here are the specifics:
<hr/>
The Spring OAuth2 `ui` client was carefully translated into Node.js to avoid any confusion in re-creating the conditions under which the Spring OAuth2 `ui` sample app works. The new node.js client is able to initiate Step A of the flow by redirecting to the Spring OAuth2 `authserver` app. The `authserver` app is able to authenticate the user and redirect back to the Node.js client in Step C of the flow. However, then the client app then initiates Step D of the flow, the `authserver` app rejects the request as anonymous in what would otherwise be Step E of the flow. Here are the logs in the `nodemon` console:
  
    Finished Step C of Authorization Code Flow. Welcome back from authserver
    queryData.code is: Z3B1mb
    About to start Step D of Authorization Code Flow.
    The POST is finished. Waiting for response.
    Step D. Token Request Sent To AuthServer.
    JSON data response is: [object Object]
    access token is: undefined
    error is: unauthorized

The following routing code that isolates at the lowest level the steps that the Node.js client takes to try to connect with Spring OAuth2 `authserver`.
    
    var url = require('url');
    var request = require('request');
    
    // expose the routes to our app with module.exports
    module.exports = function(app) {
    
        // application --------------------------------
        app.get('/resource/**', function(req, res) {
            console.log("You Hit The Resource Route TOP. ");
            request.get('http://localhost:9000/resource', function (error, response, body) {
                if(error) {console.log('ERROR with resource request.')}    
                if (!error){// && response.statusCode == 200) { 
                    console.log(response.statusCode);   
                    console.log(body); 
                };
            });
            console.log("You Hit The Resource Route BOTTOM. ");
        });
        
        app.get('/user**', function(req, res) {
            console.log("You Hit The User Route TOP");
            request.get('http://localhost:9999/uaa/user', function (error, response, body) {
                if(error) {console.log('ERROR with user request.')}
                if (!error){// && response.statusCode == 200)
                { 
                    console.log(response.statusCode); 
                    console.log(body); 
                    console.log("response is: ");
                    console.log(response);
                    console.log("end of response."); 
                };
            });
             console.log("You Hit The User Route BOTTOM");
        });
    
        app.get('/login', function(req, res) {
            console.log("You Hit The Login Route ");
            console.log("headers are: "); console.log(req.headers);
            console.log("cookies are: "); console.log(req.cookies);
            console.log("params are: "); console.log(req.params);
            console.log("body is: "); console.log(req.body);
            console.log("method is: "); console.log(req.method);
            console.log("query is: "); console.log(req.query);
            console.log("route is: "); console.log(req.route);
            console.log("signedCookies are: "); console.log(req.signedCookies);
            var queryData = url.parse(req.url, true).query;
    
            if (queryData.code) {
                //This is the end of Step C in the flow
                // "code" was in the GET request, ex: http://localhost:8080/login?code=w6zGJO&state=IuaO63
                console.log('Finished Step C of Authorization Code Flow. Welcome back from authserver');
                console.log('queryData.code is: ' + queryData.code);
                //Now start Step D in the flow
                console.log('About to start Step D of Authorization Code Flow. ');
                request.post('http://localhost:9999/uaa/oauth/token?grant_type=authorization_code&code='queryData.code'&client_id=acme&redirect_uri=http://localhost:8080/login', function(err, response, body){
                    // Step E is the response received as follows:
                    if(err) {console.log('ERROR with token request.')}
        
                        var data = JSON.parse(body);
                        console.log('JSON data response is: ' + data);
                        var variable1 = data.access_token;
                        var variable2 = data.token_type;
                        var variable3 = data.error;
                        console.log('access token is: ' + variable1);
                        console.log('error is: ' + variable3);
                        //Do more processing here
                    });
                console.log('The POST is finished. Waiting for response.');
                console.log('Step D. Token Request Sent To AuthServer.');
            } else { 
                //This is Step A console.log('Step A of Authorization Code flow about to start. ');
              res.redirect('http://localhost:9999/uaa/oauth/authorize?client_id=acme&redirect_uri=http://localhost:8080/login&response_type=code&state=IuaO63'); }
        });

        app.get('*', function(req, res) { 
            res.sendfile('./public/index.html'); // load single view file (angular will handle the front-end) }    
        );
        };
    
**So how do we fix this?**

**Comment by dsyer** [comment]
I can't see anywhere where you authenticate the request to the /token endpoint (so it's unsurprising it comes back as a 401). In the spec it says that clients must authenticate with the auth server (https://tools.ietf.org/html/rfc6749#section-3.2.1). The default in Spring OAuth is HTTP Basic using the client id and secret (it's all in the user guide).

**Comment by DollarCoffee** [comment]
Thank you.  I have been carefully studying both the entire official spec, and your entire written documentation, for some time now.  I think what is missing are cook-book-like instructions for common tasks.  Like, for example, simply showing the contents of a valid HTTP request and response for each step of a flow, in digest form so that it is easier for developers to extract the salient points when they study 50 to 100 page manuals.  
  
I was able to resolve the current problem by using your suggestion.  I hope that this posting helps others who encounter the same problem.
