### ISSUE TITLE
Spring Framework warns TokenKeyEndpointRegistrar

### ISSUE THREAD

**Issue by sunnyone** [spring-projects/spring-security-oauth#809]
ConfigurationClassPostProcessor warns TokenKeyEndpointRegistrar configuration with newer Spring Framework (4.2.7).

> o.s.c.a.ConfigurationClassPostProcessor : Cannot enhance @Configuration bean definition 'org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration$TokenKeyEndpointRegistrar' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.

This is probably caused by the change of [SPR-14234](https://jira.spring.io/browse/SPR-14234), though I don't know a correct way to remove this warning. The comment of SPR-14234 seems to recommend to create a static @Bean method.

**Comment by philippeboyd** [comment]
Having the same warning with Spring FW 4.3.1

**Comment by mrsarm** [comment]
I have the same issue, if you build and run this [project](https://github.com/dynamind/spring-boot-security-oauth2-minimal) works ok, but if you update its dependencies to spring-boot libraries >= 1.3.4, you will get this issue, but as you can see the source code, all the beans are created in static classes. So the problem looks like a framework issue in the class `AuthorizationServerEndpointsConfiguration` of the library `spring-security-oauth2`.

**Comment by WarlaxZ** [comment]
+1

**Comment by dsyer** [comment]
Can anyone explain why this is a problem? All my auth servers work fine even with the warning.
