### ISSUE TITLE
Authorization Server and OAuth2 Client don't agree on HTTP status codes

### ISSUE THREAD

**Issue by shanman190** [spring-projects/spring-security-oauth#810]
I've setup a basic test showcasing the issue that I'm seeing and the results that I would have expected. The test case that fails specifically is the `access_admin_forbidden` test. The gist is that the server returns a 403 response code from the denied access, but when the client is processing the response it creates a UserDeniedAuthorizationException whose status code is set to 400. There appears to be a discrepancy, but I'd like to solicit some feedback before creating a PR.

```java
package demo.oauth;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.boot.test.TestRestTemplate;
import org.springframework.boot.test.WebIntegrationTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.oauth2.client.OAuth2RestTemplate;
import org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsResourceDetails;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableResourceServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import static org.junit.Assert.assertEquals;

@RunWith(SpringJUnit4ClassRunner.class)
@WebIntegrationTest(randomPort = true)
@SpringApplicationConfiguration(classes = DemoOAuth2Application.class)
public class DemoOAuth2ApplicationTests {
    @Value("${local.server.port}")
    private int port;

    @Test
    public void contextLoads() {
    }

    @Test
    public void access_open_granted() {
        TestRestTemplate rest = new TestRestTemplate();

        ResponseEntity<String> response = rest.getForEntity("http://localhost:" + this.port + "/open", String.class);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("open", response.getBody());
    }

    @Test
    public void access_protected_granted() {
        ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
        details.setClientId("standard");
        details.setClientSecret("secret");
        details.setAccessTokenUri("http://localhost:" + this.port + "/oauth/token");
        OAuth2RestTemplate rest = new OAuth2RestTemplate(details);

        ResponseEntity<String> response = rest.getForEntity("http://localhost:" + this.port + "/protected", String.class);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("protected", response.getBody());
    }

    @Test
    public void access_admin_granted() {
        ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
        details.setClientId("admin");
        details.setClientSecret("secret");
        details.setAccessTokenUri("http://localhost:" + this.port + "/oauth/token");
        OAuth2RestTemplate rest = new OAuth2RestTemplate(details);

        ResponseEntity<String> response = rest.getForEntity("http://localhost:" + this.port + "/admin", String.class);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("admin", response.getBody());
    }

    @Test
    public void access_admin_forbidden() {
        ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
        details.setClientId("standard");
        details.setClientSecret("secret");
        details.setAccessTokenUri("http://localhost:" + this.port + "/oauth/token");
        OAuth2RestTemplate rest = new OAuth2RestTemplate(details);

        ResponseEntity<String> response = rest.getForEntity("http://localhost:" + this.port + "/admin", String.class);

        assertEquals(HttpStatus.FORBIDDEN, response.getStatusCode());
    }
}

@Configuration
@EnableAutoConfiguration
@RestController
@EnableAuthorizationServer
@EnableResourceServer
class DemoOAuth2Application {
    public static void main(String[] args) {
        SpringApplication.run(DemoOAuth2Application.class);
    }

    @RequestMapping("/open")
    public String openEndpoint() {
        return "open";
    }

    @RequestMapping("/protected")
    public String protectedEndpoint() {
        return "protected";
    }

    @RequestMapping("/admin")
    public String adminEndpoint() {
        return "admin";
    }

    @Configuration
    protected static class AuthConfig extends AuthorizationServerConfigurerAdapter {
        @Override
        public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
            clients.inMemory()
                        .withClient("standard")
                            .secret("secret")
                            .authorizedGrantTypes("client_credentials")
                            .scopes("read")
                    .and()
                        .withClient("admin")
                            .secret("secret")
                            .authorizedGrantTypes("client_credentials")
                            .scopes("read")
                            .authorities("ROLE_ADMIN");
        }

        @Override
        public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
            security.tokenKeyAccess("permitAll()").checkTokenAccess("isAuthenticated()");
        }
    }

    @Configuration
    protected static class ResourceConfig extends ResourceServerConfigurerAdapter {
        @Override
        public void configure(HttpSecurity http) throws Exception {
            http.authorizeRequests()
                    .antMatchers("/open").permitAll()
                    .antMatchers("/admin").hasRole("ADMIN")
                    .anyRequest().authenticated();
        }
    }
}
```

Here's my build file:
```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:1.3.+"
    }
}

apply plugin: 'java'
apply plugin: 'spring-boot'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-web"
    compile "org.springframework.security.oauth:spring-security-oauth2"

    testCompile "org.springframework.boot:spring-boot-starter-test"
}
```

**Comment by dsyer** [comment]
`UserDeniedAuthorizationException` isn't really the same as a 403 at all, so I'm not sure why it does that. It looks like the client is wrong to me.

**Comment by jgrandja** [comment]
Hi @shanman190. Thanks for reporting this!....and providing a full sample!

Yes, you are correct the server does return 403 but when the response is unmarshalled by the `RestTemplate` client using `OAuth2ExceptionJackson2Deserializer` it translates/maps the error code as follows:

```
		else if ("access_denied".equals(errorCode)) {
			ex = new UserDeniedAuthorizationException(errorMessage);
		}
```
It would make more sense if the mapped exception is `OAuth2AccessDeniedException`  for 403's.

Would you be interested in submitting a PR for this fix?

**Comment by shanman190** [comment]
Yeah, sure! I'll try to get a PR fashioned over the next couple of days.

**Comment by jgrandja** [comment]
Thanks for submitting the PR @shanman190.

However, I looked at the code in more detail and the root issue is actually more involved. Based on your test, the client authenticates successfully and obtains an access token but when it tries to access the protected resource `/admin`, it does not have the authority `ROLE_ADMIN` and therefore Spring Security throws an `AccessDeniedException`. To be clear, this is a Spring Security specific exception and **not** an OAuth specific exception. However, the response body that comes back when accessing `/admin` is:

```
{
  "error": "access_denied",
  "error_description": "Access is denied"
}
```

This indicates it's an OAuth specific error and it's not. The response body should be **empty** with status 403. We're going to have to apply changes to `OAuth2AccessDeniedHandler` and it's associated `DefaultWebResponseExceptionTranslator` as well.

Also, the `OAuth2ExceptionJackson2Deserializer`  is always expecting an OAuth specific exception for 40x series status codes. However, this is not always the case as proven by your test case. So additional changes will be required in the Jackson Deserializer's to handle exceptions that are not OAuth specific.

**Comment by shanman190** [comment]
I can partially see what you saying, but the way that I'm seeing this is that on the server side it's doing things correctly. Spring security states that access to the `/admin` protected resource is denied because our user does not have the `ROLE_ADMIN` authority as you descibed and we fall through the AccessDeniedHandler which is OAuth specific and returns the expected 403 HTTP status code. It could be debatable what the response body should look like, but I don't know.

The client side however was completely off and returning the wrong status code on the AccessDenied error.

To me, it would make sense that the response, since it's completely handled by Spring Security and with this the OAuth customization, be OAuth specific.

**Comment by jgrandja** [comment]
If you look at the spec in the following _**Error Response**_ sections:

[Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1.2)
[Implicit Grant](https://tools.ietf.org/html/rfc6749#section-4.2.1)

these are the only 2 grant flows that may return:

```
{
  "error": "access_denied",
  ....
}
```

```
access_denied
               The resource owner or authorization server denied the request.
```

Your test case is using the **client_credentials** grant flow and returning the same response which is not applicable for this flow as per spec.

Agreed, Spring Security is working as expected but the specific implementation of `AccessDeniedHandler`, specifically, `OAuth2AccessDeniedHandler` is not implemented as per spec and returning an invalid response which is misleading the client.

The client should be able to handle non-specific OAuth errors like a straight 403. Even if the response returned an empty body with 403 status, the client still won't work based on the current code. It will still translate the 403 to 400. The server and client requires changes to make this response negotiation working.

**Comment by shanman190** [comment]
I see what you're talking about now.

However, the spec isn't stating anything about the authorization to the resource and what it's response types should look like. The reason that implicit and authorization code are the only ones that have the authorization error responses are because they are the only grant types that require you to call the authorization server's `/authorize` endpoint which is where those response types are required.

As to how the resource server should respond when authentication or authorization fails is definitely a question. To me, it now seems odd that for resource server that it would return responses that mirror the error responses that are defined by the authorization server's `/authorize`endpoint. However, having the consistent status codes I believe is a must.

**Comment by jgrandja** [comment]
Agreed, the status must be 403 but the response body should not mirror the `/authorize` endpoint response given that `client_credentials` flow calls the `/token` endpoint only. Keep in mind that the OAuth handshake is complete before the call to `/admin`  so any responses generated from subsequent calls (after the handshake) should not be oauth-specific responses as is the case today.

**Comment by shanman190** [comment]
Completely agree. Although there is no requirement that they explicitly not match, but it is a bit confusing as far as the spec is concerned.

On another note, causing a large amount of change in this area could have possible downstream API-breaking ramifications, so while attempting to rectify this issue we should definitely keep that in mind.

With that being said, should a new ticket be opened to more appropriately address the larger response issue or is the intent to morph this ticket to fix the response issues?

**Comment by jgrandja** [comment]
I decided not to apply any changes `OAuth2AccessDeniedHandler` as this was too risky of a change that may break existing clients. Although the response body is misleading IMO for 403 status, we just need to ensure the client is handling the 2 scenarios correctly.

I've created a new issue to address this. Closing this PR in favour of #875.

Thanks for all your feedback @shanman190 !

**Comment by shanman190** [comment]
You're welcome, @jgrandja!

**Comment by mickaeltr** [comment]
Hello,

I am really not sure but maybe I am meeting the same kind of issue. When my access token is invalid or expired, server (Salesforce, to be precise) returns that kind of response:
```
HttpResponseProxy{HTTP/1.1 401 Unauthorized [Date: Tue, 01 Oct 2019 16:56:33 GMT, Strict-Transport-Security: max-age=31536000; includeSubDomains, Public-Key-Pins-Report-Only: pin-sha256="XXX"; pin-sha256="YYY"; pin-sha256="ZZZ"; max-age=86400; includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/nullm";, Expect-CT: max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/nullm", X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, X-Robots-Tag: none, Cache-Control: no-cache,must-revalidate,max-age=0,no-store,private, WWW-Authenticate: Token, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}
```

This is translated into `OAuth2Exception: error="invalid_request", error_description="OAuth Error"`

While I would expect this error to eventually trigger a new access token generation, it just fails as a `HttpClientErrorException$Unauthorized: 401 Unauthorized`

Stacktrace is the following:
```
[1] Caused by: org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 Unauthorized
[1]     at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:81)
[1]     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
[1]     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
[1]     at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:172)
```

Any hint would be appreciated 😊

**Comment by shanman190** [comment]
@mickaeltr, so I happened to have run into a similar use case as you have, since at my organization we use Salesforce as well, but this issue isn't quite related to this ticket. As the Spring team always says on tickets, stackoverflow.com is a better place for asking questions with regards to implementing features using the Spring portfolio.

Essentially, you're going to need to override the `AccessDeniedHandler`, if I'm remembering correctly, as Salesforce's responses look a little different that the exact OAuth 2 specification that @jgrandja linked to earlier (`WWW-Authenticate` header with differing content). The Spring Security team has formulated the `OAuthAccessDeniedHandler` as per the specification, but from there it is upon the resource servers to implement it correctly.

**Comment by mickaeltr** [comment]
Thanks @shanman190, we ended up coding our own `OAuth2ErrorHandler`:
```java
public class SalesforceOAuth2ErrorHandler extends OAuth2ErrorHandler {

  public SalesforceOAuth2ErrorHandler(OAuth2ProtectedResourceDetails resource) {
    super(resource);
  }

  @Override
  public void handleError(ClientHttpResponse response) throws CredentialsExpiredException, IOException {
    if (response.getStatusCode() == HttpStatus.UNAUTHORIZED) {
      throw new InvalidTokenException("401 Unauthorized");
    }
    super.handleError(response);
  }

}
```
