### ISSUE TITLE
BaseRequest re-wraps requestParameters setter as unmodifiableMap

### ISSUE THREAD

**Issue by theRCexp** [spring-projects/spring-security-oauth#812]
The `requestParameters` setter in the BaseRequest class re-wraps the passed `Map<String, String> requestParameters` argument as a `Collections.unmodifiableMap` regardless of whether or not the argument is already of that type.  This issue is observable when using the `requestParameters` attribute of one BaseRequest object (which is already of type `Collections.unmodifiableMap`) to set the `requestParameters` attribute of another.  

This example test below (which fails) demonstrates this issue using the OAuth2Request concrete child class and serialization:

```
@Test
public void testRequestParametersReAssignmentWithSerialization() {
    Map<String, String> requestParameters = new HashMap<String, String>();
    requestParameters.put("key", "value");

    OAuth2Request request = new OAuth2Request(
        requestParameters, "clientId", Collections.<GrantedAuthority>emptyList(),
        false, Collections.<String>emptySet(), Collections.<String>emptySet(), "redirectUri",  
        Collections.<String>emptySet(), Collections.<String, Serializable>emptyMap());

    OAuth2Request request2 = new OAuth2Request(
        Collections.<String, String>emptyMap(), "clientId", Collections.<GrantedAuthority>emptyList(),
        false, Collections.<String>emptySet(), Collections.<String>emptySet(), "redirectUri", 
        Collections.<String>emptySet(), Collections.<String, Serializable>emptyMap());
    request2.setRequestParameters(request.getRequestParameters());

    byte[] serializedRequest = SerializationUtils.serialize(request);
    byte[] serializedRequest2 = SerializationUtils.serialize(request2);

    assertSame(serializedRequest.length, serializedRequest2.length);
}
```

**Comment by joemccall86** [comment]
I'd like to submit a PR for this. I think the right solution is to copy the parameters individually into a new `Collections.unmodifiableMap`.

**Comment by jgrandja** [comment]
Thanks for the report @theRCexp and thanks for the PR @joemccall86!
This fix has now been merged to master.
