### ISSUE TITLE
Cannot switch serialization from Java Serialization to Json Without Losing Data

### ISSUE THREAD

**Issue by benkiefer** [spring-projects/spring-security-oauth#815]
We're working on decoupling from storing Java serialized authentication and token objects and ran into a snag. We need to stop using Java serialization because in the latest version of Spring Boot we are getting bumped to Spring Security 4.1.x which changes the serialization uid on the UsernamePasswordAuthenticationToken object which is serialized and stored in the authentication fields of the oauth_access_token and oauth_refresh_token tables. We cannot force our partners to put all of their users back through the oauth authentication flow and cause that level of disruption in our service.

We would like to use Jackson to convert the object to JSON, but the Oauth Authentication Token has Jackson Serialize and Deserialize annotations on it, and we lose the expiration date when trying to use Jackson's ObjectMapper to convert it to json. We end up keeping the `expires_in` field, which is not helpful without the actual date that the token should expire.

Is there any way that we can decouple the object that is returned and what is stored in the database?

Right now, our workaround is to create a custom object mapper that is set up to ignore the Jackson annotations and getter fields so that we drop the `expires_in` value. 

Are there any other options?

**Comment by dsyer** [comment]
That sounds perfect to me. The alternative, I guess is to copy to a different representation (i.e. not `DefaultOAuth2AccessToken`) and use the standard object mapper.
