### ISSUE TITLE
Client_id used as username in Oauth authentication

### ISSUE THREAD

**Issue by konopiux** [spring-projects/spring-security-oauth#820]
Hi,

I have pretty trivial configuration:

```
public class OAAuthStockDataAuthorizationServerConfigurer extends AuthorizationServerConfigurerAdapter {

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private ClientDetailsService clientDetailsService;

    @Autowired
    private TokenStoreService tokenStoreService;

    @Override
    public void configure(ClientDetailsServiceConfigurer clientDetailsServiceConfigurer) throws Exception {
        clientDetailsServiceConfigurer.withClientDetails(clientDetailsService);
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer authorizationServerEndpointsConfigurer) throws Exception {
        authorizationServerEndpointsConfigurer
                .authenticationManager(authenticationManager)
                .tokenServices(getTokenServices());
    }

    @Override
    public void configure(AuthorizationServerSecurityConfigurer authorizationServerSecurityConfigurer) throws Exception {
        authorizationServerSecurityConfigurer
//                .allowFormAuthenticationForClients();
                .tokenKeyAccess("isAnonymous() || hasAuthority('ROLE_TRUSTED_CLIENT')")
                .checkTokenAccess("hasAuthority('ROLE_TRUSTED_CLIENT')");
    }

    public DefaultTokenServices getTokenServices() {
        DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
        defaultTokenServices.setTokenStore(tokenStoreService);
        defaultTokenServices.setSupportRefreshToken(true);
        defaultTokenServices.setClientDetailsService(clientDetailsService);
        return defaultTokenServices;
    }
}

```
and security config is like that:
```
@Configuration
@EnableWebSecurity
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private UserDetailsService userDetailsService;

    @Autowired
    private AuthenticationEntryPoint authenticationEntryPoint;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        ClientCredentialsTokenEndpointFilter tokenEndpointFilter = new ClientCredentialsTokenEndpointFilter();
        tokenEndpointFilter.setAuthenticationManager(authenticationManagerBean());
        http
                .authorizeRequests()
                .antMatchers("/oauth/token").anonymous()
                .antMatchers(HttpMethod.OPTIONS).permitAll()
                .anyRequest().authenticated()
                .and().httpBasic().authenticationEntryPoint(authenticationEntryPoint)
                .and().addFilterAfter(tokenEndpointFilter, BasicAuthenticationFilter.class)
                .csrf().disable();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .userDetailsService(userDetailsService)
                .passwordEncoder(passwordEncoder);
    }

    @Override
    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }
}
```

My idea is to send client_id/secret and username/password to get token. Client data I want to take from database using custom clientservice, while for getting user data I use custom user service.

Because by default is used BasicAuthenticationFilter I send request like this:

> http://localhost:8443/oauth/token?grant_type=password&username=kono&password=123456
with header: Authorization:Basic b2FzZC1hdXRoLWNsaWVudDpteVNlY3JldA== 
(Base64 encoded clientID and secret).

Bu problem is that after correct client is retrieved from database, same `client_id` is used in Userservice as `username`.
I do not understand why it is like that, and if it possible without overwriting `AuthenticationManager` to achieve such functionality: "I send client_id,secret,username,password" and if everything correct I get token.

**Comment by yudar1024** [comment]
same issue, and I wanna customzie BasicAuthenticationFilter. but it seems can not be override

**Comment by gusev-r** [comment]
I have the same problem. I'd appreciate your help if someone showed me a solution.  I wanna customzie BasicAuthenticationFilter and use custom AuthenticationProvider.

**Comment by GAK-MPRO** [comment]
I having the exact same issue , I see that client details are successfully validated, but the end user - username and password are ignored and instead client_id is sent again to my custom user details service (those were part of my form-encoded key value pairs) . @konopiux : did you ever find a solution for it

**Comment by Hi-Shan** [comment]
i got same issue but little different . when i send the post form /oauth/token such as : 
> http://localhost:8901/oauth/token?password=1bbd886460827015e5d605ed44252251&username=510111112222233333&grant_type=password&client_secret=123&client_id=trs_ads

the token endpoint using the username as the client_id and search it form databases, finally spring can find client details when using the username as the client_id .

i don't know why , did you ever find a solution for it

**Comment by qiaojiang2** [comment]
have any solution for it?

**Comment by briceamk** [comment]
Any solution?

**Comment by raccoon1515** [comment]
Any solution?
