### ISSUE TITLE
OAuth2Request.getClientId() throws IllegalAccessException

### ISSUE THREAD

**Issue by romeara** [spring-projects/spring-security-oauth#826]
I'm not 100% sure if this was an intended change, or if its a bug:
### Background

In previous versions of the OAuth library, it was possible to get the client ID used by an OAuth authentication by getting the OAuth2Authentication object, and calling `auth.getAuthorizationRequest().getClientId()`. In 2.0, `getAuthorizationRequest()` was replaced by `getOAuth2Request()`, and the return object was changed.
### Issue

The object returned by the new method extends `BaseRequest`, which defines several public methods such as `getClientId()`. `BaseRequest` is package-protected - any attempts to call its public methods outside of its package result in an `IllegalAccessError`.

The only way to get the client ID at this time is to call `getPrincipal()` on the `Authentication` object - and this only returns the client ID if the OAuth call is being made purely by the client (client credentials) - otherwise the user principal who the request is being made on behalf on is returned.

This means that any check, logging, or auditing against the client being used is not supported by Authentication lookup anymore when it is acting on behalf of a user.
## Suggested Change

It appears hiding the class is at least somewhat desired - the comments on it indicate nothing else should reference it. I would suggest either 
- Making the class protected (which would expose it), or 
- Making the public methods protected. This would allow having extending class expose them as public methods to restore past behavior, or making them less visible to development tools so end-users don't attempt to access them at all

Assuming the ability to access the client ID is something that should be restored, I'd be happy to try to create a pull request, but I'll wait for feedback about this being intentional/bug first

**Comment by dsyer** [comment]
Do you have a failing test case? It seems to me that the public methods should be public in public subclasses (that's my experience anyway).

**Comment by romeara** [comment]
That was what I thought originally, and attempts to write unit tests to reproduce the odd behavior seem to support that. 

I will go back to the original project I experienced this in and see if I can figure out why getClientID threw that in that project but not in tests

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
