### ISSUE TITLE
RemoteTokenServices.loadAuthentication() should not check for client_id

### ISSUE THREAD

**Issue by mekangas** [spring-projects/spring-security-oauth#838]
Per [RFC 6749](https://tools.ietf.org/html/rfc6749#section-7) (which doesn't address the topic) and [RFC 7662](https://tools.ietf.org/html/rfc7662#section-2.2) (which explicitly permits this), a valid _check token_ response from the authorization server might not contain a `client_id`.  Therefore, it isn't appropriate for `RemoteTokenServices.loadAuthentication()` to validate this.  Rather, the contents of a token from an otherwise valid (i.e., non-error) response is the business of, say, `OAuth2AuthenticationManager.authenticate()`.  The check currently in place limits the usefulness of `RemoteTokenServices`, especially for bearer tokens.

**Comment by yelhouti** [comment]
this is not an improvement but a bug fix, and Google Auth doesn't work with this

**Comment by gonzalad** [comment]
PR submitted #1020 could it be considered for inclusion please ?
Thanks !

**Comment by jgrandja** [comment]
@mekangas Yes you are correct, `client_id` is optional, however, `active` is required so this needs to be added in #840 along with tests. I've applied these changes and closed your PR in favour of f1a9b97.
Thank you for the report!

**Comment by mekangas** [comment]
Thanks for taking care of this!
