### ISSUE TITLE
Why is the samples referencing an existing version and break the build ?

### ISSUE THREAD

**Issue by kopax** [spring-projects/spring-security-oauth#847]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OAuth for Spring Security - Sparklr (OAuth 1 Provider Example)  FAILURE [37.618s]
[INFO] OAuth for Spring Security - Tonr (OAuth 1 Consumer Example)  SKIPPED
[INFO] OAuth for Spring Security - Sparklr2 (OAuth 2 Provider Example)  SKIPPED
[INFO] OAuth for Spring Security - Tonr2 (OAuth 2 Client Example)  SKIPPED
[INFO] OAuth for Spring Security - Samples ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.102s
[INFO] Finished at: Fri Sep 23 12:30:36 ICT 2016
[INFO] Final Memory: 13M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sparklr: Could not resolve dependencies for project org.springframework.security.oauth:sparklr:war:2.0.12.BUILD-SNAPSHOT: Could not find artifact org.springframework.security.oauth:spring-security-oauth:jar:2.0.12.BUILD-SNAPSHOT in spring-milestone (http://maven.springframework.org/milestone) -> [Help 1]

This version doesn't exist anywhere, should I downgrade ?

**Comment by dsyer** [comment]
It does exist (https://repo.spring.io/snapshot/org/springframework/security/oauth/spring-security-oauth2/), but the repository declarations in the samples are missing a snapshot repo. You can fix it by building locally. Also fixed in master (f165cc6).

**Comment by kopax** [comment]
Does this fix the token refresh issue ? Using the latest version on the repo, I wasn't able to make OAuth2 work, the refresh token was constantly refused.

Do you mind living this open until we have confirmation that this plugin is good for production use ?

**Comment by dsyer** [comment]
I don't really know which token refresh issue you are referring to, but this issue is specifically about the build of the sample, and it is closed with a fix, so I don't see any reason to reopen.

**Comment by kopax** [comment]
I have followed the guides [rest-api-spring-oauth2-angularjs](www.baeldung.com/rest-api-spring-oauth2-angularjs) on the github repository [baeldung/spring-security-oauth](https://github.com/Baeldung/spring-security-oauth), this article is from august 2016.

The person explain how to use spring oauth2 with a mysql database. When I swapped the code as explained in the guide, it turns out that It wasn't working completely.

The token wasn't working and I found all these related issues by having troubles getting the refresh token to work : 

- https://github.com/spring-projects/spring-security-oauth/issues/834
- https://github.com/spring-projects/spring-security-oauth/issues/816
- https://github.com/spring-projects/spring-security-oauth/issues/807

If I may ask a one last simple question, does this plugin is tested for production usage or is there some critical bug with latest spring-boot version ?

**Comment by dsyer** [comment]
I'm not sure what you mean by "plugin". If you mean spring-security-oauth then I'm sure it is in production in hundreds if not thousands of apps, and for quite some years. But that shouldn't be the point of any discussion here.

If you have a usage question please take it to stackoverflow. If you have a new issue not connected with this one, please open a new ticket and provide some more details.
