### ISSUE TITLE
refresh token never renewed

### ISSUE THREAD

**Issue by kopax** [spring-projects/spring-security-oauth#867]
I created a client with refresh token validity set to 180 seconds and access token validity set to 60 seconds. The following is what I did and found.

Get the initial access token and the refresh token using password grant type
Using the refresh token, get the access token and the refresh token using refresh token grant type
Then I continually get the access token and the refresh token using the refresh token I got from my previous request/response
After 180 seconds, I can no longer get the access token and the refresh token using the refresh token
What I found is that the refresh token I get back from each /oauth/token request is the same as the original refresh token. Refresh token doesn’t refresh with each use.
=== end quote ===

So its seems that every request to /oauth/token for a new access token using refresh token grant returns the same refresh token every time, essentially putting an upper bound on the user session through the client.

We would expect to receive a new refresh token with each refresh token grant and have the capa

**Comment by benkiefer** [comment]
@kopax There is a reuseRefreshToken flag on the DefaultTokenServices class that I believe does what you want to.

**Comment by kopax** [comment]
@benkiefer I am not sure exactly what it does : 

	/**
	 * Whether to reuse refresh tokens (until expired).
	 * 
	 * @param reuseRefreshToken Whether to reuse refresh tokens (until expired).
	 */
	public void setReuseRefreshToken(boolean reuseRefreshToken) {
		this.reuseRefreshToken = reuseRefreshToken;
	}

If passed to true, I guess it will generate a new refresh token on every requests or will the refresh token will be the same between each token expired renewal request ?

**Comment by kopax** [comment]
@benkiefer 

I did configure my __tokenServices__ like this : 

```java
	@Bean
	@Primary
	public DefaultTokenServices tokenServices() {
		final DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
		defaultTokenServices.setTokenStore(tokenStore());
		defaultTokenServices.setSupportRefreshToken(true);
		defaultTokenServices.setAuthenticationManager(authenticationManager);
		return defaultTokenServices;
	}

```

I don't understand why but :

- The first login return me a [login] JWT _that include `access_token` and `refresh_token`_
- Requesting a new access token using [login] `refresh_token` return a [new] JWT.
- Requesting a new access token using [new] `refresh_token` return this error : 

    {"error":"invalid_grant","error_description":"Invalid refresh token: eyJh...uw0"}

Do you have any direction I could look at so I can close this issue. It's inconveniant not to have the possibility to extend the jwt.

**Comment by benkiefer** [comment]
I'm not sure I understand what you are saying. What type of token are you using? Specifically, what type of tokenStore are you using? Are you using Oauth tokens, or JWT tokens?

**Comment by kopax** [comment]
I am using JWT tokens.
I have followed the recommendation in #633 and tried  to use `reuseRefreshToken=false`

__ResourceServerConfig.java__

```java
	@Bean
	@Primary
	public DefaultTokenServices tokenServices() {
		final DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
		defaultTokenServices.setTokenStore(tokenStore());
		defaultTokenServices.setSupportRefreshToken(true);
		defaultTokenServices.setAuthenticationManager(authenticationManager);
		return defaultTokenServices;
	}
```

__AuthorizationServerConfig.java__

```java
	@Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
		final TokenEnhancerChain tokenEnhancerChain = new TokenEnhancerChain();
		tokenEnhancerChain.setTokenEnhancers(Arrays.asList(tokenEnhancer(), accessTokenConverter()));
		endpoints
				.tokenStore(tokenStore())
				.approvalStoreDisabled()
				.authorizationCodeServices(authorizationCodeServices())
				.tokenEnhancer(tokenEnhancerChain)
				.reuseRefreshTokens(false)
				.authenticationManager(authenticationManager)
				.userDetailsService(managerDetailsService);
	}
```


As a result, I can get my first jwt token, use it's `refresh_token` to get a new jwt token, but the next `refresh_token` is still invalid : 

    {"error":"invalid_grant","error_description":"Invalid refresh token: eyJh...uw0"}


Do you need both `reuseRefreshTokens(false)` and `setSupportRefreshToken(true)` in order for this to work?

**Comment by benkiefer** [comment]
It sounds like you need to set some breakpoints in the default token services class and debug your way through what is happening.

Are you running multiple instances of your application?

**Comment by kopax** [comment]
Ok I will, it help to know it is the correct configuration and I should debug. Thanks!

**Comment by pksheldon4** [comment]
Both supportRefreshToken  and reuseRefreshToken default to true.  We were getting this same error and setting reuseRefreshToken(false) fixed it.

**Comment by saeedcs** [comment]
I am having same issue. Using a refresh token (JWT) gives me Invalid refresh token (expired):

**Comment by silentsnooc** [comment]
Same here. I also had to add `reuseRefreshTokens(false)` in order to make this work. 

```
    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        TokenEnhancerChain enhancerChain = new TokenEnhancerChain();
        enhancerChain.setTokenEnhancers(Collections.singletonList(accessTokenConverter));
        endpoints.tokenStore(tokenStore)
                .accessTokenConverter(accessTokenConverter)
                .tokenEnhancer(enhancerChain)
                .reuseRefreshTokens(false)
                .authenticationManager(authenticationManager);
    }
```

@kopax Thanks man!

**Comment by rhtodtjs** [comment]
Thx , It's very powerfull work

Thx again
