### ISSUE TITLE
Unable to configure the algorithm used for signing and verifying.

### ISSUE THREAD

**Issue by desmondrawls** [spring-projects/spring-security-oauth#870]
We need the RsaSigner and RsaVerifier classes to use sha512 instead of sha256. Because the JwtAccessTokenConverter instantiates these classes with their default algorithm, sha256, it seems like the only way to configure the algorithm would be to extend the JwtAccessTokenConverter, RsaSigner, and RsaVerifier while rewriting the package-protected RsaKeyHelper. We don't want to maintain that many spring-security classes. How else could we do this? Could the JwtAccessTokenConverter be rewritten to allow easier configuration of the algorithm?

**Comment by dsyer** [comment]
Would it be sufficient simply to provide a setter for the `SignatureVerifier` in `JwtAccessTokenConverter`? Can the existing `RsaVerifier` work with the other algorithms (the code in `JwtAlgorithms` seems to suggest so)?

**Comment by dsyer** [comment]
To be clear: you don't need the signer (because you are only decoding tokens), if I understand the chat in the back channel. It seems like `JwtAccessTokenConverter` is not very open to this kind of customization, so you'd have to copy it, and change the way the `RsaVerifier` is created. It's not a huge amount of code, so I'd like to at least know if it works.

**Comment by desmondrawls** [comment]
Yes, I think a setter for the algorithm in RsaVerifier would be enough. That way all we would need to do is override a couple methods in the JwtAccessTokenConverter.
As it is we would also have to subclass the JwtAccessTokenConverter and the RsaVerifier and copy/paste the RsaKeyHelper. The reason for this is the JwtAccessTokenConverter setVerifierKey method:
```
public void setVerifierKey(String key) {
		this.verifierKey = key;
		try {
			new RsaSigner(verifierKey);
			throw new IllegalArgumentException(
					"Private key cannot be set as verifierKey property");
		}
		catch (Exception expected) {
			// Expected
		}
	}
```
which calls an RsaVerifier constructor that defaults to sha256
```
public RsaSigner(String sshKey) {
        this(loadPrivateKey(sshKey));
    }
```
```
 private static RSAPrivateKey loadPrivateKey(String key) {
        KeyPair kp = RsaKeyHelper.parseKeyPair(key);
        if(kp.getPrivate() == null) {
            throw new IllegalArgumentException("Not a private key");
        } else {
            return (RSAPrivateKey)kp.getPrivate();
        }
    }
```
and the RsaKeyHelper is a package-protected class. We could probably avoid some copy/paste by pulling the loadPrivateKey method up into our version of the JwtAccessTokenConverter and then calling a RsaVerifier constructor that accepts an algorithm. We would still, however, need to copy/paste the RsaKeyHelper.

The setter would be very helpful. Some way to easily configur the JwtAccessTokenConverter would be even more convenient but the setter on RsaVerifier would make us happy.

**Comment by dsyer** [comment]
Setters were added in that last commit. It would still be good if you could confirm that it actually works, either with your custom code or with snapshots.
