### ISSUE TITLE
Inconsistent generation of `authentication_id`

### ISSUE THREAD

**Issue by born2snipe** [spring-projects/spring-security-oauth#874]
If you subclass `DefaultAuthenticationKeyGenerator` and override the method `extractKey(...)` and make it return a debuggable key like below: 
```Java
Map<String, String> values = new LinkedHashMap<String, String>();
OAuth2Request authorizationRequest = authentication.getOAuth2Request();
if (!authentication.isClientOnly()) {
   values.put(USERNAME, authentication.getName());
}
values.put(CLIENT_ID, authorizationRequest.getClientId());
if (authorizationRequest.getScope() != null) {
  values.put(SCOPE, OAuth2Utils.formatParameterList(authorizationRequest.getScope()));
}
return values.toString();
```

You will see the `scopes` are some times out of order so the `authentication_id` will have a different checksum value.

The is caused by the `BaseRequest.getScope()` always returning a `HashSet`. From my perspective the proper fix is to always sort the scopes when generating the id so regardless what kind of collection we are given the results would remain the same.

**Comment by jgrandja** [comment]
Thanks for the report @born2snipe
