### ISSUE TITLE
Can custom parameters be passed in the "Authorization Phase" of OAuth2?

### ISSUE THREAD

**Issue by mohan-gliimpse** [spring-projects/spring-security-oauth#883]
I am implementing the **Authorization Code** flow + **JWT**.

I would like to know if and how it may be possible to add additional custom parameters to the _Authorization Phase_ of the flow.

Essentially, I am looking to do the following:
1. When redirecting the user to the _/oauth/authorize_ I would like to pass in an additional parameter (_customParameter_) in the GET url http://.../oauth/authorize?..._customParameter_=[VALUE] such that VALUE is dynamic
2. I will need to retrieve VALUE when creating the **JWT**, populating the **JWT** with that VALUE

Is this possible?  How can I implement?

Thanks in advance.

**Comment by jgrandja** [comment]
Hi @mohan-gliimpse,

The extension point to add custom parameters would be in `OAuth2ClientContextFilter.setRedirectStrategy(RedirectStrategy)`. 

The current implementation of `OAuth2ClientContextFilter` uses `DefaultRedirectStrategy`. You can provide your own implementation of `RedirectStrategy` and set that on `OAuth2ClientContextFilter`.

The `OAuth2ClientContextFilter` is implicitly created when you add `@EnableOAuth2Client` which imports `OAuth2ClientConfiguration`.

What you would need to do is NOT add `@EnableOAuth2Client` and extend `OAuth2ClientConfiguration` and override method `oauth2ClientContextFilter`.

For example:

```
        @Override
	public OAuth2ClientContextFilter oauth2ClientContextFilter() {
		OAuth2ClientContextFilter filter = super.oauth2ClientContextFilter();
		filter.setRedirectStrategy(new RedirectStrategy() {
			@Override
			public void sendRedirect(HttpServletRequest request, HttpServletResponse response, String url) throws IOException {
				// Add your custom parameters to 'url`
			}
		});
		return filter;
	}

```

Then annotate your extended `OAuth2ClientConfiguration` with `@Configuration` and this should do it.

Give this a try and let me know if that worked for you.

**Comment by jgrandja** [comment]
Hi @mohan-gliimpse I'm going to close this issue as I haven't heard back from you regarding the solution I proposed. I'm assuming you're good now.

**Comment by Rohit04061992** [comment]
Hey @jgrandja ,
i am actually trying to add custom params to CF uaa /authorize endpoint , in side CF Uaa code base i tried what you have  mentioned but the mentioned configurations are not getting picked up by CF UAA. 

Are you aware of any other configuration changes that can be done on CF UAA to provide custom params while /authorize endpoint that too happening dynamically.
