### ISSUE TITLE
Sanitize Error response

### ISSUE THREAD

**Issue by yiown** [spring-projects/spring-security-oauth#889]
According to the IETF: [OAuth2 RFC](https://tools.ietf.org/html/rfc6749)

> error_description
>          OPTIONAL.  Human-readable ASCII [USASCII] text providing
>          additional information, used to assist the client developer in
>          understanding the error that occurred.
>          Values for the "error_description" parameter **MUST NOT include
>          characters outside the set %x20-21 / %x23-5B / %x5D-7E.**

But i can easily send HTML with JavaScript injections in the grant_type parameter, and it gets back inside the error_description.
This is a security vulnerability that could lead to attack vectors.

PLEASE SANITIZE THE OUTPUTS.

**Comment by jgrandja** [comment]
Thanks for the report @yiown.
I'll work on that now.

**Comment by jgrandja** [comment]
Thanks again @yiown.
The fix has been merged into master.

**Comment by fhanik** [comment]
This commit incorrectly escapes characters like `'` single quote. %27 on the ascii table, well within range of valid characters.
