### ISSUE TITLE
when grant_type is password how to record login log

### ISSUE THREAD

**Issue by DemonTang** [spring-projects/spring-security-oauth#890]
when grant_type is password how to record login log

**Comment by jgrandja** [comment]
Hi @DemonTang Please provide more detail so I can understand the issue

**Comment by DemonTang** [comment]
When grant_type is password, I get access_token by username and password. After this authentication is complete, how do I log this user's login information to the database. By interceptor? Or other ways?

**Comment by jgrandja** [comment]
You can register an `AuthenticationEventPublisher` with the `AuthenticationManager`.

Here is a sample configuration for your `WebSecurityConfigurerAdapter`:

```
	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.authenticationEventPublisher(authenticationEventPublisher());
	}

	@Bean
	protected AuthenticationEventPublisher authenticationEventPublisher() {
		return new AuthenticationEventPublisher() {

			@Override
			public void publishAuthenticationSuccess(Authentication authentication) {
				System.out.println("authentication success");
			}

			@Override
			public void publishAuthenticationFailure(AuthenticationException exception, Authentication authentication) {
				System.out.println("authentication failure");
			}
		};
    }
```

I'm going to close this issue as it addresses your question.
Thanks.
