### ISSUE TITLE
When the permissions change for a user, the authenticationid changes and a new entry is inserted in access_token table

### ISSUE THREAD

**Issue by anushree-jain** [spring-projects/spring-security-oauth#898]
When the permissions change for a user, the authenticationid changes and a new entry is inserted in access_token table, and the previous token entry also exist in the access_token table. How to handle the stale token entries which result due to change in permissions/authenticationid?

**Comment by jgrandja** [comment]
Hi @anushree-jain The default  `AuthenticationKeyGenerator` used by `JdbcTokenStore` is `DefaultAuthenticationKeyGenerator`, which uses the `scope` from the _Authorization Request_ to calculate the key for `authentication_id` column. If the `scope` changes then the `authentication_id` will change which may result in the stale token entry.

You may plug in your own implementation of `AuthenticationKeyGenerator` into `JdbcTokenStore.setAuthenticationKeyGenerator()`  to handle the key generation to be more consistent.

Can you please provide more detail when you say....

> when the permissions change for a user

...a sample re-producing this issue would be ideal.

**Comment by jgrandja** [comment]
@anushree-jain I'm closing this due to lack of feedback re: sample.
