### ISSUE TITLE
How can I use the ClientApplication.java？

### ISSUE THREAD

**Issue by yohole** [spring-projects/spring-security-oauth#899]
Hi,I am studtying spring-oauth2  with JDBC,but I don't know how I can use the class "spring-security-oauth/tests/annotation/jdbc/src/main/java/demo/ClientApplication.java".How can I test this by curl?And what the connection between ClientApplication.java and Application.java?Thank you!

**Comment by jgrandja** [comment]
Hi @yohole `Application` is the server-side part of the application as denoted by `@EnableAuthorizationServer` and `@EnableResourceServer` and `ClientApplication` is the client-side part of the application as denoted by `@EnableOAuth2Client`.

I would strongly suggest to go through the following samples/tutorials to get ramped up on Spring Security OAuth:

https://spring.io/guides/tutorials/spring-boot-oauth2/
https://spring.io/guides/tutorials/spring-security-and-angular-js/
http://projects.spring.io/spring-security-oauth/docs/tutorial.html

I'm going to close this issue but feel free to create a new one if you have further questions. However, the best forum for questions would be [Gitter](https://gitter.im/spring-projects/spring-security-oauth?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
