### ISSUE TITLE
OAuth2AccessTokenSupport#retrieveToken returns OAuth2AccessToken with null scope when scope granted is the same as requested

### ISSUE THREAD

**Issue by adnanalawiyat** [spring-projects/spring-security-oauth#902]
Per 5.1.  Successful Response,  https://tools.ietf.org/html/rfc6749#section-5.1 , authorization server doesn't have to include 
scope in access token successful response unless it is not identical to the scope requested. 

In this use case I end up with OAuth2AccessToken that has null scope. OAuth2AccessTokenSupport#retrieveToken should handle 
this use case and populate OAuth2AccessToken.getScope() correctly. 

Response from Authorization server (PingFederate): 

{
	"access_token":"foo",
	"refresh_token":"bar",
	"token_type":"Bearer",
	"expires_in":7200
}

**Comment by jgrandja** [comment]
Related #828

**Comment by jgrandja** [comment]
Hi @adnanalawiyat I'm not sure if I agree that `OAuth2AccessTokenSupport#retrieveToken` should auto-populate the `OAuth2AccessToken.scope` with the same scope originally requested with the Authorization Request.

There may be Authorization Servers that never return the scope attribute in the token response at all. 
We can't make this assumption as it may cause other issues. Also, it wouldn't be a **_true representation_** of the token response returned from the Authorization Server if we auto-populated the scope in the mentioned use-case.

The important thing here is that the requested scope(s) will be encoded/associated with the access token on successful authorization.

I'm going to close this issue but if you have further input I'd be happy to discuss.

**Comment by adnanalawiyat** [comment]
Thanks @jgrandja for your reply.

RFC 6749 clearly states that if scope is not included in successful access token response, it means the scope client asked for is what has been granted. otherwise, the scope must be provided. so we only have two possible paths for this no? why isn't appropriate to make this assumption ? If an authorization server is not providing access token, and meant to say scope is other than what you requested, this is not compliant with RFC 6749. Please note I'm considering what has been requested to be the value of scope on org.springframework.security.oauth2.client.OAuth2RestTemplate#resource

To clarify why this is creating a problem for me. let me present my entire use case:

1. I have registered an OAuth2RestTemplate object that contains ClientTokenServices
   implementation within its accessTokenProvider member. (to be able to persist acquired access
   token for given user)

2. org.springframework.security.oauth2.client.OAuth2RestTemplate#getAccessToken is called
    and user is taken to authorization code flow, authorizes my client for all requested scopes
3. OAuth2RestTemplate continues to use authorization code to exchange for an access token.
4. Access token response from authorization server arrives without scope indicated in the body.
5. OAuth2RestTemplate produces OAuth2AccessToken with null scope which got persisted to
    database.
6. At a later time my client retrieves the access token from ClientTokenServices store. 

at this point I have org.springframework.security.oauth2.common.OAuth2AccessToken#getScope
returning null for me. How do I know what scope has been granted for this token ? I'm forced to
make additional call to authorization server just to know the scope. is this necessary ?

**Comment by jgrandja** [comment]
Agreed, there are 2 possible scenarios.

As per spec:

>  scope
>          OPTIONAL, if identical to the scope requested by the client;
>          otherwise, REQUIRED.  The scope of the access token as
>          described by Section 3.3.

For example:

**Based on the 1st scenario:**

If the requested scope is `read,write` and the user consents to the 2 scopes then the token response will contain one of the following:

`token.scope: read,write`
OR
`[no scope attribute]`

**Based on the 2nd scenario:**

If the requested scope is `read,write` and the user denies `write` and authorizes `read` then the token response will contain:

`token.scope: read`


Based on the 1st scenario, where the user authorizes all presented scopes, the scope is optional for the token response. If the scope attribute is not included, should the client auto-populate the scope as defined by the spec? As I mentioned in the previous post, **this would not be a 'true representation' of the token response.** This is the main reason I'm hesitant on applying this change. 

I understand your scenario that the persisted `OAuth2AccessToken` will contain a `null scope` but you can derive the scope from `OAuth2ProtectedResourceDetails`.

For example,

In step 6 of your scenario, you make the call to:

`OAuth2AccessToken accessToken = clientTokenServices.getAccessToken(OAuth2ProtectedResourceDetails resource, Authentication authentication)`

If `accessToken.scope` is null/empty then you can derive the scope from `resource.scope`. This would avoid that extra call to the token introspection endpoint to determine the scope. Would this not work for you?
