### ISSUE TITLE
Expose JWT header in JwtImpl for key rotation

### ISSUE THREAD

**Issue by ruhkopf** [spring-projects/spring-security-oauth#911]
I would like to implement key rotation for JWT and came across https://github.com/spring-projects/spring-security-oauth/issues/713. The issue addresses setting custom headers (such as `kid`) when encoding the token. However, when verifying a token we need to access the header, so that we can verify against the right key.

@dsyer suggests
> To decode and verify a token you would need to call the decode() method, extract the headers and parse them to get the key id [...]

This seems straight-forward, but `decode()` returns a `JwtImpl` instance, which holds the header in a private field, but unfortunately doesn't expose it. Would it be possible to add a `getHeader()` function to get the header (just like `getClaims()` returns the body)?

**Comment by dsyer** [comment]
Good point (I guess the UAA team never implemented that feature either). Fixed in a878032 (spring-security-jwt 1.0.7.RELEASE) with new convenience method `JwtHelper.headers(String)`.
