### ISSUE TITLE
Error getting new access token using refresh token (with Jwt converter)

### ISSUE THREAD

**Issue by felipeslago** [spring-projects/spring-security-oauth#934]
When I request the access token for the first time, I receive an access token and a refresh token (ok until here)

But when a refresh my access token, the JwtAccessTokenConverter receives a signed refresh token and sign it again.

So I'm not receiving "the same refresh token".

I solved this problem by creating a custom JwtAccessTokenConverter, extracting the refresh token and creating a new OAuth2AccessToken.

I don't know if it is the best or the correct solution...

`public class CustomJwtAccessToKenConverter extends JwtAccessTokenConverter {

   @Override
   public OAuth2AccessToken enhance(OAuth2AccessToken accessToken, OAuth2Authentication authentication) {
     OAuth2RefreshToken oAuth2RefreshToken = accessToken.getRefreshToken();

     String refreshToken = "";

     JsonParser objectMapper = JsonParserFactory.create();
     Map<String, Object> claims = objectMapper.parseMap(JwtHelper.decode(oAuth2RefreshToken.getValue().getClaims());
     if(claims.containsKey(TOKEN_ID)) {
        refreshToken = claims.get(TOKEN_ID).toString();
     }

     DefaultOAuth2RefreshToken defaultOAuth2RefreshToken = new DefaultOAuth2RefreshToken(refreshToken);
     DefaultOAuth2AccessToken defaultOAuth2AccessToken = new DefaultOAuth2AccessToken(accessToken);
     defaultOAuth2AccessToken.setRefreshToken(defaultOAuth2RefreshToken);

     return super.enhance(defaultOAuth2AccessToken, authentication);
}`

**Comment by bwangfdu** [comment]
It seems not. The codes changed a lot than when I find that problem.

**Comment by jgrandja** [comment]
This is a duplicate of #1109. Please see [comment](https://github.com/spring-projects/spring-security-oauth/issues/1109#issuecomment-546453794)
