### ISSUE TITLE
Redis based AuthorizationCodeServices

### ISSUE THREAD

**Issue by srempfer** [spring-projects/spring-security-oauth#935]
In a project on that I currently working we use the Redis based TokenStore.
To be able to completely scale out the Authorization Server with Redis it would be great to have a Redis based AuthorizationCodeServices as well.

**Comment by matejsp** [comment]
Is there any update regarding Redis support for AuthorizationCodeServices?

**Comment by srempfer** [comment]
I think currently the manpower goes into Spring Security 5.0 changes to consolidate the OAuth stuff. See https://github.com/spring-projects/spring-security/issues/3907

**Comment by subaan** [comment]
Is there any update regarding Redis support?

**Comment by zenglongx** [comment]
Is there any update regarding Redis support for AuthorizationCodeServices?

**Comment by Jeff-Walker** [comment]
Anyone have any ideas on the best way to implement one?
