### ISSUE TITLE
Remember user decision when using /confirm_access endpoint

### ISSUE THREAD

**Issue by myspri** [spring-projects/spring-security-oauth#937]
Hello,

I am new to spring Oauth2 but I am finding all the samples to be very useful. I would like to know how the AS can remember the user's decision after granting permissions. 

Basically, when the default page shows up, the user can approve/deny access to the client. If the user grants access, I would like AS to remember that decision until the permission is revoked. 
I would like to persist the decision somehow between server restarts and shouldn't display the confirmation page if the user had already granted access to the client.

Sounds like some thing custom needs to be written, but not sure how. 

I read that I might need to add `@RequestMapping("/oauth/confirm_access")` for overriding the default confirmation page, but not sure how to implement the behavior that I want.

BTW, a big kudos to @dsyer for all the awesome samples and documentation

**Comment by dsyer** [comment]
That sounds like a description of the use case for `ApprovalStore`, so probably not much custom code needed, except maybe the view. Please use stackoverflow for usage questions (and you are welcome).

**Comment by myspri** [comment]
Thank you so much for the info. I did not know about the ApprovalStore until now.
