### ISSUE TITLE
Configuring HttpSecurity is mandatory in ResourceServerConfigurerAdapter (and perhaps shouldn't be)

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-security-oauth#948]
The workaround is trivial (just add `authorizeRequests()` to any adapter you create - and most if not all existing adapters do that of necessity). See https://github.com/spring-projects/spring-boot/issues/5087

**Comment by jgrandja** [comment]
Thanks for providing all the info @philwebb!

The current state of `ResourceServerConfigurerAdapter` provides a `null` implementation of the `configure(HttpSecurity http)` operation. I think it makes sense to provide the following default implementation (at minimum):

```
	public void configure(HttpSecurity http) throws Exception {
		http.authorizeRequests().anyRequest().authenticated();
	}
```

Given this is a **Resource Server**, it is therefore responsible for **securing protected resources**. 
By default, all endpoints should be protected and if the user wants specific endpoints to be protected instead then they may override `configure(HttpSecurity http)` and provide their own specific `authorizeRequests()`.
