### ISSUE TITLE
AbstractTokenGranter didn't validate client_secret when grant_type is  client_credentials

### ISSUE THREAD

**Issue by icoding** [spring-projects/spring-security-oauth#952]
org.springframework.security.oauth2.provider.token
class : AbstractTokenGranter
public OAuth2AccessToken grant(String grantType, TokenRequest tokenRequest) {

		if (!this.grantType.equals(grantType)) {
			return null;
		}
		
		String clientId = tokenRequest.getClientId();
#                 //secret can pass any value??
		ClientDetails client = clientDetailsService.loadClientByClientId(clientId);
		validateGrantType(grantType, client);
		
		logger.debug("Getting access token for: " + clientId);

		return getAccessToken(client, tokenRequest);

	}

**Comment by jgrandja** [comment]
The `BasicAuthenticationFilter` authenticates the client credentials (client id/secret) via the Authorization Header before it proceeds to the `TokenEndpoint` (/oauth/token). The `TokenEndpoint` internally uses the `TokenGranter` for generating the Access Token. 

**NOTE:** The `TokenGranter` is not meant to be used standalone. As per spec, client credentials must be authenticated first before it proceeds to the `TokenEndpoint`.

I'm going to close this issue as it's working as designed.
