### ISSUE TITLE
Support fragment in userAuthorizationUri for redirecting user

### ISSUE THREAD

**Issue by hillmanli-seekers** [spring-projects/spring-security-oauth#959]
Some OAuth2 authorization provider contains fragment (the # anchor stuff) in their authorization uri, for example WeChat, (in this case WeChat redirect uri is https://open.weixin.qq.com/connect/qrconnect#wechat_redirect). Adding the fragment to userAuthorizationUri will cause OAuth2ClientContextFilter.redirectUser to throw IllegalArgumentException. It is due to using UriComponentsBuilder.fromHttpUrl.

I am able to workaround the problem by overriding OAuth2ClientContextFilter.redirectUser in a subclass, though it would be nice to have this out of the box.

**Comment by jgrandja** [comment]
Closing this as fragment components are not allowed in `redirect_uri`. See this [comment](https://github.com/spring-projects/spring-security-oauth/pull/1724#issuecomment-607186136) for further details.
