### ISSUE TITLE
Implementation of the OAuth Device Flow

### ISSUE THREAD

**Issue by hoalex** [spring-projects/spring-security-oauth#967]
Hi all,

we're a small team of CS students at the Karlsruhe Institute of Technology in Germany who have developed a first implementation of the current [OAuth 2.0 Device Flow](https://tools.ietf.org/html/draft-ietf-oauth-device-flow-03) draft in Spring Security OAuth.

The code is not 100% feature-complete, but will be further developed in the coming months. Before opening a pull request, I just wanted to ask around whether there is any interest on your side to have such a feature integrated into the project.

I'd love to hear back from you!

Regards
Alex

_(Additionally mentioning team members @jGleitz and @dave4422 so they're in the loop)_

**Comment by jgrandja** [comment]
Hi @hoalex @jGleitz @dave4422. Thanks for your interest in this feature. However, the Spring Security OAuth project is now in **maintenance mode** and we are limiting new features. At this time we are only working on bug fixes and smaller enhancements.

FYI, we are in the process of re-writing OAuth2 and integrating it into Spring Security core project. Our  focus is on the client-side first and then we will focus our efforts on server-side. The 1st milestone is expected sometime this March. You can track the issue [here](https://github.com/spring-projects/spring-security/issues/3907).

Of course we would be interested in any PR's targeted for the new Spring Security OAuth module.
Thanks for your contributions!

**Comment by bahirsch** [comment]
Please update if there is any intention to progress on this feature: Implementation of the OAuth Device Flow

**Comment by jGleitz** [comment]
@bahirsch: This feature was developed as a student project that has now ended. While I certainly would provide help to integrate it into this project, rewriting it for a new target code base is more than I currently can (and want) to do in my free time.

@hoalex and @dave4422 will have to speak for themselves, of course.

**Comment by dave4422** [comment]
@bahirsch My code for the client side is incomplete and unfinished. I also
currently don't have any capacities to work on the project.

2017-07-16 17:05 GMT+02:00 Joshua Gleitze <notifications@github.com>:

**Comment by bwangfdu** [comment]
Hi guys,
  I am working on the device flow in my current job. I talked with my manager and he agrees me to contribute it to the community.  Please see https://github.com/bwangfdu/spring-security-oauth
I am still working on a Redis device code store and a JDBC store. If anybody can help on review the codes or write JUnit Test code, that will be awesome.

**Comment by bwangfdu** [comment]
The Redis store is finished and also some JUnit test code is added. JDBC store is still in plan.

**Comment by bwangfdu** [comment]
I raise a pull request https://github.com/spring-projects/spring-security-oauth/pull/1199 
The known issues are:
1. I hasn't wrote JDBC store codes
2. slow_down error is not implemented
3. Lack of integrating test cases

**Comment by nivemaham** [comment]
Any flow-ups on this or the PR issued by @bwangfdu

**Comment by RegisDevOps** [comment]
@jgrandja - regarding "FYI, we are in the process of re-writing OAuth2 and integrating it into Spring Security core project." - Where can I find a status?

**Comment by jgrandja** [comment]
@RegisDevOps See this [blog](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) (and the associated links within the blog) for more details

**Comment by jgrandja** [comment]
This project is scheduled to reach EOL. Please see the [announcement](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth) for further details.

I'm going to close this as it doesn't make sense to add new features given the status of the project.
