### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by ShawnyXiao** [spring-projects/spring-security-oauth#969]
In this website https://github.com/spring-projects/spring-security-oauth/blob/f25592e682303b0cf89e1d7555174bac18e174df/docs/oauth2.md#configuring-client-details, there is a typo.

The snapshot is as follow:
![gv 0o0oi j n n511sn hpm](https://cloud.githubusercontent.com/assets/9656978/22623479/3f04fbb4-eb97-11e6-9a38-272f62d4858a.png)

**Comment by DeCaMil** [comment]
This can be closed. It was fixed in https://github.com/spring-projects/spring-security-oauth/commit/045c16b1d485fc145083d801f404fbcefcfd4e3a#diff-b2250b01f8ec60142f1afea44303a454
