### ISSUE TITLE
Resource Server does not work when remote token from auth server JDBC backend 

### ISSUE THREAD

**Issue by Widiyanto** [spring-projects/spring-security-oauth#979]
Resource Server does not work when remote token from auth server JDBC backend.

`{
  "timestamp": 1487175500458,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.web.client.HttpClientErrorException",
  "message": "403 null",
  "path": "/api/admin"
}`

But when use inMemory work fine.

this is my source https://github.com/Widiyanto/Springboot-Oauth

**Comment by Widiyanto** [comment]
Solved, my problem incorrect prefix ROLE_

**Comment by noyessielgl** [comment]
Can you explain well what is the problem. I face the same error and your answer is not clear.

Thank
