### ISSUE TITLE
OAuth2Authorization (de)serialization from MySql DB

### ISSUE THREAD

**Issue by zolia** [spring-projects/spring-security-oauth#985]
Hello, 

been trying to implement JdbcTokenStore with mysql as DB. My current versions used:

spring-security-oauth2 2.0.12.RELEASE
spring-boot-gradle-plugin 1.4.4.RELEASE

Before I successfully used inMemoriyTokenStore, but after changing to JdbcTokenStore with Mysql, i get the following error when trying to access protected resource:

_$ curl -X POST http://localhost:8090/device/registration -d "imei=12324567890123462&name=mydevice11" -H "Authorization: Bearer "6b22d792-7a3b-4079-a702-c93a8200cb54""_

**java.lang.IllegalArgumentException: Principal must not be null**
	at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.boot.actuate.audit.AuditEvent.<init>(AuditEvent.java:83) ~[spring-boot-actuator-1.4.4.RELEASE.jar:1.4.4.RELEASE]
...

Whole trace is here:
[principal_trace.txt](https://github.com/spring-projects/spring-security-oauth/files/793400/principal_trace.txt)

`oauth_access_token` table gets filled after successful authentication with such call:

_$ curl -X POST -vu clientapp:123456 http://localhost:8090/oauth/token -H "Accept: application/json" -d "pin=1324&password=12341232412341232412342&username=38068575730&grant_type=password&scope=read%20write&client_secret=123456&client_id=clientapp"_ 

After debugging I noticed that `OAuth2Authentication` object's `userAuthentication->principal record (class CustomUserDetailsService)` does not contain any data. The same record is populated when using `inMemoriyTokenStore`. But other records (such as  userAuthentication->details ) are populated.  I suspected that this `principal` record is not deserialised properly, but not sure how to proceed with this issue further. 

Just before OAuth2Authentication is serialised to db `userAuthentication->principal` record does contains required data. 

Also I failed to find any complete JdbcTokenStore+OAuth2 example with mysql as a backend. What solutions people usually apply for persistent token storage?

Would appreciate any help.

Antanas

**Comment by zolia** [comment]
A bit of update. This issue seems to arise only when I try to use `grant_type=password`, that is when `principal` should represent User object. In other grant types, when `principal` is of string type (de)serialisation works ok.

**Comment by zolia** [comment]
I have build a small example to illustrate an issue: [oauth jdbc token test](https://github.com/zolia/oauth-test)

Would really appreciate if someone could take a look on this issue.

Antanas

**Comment by jgrandja** [comment]
Hi @zolia. Thanks for putting the sample together as this is always a great help.
The issue here is that your `User` entity needs to implement `Serializable`.

Make this change and it will work.

```
public class User implements Serializable
``

I'm going to close this issue as this will solve the problem you are having.

**Comment by zolia** [comment]
thank you!

**Comment by silentsnooc** [comment]
@jgrandja Well I had to add `implements Serializable` to child tables as well e.g. `RoleEntity` which represents the users' role.

However, my problem is that with the `InMemoryTokenStore`, The user Principal was a `String` (the username):

```java
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
String username = (String) authentication.getPrincipal();
```

However, after changing this to `JdbcTokenStore`, I am now getting the `AppUserDetails implements UserDetails` - this is quite a change I have to say besides the fact that it seems to me that `JdbcTokenStore` not just stores the access token but also the entire user object. I don't understand why or the purpose.

So here is the question: Is this actually expected behavior or did I forget to configure something? At this point I don't think I want to serialize the entire user object - the username is fine since the rest is already stored in the database. 

Can this be done or am I having the wrong idea of what `JdbcTokenStore` is good for?

**Comment by silentsnooc** [comment]
@jgrandja Okay, I think I got it.

My `AppUserDetails` looked like this:

```java
public static class AppUserDetails implements UserDetails {

    private final AppUserEntity appUserEntity;

    public AppUserDetails(AppUserEntity appUserEntity) {
        this.appUserEntity = appUserEntity;
    }
    // ..
}
```

Here, `AppUserEntity` is a hibernate table/entity. I got a `NotSerializableException` which led me to believe the best way to handle this is by implements `Serializable` to all tables. 

However, I think it's much better to change the `AppUserDetails` to:

```
public static class AppUserDetails implements UserDetails {

    private final String username;
    private final String password;
    private final Collection<? extends GrantedAuthority> authorities;

    public AppUserDetails(String username, String password, Collection<? extends GrantedAuthority> authorities) {
        this.username = username;
        this.password = password;
        this.authorities = authorities;
    }
}
```

So we can 

```java
@Override
public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {

    AppUserEntity appUserEntity = this.appUserRepository.findByEmail(username).orElseThrow(() ->
        new ResourceNotFoundException("Current user not found."));

    List<GrantedAuthority> authorities = new ArrayList<>();

    Collection<AppUserRoleEntity> roles = appUserEntity.getRoles();

    for (AppUserRoleEntity appUserRoleEntity : roles) {
        RoleEntity roleEntity = appUserRoleEntity.getRole();
        authorities.add(new SimpleGrantedAuthority(roleEntity.getRoleType().toString()));
    }

    return new AppUserDetails(appUserEntity.getEmail(), appUserEntity.getPassword(), authorities);
}
```

which does not require us to serialize entity classes ..
