### ISSUE TITLE
The requestFactory not used in ApprovalStoreUserApprovalHandler

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-security-oauth#986]
However it is necessary injecting in `ApprovalStoreUserApprovalHandler`.

```java
public void afterPropertiesSet() {
    Assert.state(approvalStore != null, "ApprovalStore must be provided");
    Assert.state(requestFactory != null, "OAuth2RequestFactory must be provided"); // Is need this line ?
}
```

I think null check is not need and `setRequestFactory` method should be deprecated.

What do you think ?

**Comment by jgrandja** [comment]
Thanks for the report @kazuki43zoo. I'm not sure why `setRequestFactory()` needs to be `@Deprecated`?

Either way, `ApprovalStoreUserApprovalHandler` is now `@Deprecated`, so I don't think it's necessary to merge the PR at this point. Therefore, I will close it.
