### ISSUE TITLE
spring-security-oauth2 with github provider

### ISSUE THREAD

**Issue by criticalbh** [spring-projects/spring-security-oauth#991]
I have angular2 application and spring-boot rest API. I have managed to create own authorisation and resource server.

Is it possible with own resource and auth server to additionally integrate third part authorisations (github, facebook... etc).

Please note that I have tried spring-cloud and spring-social solutions, but as far as I could see they dont support SPA and rest (sessionless), they are cookie based.

Is it possible maybe to add multiple RemoteTokenServices which would check token according to provider I specify?

**Comment by jgrandja** [comment]
Hi @criticalbh. We are in the process of re-writing OAuth and integrating it into Spring Security proper.
You can track the issue [here](https://github.com/spring-projects/spring-security/issues/3907).

The first milestone is scheduled for this March and is focused on the OAuth client and will provide the authentication flow use-case, for example, login with GitHub, Google, Facebook, etc.

**Note:** the current Spring Security OAuth project is in maintenance mode as we are limiting new features and only focused on bug fixes and smaller enhancements.

I'm going to close this issue as I feel I have answered your question. However, if you have further questions please don't hesitate to ask.

**Comment by criticalbh** [comment]
@jgrandja I feel better now, thank you very much.
