### ISSUE TITLE
ResourceServerProperties DEFAULT filterOrder is not 0.

### ISSUE THREAD

**Issue by MysteryAngle** [spring-projects/spring-security-oauth#993]
Spring Boot 1.5.1
spring-cloud-dependencies:Camden.SR5

ResourceServerProperties is activated when I use both the authorization service and the resource service on the same server at the same time, but **filterOrder** default value is SecurityProperties.ACCESS_OVERRIDE_ORDER - 1, which will cause the AnyRequestMatcher of the custom WebSecurityConfigurerAdapter. OAuth2AuthenticationProcessingFilter will **never be used.**

**Comment by frankskywalker** [comment]
@MysteryAngle 
I run into the same issue when upgrade to Spring Boot 1.5.1.
I'm currently trying to workaround this issue.
If you have a working example, could you share some info here?

**Comment by jgrandja** [comment]
@MysteryAngle @frankskywalker The default order for the Resource Server filter chain has been changed in Spring Boot 1.5.0. It's documented [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter).

To restore the previous order, take a look at this [comment](https://github.com/spring-projects/spring-boot/issues/5072#issuecomment-271510520).

Essentially, add this configuration in your `application.yml`
```
security.oauth2.resource.filter-order=3
```

I'm going to close this issue as this should solve it for you.

**Comment by frankskywalker** [comment]
@jgrandja 
It did solve my problem, thanks.
But still I don't understand the reason of the result. 
My UserService is both a AuthenticationService and a ResourceService, and after I update to 1.5.1, I found that the Oauth2AuthenticationProcessingFilter is missing in the Spring Security Filter Chain.
Would you kindly explain why the order of filter will cause its absence in the filter chain.

I'm struggling to understand the overall structure and design of the Spring Oauth after I've gone through all the official docs. Should I read from the source code, or any other material I should look at first ?

With 1.4.3 I have Oauth2AuthenticationProcessingFilter in the Filter Chain
![17cf74bd-2625-4781-aac9-561346972de6](https://cloud.githubusercontent.com/assets/3746231/23615547/ca1d89b4-02c1-11e7-9dd4-19f12d312452.png)
With 1.5.1 the Oauth2AuthenticationProcessingFilter is missing.
![5713fc4e-302f-419a-820d-df9c2866bb93](https://cloud.githubusercontent.com/assets/3746231/23615601/f692400c-02c1-11e7-9022-396fbbe6a8db.png)

**Comment by jgrandja** [comment]
@frankskywalker Do you have a custom `WebSecurityConfigurerAdapter` configured in your app? If you do, (which I'm thinking you do), then it may be the first one in the ordered `FilterChainProxy.filterChains` list. And likely, it has a `AnyRequestMatcher` which will match all the time and ignore any other `SecurityFilterChain` in that list, including the `@EnableResourceServer` `SecurityFilterChain`. So the `OAuth2AuthenticationProcessingFilter ` is not actually missing but in fact the filter chain it's associated with is never getting applied/called because of the ordering.

**Comment by MysteryAngle** [comment]
It's work for me thanks.

**Comment by frankskywalker** [comment]
@jgrandja Thanks for the explanation.

**Comment by otinanism** [comment]
@frankskywalker  Do you have form login enabled? Do you have a working example that I can take a look at? I am also trying to combine auth and resource server and when I change filter order as suggested I can't get to the login page.

**Comment by emailalosha** [comment]
For latest release of Spring boot 2.5.1 and corresponding spring security starter which I am working on right now - the property security.oauth2.resource.filter-order=3 is not exist. 

So you can use  below annotation on top of resource server config class

@Order(value = 3)
