### ISSUE TITLE
Polish gh-977

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-oauth#994]
# General 

* [x] Update Copyright headers to be 2017
* [x] Run code coverage and check that everything you have is needed and if it is needed tested. If it is not needed, delete it. A few (but not complete examples)
  * `JwkDefinition.getPublicKeyUse` appears unused. Can possibly keep around for easier debugging and such but should be tested
  * Missing test coverage for `CryptoAlgorithm.standardName`
  * `CryptoAlgorithm.description` appears unused

# JwtTokenStore

* [x] Make `JwkTokenStore` final
* [x] Remove javadoc on `JwkTokenStore` that is discussing the implementation details of using package scope classes. Public APIs can discuss how they work, but should avoid discussing package/private scope constructs since it will not be published with the rest of the javadoc.
* [x] Add tests for `JwtTokenStore` `readAuthentication(OAuth2AccessToken)` `readAuthentication(String)`  `readAccessToken(String)`

# JwkSetConverter

* [x] `createJwkDefinition` could have a more descriptive error message. Stating something like "attribute KEY_TYPE has a value and cannot be used to constructo a KeyType. Valid values are.."
* [x] `createRSAJwkDefinition` change to `createRsaJwkDefinition`

# JwkDefinitionSource
* [x] We should improve on the efficiency of `getDefinition` & `getVerifier` which is currently iterating over every key when we could just look up the value in the map.
  * We can fix this by mapping the key id to an object that wraps the `JwkDefinition` and the `SignatureVerifier`
  * getDefinition then uses `jwkDefinitions.get(keyId).getJwkDefinition()` and getVerifier uses `jwkDefinitions.get(keyId).getSignatureVerifier()`
* [x] Atomic reference does not prevent race conditions on mutable objects, so we need to fix the concurrency. We should
  * remove the atomic reference
  * use `ConcurrentHashMap`
  * in `getDefinitionRefreshIfNecessary` we should first try `getDefinition` if the result is null, clear the old keys out and populate with the new keys
* change `createRSAVerifier` to `createRsaVerifier`
* change `createRSAVerifier` to static
* change `refreshJwkDefinitions` to a static method, name as something like `loadJwkDefinitions`, and return a value

**Comment by jgrandja** [comment]
Thanks for the feedback @rwinch. This is now merged to master.
