### ISSUE TITLE
Invalid escape of error descriptions

### ISSUE THREAD

**Issue by fhanik** [spring-projects/spring-security-oauth#997]
Commit: 
https://github.com/spring-projects/spring-security-oauth/commit/0f43bb8c0de8be261479dc5d88926821f55468ca

Github Issue:
https://github.com/spring-projects/spring-security-oauth/issues/889

According to the IETF: [OAuth2 RFC](https://tools.ietf.org/html/rfc6749)

> error_description
>          OPTIONAL.  Human-readable ASCII [USASCII] text providing
>          additional information, used to assist the client developer in
>          understanding the error that occurred.
>          Values for the "error_description" parameter **MUST NOT include
>          characters outside the set %x20-21 / %x23-5B / %x5D-7E.**

A single quote `'` character %x27 is being escaped with `&#39`. The HTML escape is incorrect.

**Comment by jgrandja** [comment]
Thanks for the report @fhanik. Would you be interested in submitting a PR?
